### ISSUE TITLE
Can't join CodeStream Team if already connected to Slack Team

### ISSUE THREAD

**Issue by xetra11** [TeamCodeStream/CodeStream#100]
**Describe the bug**
I started evaluating CodeStream by connecting to our Slack. After a while a friend tried the same but instead of connecting with Slack he created a CodeStream account. Afterwards he invited me to his team. I received the invitation:
>I've added you to the Backend team on CodeStream so that we can discuss code.

I want to point out that I have not received any invitation code/link.

In his CodeStream however he can see me as part of his team members. I only can see the old Slack team where I am the only member.
How does this work now? How can I abandon the Slack team integration and work with him on the CodeStream team? I tried to create a CodeStream account but failed as it stated I already have an account (which is the Slack connected one)

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 2.1.0+1
 - OS + version: Arch Linux
 - IDE + version: IntelliJ 2019.2.1

**Log Files**
none/

**Comment by xetra11** [comment]
I'd like to know how I can revoke my Slack Account so I can maybe join in via CodeStream and that should work then.

Additionally: He mentioned me in a codemark and I received an Email notifying me. Opening that Repo and the CodeStream plugin however did not yield any codemarks to see.

**Comment by planteater** [comment]
While we don’t yet have a team switcher built into the UI (coming soon) you can switch teams via the extension’s setting I. Your IDE. That said, if you don’t think you’ll want to continue using your Slack-connected team and would rather use the other one, I can delete the Slack team to make things easier for you. Just confirm that this is the way you’d like to go. Thanks

**Comment by xetra11** [comment]
Tell me more about the Team Changing option. In IntelliJ I can see that you can input the name of your team. I expect it to at least have the Slack Server name (since this is my current team) but it does not.
Will changing the team name to the one my friend has really work? We now work both on Slack and don't wanna try something that breaks this now.

**Comment by planteater** [comment]
@xetra11 - It's basically a poor man's team switcher, until we get it into the UI. If you're user (i.e., email address) is on two teams, you can just enter the team name of the one you want to currently user. Or you can have two different projects open in different IntelliJ windows and have a different team selected in each.

I guess the main question is really do you need/want two different CodeStream teams?

**Comment by xetra11** [comment]
@planteater nah we do not need two teams. I will try out the teamswitcher and report a bug if it does not work as intended.

Thanks so far!

**Comment by planteater** [comment]
Sounds good! BTW, we're going to try to get a real team switcher into the UI sometime next week.
