### ISSUE TITLE
CodeStream Logo loads infinitely after Slack connection

### ISSUE THREAD

**Issue by xetra11** [TeamCodeStream/CodeStream#101]
**Describe the bug**
I am not able to log me in via my Slack integration anymore. The Browser opens and I accept the Slack connection. When back in the IDE the CodeStream Loading Logo is spinning infinitely.

*After* I created a comment via the action panel I was able to see the whole CodeStream Environment again.

After I did the latter action this is not reproducable anymore.

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 2.1.0+1
 - OS + version: Arch Linux
 - IDE + version: IntelliJ 2019.2.1

**Comment by planteater** [comment]
@xetra11 - Glad that the issue can no longer be reproduced, but could I trouble you for a log file anyway? That would allow us to see what happened and make a fix if need be. Thanks!

https://github.com/TeamCodeStream/CodeStream/wiki/Instructions-for-finding-CodeStream-log-files

**Comment by xetra11** [comment]
will do if it occurs again
