### ISSUE TITLE
When creating a new PR clicking the pull button resets the comment PR input text

### ISSUE THREAD

**Issue by Frosty21** [TeamCodeStream/codestream#1012]
**Bug occurring state:** 
- when the current branch you are working on is behind and needs to pull.
- in state of new PR you put in the comment explaining the PR and you click pull to update this PR to the latest changes from main branch

(Sorry don't have a gif to show it but when i do ill update this issue)

**What I think should happen (could be wrong):**
- when clicking pull button should still hold text input state for new PR

**Environment:**
- VSCode, MacOS

**Comment by planteater** [comment]
@Frosty21 - I tried to reproduce this by bringing up the form to create a PR, then filling in the title and description fields, and then finally clicking the Pull button below the form (as my local main was behind a commit). Clicking the Pull button didn't clear out the form for me. Did I get those steps correct?

**Comment by planteater** [comment]
@Frosty21 - I'm going to close this for now, but feel free to re-open or reach out to me directly at support@codestream.com and we'll dig in. Thanks

**Comment by Frosty21** [comment]
@planteater I haven't been able to replicate it but if it does happen ill try getting the process as a gif.
