### ISSUE TITLE
Mark files as viewed automatically in VS Code extension

### ISSUE THREAD

**Issue by alanvardy** [TeamCodeStream/codestream#1015]
I searched for mentions of "viewed" :+1: 

Before further ado, thank you for this extension! I use it daily and it is very valuable for my workflow.

When clicking on files in the side bar, within the codestream extension I would like the files to be marked as "viewed" with the round check mark. I wasn't able to find an option to enable this functionality, please let me know if I missed it?

![image](https://user-images.githubusercontent.com/38899847/173613543-4cefc9e7-f81c-40ad-9496-fe16f274ac71.png)

Also, there is no visual indication in the sidebar of which file I am currently viewing. I can create a separate ticket for this if desired.

**Comment by planteater** [comment]
@alanvardy - Thanks for the feedback! If you're ever up for a chat about CodeStream (what you like, what you'd like us to add/fix/change, etc.), feel free to hit me up at support@codestream.com anytime.

In terms of marking files as viewed, in your screenshot above you can see the checkmark at the very right. Once checked the icon is always in view, as depicted. But when not checked, it only appears when you hover over a given file's row.

In theory, when you click on a file's row, the background of that row should change to a lighter gray. Are you looking for something maybe a little bit more prominent?

**Comment by alanvardy** [comment]
> In terms of marking files as viewed, in your screenshot above you can see the checkmark at the very right. Once checked the icon is always in view, as depicted. But when not checked, it only appears when you hover over a given file's row.

Oh, I think I didn't express myself clearly, sorry! I was hoping that the "viewed" checkmark could be filled in automatically when I view the file for more than a few seconds. Saving me the (admittedly small) effort of manually clicking on the small round icon.

> In theory, when you click on a file's row, the background of that row should change to a lighter gray. Are you looking for something maybe a little bit more prominent?

Perhaps I need to look at my theme settings then, I am currently viewing the `assets.ex` file in this picture but cannot see the background colour difference

![image](https://user-images.githubusercontent.com/38899847/173616414-d4208e70-4306-4607-9ecb-9e38df909a7f.png)

**Comment by planteater** [comment]
Ironically enough, we used to automatically check files as you viewed them, but most of the feedback we got was that people wanted us to be consistent with the way GItHub worked (and to have that viewed state by in sync with GitHub).

I'm going to close this out for now, but if you'd ever like to talk in more detail about your CodeStream wish list, hit me up at support@codestream.com.

**Comment by Frosty21** [comment]
@planteater that's so weird I feel like @alanvardy the same way with the UX of once you clicked a file your intention is to read through it hence automatically ticking it off 🤷 . 

Perfectly understand you have to go with your feedback (thats with any features they need iterations of changes) but if you could have that as a settings option that would be amazing. personally I liked the initial choices codestream took
