### ISSUE TITLE
Unable to Prevent Auto-Opening (even with Auto Login Disabled, Despite Not Needing 99% of the Time)

### ISSUE THREAD

**Issue by PowerAccess** [TeamCodeStream/CodeStream#102]
## Always Auto Opens Window On VS Code Startup Regardless of Settings

Code Stream auto opens on VS Code startup for any file (including non code files, when use just to open a text file as a Notepad alternative). It opens even though I only rarely use or may just consider using this extension in the future.

With that the case, I must disable this extension until fixed.

Disabling Auto Login and all other settings for the extension (Notifications=None, Logging=Silent, Status Bar=false, etc.) still failst o prevent Code Stream from opening up on VS Code startup. 

This causes it to always take up half the screen for example (initially, requiring me to close or resize), even when not actually being used by anyone yet (and may never be used), and even when used with non-code files and without any workspace.

How can auto-open be disabled?
I only want this window to show up if/when I actually have comments for a file that I'm opening.  Otherwise, this is far far more obtrusive than its worth to even consider anyone of the team trying to use it. I have hundreds of VS Code extensions installed, and this is the only extension that behaves in this obtrusive manner, opening itself up on startup instead of providing on-demand or intelligent auto-opening when appropriate.

## Critical Fixes/Changes Needed
Please implement support for auto-open intelligently (only for files which actually have Code Stream comments). Ideally can add an option to even auto close/hide when viewing files without such comments too, though less important.
Also at the very least add an option to only open on demand, via F1 > CodeStream for example, as well as when clicking on a comment indicator shown in code window/margin (which I assume is supported?)?

MS Teams Integration?

Also, how exactly does this integrate with MS Teams? 
There doesn't appear to be a tab that can be added to show comment history in MS Teams or documentation of how one can reference a file and add a comment via MS Teams.
Or is MS Teams "integration" nothing more than a means of SSO?

## System Configuration
 - CodeStream 2.1.2
 - Windows 10 x64
 - VS Code 1.38.0 (User Install)

**Comment by planteater** [comment]
@PowerAccess - This has been fixed in version 2.1.3. The CodeStream pane should only open automatically on relaunch/reload of VSC if it was already open.

**Comment by PowerSheetAI** [comment]
This issue is occurring again with latest version v5.2.3, with CodeStream tab opening up whenever VS Code starts, even though I've never used this extension and am unlikely to ever need to. I have it installed in case I may want to try some day, so it certainly shouldn't be taking over VSCode, unlike any of the other hundreds of other of extensions I have installed, none of which have ever behaved in this way.
