### ISSUE TITLE
Jira Ticket pulling from issues doesn't transition to the correct one

### ISSUE THREAD

**Issue by Frosty21** [TeamCodeStream/codestream#1023]
- IDE Version: VSCODE Version: 1.67.2
- OS Version: MacOS Version 12.3.1 (21E258)

Steps to Reproduce:
For first issue 
1. set ticket to Backlog on jira 
2. open ticket on VSCode IDE Codestream under issues
3. Should see it will automatically transition it to Done (I think this should be Backlog => Selected for Development => Open => In Progress) when it should be set to In Progress

For second issue
1. set ticket to open on jira 
2. open ticket on VSCode IDE Codestream under issues
3. Should see it will automatically transition it to Backlog when it should transition to IN PROGRESS

here is the workflow in jira 
<img width="339" alt="Screen Shot 2022-06-16 at 5 33 46 PM" src="https://user-images.githubusercontent.com/5212703/174194970-7e4ae7bd-aa1c-43a3-a89e-14b2ec585eb5.png">

**Comment by planteater** [comment]
Thanks for the report @Frosty21. We'll dig into why it doesn't appear to be honoring your workflow. Can you let me know if you're using Jira cloud or server? Also, a log file might help us here.

Reproduce the issue, and then open the Output view in VS Code (View: Toggle Output from the command palette) and select CodeStream (Agent) from the dropdown menu at the top-right. Copy all of the output you see and save it in a text file. You can send it to me at support@codestream.com.

**Comment by planteater** [comment]
Hi @Frosty21 - Just wanted to follow up on my reply above. Thanks.

**Comment by Frosty21** [comment]
Hey @planteater I'll get onto it tonight and send you a copy of the log been a little busy with a few thing atm

**Comment by Frosty21** [comment]
@planteater just sent you the logs for those two situations

**Comment by planteater** [comment]
@Frosty21 - Things should be better here in v13.7 that was just released. As we discussed, Jira doesn't provide us with an accurate workflow map, but the logic we have in place now remember your most recently used selected on a per-status basis so we should get things right most of the time.
