### ISSUE TITLE
Assigning a merge request to myself in Gitlab shows the merge request under the "Created by me" tab

### ISSUE THREAD

**Issue by HulaTime** [TeamCodeStream/codestream#1028]
Hi there, I've just started using the codestream plugin in some of my IDEA ide's and think it looks like a great tool, however I've noticed that when I filter MR's to open repos with gitlab, MRs created by other people report as being created by me when I assign myself to those MR's. It may be worth noting I've noticed this while I only have a single MR assigned to me.

- IDE Version: WebStorm 2022.1.2
- OS Version: 5.10.123-1-MANJARO (arch)

Steps to Reproduce:

1. Create account
2. Connect to gitlab self managed
3. Assign an MR created by someone else to me in gitlab
4. Filter to only show MRs from open repos
5. The MR shows in the "assigned to me" tab, but also shows in the "created by me" tab.

**Comment by planteater** [comment]
Thanks for the report @HulaTime. Just to confirm, if you turn off the option to only show MRs from open repos, the MR correctly only shows in the Assigned to Me section?

**Comment by planteater** [comment]
@HulaTime - I wasn't able to reproduce this, but let me know if I've got the steps correct.

1. User A creates an MR and adds user B as an assignee.
2. User B, in CodeStream, changes the setting in the Merge Requests section to only show MRs from open repos.
3. For me, the MR correctly only shows in the "Assigned to Me" section, and does not appear in the "Created by Me" section.

**Comment by planteater** [comment]
@HulaTime - I'm going to close this for now, but if you get a chance to provide some additional info feel free to re-open or email me directly at support@codestream.com. Thanks!
