### ISSUE TITLE
Repo Change and IDE restart always needs a new Slack connection

### ISSUE THREAD

**Issue by xetra11** [TeamCodeStream/CodeStream#103]
**Describe the bug**
I always see me reconnecting to the Slack account when restarting the IDE or changing my repo.
That happens to be inconvenient over time. The auto login feature there seems *not* to work.

**System Info (please complete the following information):**
Version of the CodeStream extension: 2.1.0+1
OS + version: Arch Linux
IDE + version: IntelliJ 2019.2.1

**Comment by planteater** [comment]
@xetra11 - Right now the setting is at the project level, so any time you open a new project it will prompt you to authenticate again. However, once you've authenticated for that project, you shouldn't have to do so again the next time you open in.

That said, we are working on a change to have this be global to simply things for you.

**Comment by planteater** [comment]
With v5.0 of our extension, settings are now saved globally so you should not have to reauthenticate when opening a new project. Note that if you had changed any of your settings you'll have re-do those changes after updating to 5.0.
