### ISSUE TITLE
不支持中文输入idea

### ISSUE THREAD

**Issue by tomsean** [TeamCodeStream/CodeStream#104]
**Describe the bug**
A clear and concise description of what the bug is, as well as detailed steps to reproduce. If applicable, please add screenshots to help explain your problem.

**System Info (please complete the following information):**
 - Version of the CodeStream extension: [e.g., 0.53.1]
 - OS + version: [e.g. Win 10]
 - IDE + version: [e.g. VS Code 1.33.1]

**Log Files**
Sending log files along with your report will help us investigate the issue. Instructions can be found here: https://github.com/TeamCodeStream/CodeStream/wiki/Instructions-for-finding-CodeStream-log-files

**Comment by planteater** [comment]
@tomsean - Please follow this issue to get notified once we've been able to address this:

https://github.com/TeamCodeStream/CodeStream/issues/56
