### ISSUE TITLE
Remove hyphens when merge request title from branch name

### ISSUE THREAD

**Issue by mazury** [TeamCodeStream/codestream#1041]
When we create merge request, there is an option to use latest commit message or branch name as title. Branches almost always have hyphens to divide words in the description. It would be great if codestream automatically removed them when we use the option to use branch name as merge request title, because titles should not generally have them, it looks bad in code repo.

**Comment by Frosty21** [comment]
Same here with @mazury . Especially in the case of using Jira tickets to track when i want to select for example "ABC-123-pt2-FE-..." i want to have the ticket to be similar to "ABC-123 pt2 FE ..." so then when one of my lead dev is using SR&ED with Jira reporting will link to these branches of these layouts. 

Maybe having a filter/ auto layout preferences for PRs Pull Request Title would help us devs dramatically. I feel from the three options from Pull Request Title (Use Current Ticket, Current commit message and User branch name) Current Commit Message should be removed and add the last one as create your own auto title (linked to the branch name but formatted in your way).
