### ISSUE TITLE
VS Code Login Exception (Proxy Issue)

### ISSUE THREAD

**Issue by FuadBalashov** [TeamCodeStream/CodeStream#11]
**Background**
Hello, my team and I are trying to make use of the Code Stream VSCode extension but we keep running into a login issue in one of our office networks (we are able to login from other networks on the same computers). We are fairly certain this is a network configuration issue, but we are finding it hard to get error info to address the problem. I would appreciate some help in getting a more descriptive error so we know why this is failing. Thank you!

**Error Description**
Request initialize failed with message: Login failed: request to https://api.codestream.com/login failed, reason: unable to get local issuer certificate
![image](https://user-images.githubusercontent.com/7839848/47684198-6927ba00-dba8-11e8-8452-2be90e3cf79d.png)

I tried looking in the console logs but can't see anything helpful:
![image](https://user-images.githubusercontent.com/7839848/47684207-6f1d9b00-dba8-11e8-9b5c-cda135e593ae.png)

**System**
OS - Windows 10
Version: 1.28.2 (system setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by eamodio** [comment]
@FuadBalashov Sorry for the issues you are running into -- and thank you for the detailed report! Do you use a proxy server on your office network? Are you using Slack or CodeStream channels?

**Comment by FuadBalashov** [comment]
Thanks for the response @eamodio , I'm glad to hear its up to snuff!
We are using a proxy at work.
We have not integrated Code Stream with Slack, so I think what we are using are Code Stream channels. To confirm, here is what the UI looks like when I am actually logged in:
![image](https://user-images.githubusercontent.com/7839848/47717732-f0af1080-dc1c-11e8-8ca1-7448d18a413a.png)

**Comment by eamodio** [comment]
@FuadBalashov Unfortunately we don't currently have proxy support (I'm actually adding the support as I type this). We are hopeful to have a first-pass version of this working in an update tomorrow -- would you be willing to try it out for us to see if it resolves the issues for you?

**Comment by FuadBalashov** [comment]
Absolutely, thanks for the heads up @eamodio , let me know how I can get the update to try out.

**Comment by afreix** [comment]
Any updates here?

**Comment by planteater** [comment]
@afreix - The latest version of our extension has proxy support. When @FuadBalashov tried it, it didn't solve the problems right out of the gate, but we sent the following further instructions:

Can you try adding your proxy configuration into your vscode user settings? Try setting `”http.proxy” = “<your-proxy-url-here>”` and then reload the vscode window and try again. If you still run into the same issue, then try setting `”http.proxyStrictSSL” = false` and then reload the vscode window and try again.

Not sure if he's tried that yet, but we're anxious to find out if it solves the problems.

**Comment by planteater** [comment]
@afreix @FuadBalashov - Any update on whether those instructions got things working for you? Thanks!

**Comment by planteater** [comment]
@afreix @FuadBalashov - Looks like other customers with proxies are able to get in, so I'm going to close this issue. Definitely reach out if you're still seeing problems though.
