### ISSUE TITLE
VSCode: When CodeStream is open in a split focusing on CodeStream can sometimes lose the last editor context

### ISSUE THREAD

**Issue by AndrewMorsillo** [TeamCodeStream/CodeStream#110]
I have VSCode split into several editor groups. One of which only contains CodeStream. If I am working in a file CodeStream properly shows the marks in that file. If I click to focus the CodeStream tab, CodeStream loses context on the file I was working with and says "No file open". I expected CodeStream to maintain the context of the last active editor.

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 2.1.3
 - OS + version: macOS 10.14.6
 - IDE + version: VSCode 1.38.1

**Comment by AndrewMorsillo** [comment]
I'm using a 3x2 grid. When I have a file with marks in it focused things work as expected:

![image](https://user-images.githubusercontent.com/858965/64882678-9dbf2b80-d62b-11e9-85d5-bdad00429367.png)

When I focus the editor group with the CodeStream tab it stops showing the marks. Interestingly this time it isn't saying "no file open" -- it was doing that yesterday. Regardless I think it would be more useful if CodeStream always maintained the context of the last focused editor.

![image](https://user-images.githubusercontent.com/858965/64882825-e1199a00-d62b-11e9-8745-070168979e26.png)

**Comment by eamodio** [comment]
This will be resolved in the next CodeStream release. Thanks for the report!

**Comment by planteater** [comment]
Fixed in v3.0
