### ISSUE TITLE
"Show line-level blame" hover action

### ISSUE THREAD

**Issue by adityasrini** [TeamCodeStream/codestream#1101]
Hi there! I'm loving this plugin(13.4.0+244) as I use WebStorm(2022.2). I like the feature "Show line-level blame" as I browse code, but I dislike how frequently the popup comes up almost immediately after I hover over it. This becomes especially annoying when I click on an empty line with code on the previous and next lines and the pop-up obscures view of the previous lines.

My request: Have a way to disable this hover feature, but retain the line-level blame. Right now, I have to disable the line-level blame feature entirely to make the hover thing go away.

**Comment by planteater** [comment]
@adityasrini - Thanks for the feedback. We are working on a small fix to the hover behavior in JetBrains IDEs that may address your concerns. I'll follow up once it's out there.

**Comment by planteater** [comment]
@adityasrini - Have you tried this again in the most recent version of CodeStream? There was a bug that was causing the hover to display as you moved off of the codelens. I think you should see a lot less accidental displays of that hover now.

**Comment by adityasrini** [comment]
Sorry for the delay. This has been fixed 😄
