### ISSUE TITLE
[Bug] DeprecationWarning: Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by Frosty21** [TeamCodeStream/codestream#1102]
This is coming up in my output when trying to grab the logs for an issue
`(node:995) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper --trace-deprecation ...` to show where the warning was created)`

- IDE Version: Version: 1.70.0
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:55.829Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.6.0
- OS Version: MacOS Monterey 12.5 (21G72)

**Comment by planteater** [comment]
Thanks for the heads up @Frosty21. This shouldn't cause any issues, but we'll get it resolved.
