### ISSUE TITLE
Line-level blame not showing up in Android Studio

### ISSUE THREAD

**Issue by jakoss** [TeamCodeStream/codestream#1108]
- IDE Version: Android Studio Chipmunk 2021.2.1 Patch 2 and Android Studio Electric Eel 2022.1.1 Canary 9
- OS Version: Windows 11 21H2 22000.856
- Plugin version: 13.4.0+244

Steps to Reproduce:

1. Install the CodeStream plugin
2. Select any line

No line-level blame is showing up. I disabled and later completely removed the Git Toolbox plugin, but it's still not showing up. It is enabled in CodeStream settings

**Comment by jakoss** [comment]
@planteater I found out that the real issue is not with the line-level blame but with user session. 

First issue (i think it's an issue) is that i have to be logged in to CodeStream for line-level blame to show up. This is weird since we're talking about local repo, but it's not that big of an issue, BUT, for some reason, i have to log in to CodeStream every single time i run the Android Studio. It's not keeping the session for me. I tried logging in using email and GitHub with the same result. I can send you the logs to debug that

**Comment by planteater** [comment]
Thanks for the additional info @jakoss! A log file would be great.

**Comment by marcelofarias** [comment]
Hi @jakoss. It looks like Android Studio is failing to retrieve your CodeStream access token from the Password Safe. Please verify your IDE passwords settings (Settings > Appearance & Behavior > System Settings > Passwords). Make sure password saving is enabled. Alternatively, check if switching to KeePass fixes the issue (will require at least one more cycle of logging in and restarting to check if the token was persisted).

**Comment by jakoss** [comment]
@marcelofarias On windows the KeePass is the only available option but enabling that fixed the issue. Thanks!
