### ISSUE TITLE
Observability throughput incorrect

### ISSUE THREAD

**Issue by ethanmills** [TeamCodeStream/codestream#1109]
- IDE Version: IntelliJ IDEA 2022.2.1 RC Ultimate
- OS Version: Windows 10

Displayed throughput in plugin
![image](https://user-images.githubusercontent.com/40488007/184839127-395ce62a-d601-4395-97b1-2ea9d9ae29fc.png)
Throughput in NR
![image](https://user-images.githubusercontent.com/40488007/184839206-5ddead3b-2be7-4674-b388-7b6361575d99.png)

Steps to Reproduce:

1. Link service using plugin
2. Observe

**Comment by ethanmills** [comment]
Looking closer, response time is also incorrect, but closer (122ms vs 89ms)

**Comment by planteater** [comment]
@ethanmills - Could you share a permalink to the service in question on New Relic, or even just the name of the service? If you’d prefer you can email that info to me at support@codestream.com.

**Comment by ethanmills** [comment]
@planteater https://onenr.io/0MR2Ao4oYwY

**Comment by bcanzanella** [comment]
hey @ethanmills could you try the latest version of the CodeStream plugin (v13.5)?

**Comment by ethanmills** [comment]
@bcanzanella Looks great, thanks! Really impressed by how response you folks have been and how quickly this was fixed
