### ISSUE TITLE
Issue with VS22 installation leading to error. 'WebViewPackage' package did not load correctly.

### ISSUE THREAD

**Issue by metanpatel** [TeamCodeStream/codestream#1110]
- IDE Version: 2022 17.1.4
- OS Version: Windows 10

Steps to Reproduce:

1. Open VS 2022 after installation

![image](https://user-images.githubusercontent.com/53191866/184918019-0589f410-dbf9-4c83-a78c-80f056ccd468.png)

![2022_08_16_09_47_34_Window](https://user-images.githubusercontent.com/53191866/184918173-f411f4a4-5a6c-42dc-ba0f-a38ed1fcbd45.png)

<?xml version="1.0" encoding="utf-16"?>
<?xml-stylesheet type="text/xsl" href="#stylesheet"?>
<activity>
	<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" id="stylesheet" xml:id="stylesheet">
		<xsl:output method="html"  encoding="utf-16"/>
...
  <entry>
    <record>2414</record>
    <time>2022/08/16 15:00:39.099</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Loading UI library</description>
    <guid>{94FD8BFF-40F1-4EF2-8771-E6BFB05FCB18}</guid>
    <hr>800a006f</hr>
    <errorinfo>Cannot find the requested resource: 'Commands.ctmenu'.</errorinfo>
  </entry>
  <entry>
    <record>2415</record>
    <time>2022/08/16 15:00:39.099</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Error loading UI library for package Microsoft.Publish.Framework.VisualStudio.PublishPackage, Microsoft.Publish.Framework. HrLoadNativeUILibrary failed with 0x800a006f.</description>
  </entry>
  <entry>
    <record>2416</record>
    <time>2022/08/16 15:00:39.510</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Loading UI library</description>
    <guid>{F5D4BB28-24EB-4FC7-BDEC-BF96BA99A8EE}</guid>
    <hr>800a006f</hr>
    <errorinfo>Cannot find the requested resource: 'Menus.ctmenu'.</errorinfo>
  </entry>
  <entry>
    <record>2417</record>
    <time>2022/08/16 15:00:39.510</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Error loading UI library for package Microsoft.VsSDK.ExtensibilityProjectFlavor.ExtensibilityProjectFlavorPackage. HrLoadNativeUILibrary failed with 0x800a006f.</description>
  </entry>
  <entry>
    <record>2418</record>
    <time>2022/08/16 15:00:39.543</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Loading UI library</description>
    <guid>{F23B5FBD-9F59-486F-A8B3-A3D1AD8F0900}</guid>
    <hr>800a006f</hr>
    <errorinfo>Cannot find the requested resource: 'Menus.ctmenu'.</errorinfo>
  </entry>
  Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{5498F07E-2CA1-4D3B-BCFB-5E8A8A082EED}</guid>
    <hr>80070002</hr>

**Comment by metanpatel** [comment]
<entry>
    <record>3111</record>
    <time>2022/08/16 15:00:52.839</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [WebViewPackage]Source: &apos;CodeStream.VisualStudio.Vsix.x64&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=17.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=17.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Threading, Version=17.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at CodeStream.VisualStudio.Shared.Packages.WebViewPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{2E5983FB-7DBC-458E-B8F1-8561684049D0}</guid>
    <hr>80070002</hr>
    <errorinfo></errorinfo>
  </entry>

**Comment by metanpatel** [comment]
<entry>
    <record>3111</record>
    <time>2022/08/16 15:00:52.839</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [WebViewPackage]Source: &apos;CodeStream.VisualStudio.Vsix.x64&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=17.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=17.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Threading, Version=17.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at CodeStream.VisualStudio.Shared.Packages.WebViewPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{2E5983FB-7DBC-458E-B8F1-8561684049D0}</guid>
    <hr>80070002</hr>
    <errorinfo></errorinfo>
  </entry>

**Comment by CalvinAllen** [comment]
Hey, @metanpatel, is there any chance you could try upgrading Visual Studio to at least 17.2? I think we may have some dependencies that rely on that as a minimum that aren't reflected in the manifest.

**Comment by metanpatel** [comment]
Thanks! This fixed that error



 
Metan Patel | 
Lead Systems Developer
p: 
(312) 441-9897 w: www.accessoneinc.com
 
 
Join the conversation!  LinkedIn | Twitter | Facebook | YouTube | Instagram
This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of Access One. Finally, the recipient should check this email and any attachments for the presence of viruses. Access One accepts no liability for any damage caused by any virus transmitted by this email.
