### ISSUE TITLE
VSCode: when multiple editor groups are open code marks often go to the wrong file

### ISSUE THREAD

**Issue by AndrewMorsillo** [TeamCodeStream/CodeStream#112]
I have my VSCode instance split into a 3x2 grid. If I add a CodeMark by hovering over the code stream view and clicking an icon it appears that CodeStream picks a random editor to add the mark to instead of using the last focused editor.

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 2.1.3
 - OS + version: macOS 10.14.6
 - IDE + version: VSCode 1.38.1

**Comment by planteater** [comment]
@AndrewMorsillo - This should also be fixed in v3.0
