### ISSUE TITLE
Cannot open resolved conversations

### ISSUE THREAD

**Issue by doronguttman** [TeamCodeStream/codestream#1125]
- IDE Version:
  > Version: 1.70.2 (user setup)
  > Commit: e4503b30fc78200f846c62cf8091b76ff5547662
  > Date: 2022-08-16T05:35:13.448Z (1 wk ago)
  > Electron: 18.3.5
  > Chromium: 100.0.4896.160
  > Node.js: 16.13.2
  > V8: 10.0.139.17-electron.0
- OS Version:
  > OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. open a PR
2. select a review conversation
3. if there are any other conversations on the same file which are resolved it will show as "_This conversation is already resolved_":
  ![image](https://user-images.githubusercontent.com/8771525/186656445-c2d8f15a-0261-493a-8200-838700a0511a.png)
4. click on "_Show resolved_"
5. nothing happens

Expected: resolved conversation expands

**Comment by planteater** [comment]
Thanks for the report @doronguttman! We'll get that fixed.

**Comment by planteater** [comment]
@doronguttman - This should be fixed in v13.7.
