### ISSUE TITLE
VSCode: bookmarks aren't saved

### ISSUE THREAD

**Issue by AndrewMorsillo** [TeamCodeStream/CodeStream#113]
Any time I create a bookmark code mark it disappears later. Not sure of the exact circumstances but every bookmark I have made has at some later point disappeared. It may have been on editor restart but I'm not sure. Hopefully these issues can get patched up soon, I love the idea of CodeStream but it has been so unreliable with vscode that I haven't really been able to test it.

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 2.1.3
 - OS + version: macOS 10.14.6
 - IDE + version: VSCode 1.38.1

**Comment by planteater** [comment]
@AndrewMorsillo - Are the bookmarks displayed on the Search tab, just not when on the Current File tab? Or are they not on Search either?

Could you let me know your team name so that I can check on things on our backend? You can also email it to us at support@codestream.com if you'd prefer.

**Comment by AndrewMorsillo** [comment]
Since bookmarks are going away in next release I'm just going to close this. Bookmarks do seem like they could still be a useful feature however. For example, I have a file of mobx-state-tree models which unfortunately has to be extremely long because of a typescript limitation. I can't break it up into multiple files so having a way to navigate quickly to the various sections of the file would be convenient. I can just use comments for this but the concept of a bookmark makes more sense because there's no need for commenting on these things, they are just location placeholders.

**Comment by planteater** [comment]
@AndrewMorsillo - Note that you can assign keybinds to any codemark, not just bookmarks, so using comments, maybe with a "bookmark" tag, is essentially no different that using the current bookmarks. Other than the name, the only current difference between a bookmark and a comment is that bookmark's have just a title, and no description.
