### ISSUE TITLE
VSCode: When typing a code mark, pressing enter discards it

### ISSUE THREAD

**Issue by AndrewMorsillo** [TeamCodeStream/CodeStream#115]
Steps to reproduce:

Focus an editor. Run the `CodeStream: Create Bookmark` command from the command palette. Type some text in the code mark box. Press enter.

Expected behavior: The bookmark is saved
Actual behavior: The bookmark is discarded 

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 3.0
 - OS + version: macOS 10.14.6
 - IDE + version: VSCode 1.38.1

**Comment by planteater** [comment]
As noted in my email, only an issue with bookmarks, which are being removed (at least for the short term) from the product. When we bring them back we'll make sure this is no longer an issue.

**Comment by AndrewMorsillo** [comment]
This is still a bit of an issue I think. I tried it with a comment and pressing enter adds a newline which is fine, but if I press tab then enter the codemark gets discarded. I would expect tab to highlight the next control but I don't see where the focus moves to when I press it. It seems like the focus moves to the cancel button which would be fine but the button isn't highlighted so the behavior is pretty confusing.

**Comment by planteater** [comment]
Fix incoming!

**Comment by planteater** [comment]
Fixed in v3.0.1. When you tab to the buttons, you're now able to see which button has focus. So two tabs to get to the Submit button. :-)
