### ISSUE TITLE
[Request] Darken the colors for review elements when using a light theme

### ISSUE THREAD

**Issue by rustysys-dev** [TeamCodeStream/codestream#1153]
- IDE Version: v1.70.2
- OS Version: Fedora 36

**Description**

For light themes, and I have tried a few, the color used for changed files in PR review makes this tool very difficult to use.

The theme pictured here is [PewPew's grey matter] but even the default light themes are very unreadable for me. 

Is it possible to darken the colors used here? My default colors in editor for files changed are different than this, and doesn't seem to change with different themes so i feel like this is a codestream chosen color, but correct me if I am wrong?

![image](https://user-images.githubusercontent.com/34673206/188796889-282fc788-cab0-47d8-b093-4c28f5a4e6c4.png)

**Comment by planteater** [comment]
Thanks for the report @rustysys-dev. I think we should be able to improve this. I'll follow up with you.

**Comment by rustysys-dev** [comment]
Yes please!
