### ISSUE TITLE
can't use PRs

### ISSUE THREAD

**Issue by doronguttman** [TeamCodeStream/codestream#1154]
- IDE Version:

> Version: 1.70.2 (user setup)
> Commit: e4503b30fc78200f846c62cf8091b76ff5547662
> Date: 2022-08-16T05:35:13.448Z (3 wks ago)
> Electron: 18.3.5
> Chromium: 100.0.4896.160
> Node.js: 16.13.2
> V8: 10.0.139.17-electron.0
> 

- OS Version:

> OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. try to use codestream
2. expected: able to look at PRs
3. observed: getting an error: `Request codestream/provider/generic failed with message: Cannot read properties of null (reading 'id')`

![image](https://user-images.githubusercontent.com/8771525/188925424-a92afce4-542c-4cc9-ab47-7c095f170d51.png)

NOTE: issues show up fine

**Comment by planteater** [comment]
@doronguttman - This issue was fixed in version 13.7.1 of the CodeStream extension. If you update you should be good to go.

**Comment by doronguttman** [comment]
@planteater thanks for the quick response. after updating to 13.7.1 I'm getting the following error:
`Request codestream/provider/generic failed with message: Cannot read properties of null (reading 'login')`

![image](https://user-images.githubusercontent.com/8771525/188977353-137d5aee-3d4d-4928-b11e-2844fa965606.png)

**Comment by planteater** [comment]
@doronguttman - Thanks for the update. Could I trouble you for a log file? Open the Output view in VS Code (View: Toggle Output from the command palette) and select "CodeStream (Agent)" from the dropdown menu at the top-right. Copy all of the output you see and save it in a text file. You can send it to me directly at support@codestream.com.

**Comment by doronguttman** [comment]
sent

**Comment by charcoast** [comment]
Same problem here.

```
IntelliJ IDEA 2022.2.1 (Ultimate Edition)
Build #IU-222.3739.54, built on August 16, 2022

Runtime version: 17.0.3+7-b469.37 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-46-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 12
Non-Bundled Plugins:
    com.codestream.jetbrains-codestream (14.0.0+253)

Kotlin: 222-1.7.10-release-334-IJ3739.54
```

Gitlab integration

![image](https://user-images.githubusercontent.com/11007668/189146543-97f678fc-72f0-4c7f-ae65-d4286fa8874a.png)

**Comment by planteater** [comment]
@charcoast - I think your issue may be different. Could I trouble you to install the version of the extension at the link below? It has some additional logging. You can install by going to Preferences/Settings > Plugins and then select “Install plugin from disk” from the gear menu at the top-right. Then restart your IDE.

https://drive.google.com/file/d/1INjLV-v3s9qAfwtiom51gM6Xitwh0-c1/view?usp=sharing

To grab a log file, go to Help > Collect Logs and Diagnostic Data in your IDE. This will open the finder where you should see a newly created zip file. You can send it to me at support@codestream.com. Thanks!

**Comment by charcoast** [comment]
> @charcoast - I think your issue may be different. Could I trouble you to install the version of the extension at the link below? It has some additional logging. You can install by going to Preferences/Settings > Plugins and then select “Install plugin from disk” from the gear menu at the top-right. Then restart your IDE.
> 
> https://drive.google.com/file/d/1INjLV-v3s9qAfwtiom51gM6Xitwh0-c1/view?usp=sharing
> 
> To grab a log file, go to Help > Collect Logs and Diagnostic Data in your IDE. This will open the finder where you should see a newly created zip file. You can send it to me at [support@codestream.com](mailto:support@codestream.com). Thanks!

Yesterday I tested this version of Google Drive, and I still had problems. Today the codestream is working again.

**Comment by doronguttman** [comment]
confirmed. thank you!
