### ISSUE TITLE
Upgrade to latest CodeStream 14.0.0  in VSCode removes Jira link already established previously

### ISSUE THREAD

**Issue by Frosty21** [TeamCodeStream/codestream#1158]
- IDE Version: Version: 1.71.0
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:25:38.437Z (1 wk ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No
- OS Version: MacOS Monterey Version 12.5.1

Steps to Reproduce:

1. VSCode have Jira already linked in your own jira
2. try clicking "jira" to re-establish connection in vscode
3. gives an error on chrome browser unable to establish 0auth link

<img width="720" alt="Screen Shot 2022-09-08 at 12 11 30 PM" src="https://user-images.githubusercontent.com/5212703/189217655-1a37a31a-b70b-4a20-829c-9b59e430b85a.png">
<img width="1187" alt="Screen Shot 2022-09-08 at 2 21 45 PM" src="https://user-images.githubusercontent.com/5212703/189218439-8e4789c5-e43c-4496-8dc6-6c137fde8ed5.png">

When updating to latest version of Codestream the Jira link still exists within Jira but the integration to re-establish goes directly to my personal account not the work email i setup with. Or is it just me?

**Comment by planteater** [comment]
Hi @Frosty21 - The only times I've ever encountered that web page are where in instances where I was signed into the wrong Atlassian account on the web. I would suggest re-authing with Jira on the web and then trying again.

**Comment by Frosty21** [comment]
Hey @planteater - got it to work had to remove the access on jira and restart or wait a few hours before the re-authing worked. Closing issue now
