### ISSUE TITLE
VSCode: Adding a new code mark turns off list view

### ISSUE THREAD

**Issue by AndrewMorsillo** [TeamCodeStream/CodeStream#116]
After adding a new CodeMark if the CodeStream tab had the list toggle turned on it is now turned off.

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 3.0
 - OS + version: macOS 10.14.6
 - IDE + version: VSCode 1.38.1

**Comment by planteater** [comment]
Fixed in v3.0.1
