### ISSUE TITLE
GitHub Enterprise: cannot read properties of null (reading 'origin')

### ISSUE THREAD

**Issue by surjyams** [TeamCodeStream/codestream#1168]
- IDE Version: VSCode 1.71.0
- OS Version: Windows 11

Steps to Reproduce:

1. Launch VSCode and open a JavaScript project workspace
2. Open Codestream add-on
3. Shows this error: 
![image](https://user-images.githubusercontent.com/23640808/189841513-7d514507-9836-4ec0-8607-1182f9065c87.png)

**Comment by planteater** [comment]
@surjyams - We've got a fix for this going out in a release on Thursday. I'll update you as soon as it's available.

**Comment by planteater** [comment]
Fixed in version 14.1.
