### ISSUE TITLE
VSCode: Deleting a codemark after navigating to it from search tab crashes CodeStream

### ISSUE THREAD

**Issue by AndrewMorsillo** [TeamCodeStream/CodeStream#117]
1. Create a codemark comment
2. Go to search tab and click on the new comment
3. Delete the comment
4. CodeStream tab crashes with "an unexpected error has occurred click here to reload this tab"

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 3.0
 - OS + version: macOS 10.14.6
 - IDE + version: VSCode 1.38.1

Log output looks like it contains copies of some of my source files so I don't want to post it here.

**Comment by planteater** [comment]
Fixed in v3.0.1
