### ISSUE TITLE
How do I open the code stream window in Visual Studio 2022?

### ISSUE THREAD

**Issue by THammond9** [TeamCodeStream/codestream#1170]
I have looked in the View menu and I performed a search but I do not see an option to open the Code Stream window. I also looked over the documentation but there is no mention, that I saw, of how to open the code stream menu in the IDE.

**Comment by planteater** [comment]
@THammond9 - after installing the extension the CodeStream pane should automatically appear at the right side of the IDE. If that didn’t happen you can display it by clicking on the CodeStream logo in the toolbar.

**Comment by planteater** [comment]
@THammond9 - Just wanted to follow up to see if you were able to get CodeStream to open. Thanks

**Comment by THammond9** [comment]
Yes, I was able to. I think it would be helpful to add the option somewhere else as I like to keep my toolbars minimal and had/have CodeStream hidden. The first place I checked is the "Extensions" menu and I think this makes the most sense. The other place is "View > Other Windows". For me, the toolbar was not the most obvious place to check for "Open the CodeStream window".

**Comment by planteater** [comment]
Excellent suggestion @THammond9! I'll get that into the queue.
