### ISSUE TITLE
Repo *** not found in your editor when having multiple repositories in pull requests - PHPStorm

### ISSUE THREAD

**Issue by mathiaskk** [TeamCodeStream/codestream#1171]
- IDE Version: PhpStorm 2022.2.1
- OS Version: Windows 11

Hi there.

We have this issue with having multiple repositories in pull requests. 
Whenever i click on a repository that is not a part of my editor then i'm not able to see any pull requests from my selected editor.
So now i can't see anything, therefore i'm forced to restart PHPStorm.
It would be nice to not be forced to only show pull requests from open repositories.

**Comment by planteater** [comment]
@mathiaskk in the heading of the Pull Requests section click on the gear menu and make sure you don’t have it set to only show PRs for repos you have open in your ide.

**Comment by mathiaskk** [comment]
> @mathiaskk in the heading of the Pull Requests section click on the gear menu and make sure you don’t have it set to only show PRs for repos you have open in your ide.

I think you misunderstand :)

The thing is, when i can see all PRs for repos and i expand one that is not open in my IDE then it tells me that "Repo not found in your editor" which is fine. After that i'm getting "Repo not found in your editor" on the repo that are in my IDE. - Then i have to restart PHP Storm 

If i haven't expanded such repo then i can expand all PRs that are connected to my current IDE. But not if i expand a repo from outside current

**Comment by planteater** [comment]
Thanks for the clarification @mathiaskk! We'll get a fix out for this asap.

**Comment by planteater** [comment]
I haven't been able to reproduce, but let me make sure I've got the steps correct:

1. Have Repo A open in the IDE.
2. Click to view a PR from Repo A. It expands correctly.
3. Click to view a PR from a repo you don't have open in the IDE. Correctly get the repo-not-found message.
4. Now try to view a PR from Repo A again, and you incorrectly get the repo-not-found message.

That right? In any case, if you can reproduce your scenario, could I trouble you for a log file? In PhpStorm go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. You can send the file to me directly at codestream@newrelic.com. Thanks

**Comment by mathiaskk** [comment]
I have send the logs :)

**Comment by planteater** [comment]
@mathiaskk - This has been fixed in version 14.2.

**Comment by lc-4918** [comment]
Still not fixed in version 14.11.

[codestream.log](https://github.com/TeamCodeStream/codestream/files/10343748/codestream.log)
