### ISSUE TITLE
PhpStorm Plugin not work

### ISSUE THREAD

**Issue by 1xtr** [TeamCodeStream/codestream#1172]
- IDE Version: PhpStorm 2022.2.1 Build #PS-222.3739.61, built on August 18, 2022
- OS Version: Windows 10 Home 19044.1949
- Plugin Version: 14.0.0+253

Steps to Reproduce:

1. Work same as every day
2. In one moment see that plugin in latest PhpStorm not work. Plugin page empty.

After close PS and open again all work fine.

**Comment by planteater** [comment]
@1xtr - Could in trouble you for a log file? You can send it to me at support@codestream.com. Instructions are here:

https://docs.newrelic.com/docs/codestream/troubleshooting/client-logs

**Comment by planteater** [comment]
Hi @1xtr - Just wanted to follow to see if we could get that log file. Thanks

**Comment by planteater** [comment]
@1xtr I'm going to close this for now, but please re-open if you're still experiencing the issue. Make sure that you've updated to version 14.1.1 of the CodeStream extension. Thanks
