### ISSUE TITLE
Can't log in in VS2022

### ISSUE THREAD

**Issue by merlinschumacher** [TeamCodeStream/codestream#1184]
- IDE Version: Visual Studio 2022 Professional 64 Bit 17.3.4
- OS Version: Windows 10

Steps to Reproduce:

1. Install the Codestream 2022 extension 
2. Open any solution
3. The "Sign In" button in the CodeStream Toolbar is visible, but has no function. The CodeStream side pane only shows "Open a folder or soultuin to start using Codestream".

**Comment by planteater** [comment]
@merlinschumacher just to confirm, do you have a file open in the editor?

**Comment by merlinschumacher** [comment]
Yes I do.

**Comment by merlinschumacher** [comment]
I've sent the logs via mail.

**Comment by CalvinAllen** [comment]
@merlinschumacher Any possibility you could try this CI build that has a _possible_ fix?

[codestream-vs-14.1.1.7069-x64.vsix](https://drive.google.com/file/d/1Lm5vlbeW8K6NfhIj3XyGiwr0ynyrY0es/view?usp=sharing)

Once downloaded, you can double-click it and it'll launch an installer that should allow you to choose VS2022.

**Comment by CalvinAllen** [comment]
Shoot - can you send us another set of logs from this version?

Its a strange scenario and seems timing related, but I'm not able to reproduce it locally so unfortunately the logs are my only gateway into where the issue is occurring.

**Comment by merlinschumacher** [comment]
No problem. I just sent  you the logs.

**Comment by CalvinAllen** [comment]
Got'em, thanks! This is a different error (that I still can't reproduce), but at least there's some progress.

**Comment by CalvinAllen** [comment]
Hey, @merlinschumacher, 

Unfortunately, there are no errors in your log files now (good!), but with the issue persisting, it gets a little more difficult to diagnose.

With that, a few more questions for you -

1. Do you have an `vs-agent.log` file in the same directory as the `vs-extension.log`?
2. I can see the solution you have opened, `AccessNotesDatabase.sln`, but I can't see any information about it - what types of projects are in the solution and what filetypes are within? For example, are you opening C# files, VB files, etc. Are there any filetypes in there that might deviate from that at all?

One other quick test would be to change the CodeStream setting (Tools | Options, CodeStream) for logging to `Verbose` and restart Visual Studio, and then send us the new log files (which should be much bigger).

Thanks!

**Comment by CalvinAllen** [comment]
Hey, @merlinschumacher, just wanted to check in, see if you had a chance to try any of the above ideas.  Thanks!

**Comment by merlinschumacher** [comment]
Hey, I just mailed you the logs with the verbose setting. The project is an ASP .NET WebAPI project including C# files. There is no vs-agent.log present.

**Comment by CalvinAllen** [comment]
@merlinschumacher 

Unfortunately the verbose logging didn't add anything of value that indicates an error condition.

One thing I'd like to see if you could try would be to launch our "agent" separately from a command prompt. Since you're never getting that vs-agent.log file, seems to indicate it can't startup (we `Process.Start` this from the extension itself)

The command we use to launch it is -
`C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PROFESSIONAL\COMMON7\IDE\EXTENSIONS\5SPHOTSV.GAO\agent\agent.exe --stdio --nolazy --log=C:\Users\Merlin Schumacher\AppData\Local\CodeStream\Logs\vs-agent.log`

I'd be curious to see if -
1. That works at all and you do get that log file created
2. If it returns something else with an error condition / etc.

Let me know what happens when you try that.

Thanks again - I know this is frustrating, but I appreciate your patience and willingness to help triage!

**Comment by CalvinAllen** [comment]
Hey, @merlinschumacher, just wanted to check in, see if you had a chance to try the previous idea. Thanks!

**Comment by merlinschumacher** [comment]
Hi, 

I was off for the week, but tried your suggestion. The agent outputs the following:

```
C:\Users\Merlin Schumacher>"C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PROFESSIONAL\COMMON7\IDE\EXTENSIONS\5SPHOTSV.GAO\agent\agent.exe" --stdio --nolazy --log="C:\Users\Merlin Schumacher\AppData\Local\CodeStream\Logs\vs-agent.log"
New Relic for Node.js was unable to bootstrap itself due to an error:
Error: New Relic requires that you name this application!
Set app_name in your newrelic.js file or set environment variable
NEW_RELIC_APP_NAME. Not starting!
    at JOt (C:\snapshot\dist\agent.js)
    at YOt (C:\snapshot\dist\agent.js)
    at C:\snapshot\dist\agent.js
    at C:\snapshot\dist\agent.js
    at Object.<anonymous> (C:\snapshot\dist\agent.js)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1847:12)
(node:16356) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `agent --trace-deprecation ...` to show where the warning was created)
```

A log file is created. I will mail it to you.

**Comment by merlinschumacher** [comment]
This is with the latest update: 
```
C:\Users\Merlin Schumacher>"C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\qymm55ua.ppn\agent\agent.exe" --stdio --nolazy --log="C:\Users\Merlin Schumacher\AppData\Local\CodeStream\Logs\vs-agent.log"
New Relic for Node.js was unable to bootstrap itself due to an error:
Error: New Relic requires that you name this application!
Set app_name in your newrelic.js file or set environment variable
NEW_RELIC_APP_NAME. Not starting!
    at bMt (C:\snapshot\dist\agent.js)
    at yMt (C:\snapshot\dist\agent.js)
    at C:\snapshot\dist\agent.js
    at C:\snapshot\dist\agent.js
    at Object.<anonymous> (C:\snapshot\dist\agent.js)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1847:12)
(node:16808) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `agent --trace-deprecation ...` to show where the warning was created)
```

**Comment by CalvinAllen** [comment]
Hey, @merlinschumacher, just following up to see if you saw my last message / had a chance to try anything out. Thanks!
