### ISSUE TITLE
VSCode CodeStream view continues to open up

### ISSUE THREAD

**Issue by jabacchetta** [TeamCodeStream/CodeStream#120]
**Describe the bug**
Changing a color theme or color theme setting appears to cause the `codestream.focus` command to execute.

There also seems to be a variety of other actions (toggling the sidebar view) that cause the CodeStream view to randomly pop up, but it's not clear if this is happening only after updating a color theme setting (had to uninstall for now until I have the time to investigate further).

Unfortunately, similar bugs related to the CodeStream view popping up unexpectedly seems to be a common occurrence, at least over the past couple of versions.

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 3.0.0-117
 - OS + version: macOS 10.14.6
 - IDE + version: 1.38.1

**Comment by planteater** [comment]
Fixed in v3.0.1
