### ISSUE TITLE
Can't set Auto-Prompt for feedback when committing to No

### ISSUE THREAD

**Issue by rm-jamotion** [TeamCodeStream/codestream#1205]
- IDE Version: PyCharm 2022.2.2
- OS Version: Ubuntu 20.04 and Ubuntu 22.04
- Plugin Version: 14.2.0+263 New Relic

Steps to Reproduce:

1. Open CodeStream Tool Window
2. Click on toggle button "Yes"
3. Nothing happens. The button seams to be disabled. So it is not possible to disable the auto-prompt.

![image](https://user-images.githubusercontent.com/4548525/194228223-5028ed82-5d98-40ab-bcdd-6e4dd4ae2c73.png)

**Comment by planteater** [comment]
Thanks for the heads up @rm-jamotion ! We'll get this fixed. In the meantime, you can also turn off the auto-prompt by clicking on the gear icon in the heading of the Feedback Requests section.

**Comment by planteater** [comment]
Fixed in version 14.4.
