### ISSUE TITLE
Code stream Crashing

### ISSUE THREAD

**Issue by devzer01** [TeamCodeStream/codestream#1208]
When i am browsing code that is inside excluded folders or library packages, the git command fails and this failure is not handled well causing the CodeStream window not to appear, some sort of crash i believe, i just download the repo, i am going to see if this is something i can quickly fix. 

```
ct 10 15:02:04 nayana-295 jetbrains-idea.desktop[4114030]:     (128) Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false blame --root --inc
remental -w -L 18,20 --contents - -- vevn/lib/python3.10/site-packages/hautils/web.py
Oct 10 15:02:04 nayana-295 jetbrains-idea.desktop[4114030]: fatal: no such path 'vevn/lib/python3.10/site-packages/hautils/web.py' in HEAD
Oct 10 15:02:04 nayana-295 jetbrains-idea.desktop[4114030]: fatal: no such path 'vevn/lib/python3.10/site-packages/hautils/web.py' in HEAD
Oct 10 15:02:04 nayana-295 jetbrains-idea.desktop[4114030]: 2022-10-10 15:02:04,224 [12506101]   WARN - #c.c.a.CodeStreamLanguageClient - [2022-10-10 08:02:04:
224] git — -c, core.quotepath=false, -c, color.ui=false, blame, --root, --incremental, -w, -L 18,20, --contents, -, --, vevn/lib/pyth
```

**Comment by devzer01** [comment]
errors when running build dependencies adjust the shell npm use

```
npm config set script-shell bash
```

**Comment by planteater** [comment]
@devzer01 - Just wanted to follow up on the above. Thanks.

**Comment by planteater** [comment]
@devzer01 I'm going to go ahead and close this out, but if you get a chance to grab that log file go ahead and send it to me at codestream@newrelic.com and we'll dig right into this. Thanks
