### ISSUE TITLE
Long Code Blocks causes content to not wrap appropriately

### ISSUE THREAD

**Issue by n1ddeh** [TeamCodeStream/codestream#1211]
- IDE Version: 1.72.0 (Universal)
- OS Version: Darwin arm64 21.6.0 

Steps to Reproduce:

1. Create a code block/fenced code block with text that spans past the content window.
2. Add some text outside the code block that is expected to wrap to the next line
3. See that the content in the code block does not wrap and the content outside the code block does not wrap as expected

**Comment by kjoshi31** [comment]
Thanks for submitting this bug 👍🏽 
Would you be able to provide more context around this issue, such as the IDE you were using, as well as potentially a gif or screenshot with the issue occurring in real-time (the code can be blurred out or changed to be gibberish)? These details will help us reproduce this on our end so we can roll out a fix quickly

**Comment by planteater** [comment]
@n1ddeh - Just wanted to follow up on the ask above. Thanks!

**Comment by planteater** [comment]
@n1ddeh - I'm going to close this for now, but if you get a chance to provide some additional info either re-open this issue or email me at codestream@newrelic.com.
