### ISSUE TITLE
Infinite delete branch title 

### ISSUE THREAD

**Issue by rv-aholsinger** [TeamCodeStream/codestream#1215]
- IDE Version: PHPStorm 2022.1.4
- OS Version:  macOS 12.6 Monterey

Steps to Reproduce:

1. Follow flow to create a new feature branch. 
2. When setting name of new branch, when you hit backspace you can do it infinitely.  ( see video ) 

https://user-images.githubusercontent.com/100858389/195649737-d2a78bf2-df0f-40dc-a13d-918540080eae.mov

**Comment by planteater** [comment]
Fixed in CodeStream v14.14
