### ISSUE TITLE
Wrong Issues shown for YouTrack

### ISSUE THREAD

**Issue by SaschaWeisenberger** [TeamCodeStream/codestream#1222]
- IDE Version: Visual Studio Community 17.3.6 / VSCode 1.72.2
- OS Version: Windows 11 Pro

Steps to Reproduce:

1. Install Codestream Plugin
2. Connect to Youtrack (SaaS)
3. Go to issues list, the issues shown are not even related to me, totally random from my point of view. But the list is the same in VSCode and VS.

In the logs it says `YouTrack: Completed GET /issues?fields=id%2CidReadable%2Cmodified%2Csummary%2Cdescription&query=for%3A%20me%20state%3Aunresolved` which seems okay, but when I search in YouTrack directly with `for: me state: unresolved` I see different issues.

Any help on this?

**Comment by planteater** [comment]
Hi @SaschaWeisenberger - Could I trouble you for a log file? Instructions can be found at link below, and you can email the file to me at codestream@newrelic.com.

https://docs.newrelic.com/docs/codestream/troubleshooting/client-logs/

Just curious, are any of your teammates seeing the same issue? If not I'm wondering if it's related to your token somehow.

**Comment by SaschaWeisenberger** [comment]
Log is sent. I tried it on my machine with different tokens from different users: same behaviour.

**Comment by planteater** [comment]
@SaschaWeisenberger - We've got a fix for this ready to go in a release next week. I'll update you as soon as it's available.

**Comment by SaschaWeisenberger** [comment]
Tried it on my machine, it works. Thanks a lot!
