### ISSUE TITLE
Java Chromium Embedded Framework (JCEF) Helper gets 40-100% CPU

### ISSUE THREAD

**Issue by 1xtr** [TeamCodeStream/codestream#1223]
- IDE Version: PhpStorm 2022.2.3 Build #PS-222.4345.15, built on October 5, 2022
- OS Version: Windows 10

Steps to Reproduce:

1. Open any project
2. Don't do anything
3. Wait one minute
4. One proccess Java Chromium Embedded Framework (JCEF) getting 40% CPU

After disabling Codestream plugin all work fine

**Comment by planteater** [comment]
Thanks for the report @1xtr! Could I trouble you for a log file? That should give us some insight into what's going on. In your IDE go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. You can send the file to me at codestream@newrelic.com.

In the interim, you can go to Settings > Tools > CodeStream and uncheck the box for "Use JCEF webview". This will switch you to JXBrowser for webview support in CodeStream. It may result in some display issues, but should be a good workaround while we see what's going on.

**Comment by 1xtr** [comment]
@planteater Check mail, for logs. Theme of the mail is issue link

**Comment by marcelofarias** [comment]
@1xtr Could you try switching back to JCEF disabling GPU usage to see if helps? Open the IDE Registry and look for `ide.browser.jcef.gpu.disable`.
![image](https://user-images.githubusercontent.com/1028286/197575131-8dd81fbc-db6c-4634-b904-25de0023d311.png)
![image](https://user-images.githubusercontent.com/1028286/197575157-8442ef65-d528-4a73-a3c6-6dc9c16139c9.png)

**Comment by 1xtr** [comment]
> @1xtr Could you try switching back to JCEF and then disabling GPU usage to see if helps? Open the IDE Registry and look for `ide.browser.jcef.gpu.disable`.


Hi @marcelofarias and thx!
After set `ide.browser.jcef.gpu.disable=true` one process JCEF get 40% CPU but if I open CodeStrem tab it let go down and all working fine.
![image](https://user-images.githubusercontent.com/59780048/197711022-81f18f0f-f4b1-459a-839a-42e3bea55b44.png)

keep watching
