### ISSUE TITLE
Long git commit messages are not wrapped, instead a preceding short code is chopped 

### ISSUE THREAD

**Issue by IndreIndre** [TeamCodeStream/codestream#1226]
- IDE Version: PhpStorm 2022.2.3
- OS Version: Windows 10

![image](https://user-images.githubusercontent.com/3390889/197050037-3be69cd9-c941-44ee-8433-e1e1b027ded5.png)

Steps to Reproduce:

1. Place a cursor inside a short code line having a long git commit message.
2. After placing a cursor in another place, the code stays chopped.

![image](https://user-images.githubusercontent.com/3390889/197054267-4e04eefd-882f-499c-bdbe-2f2037e0e751.png)
![image](https://user-images.githubusercontent.com/3390889/197054391-8edaea70-0cac-430d-b7ef-8a6992743e4c.png)
![image](https://user-images.githubusercontent.com/3390889/197054503-a329d60c-d83e-4e29-9832-6354ada2f73d.png)

**Comment by kjoshi31** [comment]
@IndreIndre would you be able to send a screencast or screen recording of this issue? we are having some difficulties reproducing this issue on our end.

**Comment by IndreIndre** [comment]
Sure, sending one recording. Please let me know if you need more
information.

Indrė

2022-11-14, pr, 20:06 Karan Joshi ***@***.***> rašė:

**Comment by kjoshi31** [comment]
hey @IndreIndre I haven't received your recording yet. If unable to post here, please send it to kjoshi@newrelic.com . thank you
