### ISSUE TITLE
[Feature] Switches to show/hide resolved and archived comments in thread view

### ISSUE THREAD

**Issue by cubezero** [TeamCodeStream/CodeStream#123]
Switches to show/hide resolved and archived comments in thread view would be nice to hide archived comments from this view like it's already done in "comments in this file" view which is rarely used in common cases like "feature code review" when a lot of files was affected.

**Comment by planteater** [comment]
Just to confirm, are you referring to adding these filters under the Search tab?

**Comment by cubezero** [comment]
I mean "channel" view (https://dl.dropboxusercontent.com/s/djbf5rbjlkaj0so/chrome_2019-10-21_19-50-22.png) to have the ability like pointed here: https://dl.dropboxusercontent.com/s/ghm1num59bsjmj4/phpstorm64_2019-10-21_19-52-42.png

**Comment by planteater** [comment]
Closing this, as the Channels tab is no longer part of the product.

**Comment by huguesbr** [comment]
I think this still apply to in code comment? 
![Pasted_Image_1_14_21__11_59](https://user-images.githubusercontent.com/1517759/104582405-1ee36400-5660-11eb-8809-4403911e7432.png)

**Comment by planteater** [comment]
@huguesbr - I think what you're referring to is probably a different issue altogether. I'm guessing what you're looking for is to not have the icons for PR comments appear in the editor gutter if the comment has been resolved? Or something along those lines?

We do have an enhancement in the queue in this area. Current behavior is to show icons in the gutter for comments from all merged in PRs, and from open PRs if you're on either the base or compare branch. Instead, we want to give you the choice between this behavior, and only showing comments from open PRs when you're on the compare branch. The latter option may also be limited to unresolved comments.

I'd suggest creating a new issue for this.

**Comment by huguesbr** [comment]
@planteater yep that's what I want ^^ thx will create a new issue.
