### ISSUE TITLE
Codestream does not work anymore after last VSCODE update

### ISSUE THREAD

**Issue by Perh0rd** [TeamCodeStream/codestream#1250]
- IDE Version: https://share.getcloudapp.com/9ZugkkPO
- OS Version: https://share.getcloudapp.com/9ZugkkPO

Steps to Reproduce:

1. Open a project on VSCODE
2. Codestream Panel does not load

Hi it seems the panel since the last vscode update is not loading, I have uninstall, reinstall, but nothing seems to work, was working before the update of vscode.

Got this error on console : https://share.getcloudapp.com/BluW88E1

Thanks.

**Comment by planteater** [comment]
@lukechen526 - I'm running the latest CodeStream in both the latest VSC and VSC Insiders without issue. If you want to send a log file to me at codestream@newrelic.com I can check into this.

To generate the log, open the Output view in VS Code (View: Toggle Output from the command palette) and select "CodeStream (Agent)" from the dropdown menu at the top-right. Copy all of the output you see and save it in a text file.

**Comment by Perh0rd** [comment]
I reopen this actually; I thought it was gone but it's here again.

**Comment by Perh0rd** [comment]
@planteater  I confirm it works locally, but it does it work on codespace remote workspace using github. 

Here is a video of the problem : https://share.getcloudapp.com/rRuQrXRE

**Comment by planteater** [comment]
Yep, that appears to be the source of the issue. Good news is that we've already got a fix in place. It will go out in a release on Thursday evening. I'll update you here as soon as it's available.

**Comment by Perh0rd** [comment]
@planteater  Thank you so much for your great support and fast help!

**Comment by lukechen526** [comment]
@planteater hi - I just emailed you the log. I am running Codestream on my Win 11 PC locally and it is still having the issue. Thanks.

**Comment by planteater** [comment]
This issue has been fixed in version 14.6 of the CodeStream extension.
