### ISSUE TITLE
VS2022 Startup Crash when ...

### ISSUE THREAD

**Issue by jur-bsw** [TeamCodeStream/codestream#1266]
- IDE Version: VS2022 and VS2022 preview both latest
- OS Version: Win10 latest

Steps to Reproduce:

1. 3 Monitor Setup. 3,2,1 physical order. nr 2 is my main screen in windows
2. work in a solution and put the CodeStream Window on screen 3 or 1
3. close VS
4. Start VS without Solution without Code
5. only in this case VS crashes

My workaround was: Start VS with Solution, move the Window to screen 2, close VS, then "Start VS without Solution without Code" works.

**Comment by CalvinAllen** [comment]
Hey, @jur-bsw, could I trouble you for some log files?

Check out https://docs.newrelic.com/docs/codestream/troubleshooting/client-logs/#visual-studio (your path will be `17.0_` for VS 2022)

You can email them to [codestream@newrelic.com](mailto:codestream@newrelic.com). Thanks!

**Comment by jur-bsw** [comment]
I think the problems are solved by the newest update.
Greetings

JS

Von: Calvin A. Allen ***@***.***>
Gesendet: Mittwoch, 16. November 2022 17:31
An: TeamCodeStream/codestream ***@***.***>
Cc: Jürgen Scheffler ***@***.***>; Mention ***@***.***>
Betreff: Re: [TeamCodeStream/codestream] VS2022 Startup Crash when ... (Issue #1266)


Hey, @jur-bsw<https://github.com/jur-bsw>, could I trouble you for some log files?

Check out https://docs.newrelic.com/docs/codestream/troubleshooting/client-logs/#visual-studio (your path will be 17.0_ for VS 2022)

You can email them to ***@***.******@***.***>. Thanks!
