### ISSUE TITLE
number of differences between the source code and the merge request

### ISSUE THREAD

**Issue by Hoffmman22** [TeamCodeStream/codestream#1267]
- IDE Version: Goland 2022.2.4
- OS Version: Linux Ubuntu 

hi,
I use goland on linux and today I discovered this magnificent plugin.
Many congratulations in advance.

My problem is that I can't see the number of differences between the source code and the merge request.
As shown in the picture.
Can someone help me with this situation please?! Is it something I haven't set up yet?

![315527342_499971615411834_2249025250916871103_n](https://user-images.githubusercontent.com/118385835/202258617-c6f8feed-5826-4dd6-9855-f9d69fe2675a.png)

**Comment by planteater** [comment]
@Hoffmman22 - Last time we checked into this, GitLab's api didn't have support for displaying that info. We'll take another look though to see if anything has changed.
