### ISSUE TITLE
Repo not found in your editor! 

### ISSUE THREAD

**Issue by Polyhistor** [TeamCodeStream/codestream#1274]
- IDE Version: 1.73.1
- OS Version: Manjaro 22.0.0 

Steps to Reproduce:

1. Connect to a Gitlab Repo
2. Review a code
3. Try to review again
4. You will get an error, the repo is not open in your editor

Look at the screenshot below:

![image](https://user-images.githubusercontent.com/8538115/204434955-d39317c9-e052-4c5f-a781-f2dae022365e.png)

The system is literally telling me the pull request is associated to the repo I have open!

**Comment by Polyhistor** [comment]
just assiged myself to another MR, and that worked fine! not sure at what point it breaks.

**Comment by planteater** [comment]
@Polyhistor coukd I trouble you for a log file? You can send it to me at codestream@newrelic.com. Thanks!

https://docs.newrelic.com/docs/codestream/troubleshooting/client-logs/
