### ISSUE TITLE
No way to close window with feedback_request

### ISSUE THREAD

**Issue by Reflector93** [TeamCodeStream/codestream#1278]
- IDE Version: Android Studio Dolphin | 2021.3.1 Patch 1
Build #AI-213.7172.25.2113.9123335, built on September 30, 2022
- OS Version: 
Runtime version: 11.0.13+0-b1751.21-8125866 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12

Steps to Reproduce:

1. Tap on Feedback_requests and select one
2. No way to close it

Hi, in IDE there is not way to exit from feedback request. Thx for reply

![image](https://user-images.githubusercontent.com/83594255/205676471-4e9178ae-52a9-4168-b726-6c05fc485f2b.png)

**Comment by planteater** [comment]
@Reflector93 - Thanks for reaching out. More than likely this is the result of us having to use JxBrowser (instead of native JCEF) to render our webview in Android Studio. We'll dig into it, but hopefully hitting Esc will work for you in the meantime.

**Comment by Reflector93** [comment]
Unfortunately, hitting escape close all widget, Reopen return you also to this window...
No way to avoid it(

**Comment by Reflector93** [comment]
Finally, i've got workaround. Just commit some changes and it changes to another screen. But plz fix it(

**Comment by MiaShopgal** [comment]
I have this issue, too.
My workaround is... create another workspace...
it's really awful to get stuck in nowhere..

**Comment by planteater** [comment]
@Reflector93 @MiaShopgal - Are either of you still experiencing this issue? I haven't been able to reproduce either the issue of the X not appearing, or Esc closing the entire CodeStream window.

**Comment by Reflector93** [comment]
@planteater thx for your feedback
No i see the X, and Esc button also working
version 14.15.2+297
