### ISSUE TITLE
In vscode plugin can't see all issues assigned to me or comments where i mentioned

### ISSUE THREAD

**Issue by melfa** [TeamCodeStream/CodeStream#128]
When in code stream tab neither in channel view nor in search view i can't see all issues assigned to me (or filter by any other user). Maybe i just don't understand workflow, but how one can review all issues assigned to him, or all comments where user is mentioned?

**System Info:**
 - Version of the CodeStream extension: 5.2.0
 - OS + version: MacOS 10.15.1
 - IDE + version: VS Code 1.40.0

**Comment by melfa** [comment]
Our team uses Wrike as issue tracker, but it is not very handy to create issue in external tool, because power of code stream is to see comments/issues right in IDE. I'm create issues (not comments) because my workflow is:
- assign issue to someone
- someone see list of issues assigned to him
- someone fix issue and mark it as resolved
So we need a way to see all issues assigned to someone for this workflow.

**Comment by planteater** [comment]
@melfa - If there are any open issues assigned to you w (which doesn't appear to be the case at the moment), you'll automatically see an "Open Issues Assigned to Me" section at the top of the Search tab (see screenshot). Unfortunately, at the moment there isn't a way to filter by other assignees, but that's definitely coming soon.

![Screen Shot 2019-11-08 at 9 49 46 AM](https://user-images.githubusercontent.com/3442587/68485369-34176400-020d-11ea-97d3-48f59f45b3ed.png)

**Comment by melfa** [comment]
Thank you! Section just appear in developer's CodeStream tab, was not visible before.
