### ISSUE TITLE
Unable to start a review on any pending PR

### ISSUE THREAD

**Issue by palashjhabak** [TeamCodeStream/codestream#1283]
![image](https://user-images.githubusercontent.com/4964924/206676645-d67f7746-0d54-4f76-bfbd-1cb27690e06d.png)

I am on Visual Studio 2022. 

Even if I click on the code block which was changed in the concerned PR, I only get an option to "Add Commend" as opposed to "Start a Review" or "Add Comment on Review"

I don't know if I am missing anything. 

PS: Thanks for such an awesome extension.

**Comment by planteater** [comment]
Thanks for the report @palashjhabak ! We'll dig into this asap.

**Comment by palashjhabak** [comment]
@planteater Thanks for the prompt reply. Its working fine on VS Code. If you need any more details to debug, I will be happy to help.

**Comment by planteater** [comment]
We've got a fix ready to go out on Monday afternoon. In the interim, you can download this pre-release version of the extension if you'd like. 

https://drive.google.com/file/d/1_iERhXTQ4wFR1mAYPhrch64AhECCYwvo/view?usp=share_link

**Comment by palashjhabak** [comment]
@planteater Thanks for the update. Appreciate it.

**Comment by planteater** [comment]
@palashjhabak - This should be fixed in version 14.11 of the CodeStream extension.
