### ISSUE TITLE
Multiline description shown without line breaks when open from search or current file

### ISSUE THREAD

**Issue by melfa** [TeamCodeStream/CodeStream#129]
Create issue with multiline description. Displayed with line breaks when opened from channel view.
Displayed without line breaks when opened from current file view or search view.

Opened from current file view (unresolved):
<img width="1024" alt="Снимок экрана 2019-11-11 в 14 21 02" src="https://user-images.githubusercontent.com/1078418/68583561-83b89280-048e-11ea-966d-dd44c4d89fbb.png">

Opened from search (resolved):
<img width="1021" alt="Снимок экрана 2019-11-11 в 14 15 24" src="https://user-images.githubusercontent.com/1078418/68583370-042ac380-048e-11ea-86eb-563ca3c8bf41.png">

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 5.2.0
 - OS + version: Mac OS 10.15.1
 - IDE + version: VS Code 1.40.0

**Comment by planteater** [comment]
This should be fixed in v7.2.2 of the CodeStream extension.
