### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by NickBolles** [TeamCodeStream/CodeStream#13]
Myself and another friend of mine aren't able to get CodeStream setup in vscode through any of the login methods (codestream code, slack, or codestream account, although the last I'm not 100% sure I'm using the right credentials anyways)

With the codestream code or slack the loader just spins continuously.

**Comment by AchilleLacoin** [comment]
I have the same issue (on Ubuntu mate)

**Comment by eamodio** [comment]
v0.22 will be released shortly that should resolve this issue. Sorry for the inconvenience!

**Comment by AchilleLacoin** [comment]
The update did resolve the issue for me :)

**Comment by NickBolles** [comment]
Sweet! Wicked fast!
