### ISSUE TITLE
Code Stream stealing focus when open on Linux

### ISSUE THREAD

**Issue by pbs-dg** [TeamCodeStream/codestream#1307]
- IDE Version: 2022.3.1
- OS Version: Linux Mint Cinnamon Edition, versions 19.3, 21.1

Steps to Reproduce:

1. Open CodeStream panel
2. Try to click on any menu outside of CS window or type something in editor - you can't 
3. Close CS panel or switch to other tool window (to hide CS) - everything starts to work

**Comment by planteater** [comment]
@pbs-dg - Thanks for reaching out. In your IDE go to Preferences > Tools > CodeStream, and change the state of the "Use JCEF Webview" checkbox (i.e., if already checked, uncheck it, or vice-versa). Let me know if that does the trick.

**Comment by pbs-dg** [comment]
@planteater Yes, it fixed it! I had it checked, so I unchecked it and restarted the IDE.
