### ISSUE TITLE
Error gpg bad revision

### ISSUE THREAD

**Issue by GeovannyGil** [TeamCodeStream/codestream#1317]
- IDE Version: Visual Studio Code 1.74.3 (Universal)
- OS Version: macOS Ventura 13.1

I'm trying to receive feedback or add a comment to my code and have it reviewed through Slack but when I send it, I get this error where it says it's related to gpg, I checked my keys of gpg and I have it right, I don't know what can cause this error.

It happens when creating Feedback Request and in Add Comment, when making Pull Request it does not give me any problem.

Could you please help me to solve it?

`
[2023-01-20 09:32:12:959] handleResponse
Error: Request codestream/codemarks/sharing/create failed with message: Command failed: /opt/homebrew/bin/git -c core.quotepath=false -c color.ui=false show gpg: Signature made Fri Jan 20 02:00:51 2023 CST
gpg:                using EDDSA key C1CDEC01152E20EC1DF3519863E60371F7195FF8
gpg: Good signature from "Geovanny Gil (192.168.1.86) <mydirectionemail@gmail.com>" [ultimate]
3dd5d28e228a6b284a118ced0ec46874669d99d3:./src/tokens/light/misc.js --
fatal: bad revision 'gpg: Signature made Fri Jan 20 02:00:51 2023 CST
gpg:                using EDDSA key C1CDEC01152E20EC1DF3519863E60371F7195FF8
gpg: Good signature from "Geovanny Gil (192.168.1.86) <mydirectionemail@gmail.com>" [ultimate]
3dd5d28e228a6b284a118ced0ec46874669d99d3:./src/tokens/light/misc.js'
`

**Comment by planteater** [comment]
Thanks for reaching out @GeovannyGil! Could I trouble you to send over a complete "CodeStream (Agent)" log?

Reproduce the issue. Then open the Output view in VS Code (View: Toggle Output from the command palette) and select CodeStream (Agent) from the dropdown menu at the top-right. Copy all of the output you see and save it in a text file. If you'd prefer, you can send the file to me at codestream@newrelic.com. Thanks!

**Comment by GeovannyGil** [comment]
Thanks @planteater, I have already sent you the email

**Comment by planteater** [comment]
@GeovannyGil - I think we've got a fix for this. Would you mind installing this pre-release version of the extension and letting us know how it goes? To install, click on the Extensions entry in the activity bar at the left side of VS Code, and then select “Install from VSIX” from the ellipses menu at the top-right of the sidebar. Restart your IDE when prompted.

https://drive.google.com/file/d/1dBD-nZEGgywWWdcb6ZB58k_-XUF5kb4V/view?usp=share_link

**Comment by GeovannyGil** [comment]
Excellent, now everything works great for me.
Thank you, @planteater

![Screenshot 2023-05-16 at 5 04 39 PM](https://github.com/TeamCodeStream/codestream/assets/65850956/90195e0b-abec-4a0b-b89a-23a6823971b8)

**Comment by planteater** [comment]
Thanks @GeovannyGil ! The fix should go out officially in our next release on Friday.

**Comment by GeovannyGil** [comment]
Great, I'll be watching!!
