### ISSUE TITLE
PhpStorm does not connect to youtrack

### ISSUE THREAD

**Issue by yujin1st** [TeamCodeStream/codestream#1319]
- IDE Version: PhpStorm 2022.3.1
- OS Version: MacOS 12.4

Steps to Reproduce:

1. Have latest PhpStorm with CodeStream plugin
2. Try to connect to youtrack cloud with valid credentials

Plugin shows connection error, but if you switch to issue tab - it seems to be loaded, but disappears immediately.

![Снимок экрана 2023-01-23 в 11 20 13](https://user-images.githubusercontent.com/2317913/213965720-905e9195-4626-4868-a914-1cd8e7e00dfb.png)
![Снимок экрана 2023-01-23 в 11 25 50](https://user-images.githubusercontent.com/2317913/213965933-5ea52be2-f6f2-487c-9c22-adc0e89ad963.png)
[phpstorm-logs-20230123-112310999030868236939779.zip](https://github.com/TeamCodeStream/codestream/files/10476773/phpstorm-logs-20230123-112310999030868236939779.zip)

**Comment by planteater** [comment]
@yujin1st - Can you disconnect from YouTrack and then reconnect trying just https://yujin1st.myjetbrains.com as the base URL?

**Comment by planteater** [comment]
Never mind. I'm seeing the same issue with my two test accounts as well. We'll dig in further.

**Comment by planteater** [comment]
@yujin1st - This should be fixed in CodeStream v14.14.

**Comment by yujin1st** [comment]
thank you, will wait

**Comment by planteater** [comment]
@yujin1st - v14.14 should already be available in the marketplace.

**Comment by yujin1st** [comment]
thank you, it works
