### ISSUE TITLE
Codemarks showing up in different repositories with "position lost for this code mark"

### ISSUE THREAD

**Issue by mrjayoc** [TeamCodeStream/CodeStream#132]
**Describe the bug**
I am a computer science teacher using Codestream in my class to give students feedback. All students received a forked version of my original repository. I leave comments on one student's work, and those codemarks are showing up in other students' projects (with "position lost for this codemark"). I have tried to fix the issue by making my original starting repository a template, and use that template to generate a new repository (this way it doesn't have the same commit IDs attached to it like a straight fork would). See screenshots below. The first one is student I left comments for, and the second one is on another student's project when I open their Main.java file

<img width="423" alt="Screen Shot 2019-12-15 at 7 37 26 PM" src="https://user-images.githubusercontent.com/51881054/70871973-689bdf80-1f72-11ea-875f-db0a03120c50.png">

<img width="438" alt="Screen Shot 2019-12-15 at 7 37 48 PM" src="https://user-images.githubusercontent.com/51881054/70871976-6e91c080-1f72-11ea-8ca8-740460203eaa.png">

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 5.2.3+26
 - OS + version: macOS 10.15.1
 - IDE + version: IntelliJ IDEA 2019.3

**Log Files**
Sending log files along with your report will help us investigate the issue. Instructions can be found here: https://github.com/TeamCodeStream/CodeStream/wiki/Instructions-for-finding-CodeStream-log-files

**Comment by mrjayoc** [comment]
After further testing, I think it has something to do with Codestream’s method of using the remote URL to help determine if the repositories are related. All the assignments are named similar, the name of the assignment plus their username. So other than the part of repository name that includes their username, the repositories are named the same. 

I came to this conclusion after I created _brand new_ repositories, but I named the same as before and the issue continued. As soon as I renamed them to something completely different the issue went away. 

I use GitHub Classroom, which helps automate the process of creating a repository for every student. All the repositories are part of the same organization, so each student’s repo is “ORGANIZATION_NAME/Project-Name-Username”. Maybe just knowing how Codestream uses the URL would be helpful (what algorithm is it using to determine if the repositories are “matches” based on the remote URL alone). This way I could rename them in a way that would not cause this issue.

**Comment by planteater** [comment]
@mrjayoc - CodeStream uses both remote URL and commit hashes to try to determine if two developers are looking at the same repo. If the new repos you’re creating really don’t have any commit IDs, and the remote URLs are unique, this should work for you. 

I see one of your repos with two different remotes:

old-colony-voc-tech/java-i-unit-2-arithmetic-performance-assessment-evansouza
old-colony-voc-tech/java-i-unit-2-arithmetic-performance-assessment-christyil

In theory, these should only get grouped together if either a) your copy of the repo had both of these remotes set, or b) the two repos did in fact have a commit commit ID. Are either of those a possibility here?

**Comment by mrjayoc** [comment]
GitHub Classroom has two options when creating an assignment. I create started code and commit that.
1. The the assignments will be _forked_ for each student, which will have the same "initial commit" commit ID.
2. You can turn the original repo into a template, and then create the assignments based off the template (which generate new commit IDs, as the initial commit occurs during the creation of the new copy for the students).

I had a feeling Codestream was using the commit IDs to track, so when I recently created an assignment using the first option I had issues. However I then recreated the assignment using the second option, and at first it seemed to work, but I quickly started having the same issue. Then I renamed them slightly differently and it seemed to resolve:

### Original:
`old-colony-voc-tech/quiz-game-Evan-Souza`  
did _not_ work 
### Renamed
`old-colony-voc-tech/Evan-Souza-quiz-game`  
so far has worked. 

I do not believe the student's repos have the same exact remote URLs, but I can do further testing and find out. I was thinking that Codestream was doing the first part part of the url and if they were close, then it would match

e.g. All the repos would be "matched, because it sees `old-colony-voc-tech/quiz-game`
`old-colony-voc-tech/quiz-game-evansouza`
`old-colony-voc-tech/quiz-game-christyil`

**Comment by planteater** [comment]
@mrjayoc - I suspect that after you first tried option #1, you ended up with some remotes grouped together in a single repo that shouldn't have been. Looking in our database, I do see a couple of repos that have a ton of remote URLs that seem to map to different student names. 

If you were starting from scratch using option #2, I think everything would be fine. Going foward with that option should be fine as well, although there's probably nothing you can do to correct existing codemarks. This is, unfortunately, one of those situations where starting from scratch would be good. Have us clear all the bad data out on our side. But, I see that you have a lot of codemarks in there already and it probably would be less than ideal to lose all of them.

**Comment by mrjayoc** [comment]
That's interesting. I wouldn't have an issue with losing codemarks for the "quiz-game" repos, but if _everything_ needed to be wiped (all codemarks for all repos), then ya that would be a problem (as I have feedback for the students and myself about tests they took).

I mean this seems to be working as far as I can tell, and now know going forward to use a template repo when creating assignments to eliminate the chance of this happening again. Thanks!
