### ISSUE TITLE
Cannot view files in commit even if i have the correct repository open

### ISSUE THREAD

**Issue by collintje01** [TeamCodeStream/codestream#1322]
- IDE Version: PhpStorm 2022.3.1
- OS Version: MacOS Ventura Version 13.1 (22C65)

Steps to Reproduce:

1. load merge request from url
2.error pops up
![Scherm­afbeelding 2023-01-25 om 10 27 52](https://user-images.githubusercontent.com/35344164/214527449-eec4b94f-303a-4f59-b8dd-9063dea82e33.png)

[phpstorm-logs-20230125-1024206715901590497471343.zip](https://github.com/TeamCodeStream/codestream/files/10497884/phpstorm-logs-20230125-1024206715901590497471343.zip)

**Comment by collintje01** [comment]
Looks like my question is to hard to solve for the dev team.

I guess I won't be using codestream.

**Comment by planteater** [comment]
@collintje01 - Apologies for the lack of reply here, but we actually have a developer looking into this right now.

**Comment by planteater** [comment]
@collintje01 - Can you install v14.14 of the CodeStream extension that just went out, and then try again? This issue may be the result of your setup requiring a password to do a git fetch, and this release should clarify that. You could also try a `git fetch -all` from the repo in question and see if that gives a more illuminating error message.

**Comment by collintje01** [comment]
Still Doesn't work.
If I login with the authenticator it shows me a new message when I try to review a merge request that I need to authenticate my gitlab but at that moment it is authenticated.
So I tried using a personal access token to log in but now I get no message to authenticate but I got the same error as before.

[phpstorm-logs-20230206-09050417879258012237934673.zip](https://github.com/TeamCodeStream/codestream/files/10660911/phpstorm-logs-20230206-09050417879258012237934673.zip)

**Comment by planteater** [comment]
@collintje01 Just to confirm, you definitely have that repo open locally in your IDE? Our "show more" info looks like it's actually a bit incorrect as it's including remote repositories. The logs seem to indicate that the repo isn't open in your IDE.

**Comment by collintje01** [comment]
this is my git status:

`
On branch develop
Your branch is up to date with 'core/develop'.

nothing to commit, working tree clean
`

git remote -v

`Memsource_Api_Php       https://gitlab.com/(redacted)/memsource/memsource-api-php.git (fetch)
Memsource_Api_Php       https://gitlab.com/(redacted)/memsource/memsource-api-php.git (push)
Sales_targets   https://gitlab.com/(redacted)/dashboards/sales-targets.git (fetch)
Sales_targets   https://gitlab.com/(redacted)/dashboards/sales-targets.git (push)
core    git@gitlab.com:(redacted)/connect/core.git (fetch)
core    git@gitlab.com:(redacted)/connect/core.git (push)
`
git remote

`Memsource_Api_Php
Sales_targets
core
`

looks like core is open to me

**Comment by planteater** [comment]
The only repo CodeStream perceives you to have open is `/Users/(redacted)/projects/connect` which makes me think that maybe you have a folder containing the repo open, and not the repo itself? Or something along those lines?

**Comment by collintje01** [comment]
Okay then what is the way you would open a repo to successfully connect codestream? maybe if I do it that way it'll work.

**Comment by marcelofarias** [comment]
Hi @collintje01 

Your git repository under /Users/collintersteege/projects/connect contains remotes pointing to 3 different repos

https://gitlab.com/xxxx/memsource/memsource-api-php.git
https://gitlab.com/xxxx/dashboards/sales-targets.git
ssh://git@gitlab.com:xxxx/connect/core.git

so it is being identified as memsource/memsource-api-php, rather than connect/core

Please remove the incorrect remotes, reopen the project and try again.
