### ISSUE TITLE
VSCODE toggle codestream prolem

### ISSUE THREAD

**Issue by cubeeso** [TeamCodeStream/CodeStream#134]
**Describe the bug**
when i click the toggle stream button  ,the codestream window always  reload and signup  ,it consuming my a long time 

**System Info (please complete the following information):**
 - Version of the CodeStream extension: [5.24 139]
 - OS + version: [ Win 7]
 - IDE + version: [ VS Code 1.41]

**Comment by planteater** [comment]
@cubeeso - Could I trouble you for some log files? We'll dig into this asap! Instructions got generating the logs can be found here: https://github.com/TeamCodeStream/CodeStream/wiki/Instructions-for-finding-CodeStream-log-files

**Comment by planteater** [comment]
@cubeeso - Just wanted to follow up on this. If you'd prefer not to post log files here, you can send them to me directly at support@codestream.com. Thanks!
