### ISSUE TITLE
Changed the git and GitHub name of my repo, CodeStream didn't update

### ISSUE THREAD

**Issue by hmbrg** [TeamCodeStream/codestream#1342]
I've had to change the name of my repo. CodeStream continues to work, but no Pull Requests are displayed, because the repos don't match according to CodeStream.

I've tried deleting my account and the repo, but nothing seems to work. 

- IDE Version: VSCode 1.75.0
- OS Version: macOS 13.1

Steps to Reproduce:

1. Signup for CodeStream, setup project with GitHub Repo
2. Change repo name locally and on GitHub
3. Issues start to show: Pull Request are not displayed etc.

**Comment by planteater** [comment]
@hmbrg - Thanks for the report. As long as the remote URL you have configured locally matches the URL of the pull request, things should work. That said, if you can send over a log file we can dig into this more closely. First, reproduce the issue. Then, open the Output view in VS Code (View: Toggle Output from the command palette) and select "CodeStream (Agent)" from the dropdown menu at the top-right. Copy all of the output you see and save it in a text file.

You can send the file to me at codestream@newrelic.com.

**Comment by planteater** [comment]
@hmbrg - Just wanted to follow up on that log file. Thanks!

**Comment by hmbrg** [comment]
Thanks for your answer. You were right, my local remotes were set up incorrectly. After fixing the remotes, CodeStream works perfectly. Sorry for posting an issue before looking into this more!
