### ISSUE TITLE
keymaps & right click won't work when CodeStream is opened in sidebar of PHPStorm

### ISSUE THREAD

**Issue by realgs** [TeamCodeStream/codestream#1347]
- IDE Version: PHPStorm 2022.3.2 Build #PS-223.8617.59 Runtime version: 17.0.5+1-b653.25 amd64
-CodeStream version: 14.8.1+280 -> updated to the newest 14.14.0+291 and still won't work
- OS Version: Ubuntu 22.04.1 LTS

Steps to Reproduce:

1. Open CodeStream from sidebar and leave it opened
![image](https://user-images.githubusercontent.com/5749095/219580952-b4c608b8-7c38-4ee1-bc09-7d0c29e9437e.png)

2. Go to your tab with code
3. Try to right click, or use any shortcut as ctrl+f / ctrl+shift+f / shift+shift etc
4. Won't work. The focus is set to CodeStream tab independently on where you actually place your focus in

**Comment by planteater** [comment]
Apologies for the delayed response on this! Unfortunately it is a problem with the JCEF engine provided by JetBrains. As a workaround, you can have CodeStream use an alternative webview engine by unchecking "Use JCEF WebView" under Settings -> Tools -> CodeStream (requires an IDE restart after changing the setting).
