### ISSUE TITLE
Not showing all github PR review requests

### ISSUE THREAD

**Issue by diannall** [TeamCodeStream/codestream#1355]
- CodeStream Extension version: 14.15.1+295
- IDE Version: 2022.3.1
- OS Version: Mac OS 13.2 (22D49)

Steps to Reproduce:

1. Look at "Pull Requests > Waiting on my Review"
2. There is much less shown there than what is shown in github with the same query

I believe the original query was `is:open is:pr involves:@me`
which wasn't showing everything, so I changed it to `is:open is:pr review-requested:@me`
which is showing nothing... but in github it shows 7 PRs.

**Comment by bcanzanella** [comment]
Hi @diannall are you using github.com or a version of github enterprise? thanks!

**Comment by diannall** [comment]
> Hi @diannall are you using github.com or a version of github enterprise? thanks!

Hi @bcanzanella , we use github.com. It's a private repo, but it doesn't seem like that is the issue since I can see the PRs I created (should have noted that)... although it only shows 2 of the 4 I have up right now.

**Comment by diannall** [comment]
> are all the PRs you're missing from the same repo? is that repo open in your IDE? by any chance is this option in the screenshot below selected?

<img width="251" alt="image" src="https://user-images.githubusercontent.com/2326444/221265806-bbdaba2d-7c20-4445-9914-6315caf97447.png">
 
> something else you could try is reconnecting to github.com (main menu > integrations > github [disconnect], then reconnect using a github.com personal access token [PAT])

I didn't find `main menu > integrations > github [disconnect]` but I did via `Settings > Version Control > Github` and added my github account via token (with all perms). I restarted for good measure... Still nothing showing.
Sorry I just now realized I gave you the IDE version but not IDE name... I'm on phpstorm.

Thanks for the help @bcanzanella

**Comment by diannall** [comment]
> @diannall - Here's where you find the Integrations option. Just click your username at the top of the CodeStream pane.

@planteater ah HA! found it and disconnected, reconnected, restarted phpstorm... still no PRs showing in waiting.

**Comment by planteater** [comment]
@diannall - This is a bit of a long shot, but when you reconnected did you use the personal access token option? Sometimes organizations have restrictions on oauth access that aren't applicable when you use a token. That said, if the PRs that aren't appearing are from the same repo as some of those that are appearing, that would make this scenario unlikely.

**Comment by planteater** [comment]
Hi @diannall - Just wanted to follow up here to see if you had a chance to try the personal access token option. Thanks!

**Comment by diannall** [comment]
@planteater So sorry I forgot to respond. Yes, I did use the personal access token. When I first installed the plugin I saw one PR in the "waiting on my review" but now I don't see any (with either query) and there are 4 that should be showing (per github gui). I _do_ see my own PRs in "created by me", btw.
