### ISSUE TITLE
Using OAuth on Github does not work around REST API rate limit restrictions

### ISSUE THREAD

**Issue by habuchin** [TeamCodeStream/codestream#1363]
- CodeStream Extension version: 14.15.1+295
- IDE Version: GoLand 2022.3.1
- OS Version: MacOS 13.2.1

Steps to Reproduce:

1. OAuth authentication with Github integration
2. After using it for a while, the following message will appear and it will be unavailable thereafter

```
GitHub: Could not resolve to a Repository with the name 'example/example'.: {"response":{"data":{"rateLimit":{"cost":1,"resetAt":"2023-03-01T05:05:48Z","remaining":4720,"limit":5000},"repository":null},"errors":[{"type":"NOT_FOUND","path":["repository"],"locations":[{"line":8,"column":6}],"message":"Could not resolve to a Repository with the name 'example/example."}],"status":200,"headers":{}},"request":{"query":"query getRepoInfo($owner:String!, $name:String!) {\n\t\t\t\t\trateLimit {\n\t\t\t\t\t\tcost\n\t\t\t\t\t\tresetAt\n\t\t\t\t\t\tremaining\n\t\t\t\t\t\tlimit\n\t\t\t\t\t}\n\t\t\t\t\trepository(owner:$owner, name:$name) {\n\t\t\t\t \t\tid\n\t\t\t\t\t\tisFork\n\t\t\t\t \t\tdefaultBranchRef {\n\t\t\t\t\t\t\tname\n\t\t\t\t \t\t}\n\t\t\t\t\t\tnameWithOwner\n\t\t\t\t\t\tpullRequests(first: 25, orderBy: {field: CREATED_AT, direction: DESC}, states: OPEN) {\n\t\t\t\t\t\t\ttotalCount\n\t\t\t\t\t\t\tnodes {\n\t\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\t\turl\n\t\t\t\t\t\t\t\ttitle\n\t\t\t\t\t\t\t\tstate\n\t\t\t\t\t\t\t\tcreatedAt\n\t\t\t\t\t\t\t\tbaseRefName\n\t\t\t\t\t\t\t\theadRefName\n\t\t\t\t\t\t\t\theadRepository { nameWithOwner }\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t \t}\n\t\t\t ","variables":{"owner":"example","name":"example"}}}
```

![Notification_Center](https://user-images.githubusercontent.com/36428658/222047441-e021ed3b-77fe-423a-a62b-49ccbb2cd5f5.png)

We can work around this by using a personal access token, but we want to use OAuth and would like you to provide a way to remove the limit.
Re-authentication and reinstalling the plugin did not resolve the issue.
https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting

Thank you for providing us with a great tool.

**Comment by planteater** [comment]
@habuchin - I don't think this is actually a rate limit issue, but we'll need a log file to really dig into it. After reproducing the issue, in your IDE go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file.

You can send it to me directly at codestream@newrelic.com. Thanks!

**Comment by planteater** [comment]
@habuchin - Just wanted to follow up on that log file. Thanks!

**Comment by planteater** [comment]
@habuchin - I'm going to go ahead and close this out, but if you're still seeing issues, please reach out to us at codestream@newrelic.com. Thanks.
