### ISSUE TITLE
Cannot Login in vscode remote development (remote ssh)

### ISSUE THREAD

**Issue by jhh9232** [TeamCodeStream/codestream#1367]
- CodeStream Extension version: 14.15.2 (recent version)
- IDE Version: Visual Studio Code (Portable) 1.75.1
- OS Version: Local ) Windows 10 21H2, Remote ) Ubuntu 18.04.3 LTS

Steps to Reproduce:

1. In version 14.15.2, I can't login from vscode remote ssh.
2. However, in version 14.14.0, it works fine.

![error_message1](https://user-images.githubusercontent.com/25794008/223068918-1264d3c0-a437-48ab-a894-085c10d6bf1c.png)
![error_message2](https://user-images.githubusercontent.com/25794008/223068936-6a34daa2-23fa-4334-b6bb-a5869912417e.png)

**Comment by planteater** [comment]
Thanks for reaching out @jhh9232. I think we might need a log file for this one.

First, reproduce the issue. Then open the Output view in VS Code (View: Toggle Output from the command palette) and select CodeStream (Agent) from the dropdown menu at the top-right. Copy all of the output you see and save it in a text file.

You can send the file to me directly at codestream@newrelic.com. Thanks!

**Comment by CalvinAllen** [comment]
Hey @jhh9232, I'm picking up this issue - will be in touch once I have some more information!

**Comment by CalvinAllen** [comment]
@jhh9232 Out of curiosity, after you upgraded, do you have (still have) a "Region" selected on the initial pane for CodeStream?

![image](https://user-images.githubusercontent.com/41448698/223533011-fdc26f84-db32-4263-9f08-8d5a70612f3c.png)

**Comment by jhh9232** [comment]
Yes. US is selected.

[image: image.png]

I logged out in version 14.14.0 and upgraded to version 14.15.2. After I
tried to log in again.

Unlike before, login was successful.
However, I couldn't see and create merge requests.

[image: image.png]

It's my settings.
[image: image.png]



2023년 3월 8일 (수) 오전 4:33, Calvin A. Allen ***@***.***>님이 작성:

**Comment by jhh9232** [comment]
I am attaching the broken image file together. Sorry for the inconvenience.

**Comment by planteater** [comment]
@jhh9232 Doesn't look like the images came through. If you'd prefer, you could try sending them to me directly at codestream@newrelic.com.

**Comment by jhh9232** [comment]
I am attaching the broken image file together. Sorry for the inconvenience.

2023년 3월 8일 (수) 오후 11:08, David Hersh ***@***.***>님이 작성:

**Comment by jhh9232** [comment]
The picture is not attached to the email.
I'll attach the picture here.

![1](https://user-images.githubusercontent.com/25794008/224183691-0a117a2d-cf3c-4c3e-8a7d-7429317cffa8.png)

![2](https://user-images.githubusercontent.com/25794008/224183693-81982a35-8c10-4e8f-924c-2a8976ce4353.png)

![3](https://user-images.githubusercontent.com/25794008/224183697-07e01141-b167-4152-b660-3c449ddee46e.png)

Thanks.

**Comment by CalvinAllen** [comment]
Hey @jhh9232, we pushed an update yesterday for v14.16.1 - can you give that a try and let us know? It takes care of an issue we were seeing with Linux hosts. Thanks!

**Comment by jhh9232** [comment]
It works well in version 14.16.1.
Thank you for fixing it.
