### ISSUE TITLE
Slack slash-command support

### ISSUE THREAD

**Issue by tsaodown** [TeamCodeStream/CodeStream#137]
Doesn't seem like CodeStream messages respond to slash-commands that are integrated with our Slack workspace. For example, I use [timy](https://timy.website/) to send scheduled messages to my team members. To do so, I send a `/send <msg> at <time>` command on the standard Slack client, but when I try the same command through CodeStream, the message gets sent as plain-text.

Is there some configuration/interaction I'm missing here, or is this a limitation of CodeStream's Slack integration?

**Comment by planteater** [comment]
@tsaodown - You are correct in that most Slack slash commands will not work from CodeStream. Unfortunately, this is unlikely to change.
