### ISSUE TITLE
Telemetry chart sometimes cuts off a significant amount of data due to poorly selected vertical scale

### ISSUE THREAD

**Issue by mhenry-cb** [TeamCodeStream/codestream#1378]
- CodeStream Extension version: 14.16.0.2656
- IDE Version: Visual Studio 2022 (17.5.1)
- OS Version: Windows 10 Pro 22H2 (19045.2604)

Steps to Reproduce:

1. Click the CodeStream CodeLens summary for a method.
2. Click "View charts and change entity selection" from the Code Level Metrics popup.
    - ![image](https://user-images.githubusercontent.com/80974267/224189195-d41cf972-5de6-4144-a651-3670fad88e77.png)
3. In some cases, the chart uses a vertical scale which cuts off a significant amount of data. In this example, the avg. duration was 153 ms, but the chart range is 0 to 100 ms, so there are many data points above 100 ms which get cut off, including average values.
    - ![image](https://user-images.githubusercontent.com/80974267/224189615-161bbf7c-74d6-4f0f-a532-ac9115ab65df.png)
    - This is intermittent but I see it happen fairly often. In some cases, the scale is ok and shows the majority of data points, but in some cases it cuts off a lot of data points like above.

Secondary issue: Samples is missing from the Code Level Metrics popup even though it shows in the CodeStream CodeLens summary. This happens consistently.

**Comment by CalvinAllen** [comment]
@mhenry-cb This issue has been resolved and QA'd and should be out in a release soon!  Thanks for reporing it 👍🏻

**Comment by CalvinAllen** [comment]
@mhenry-cb This issue should be resolved with a release that went out earlier today. Going to go ahead and close this, but let us know if you run into the issue again (or have any others!) Thanks!
