### ISSUE TITLE
We were not able to authenticate you (error: RAPI-1010)

### ISSUE THREAD

**Issue by linwh1115** [TeamCodeStream/CodeStream#138]
**Describe the bug**
When I try to connect GitLab Self-Managed, the configure information according to the [document](https://github.com/TeamCodeStream/CodeStream/wiki/Configuring-the-GitLab-Self-Managed-Integration), but
  It reported a `We were not able to authenticate you (error: RAPI-1010). ` error，

**System Info (please complete the following information):**
 - Version of the CodeStream extension: [e.g. 5.2.5]
 - OS + version: [e.g. MacOS 10.13.6]
 - IDE + version: [e.g. VS Code 1.41.1]

**Log Files**
Sending log files along with your report will help us investigate the issue. Instructions can be found here: https://github.com/TeamCodeStream/CodeStream/wiki/Instructions-for-finding-CodeStream-log-files

**Comment by planteater** [comment]
@linwh1115 - is the url for your GitLab instance publicly accessible, or is it behind a firewall?

**Comment by planteater** [comment]
@linwh1115 - Wanted to follow up on my previous question. I ask because currently our on-prem integrations require that they be publicly accessible. We're coming out with new integrations that leverage personal access tokens so that this requirement goes away, but those are still a number of weeks away.

**Comment by linwh1115** [comment]
I'm sorry to reply so late，I think the url for my GitLab instance is not publicly accessible，so i'm look forward to the day of your team provide leverage personal access tokens.

**Comment by planteater** [comment]
@linwh1115 - I wanted to let you know that v7.1.0 of the CodeStream extension that was just released now includes an all new integration with GitLab Self-Managed. This integration uses personal access tokens and it is no longer a requirement that your GitLab instance be publicly accessible.
