### ISSUE TITLE
I can't see PR from my BitBucket (cloud) repo 

### ISSUE THREAD

**Issue by cubocicloide** [TeamCodeStream/codestream#1382]
I am able to see the issues and codemarks, and I can create Jira issues, but I can't see the PR from my BitBucket (cloud) repo (in the PULL REQUESTS section, I see:

<img width="1478" alt="Screenshot 2023-03-13 at 10 36 17" src="https://user-images.githubusercontent.com/20613071/224662846-22ca70fb-b8f5-4df4-8853-6afc62ed8908.png">

**Comment by planteater** [comment]
@cubocicloide - Our Bitbucket support should be ready soon. Please follow this issue:
https://github.com/TeamCodeStream/codestream/issues/372

**Comment by cubocicloide** [comment]
Thanks @planteater . Can't wait to see it live.
