### ISSUE TITLE
Could not connect to GitLab Self-Managed

### ISSUE THREAD

**Issue by MiaShopgal** [TeamCodeStream/codestream#1398]
- CodeStream Extension version:14.16.2+302
- IDE Version:Android Studio Flamingo | 2022.2.1 Beta 5 / Build #AI-222.4459.24.2221.9682058, built on March 3, 2023
- OS Version:macOS 13.2.1 (22D68)

Steps to Reproduce:

1. Having a GitLab Self-Managed server which version is 15.9
2. Open CodeStream Plugin
3. Provide a new created personal access token
4. Saw Could not connect. Please verify your base URL and personal access token.

![image](https://user-images.githubusercontent.com/2044967/227086595-2830ede4-e2a1-4a66-b8c1-80ffadc1bf9e.png)
![image](https://user-images.githubusercontent.com/2044967/227086992-3b732fb2-fa4e-481b-8ae0-60fc294ad65e.png)

**Comment by planteater** [comment]
@MiaShopgal - One thing to make sure of is that you used a Personal access token and not a Project access token.

**Comment by MiaShopgal** [comment]
> @MiaShopgal - One thing to make sure of is that you used a Personal access token and not a Project access token.

It's a Personal Access Token 

![image](https://user-images.githubusercontent.com/2044967/227405202-ac471b18-8c7f-4bef-bb38-2dc34e917246.png)

**Comment by planteater** [comment]
I don't see anything obvious with your account. The one thing I might suggest is check the base URL your teammate Cary is using, as she seems to be connected to GL successfully.

**Comment by MiaShopgal** [comment]
> I don't see anything obvious with your account. The one thing I might suggest is check the base URL your teammate Cary is using, as she seems to be connected to GL successfully.

Cary, he leaved us.. :(

I can't manage the meam from https://api.codestream.com/web/login 

I got Nick to check upon his status.

He got this

![image](https://user-images.githubusercontent.com/2044967/227669778-23c16d6c-6bd5-4789-a709-d9ee21ec971f.png)


Just like me before. 
I remove the integration of gitlab to give it another try, and this issue is what I got from there.

And today I open the IDE and saw CodeStream loading.... forever

![image](https://user-images.githubusercontent.com/2044967/227671211-ca37d7be-2eb2-4259-ba45-caa6a5319b0f.png)

I also update to 14.17.0+304, but the loading stays...

**Comment by MiaShopgal** [comment]
I found this image, it's vanished like a flash! 
I have to use recording to capture it, apology for the quality.

![image](https://user-images.githubusercontent.com/2044967/227694616-247fa501-ece2-4b50-81fb-e6c129e00796.png)

**Comment by planteater** [comment]
Based on the screenshot in your previous post, it seems like you might need to disable Strict SSL:

https://docs.newrelic.com/docs/codestream/troubleshooting/proxy-support/

**Comment by MiaShopgal** [comment]
I turn it off and restart IDE, the issue remains.

![image](https://user-images.githubusercontent.com/2044967/228101467-244b7384-85a9-44a6-8e76-b313453d9e72.png)

**Comment by planteater** [comment]
Actually, you'll want that box checked. But, obviously things weren't working then either so I think we'll need a log file to dig into this. First, check that "Allow self-signed certificates" box again and then restart your IDE. Now trying to connect to GitLab again, and then grab a log file. You can do so by going to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file.

You can email it to me at codestream@newrelic.com. Thanks!

**Comment by planteater** [comment]
@MiaShopgal - I'm going to close this for now, but let's pick it up via email when you send in that log file. Thanks!

**Comment by cstryker** [comment]
@MiaShopgal @planteater is out for a few days and has asked me to look at your log file. It appears you are still having certificate related issues, which are difficult for us to diagnose because we don't know the details of your network setup. One option that may help is if you can get a hold of the certificate(s) in use on your network, and copy them into a file, then there is an "Extra Certs" option in your CodeStream settings. Paste the full path to your certificate file into this setting, then restart your IDE. If that still doesn't fix it, send another log file as there may be additional information I can use to help. Other than that, you may need help from your network manager to better understand the certificate chain between CodeStream and your GitLab server.

**Comment by MiaShopgal** [comment]
> @MiaShopgal @planteater is out for a few days and has asked me to look at your log file. It appears you are still having certificate related issues, which are difficult for us to diagnose because we don't know the details of your network setup. One option that may help is if you can get a hold of the certificate(s) in use on your network, and copy them into a file, then there is an "Extra Certs" option in your CodeStream settings. Paste the full path to your certificate file into this setting, then restart your IDE. If that still doesn't fix it, send another log file as there may be additional information I can use to help. Other than that, you may need help from your network manager to better understand the certificate chain between CodeStream and your GitLab server.

Hi @cstryker 
Thanks for these info, I don't know how to have this certificate at the moment. I'll keep trying, thank you. :)

**Comment by planteater** [comment]
@MiaShopgal - I'm going to close this out for now, but if you're still experiencing issues once you add the certificates please email me at codestream@newrelic.com. Thanks
