### ISSUE TITLE
Definition of build process

### ISSUE THREAD

**Issue by bostandyksoft** [TeamCodeStream/codestream#1408]
Hi. 

My team need Azure PR feature, so i want to study ability to develop this feature. I've tried to build JB IDEA plugin, but have many errors from UI components like following:

```
stream/MessageInput.tsx(943,5): error TS2786: 'Menu' cannot be used as a JSX component.
  Its instance type 'Menu' is not a valid JSX element.
```

Is there some guide - how to build plugin localy? 

Best regards

**Comment by bcanzanella** [comment]
hi @bostandyksoft some documentation for building these shared components can be found at https://github.com/TeamCodeStream/codestream/blob/develop/jb/docs/dev.md
