### ISSUE TITLE
Installing VS Code editor extension doesn't pop up right-side view

### ISSUE THREAD

**Issue by sqs** [TeamCodeStream/CodeStream#141]
The wiki page at https://github.com/TeamCodeStream/CodeStream/wiki/Installing-CodeStream says:

> Once you've installed the extension, the CodeStream view should automatically appear at the right side of your editor. If for some reason it doesn't, simply click on the CodeStream entry in your IDE's status bar. Just look for the double chat bubble icon.

After I installed CodeStream, though, I didn't see anything on the right side. I do see the "Sign in..." in my status bar.

**Comment by planteater** [comment]
@sqs - Not sure why the CodeStream pane didn't display automatically, but if you click on that "Sign in..." in the status bar that should do the trick. You can use that status bar entry to toggle CodeStream at any time. There's also a "CodeStream: Toggle CodeStream" entry in the command palette.
