### ISSUE TITLE
Error fetching cards from Jira: Jira access does not include any jira sites

### ISSUE THREAD

**Issue by torqataNate** [TeamCodeStream/codestream#1418]
Jira interation has been working fine for a yearish,   now i continually get this warning.    Not sure what the action to take is

**Comment by bcanzanella** [comment]
Hi @torqataNate could you send a copy of your CodeStream logs to us here: codestream@newrelic.com

Instructions can be found here: https://docs.newrelic.com/docs/codestream/troubleshooting/client-logs/ 

thanks

**Comment by planteater** [comment]
@torqataNate - I'm going to close this issue for now, but if you get a chance to grab that log file and send it over, we'll pick up the issue from there. Thanks!

**Comment by torqataNate** [comment]
Ah didn't see the comments. Open it back up I'll try and getva log

**Comment by torqataNate** [comment]
Sent

**Comment by planteater** [comment]
@torqataNate - The logs indicate that our call to jira's /oauth/token/accessible-resources, which checks that your auth token is working, is giving us a 0 length response. I think the best bet would be to try reconnecting to Jira. Click on your username at the top of CodeStream and then select Integrations. From there click on the green Jira button to disconnect, and then reconnect. If you're using Jira Server, I'd suggest creating a new personal access token, or checking to see if your current one is expired.

**Comment by planteater** [comment]
Hi @torqataNate - Wanted to follow up here to see if you were still experiencing issues with the Jira integration.

**Comment by planteater** [comment]
I'm going to close this for now, but reach out to me at codestream@newrelic.com if you're still seeing any issues.
