### ISSUE TITLE
Prefer opening a web browser when creating an account

### ISSUE THREAD

**Issue by sqs** [TeamCodeStream/CodeStream#142]
I am installing CodeStream in VS Code. After clicking "Sign in..." and choosing to create a new account, I see the form is in a VS Code webview:

![image](https://user-images.githubusercontent.com/1976/72560871-c4e96c00-385c-11ea-997c-aa045f27346a.png)

I would prefer for the form to open in my default web browser because I use a password manager (1Password) and want to save my account credentials to it.

If I create my account credentials in a VS Code webview, I need to manually create a new login in 1Password. I might not, and then it would be a pain to sign in next time.

**Comment by planteater** [comment]
@sqs - We did have a web-based signup flow at one point, but the jumping back and forth between the web and the IDE didn't prove to be a good user experience. We do, however, plan to offer sign in via GitHub and other SSO options in the near future.
