### ISSUE TITLE
Unable to type text into new comment for code

### ISSUE THREAD

**Issue by LoganFoxUK** [TeamCodeStream/codestream#1421]
- CodeStream Extension version: 14.17.0+304(EU)
- IDE Version: Rider 2023.1 Build #RD-231.8109.212, built on April 4, 2023 
- OS Version: Ubuntu 22.04.2 LTS

Steps to Reproduce:

1. Select a line in the code to add a comment
2. Either right click to add a comment or use the icon that appears in the left of the editor to add a comment, either approach is fine
3. When the add comment dialogue appears I'm unable to type anything in, it's as if I've unplugged my keyboard.  I can however use the mouse to say insert an emoticon.  Bizarrely the backspace key is still recognised so I can still delete text.  The only workaround really at the moment is to write a comment in a text editor, then paste it into the add comment dialogue box.

Steps to resolve:
- Rebooted
- Restarted the IDE
- Uninstalled and reinstalled the plugin (requiring a reboot of the IDE between steps)

**Comment by kjoshi31** [comment]
@LoganFoxUK what operating system are you using?

**Comment by LoganFoxUK** [comment]
Hi @kjoshi31 
Just realised I had a copy and paste fail in my original post.  I've edited and updated to show the OS as: Ubuntu 22.04.2 LTS
 :)

**Comment by kjoshi31** [comment]
@LoganFoxUK thank you! also, is this happening frequently or is this the first time you've seen this issue occur?

**Comment by kjoshi31** [comment]
@LoganFoxUK thanks for bringing this up, terribly sorry you're experiencing this. We have our team looking into it and will resolve soon!

**Comment by LoganFoxUK** [comment]
Bingo!  That did the trick :) Long term, I guess it's ok to leave this disabled for CodeStream?  Thanks again for investigating and helping to get things sorted.

**Comment by vincent-debes** [comment]
Hi,

Sorry to re-open this issue but the workaround did not work for me. Here is my config :  
```
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=21.1
DISTRIB_CODENAME=vera
DISTRIB_DESCRIPTION="Linux Mint 21.1 Vera"
NAME="Linux Mint"
VERSION="21.1 (Vera)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.1"
VERSION_ID="21.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=vera
UBUNTU_CODENAME=jammy
```
Is there any other workaround ? I already miss this plugin :disappointed:

**Comment by planteater** [comment]
Thanks for reaching out @vincent-debes. Just to confirm, the steps to reproduce are the same as in the original report here?

**Comment by vincent-debes** [comment]
Sorry, I deleted previous post without noticing your reply. This is fixed in latest release on my side, so all good! Thank you for this great work, this plugin is awesome :+1:
