### ISSUE TITLE
Unclear if Team Name is conventionally capitalized or lowercase

### ISSUE THREAD

**Issue by sqs** [TeamCodeStream/CodeStream#143]
In VS Code's webview I see this form:

![image](https://user-images.githubusercontent.com/1976/72561070-3c1f0000-385d-11ea-8cac-893f98b08ee8.png)

Is my team name a Unix username-like thing (conventionally lowercase, like `sourcegraph`) or a SaaS app team name-like thing (conventionally capitalized, like `Sourcegraph`)? I am not sure. I capitalized it, but I may regret that.

**Comment by planteater** [comment]
@sqs - Think of it kind of like your Slack workspace name. Capitalized is totally fine.
