### ISSUE TITLE
[Question] Show issues/PR for open project only

### ISSUE THREAD

**Issue by tomaae** [TeamCodeStream/codestream#1440]
Hi,
I manage several open source projects and would like to see only issues and PR for currently open project no matter who it is assigned to.
If I set up a filter, it is persistent across all projects, not just current one. So I would have to change all filters every time I open UI.
Is there any solution for this?

**Comment by planteater** [comment]
Hi @tomaae! For PRs you can accomplish this by clicking on the gear icon in the heading of the Pull Requests section, and then checking the "Only show PRs from open repos" option in the menu. Unfortunately, we don't currently have a similar option for issues, but an updated UX we have planned for a few months from now will likely address this.

**Comment by tomaae** [comment]
> 

Hi, I noticed that in PR, but it still shows PR from other projects from same platform (github), but hides ones from different platform (gitlab).
Making filters project specific, instead of global would help here a lot.

**Comment by planteater** [comment]
If your custom PR query includes a specific repo, that will override the "one show PRs from open repos" setting. But now that you have that setting on, I assume the project-specific queries aren't really necessary anymore?

**Comment by tomaae** [comment]
No, that is the behavior without custom query. I have removed all custom queries when I tested it.
