### ISSUE TITLE
Text boxes do not work in Clion

### ISSUE THREAD

**Issue by VintageDesign** [TeamCodeStream/codestream#1446]
- CodeStream Extension version: 14.18.1+307
- IDE Version: Clion 23.1.1
- OS Version: Ubuntu 22.04.2 LTS

I've tried most of the text boxes in the code stream window and none of them allow me to put info in. I have tried with all my other plugins disabled and I have the same issue.

Steps to Reproduce:

1. Install CodeStream
2. Attempt to create an account via email.

**Comment by marcelofarias** [comment]
Hi @VintageDesign. I wasn't able to reproduce the issue using the same OS and IDE versions you mentioned. That being said, it is likely a problem in the WebView engine used to render the CodeStream UI and it is usually intermittent (might go away if you click on an editor and then back in the CodeStream tool window).

If the problem persists, you can try switching engines by checking/unchecking "Use JCEF WebView" under Settings -> CodeStream (requires an IDE restart after changing the setting) - it often helps especially on Linux environments.
