### ISSUE TITLE
Comment icon is misaligned with selection

### ISSUE THREAD

**Issue by sqs** [TeamCodeStream/CodeStream#145]
The comment icon is 3-4 lines below my selection when the selection is near the bottom of the viewport:

![image](https://user-images.githubusercontent.com/1976/72561431-121a0d80-385e-11ea-9831-3a7c11021700.png)

When the selection is near the top, it is closer to proper alignment (but still ~1 line too low).

![image](https://user-images.githubusercontent.com/1976/72561470-265e0a80-385e-11ea-827b-89e20a34e992.png)

Possibly relevant settings:

* Font size = 14
* Font = monaco
* Zoom level = 3
* Linux

**Comment by keegoid-nr** [comment]
I also have this issue. New install on code-insiders. The CodeStream comment icons are too low and don't line up with the matching line of code.

- Font size: 14
- Font family: Ubuntu Mono
- Zoom level: 0
- Font weight: normal
- Line height: 0
- Ubuntu

**Comment by planteater** [comment]
@keegoid-nr - Are you still seeing this issue with more recent versions of CodeStream?
