### ISSUE TITLE
Can't type / in Webstorm

### ISSUE THREAD

**Issue by maxbeba** [TeamCodeStream/codestream#1451]
- CodeStream Extension version:
- IDE Version: Webstorm 2023.1
- OS Version: MacOS 13.3.1

![image](https://user-images.githubusercontent.com/129515369/235422804-b30493dc-08c5-480c-9c01-6b8e4c7c080e.png)

Steps to Reproduce:

1. Get a german keyboard layout and a Mac
2. Open a branch in CodeStream
3. Type the slash character

I reported almost the same to the NRWL guys for NX Console. 
Maybe this is actually an issue with Jetbrains?
https://github.com/nrwl/nx-console/issues/1707

**Comment by planteater** [comment]
Thanks for the report @maxtranslaya - We'll dig in and follow up later.

**Comment by maxbeba** [comment]
@marcelofarias You saved my day 🤣 
No more copy paste of slash chars

I'll report it

**Comment by MaxKless** [comment]
Hey! I'm a maintainer of Nx Console and we had another issue filed for this behavior. 
Are you folks sure it's a JCEF issue? 
When I test this locally via `runIde`, the JCEF behaves differently from the installed version. That makes me think there's something more going on.

**Comment by MaxKless** [comment]
Sorry that I wasn't clear here. I'm saying that in Nx Console, we get the wrong behaviour in intellij `2023.1` but if we go back to `2022.3` (by using `runIde`), the correct characters are typed.
Are you seeing the same?
