### ISSUE TITLE
Unclear that duplicated shortcut label means keychord

### ISSUE THREAD

**Issue by sqs** [TeamCodeStream/CodeStream#146]
In VS Code I see the keyboard shortcuts are labeled:

![image](https://user-images.githubusercontent.com/1976/72561573-5b6a5d00-385e-11ea-801d-092e7f118288.png)

I was confused by the "Toggle CodeStream Panel" label. I did not realize it meant pressing Ctrl-Shift-/ 2x because the labels are on 2 different lines. Here is how a similar keychord is shown in VS Code for comparison (on 1 line):

![image](https://user-images.githubusercontent.com/1976/72561646-7f2da300-385e-11ea-967f-0bb9395a7707.png)

This is minor.

**Comment by ppezaris** [comment]
Should be fixed in the next release.

**Comment by planteater** [comment]
Fixed in v6.0.1
