### ISSUE TITLE
In 2x1 split view VS Code, opening CodeStream view opens new editor

### ISSUE THREAD

**Issue by sqs** [TeamCodeStream/CodeStream#147]
I always use VS Code with 2 editors like this:

![image](https://user-images.githubusercontent.com/1976/72561854-f4997380-385e-11ea-9c91-52e0ec184f2a.png)

If I am in the left editor and comment or toggle open the CodeStream panel, it (as desired) opens it in the right editor. This is what I want:

![image](https://user-images.githubusercontent.com/1976/72561936-2579a880-385f-11ea-859b-769e024aba95.png)

If, however, I do that in the right editor, it opens a 3rd editor to the right, which I don't like. I would prefer for it to take over the left editor (the one I am not focused in). This is not what I want:

![image](https://user-images.githubusercontent.com/1976/72561997-43470d80-385f-11ea-96e5-4d7abc73de6b.png)

It would also be OK (maybe preferable) if it opened a peek webview or if it used VS Code's existing discussions provider UI.

**Comment by planteater** [comment]
@sqs - I'm going to lump this in with the following issue, which is ultimately where we want to go (although VS Code may in fact give us more control over our pane at some point).

https://github.com/TeamCodeStream/CodeStream/issues/19
