### ISSUE TITLE
Web dropdown menu is misaligned

### ISSUE THREAD

**Issue by sqs** [TeamCodeStream/CodeStream#148]
![image](https://user-images.githubusercontent.com/1976/72562189-adf84900-385f-11ea-91a3-a846996f6918.png)

The dropdown menu covers up the button. I think it should expand down, with the top of the menu at the bottom of the button, on my screen. (Minor)

**Comment by planteater** [comment]
This should be good now, largely through a redesign of the page that moves the dropdown to the top.
