### ISSUE TITLE
Open in VS Code did not work

### ISSUE THREAD

**Issue by sqs** [TeamCodeStream/CodeStream#149]
From https://api.codestream.com/c/XiDJ3k5gmy-JI5WE/brIWCe9eTRCqtm0z6QfZIg?identify=true&provider=CodeStream, when I click "Open in VS Code", nothing happens. My JS console log says:

```
CodeStream: success in 0.414s for Moniker=vsc Path=vscode://codestream.codestream/codemark/5e20cdc…/open?repoId=5e20c9e…&marker=5e20cdc…
```

but nothing changes in VS Code.

I am running on Linux and might need to fix my URI scheme registrations. But some kind of debug instructions or info would be nice. Slack shows a helpful message if you visit a Slack URL in your browser and remain at the page for a while (it assumes the Slack app was not able to open). You could do this.

**Comment by MozyOk** [comment]
I get the same error in "open in IntelliJ IDEA". In my browser console log error says "missing markerId". It might be a bug with this part of the code. FYI.

**Comment by planteater** [comment]
@MozyOk - I’ll reach out to you directly via email, as I suspect yours is a different issue.

**Comment by planteater** [comment]
This should be working now.
