### ISSUE TITLE
Unable to open japanese name channels.

### ISSUE THREAD

**Issue by 92thunder** [TeamCodeStream/CodeStream#15]
I tried to open a channel using Japanese characters (`開発`, `フロントエンド` ), but no message was displayed.

It just opened page like below and didn't change from here.
![image](https://user-images.githubusercontent.com/3332571/48687148-1ec3b700-ec03-11e8-9dce-f6fa395070b4.png)

**Comment by planteater** [comment]
Thanks for the report @92thunder. We'll get this fixed asap!

**Comment by eamodio** [comment]
This has been fixed in CodeStream v0.30
