### ISSUE TITLE
Blank screen on PHPStorm

### ISSUE THREAD

**Issue by eskimetalci** [TeamCodeStream/CodeStream#150]
The status bar shows me that It logged in my slack profile successfully but the CodeStream window goes completely blank. 

I tried on 2019.3, 2019.2, and 2018.3 versions of PHPStorm. 
I reinstalled the IDEs and plugins multiple times but no change.

**Comment by planteater** [comment]
@eskimetalci - Could I trouble you to send us a log file? Instructions can be found here:

https://github.com/TeamCodeStream/CodeStream/wiki/Instructions-for-finding-CodeStream-log-files

If you'd prefer, you can email the file to me at support@codestream.com

Once you grab the log file, try selecting "CodeStream: Sign out" from the action list in PHPStorm, and then sign back in. Let me know if that does the trick.
