### ISSUE TITLE
Proxy doesnt work

### ISSUE THREAD

**Issue by almirus** [TeamCodeStream/CodeStream#151]
**Describe the bug**
Cant connect via Proxy localhost:3128

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 6.0.0+29
 - OS + version:. Win 10
 - IDE + version: IntelliJ IDEA 2019.3.2 (Ultimate Edition)
Build #IU-193.6015.39, built on January 21, 2020
Runtime version: 11.0.5+10-b520.30 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 974M
Cores: 12
Registry: debugger.watches.in.variables=false, debugger.valueTooltipAutoShowOnSelection=true, compiler.automake.allow.when.app.running=true
Non-Bundled Plugins: com.intellij.plugins.watcher, CMD Support, Lombook Plugin, com.arcbees.plugin.idea, com.codestream.jetbrains-codestream, com.codota.csp.intellij, com.jetbrains.plugins.ini4idea, com.perl5, com.perl5.lang.mason.framework, com.perl5.lang.mason.htmlmason, izhangzhihao.rainbow.brackets, me.laria.code.idea_caseconv

**Log Files**
[idea-logs-20200128-104608.zip](https://github.com/TeamCodeStream/CodeStream/files/4121206/idea-logs-20200128-104608.zip)

![image](https://user-images.githubusercontent.com/16898685/73426878-87014300-4346-11ea-9768-ce48506fcf34.png)

![image](https://user-images.githubusercontent.com/16898685/73426998-d3e51980-4346-11ea-9b9c-e13c71651549.png)

![image](https://user-images.githubusercontent.com/16898685/73242248-808f9180-41b5-11ea-8cf2-d46b8e2b8742.png)

**Comment by marcelofarias** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GH #151 - Proxy doesn't work](https://trello.com/c/uzbipza8/2997-gh-151-proxy-doesnt-work)

**Comment by planteater** [comment]
@almirus - Fixed in v6.1.1 which just hit the marketplace.
