### ISSUE TITLE
Intellij IDEA: Login failed: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by kevinsarsen** [TeamCodeStream/CodeStream#152]
I have been using CodeStream with Intellij IDEA for a couple of months using Slack to sign in. With the recent change to requiring a CodeStream account I was forced to change how I did things. 

First, signing in with Slack gave me

`Invalid Credentials
Please sign in using your email address and CodeStream password.`

But since I'd never explicitly created a CodeStream password, I figured I needed to create a CodeStream account along with specifying a team. But when I tried to do that, it said I already had an account and to use it to log in. Since I'd never set a CodeStream password, I used the "Forgot password?" link to set a password, which showed a success. All good so far.

Then, back to IDEA to login with my email address and new password. But when I tried to login with the new password, I get 

`Request codestream/login/password failed with message: Login failed: Cannot read property 'id' of undefined.`

This may be related to #55

**Comment by kevinsarsen** [comment]
Nvrmnd...I had to use the original Slack workspace I'd used from the beginning, not just any of my Slack workspaces.

**Comment by planteater** [comment]
Phew! Had me worried there for a sec @kevinsarsen. Note that the migration that will require you to set a password and start signing in that way should happen in the next day or two.
