### ISSUE TITLE
Keytar Migration Plan

### ISSUE THREAD

**Issue by TylerLeonhardt** [TeamCodeStream/codestream#1528]
Hello :wave: I'm Tyler from the VS Code team. I'm opening this issue because you use the [keytar](https://github.com/atom/node-keytar) shim that VS Code provides.

Keytar is [officially archived](https://github.com/atom/node-keytar) and not being maintained... In an effort to promote good security practices by _not_ depending on an archived piece of software for storing secrets, we are working on a plan to remove this shim from VS Code. We want to communicate this to you so we minimize the disruption due to this change, hence this issue. I know this isn't the best news... we had a fair amount of work to remove our dependency on keytar as well, but we believe this is the right thing to do to ensure extensions are using secure APIs.

There are a couple of options for you to consider:
* _(recommended)_ Use the [SecretStorage API](https://code.visualstudio.com/api/references/vscode-api#SecretStorage) that VS Code provides on the [ExtensionContext](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext). This API is cross-platform and will work on all platforms that VS Code supports. It is also maintained by the VS Code team and will continue to be maintained and has been a part of the VS Code API for years at this point.
* _(not recommended)_ You can bundle the [keytar](https://github.com/atom/node-keytar) module with your extension. Keep in mind that keytar is a native node module which means that you will need to [publish a platform specific extension](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions) for each platform you want to support.

### Timeline

The current plan is to remove this shim from VS Code Insiders in **early July** which means that **August 2023's** stable release will be the first release without the shim.

### Questions?

If you have any questions, please feel free to ask them here. I will do my best to answer them as quickly as possible. Your cooperation is greatly appreciated :heart:

**Comment by bcanzanella** [comment]
thanks @TylerLeonhardt we'll get this into an upcoming release

**Comment by dsellarsnr** [comment]
HI @TylerLeonhardt, 

With keytar we had control of the service name and we've been using codestream:vscode. With the SecretStorage api vscode is internally using vscodecodestream.codestream. This means the SecretStorage api won't be able to access any existing secrets. Is there any we can control the service name used by the SecretStorage api to avoid having to do a migration of the secrets?

**Comment by TylerLeonhardt** [comment]
You will need to handle migration within your extension.

SecretStorage doesn't have a concept of a `service` and also in insiders (soon to be stable) we no longer store secrets directly into the keyring and use Electron's [safeStorage](https://www.electronjs.org/docs/latest/api/safe-storage) instead so we don't really have the ability to handle the migration automatically.

FWIW, we are pushing back the timeline a month to give some more time for migration on your end.

**Comment by dsellarsnr** [comment]
@TylerLeonhardt thanks for the timeline extension. 

To fully understand this - if we use the current version of vscode SecretStorage api it will store the secrets in the OS keystore. The future insiders api for SecureStorage will use OS user encryption and store the secret in vscode globalSettings. If we were already using vscode SecureStorage does vscode migrate it's secrets from OS keystore secrets to the encrypted string in globalStorage on the future insiders version?

**Comment by TylerLeonhardt** [comment]
@dsellarsnr 

The most recent release of VS Code (1.80) [uses the new approach for the Secret Storage API](https://code.visualstudio.com/updates/v1_80#_secretstorage-api-now-uses-electron-api-over-keytar).

This move should be totally transparent to users of the Secret Storage API because secrets are automatically migrated to the new location and the same `key` can be used to acquire the secret.

For users of `keytar` directly, it's not possible to map the `service` and `account` concept of `keytar` to the Secret Storage API of just `key` without assuming how the data should be represented (what would the key be? A concatenation of `service` and `account`? just `account`? something different?) ... so we don't handle that migration and ask that extensions that are still using `keytar` do the migration themselves.

**Comment by TylerLeonhardt** [comment]
👋 for reasons, we needed to push this date back... but the new date to remove this shim from VS Code Insiders in **early September** which means that **October 2023**'s stable release will be the first release without the shim.
