### ISSUE TITLE
Option to toggle visibility on startup | VSCode

### ISSUE THREAD

**Issue by DAmNRelentless** [TeamCodeStream/CodeStream#153]
**Describe the bug**
The code stream tab always opens when I start VSCode. I only want to use it when I need it.
Would be cool to have an option somewhere to disable auto-opening on startup.

**System Info:**
 - Version of the CodeStream extension: 6.1.0
 - OS + version: Win 10 64-Bit 1909
 - IDE + version: VS Code 1.42.0

**Comment by planteater** [comment]
@DAmNRelentless - Just to confirm, the CodeStream auto opens on startup of VS Code, even when you had CodeStream closed at the time you closed VS Code?

**Comment by DAmNRelentless** [comment]
Yes, it does but even if it wouldn't. I don't want it to open automatically on new files or projects.
An option to toggle that would be cool.

**Comment by planteater** [comment]
@DAmNRelentless - This issue has been fixed in v7.0.2 of our extension.
