### ISSUE TITLE
[Request] Closing Gitlab Issue Should Resolve Codestream Codemark

### ISSUE THREAD

**Issue by Logikgate** [TeamCodeStream/codestream#154]
Codestream makes it so easy to open tickets in Gitlab from the IDE. However, when the ticket is closed in Gitlab via code commit or manually the Codemark remains open in the IDE. Since this is a common workflow it would great if the Codemark would automatically resolve as well.

**Comment by feekApp** [comment]
I'am really looking forward to the implementation of this enhancement. BTW also the opposite way. When closing/resolve/archive a Codestream issue, also the related gitlab issue will be closed!
