### ISSUE TITLE
[Request] Add Configuration Option For Default Repo For Issues

### ISSUE THREAD

**Issue by Logikgate** [TeamCodeStream/CodeStream#155]
Currently when creating a bug in CodeStream and sending it to Gitlab the user needs to select the repo that the issue should be created in each time because it defaults to the first one in the list.

It would be awesome if there was a vscode workspace configuration setting that would allow a team to set the default repo for issue creation.  That way if you are jumping from one project to another project in vscode you don't have to remember to select the correct one every time you make an issue via CodeStream

**Comment by planteater** [comment]
@Logikgate - Sorry for the delayed reply on this. When you're creating an issue on GitLab, the repo selection should default based on the repo associated with the code block you selected. Is that not what you're seeing?
