### ISSUE TITLE
How to disable weekly emails?

### ISSUE THREAD

**Issue by rmilansky** [TeamCodeStream/codestream#1559]
How do I disable weekly emails for people who worked with me on the same git project?

**Comment by planteater** [comment]
@rmilansky - If the person is signed up for CodeStream they can control this themselves. Otherwise, click on the My Org icon at the top of CodeStreaam and select Invite Teammates. Click the "remove" link where appropriate.

**Comment by rmilansky** [comment]
> @rmilansky - If the person is signed up for CodeStream they can control this themselves. Otherwise, click on the My Org icon at the top of CodeStreaam and select Invite Teammates. Click the "remove" link where appropriate.

How to make sure that they are not added there?

**Comment by planteater** [comment]
@rmilansky - If there are outstanding invitations to people that you don't think were explicitly invited, chances are this happened as part of creating a codemark or feedback request. CodeStream will suggest people to get notified based on the commit history of the code being discussed/reviewed, and it's possible that you overlooked that when posting.
