### ISSUE TITLE
[Request] Allow desktop and email notifications to be controlled separately

### ISSUE THREAD

**Issue by Logikgate** [TeamCodeStream/CodeStream#156]
It would be awesome if we could opt-out of email notifications.  Currently if someone replies to a codemark that I made I get a vscode pop up notification, slack notification (if they send to slack) and an email notification.  The email notifications are the least useful of these and our team just ends up deleting them all.  

Would it be possible to add a user setting that allows each user to opt-out of email notifications?

**Comment by planteater** [comment]
@Logikgate - If you click on the ellipses menu at the top of the CodeStream pane, and then select "Notifications...", you'll be able to turn them off.

**Comment by Logikgate** [comment]
@planteater Yes this can turn off all notifications but we would still like the VSCode push notifications.  This ticket was about separating that feature so that you can opt-out of emails only.  Is it possible to do this currently?

**Comment by planteater** [comment]
@Logikgate - Gotcha. I understand now. Not possible at the moment so I'll reopen the issue. Thanks for the clarification.

**Comment by planteater** [comment]
@Logikgate - This is now available in v6.4.0 of the extension.
