### ISSUE TITLE
Feedback requests displaying old repo name

### ISSUE THREAD

**Issue by bensullivan-ag** [TeamCodeStream/codestream#1564]
- CodeStream Extension version:
- IDE Version: Build #IU-231.9161.38, built on June 20, 2023
- OS Version: macos 13.4.1

Steps to Reproduce:

1. Create feedback request
2. View feedback request
3. repo name is incorrect - it lists the repo name from an old bitbucket repo instead of the new GitLab repo that is open in the IDE.

`git remote -v` lists the gitlab origins and not the old repo origins from bitbucket.

Just some background - I initially installed and used CodeStream with a repo on bitbucket (repo name `atuin`).  We then migrated repo to GitLab (repo name `harbinger`).  CodeStream displays the old bitbucket repo name.

I have tried uninstalling and reinstalling plugin as well as clearing all IDEA caches with no success.

**Comment by planteater** [comment]
Sorry for the delay on this @bensullivan-ag. If you reload your IDE the repo name should be correct now.
