### ISSUE TITLE
List open feedback requests

### ISSUE THREAD

**Issue by bensullivan-ag** [TeamCodeStream/codestream#1565]
Hi

We'd like to practice non-blocking code reviews for our trunk based development.

Is it possible to see a list of open feedback requests created by anyone and available to anyone to review?

As a team lead is it possible for me to view a complete list of all feedback requests performed by members of my team and what was reviewed and potentially changed?

Thanks

Ben

**Comment by planteater** [comment]
Hi @bensullivan-ag - Click on the search icon at the top-right of the CodeStream pane. The following filter will get you all open feedback requests:

is:open is:fr

The other query is more problematic, as you can only query for one author at a time. Like this...

is:fr author:@username

We do have the concept of a team coming in the Fall and that should help.

**Comment by bensullivan-ag** [comment]
OK thanks @planteater - thanks for the info.
