### ISSUE TITLE
There is no Github PR items in the plugin 

### ISSUE THREAD

**Issue by vkhanikyan** [TeamCodeStream/CodeStream#157]
The plugin is empty. I haven't seen it working at any time. No Comments from the Github PR.

**Comment by planteater** [comment]
@vkhanikyan - Just to confirm, you're using GitHub's cloud service, and not GitHub Enterprise?

If so, you should see comments from merged in PRs, or open PRs as long as you're checked out to either the source or destination branch for that PR. Also note that only comments  tied to lines of code are displayed, and not comments on the PR itself.

**Comment by stormsurehire** [comment]
@planteater I'm experiencing this issue as well.

My repo is private, I have an open PR from my feature branch to master, I've linked the plugin to my github account, I'm on my feature branch and I've toggled the PR selector in the codestream plugin, and I made a comment on the PR in Github that is tied to a range of lines of code. The PR comment still doesn't show in codestream. I'm using Github's cloud service (normal Github), and I'm using the PyCharm codestream plugin. 

I'm pretty sure I followed all the instructions in this faq: https://github.com/TeamCodeStream/CodeStream/wiki/Pull-Request-Integrations

**Comment by planteater** [comment]
@stormsurehire - How new are the comments you added? Note that we fetch new comments every 30 minutes or so, although you can force things by restarting your IDE.

**Comment by stormsurehire** [comment]
@planteater Ahh yeah they were very new, I was testing it out, so probably ~5 minutes. That makes sense. Can that be put in the wiki documentation? 

Thanks for the help!

**Comment by planteater** [comment]
@stormsurehire - Excellent idea! Done.
