### ISSUE TITLE
Allow replies from the MS Teams integration

### ISSUE THREAD

**Issue by belaborbely** [TeamCodeStream/codestream#159]
The comments added to a codemark in MS Teams breaks synchronization between CodeStream and MS Teams.

1. "CodeStream connect" called in a channel of MS Teams.
2. When a codemark created in IntelliJ, the message appears in MS Teams.
3. The codemark is commented in MS Teams, but comment does not appear in Intellij.
4. Adding comment in IntelliJ no more appears in MS Teams.

IntelliJ CodeStream-plugin version:
![image](https://user-images.githubusercontent.com/3542453/76070952-16c98b00-5f9e-11ea-8e3f-b51a4e742c74.png)
Teams CodeStream-bot version:
![image](https://user-images.githubusercontent.com/3542453/76071062-4f696480-5f9e-11ea-8cf9-b94f8dfaac52.png)
IntelliJ-version:
![image](https://user-images.githubusercontent.com/3542453/76071182-817ac680-5f9e-11ea-9eee-09a29e1a4566.png)

**Comment by planteater** [comment]
@belaborbely - The Teams integration is currently just a notification mechanism for new codemarks. Teammates will need to use the “Open in IDE” button to participate in the discussion. Replies don’t sync in either direction. 

We hope to add replies as well in the coming weeks.
