### ISSUE TITLE
Black login screen

### ISSUE THREAD

**Issue by Al12rs** [TeamCodeStream/CodeStream#160]
**Describe the bug**
I installed CodeStream  on VSCode 1.43.0 and tried logging in using the button from the status bar and the login command. Both result in the right codestream panel appearing blank (waited over 30 seconds to make sure) on the first try. On the second try it usually works, but not consistenty. 
I tested uninstalling the extension and reinstalling, and I also tested the previous version with the same result. I tested version 6.3.0 and 6.2.0.

To further test I disabled all my other vsCode extensions and left only CodeStream, and while it now opened also on the first try sometimes, most of the time it still required two tries.

At first I could not make it show the login screen no matter what and I tested different workspaces, reinstalling, using the previous version etc. Not the entry experience I think you wish for new users so I thought to take the time to report this (maybe other people also had this issue but didn't take the time to report since it eventually works).

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 6.3.0 
 - OS + version: Win 10, 1909 build 18363.719
 - IDE + version: VSCode 1.43.0

**Log Files**
Run where the login failed to show on the first try and showed up on the second try.
[codestream.log](https://github.com/TeamCodeStream/CodeStream/files/4325096/codestream.log)
[codestream_agent.log](https://github.com/TeamCodeStream/CodeStream/files/4325097/codestream_agent.log)

**Comment by planteater** [comment]
@Al12rs - We've seen this issue as well and it appears to be a bug in VS Code. We're awaiting a fix from Microsoft:

https://github.com/microsoft/vscode/issues/89038

**Comment by Al12rs** [comment]
Ok, glad to hear it wasn't something on my end. Better leave this open so others can see and not open new issues.

**Comment by planteater** [comment]
Definitely. In general, simply closing and re-opening the CodeStream pane should resolve this, but I'll update everyone here once the fix is in from MSFT.

**Comment by planteater** [comment]
@Al12rs - This should be "fixed" in v7.0 of the extension. I use quotes there because its basically a hack to make things work while we wait for MSFT to fix that aforementioned issue.
