### ISSUE TITLE
Share on Slack hangs

### ISSUE THREAD

**Issue by aNickzz** [TeamCodeStream/CodeStream#161]
I'm aware of #88 but this is happening in both "normal" workspaces and remote ones.

**Describe the bug**
When creating a comment, the "Share on Slack" button just starts loading "Authenticating with Slack" without doing anything, I expect a browser window should open with some sign in process like it does with the "MS Teams" button?

Also, in the CodeStream window, under the "More..." menu, there's a number of "Connect to X" but no option to connect to Slack, however there is an empty submenu titled "Slack Connections"

**System Info (please complete the following information):**
 - Version of the CodeStream extension: v6.3.1-154 
 - OS + version: Windows 10 Pro
 - IDE + version: VS Code (v1.44.0-insider)

**Log Files**
I'm not including a full copy paste because they are long and contain potentially sensitive data (client names etc.).

`CodeStream`  
Nothing interesting

`CodeStream (Agent)`

```
[2020-03-18 01:27:52:686] [f4] CodeStreamAgent.sendNotification(codestream/didLogin) — e=codestream/didLogin, t={"data": .... {"slack":{"userId":"<removed>","teamId":"<removed>","accessToken":"<accessToken>","data":{"ok":true,"scope":"identify,channels:history,groups:history,im:history,mpim:history,channels:read,groups:read,im:read,mpim:read,users:read,users:read.email,users.profile:read,channels:write,chat:write:user,groups:write,im:write,mpim:write,reactions:write","user_id":"<removed>","team_name":"<removed>","team_id":"<removed>","enterprise_id":null}}, ...
```

It looks like its got a slack token stored already. I've removed the app from slack (from the `https://my slack domain.slack.com/apps/AKGBLDNFK-codestream?did_revoke_all=1`) to see if it would trigger a new sign in flow, but I get the same result, and it looks like CodeStream is still trying to use the existing token (which should now be invalid).

It looks like it doesn't log anything specific when clicking on the "Share with Slack" button.

I guess its not communicating with the slack API properly or it would see that the token is now invalid. ?

**Comment by planteater** [comment]
@aNickzz - I think we’ll need your email address so that we can check your account and dig into this further. If you’d prefer not to post it here could you send it to support@codestream.com? Thanks!

**Comment by aNickzz** [comment]
Sure no problem, I've just sent an email
