### ISSUE TITLE
There is no option to manage to manage Teams created in Visual Studio 2019.

### ISSUE THREAD

**Issue by davalillo** [TeamCodeStream/CodeStream#162]
I can't delete users from a team created in Visual Studio 2019.  I can't change the password. 

If you add a user by mistake, there is no way to remove it from the team. 

I tried to log in to www.codestream.com and there is no option. I have also tried https://api.codestream.com/web/login and with the credentials received in the email it does not work.

There is also no password recovery option.

I don't know if I'm missing information or if this kind of thing can't be done at all, but it's unfeasible to implement CodeStream on my team with all these obstacles.

**Comment by planteater** [comment]
@davalillo - Admin/settings options are coming very soon. Hopefully next week. In the meantime, if you need to remove someone, change an email, etc., just email support@codestream.com and we'll take care of it asap.

Note that there is a password-reset option. Just look for the "forgot password" link on the Sign In page in the extension.

**Comment by davalillo** [comment]
I'll wait for this features.

Thank you in advance.

**Comment by planteater** [comment]
@davalillo - v7.0 of the extension now includes some admin/team settings and user settings:

-   Ability for an admin to rename the team
-   Ability for an admin to assign/remove admin privileges
-   Ability for an admin to remove people from the team
-   Ability for an admin to control Live View usage for the team
-   Ability for users to change their username
-   Ability for users to change their full name
    <li>Adds the ability for users to cancel their accounts
