### ISSUE TITLE
If I want to quit the team or I disband the team, I don't find the corresponding button

### ISSUE THREAD

**Issue by Aurorxa** [TeamCodeStream/codestream#163]
**Describe the bug**
If I want to quit the team or I disband the team, I don't find the corresponding button

**System Info (please complete the following information):**
 - Version of the CodeStream extension: [e.g., 0.53.1]
 - OS + version: [e.g. Win 10]
 - IDE + version: [e.g. IDEA 2019.3.4]

**Comment by JavierPeris** [comment]
Any update on this? It seems the workaround is to ask somebody else to remove you from the team, doesn´t it?

**Comment by planteater** [comment]
@JavierPeris - As long as you're not the admin of the team, if you'd like to delete your user account you can do so via a link at the bottom of your profile page. Note that this truly deletes your account, so it should be used if you're looking to just be removed from one of multiple teams you're on.

**Comment by felipecrs** [comment]
If I delete my account, will I be able to create another again? This seems to be the only way to drop from a team which I got invited without knowing the admin.

**Comment by planteater** [comment]
@felipecrs - That's one option, but if you'd prefer to keep your existing account you can just go ahead and create a new team and then I'll remove you from the current team. Click on your username at the top of the CodeStream pane and then go to Switch Team > Create New Team. Once you've created the new team, let me know and then I'll remove you from the current team.

**Comment by felipecrs** [comment]
@planteater This is awesome, thank you so much for the support. I just did, created and switched to another team.

Old team: Dev-npm

New: felipecrs
Org: felipecrs

My user: felipecrs
