### ISSUE TITLE
Change username

### ISSUE THREAD

**Issue by serhiirepin** [TeamCodeStream/CodeStream#164]
**Describe the bug**
Hey, is it possible to change username ?
I've set the password as username accidentally.

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 6.3.2+38
 - OS + version: Ubuntu 18.04
 - IDE + version:  PHPStorm 2019.03

**Comment by planteater** [comment]
@serhiirepin - We’ll have a settings page in place in the next week or so, but in the meantime I can update your username for you. Just let me know what you would like it to be.

**Comment by serhiirepin** [comment]
Hey @planteater, could you change my username to sergii.repin please ?

**Comment by planteater** [comment]
All set @serhiirepin!
