### ISSUE TITLE
Buggy behavior using GitLab Self-Managed with non-standard port

### ISSUE THREAD

**Issue by clemyan** [TeamCodeStream/codestream#1667]
- CodeStream Extension version: 14.25.0
- IDE Version: 1.81.0
- OS Version: Windows 10 10.0.19045

## Details

When using GitLab Self-Managed instance with a non-standard port (i.e. not 443 for https and not 80 for http), several features do no work:

1. **Merge Requests view** - With the "Only show PRs from open repos" option enabled, no MR is shown at all.
2. **Create Merge Request** - No branches are shown to create an MR

![image](https://github.com/TeamCodeStream/codestream/assets/41266433/ff049ead-5869-40e2-9e93-676b2f05e6f9)

Steps to Reproduce:

1. Set up Codestream with a GitLab Self-Managed instance with a non-standard port
2. Open a project with a git remote in the GitLab instance
3. Go to the Merge Requests view and enable the "Only show PRs from open repos"
4. Try to create a Merge Request via Codestream

## Investigation

I have traced these two buggy behavior to two lines of code

https://github.com/TeamCodeStream/codestream/blob/5fa2eccc76c4d79ba2b88bc94d9075cf458cb183/shared/agent/src/git/models/remote.ts#L101

https://github.com/TeamCodeStream/codestream/blob/5fa2eccc76c4d79ba2b88bc94d9075cf458cb183/shared/agent/src/providers/gitlabEnterprise.ts#L37

These two lines disregard the port in the parsed URI, causing other code that match the local repo remote list to the configured GitLab instance to consider them different.

I have verified locally that fixing these two lines will fix the bugs described above, though I am unsure if this affects other features and/or whether there are other places that need fixing.

**Comment by planteater** [comment]
Unfortunately, no longer applicable given CodeStream's new product direction
