### ISSUE TITLE
multi-row tabs cause comment line to be offset in codestream panel | IntelliJ IDEA

### ISSUE THREAD

**Issue by thetoothpick** [TeamCodeStream/CodeStream#167]
When the IntelliJ setting "show tabs in one row" (Settings > Editor > Editor Tabs) is unchecked, the editor tabs can take up multiple rows above the text editor.  The CodeStream panel behaves as if the tabs were still in one line, and the line highlighted by hovering over the left side of the CodeStream panel is actually a few lines below where the cursor is.

Here's an example of the difference:

One-row tabs:
![image](https://user-images.githubusercontent.com/1460628/78080701-9bbc8000-7363-11ea-9dd2-3d17f0163e4f.png)

Multi-row tabs:
![image](https://user-images.githubusercontent.com/1460628/78080724-ac6cf600-7363-11ea-99cd-34d3878c10cc.png)

**Comment by marlon-assef** [comment]
I have a similar problem in Rider. Add code review comments the plugin adds the comment to the wrong line. The CodeStream plugin panel acts as if the code is in the same line, but the CodeStream panel is two lines up.

**Comment by planteater** [comment]
This issue has been fixed in v7.1.1 of the CodeStream extension.
