### ISSUE TITLE
Cannot post issues on git

### ISSUE THREAD

**Issue by aak-dev** [TeamCodeStream/CodeStream#168]
**Describe the bug**
unable to post issues from codestream to git nor retrieve closed issues from git

**System Info (please complete the following information):**
 - Version of the CodeStream extension: [e.g., 0.53.1]
 - OS + version: MAC Mojave 10.14.6
 - IDE + version: VS Code 1.43.2

**Log Files**
Error: Request codestream/codemarks/sharing/create failed with message: Could not retrieve contents for

![image](https://user-images.githubusercontent.com/58189246/78141710-815cd200-7449-11ea-8e49-04fc82d7b0b3.png)
)

**Comment by planteater** [comment]
@aak-dev - This should be fixed in v7.0.0 of the extension.
