### ISSUE TITLE
Export data has bad header

### ISSUE THREAD

**Issue by psybers** [TeamCodeStream/codestream#1682]
- CodeStream Extension version: v14.26.0
- IDE Version: Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:20:33.924Z (5 days ago)
- OS Version: macOS Ventura 13.4.1 (c) (22F770820d)

Steps to Reproduce:

1. Create at least one codemark
2. Go to "Organization Admin" -> "Export Data"
3. Inspect the generated CSV export

Note the header has 12 columns listed.  Note the rows have fewer columns.  The problem is the header lists `parentId`:

https://github.com/TeamCodeStream/codestream/blob/a37dd9d46324bc12084efd74ddbf5e0f1e9dd166/shared/ui/Stream/ExportPanel.tsx#L57

but that is never output:

https://github.com/TeamCodeStream/codestream/blob/a37dd9d46324bc12084efd74ddbf5e0f1e9dd166/shared/ui/Stream/ExportPanel.tsx#L70

There are two possible fixes:

1. remove `parentId` from the header
2. actually output the parent ID (I do not know the code, so I have no idea if this is even a thing)

**Comment by psybers** [comment]
One other minor note: I am not entirely sure why the header row has `//` at the start.  CSV has no notion of comments according to the [RFC](https://www.rfc-editor.org/rfc/rfc4180).

**Comment by planteater** [comment]
Fixed in 15.1.0
