### ISSUE TITLE
Export data corrupt when comment has a comma

### ISSUE THREAD

**Issue by psybers** [TeamCodeStream/codestream#1683]
- CodeStream Extension version: v14.26.0
- IDE Version: Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:20:33.924Z (5 days ago)
- OS Version: macOS Ventura 13.4.1 (c) (22F770820d)

Steps to Reproduce:

1. Create a new comment on any file, with the comment text: "this is, a test"
2. Go to "Organization Admin" -> "Export Data"
3. Inspect the generated CSV export

While the data is fully output, the comma is not properly escaped in the CSV.  Thus, importing it later will fail because it is impossible to know when the column truly ends or not, as any "," in the data will prematurely cause a parser to move to the next column.

The escape function:

https://github.com/TeamCodeStream/codestream/blob/a37dd9d46324bc12084efd74ddbf5e0f1e9dd166/shared/ui/Stream/ExportPanel.tsx#L50

does not seem to fully/properly escape things.  First, the escaped strings should be surrounded by "double quotes".  This will fix the issue with the comma.  But then any double quote character `"` that appears in the string is a problem.  So the second thing the function needs is to replace `"` with two double quotes `""` instead of the strange attempt at escaping here:

https://github.com/TeamCodeStream/codestream/blob/a37dd9d46324bc12084efd74ddbf5e0f1e9dd166/shared/ui/Stream/ExportPanel.tsx#L52

**Comment by planteater** [comment]
Thanks for the report @psybers! We'll get both of these issues fixed.

**Comment by planteater** [comment]
Fixed in 15.1.0
