### ISSUE TITLE
On CLion/ Ubuntu addon fails due to usage of weird file paths

### ISSUE THREAD

**Issue by andrey-chu** [TeamCodeStream/CodeStream#169]
When the comment is added to a code the filename is referred to using multitude of ".."  from the cwd and back (see the attached snapshot)
![Selection_380](https://user-images.githubusercontent.com/52890300/78567263-b6d63680-7820-11ea-8e37-63698cd72122.png)
which is ugly and seemingly causes problems if the same repo is opened in the other computer.
But also it causes an error in the log:
`
2020-04-06 16:06:39,231 [ 147259]   WARN - agent.CodeStreamLanguageClient - [2020-04-06 14:06:39:231] Error(/data/au517882/CLionProjects/ALMaSS_all): /usr/bin/git -c core.quotepath=false -c color.ui=false show 2b9346fde037b0707784b94108021bc5c3faee20:./../../../../home/andrey/CLionProjects/ALMaSS_all/qt/colmap.cpp --)
    (128) Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false show 2b9346fde037b0707784b94108021bc5c3faee20:./../../../../home/andrey/CLionProjects/ALMaSS_all/qt/colmap.cpp --
fatal: './../../../../home/andrey/CLionProjects/ALMaSS_all/qt/colmap.cpp' is outside repository
`

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 0.7
 - OS + version: Ubuntu 18.04
 - IDE + version: CLion 2019.3
[clion-logs-20200406-160927.zip](https://github.com/TeamCodeStream/CodeStream/files/4438873/clion-logs-20200406-160927.zip)

**Log Files**
Sending log files along with your report will help us investigate the issue. Instructions can be found here: https://github.com/TeamCodeStream/CodeStream/wiki/Instructions-for-finding-CodeStream-log-files

**Comment by planteater** [comment]
Thanks for the report @andrey-chu. We're on it!

**Comment by marcelofarias** [comment]
Could you please try the following:

- Close all instances of your IDE
- Delete `~/.codestream/mappings.json`
- Open your IDE again

Let me know if it helps

**Comment by andrey-chu** [comment]
Thank you for your suggestion, Marcelo. 
it did not help, but it seems like now I know what causes the problem.
my clion repo is located in /home/andrey/CLionProjects/<name of the repo> while actually /home/andrey/CLionProjects/ is a symlink to the other directory (on the other disk: /data/<some otheuid>/CLionProjects) 
so when I remove `~/.codestream/mappings.json` it turns `paths` and `defaultPaths` to point to /data/<some otheuid>/CLionProjects/<nameoftherepo>. The same happens if I overwrite the json file to point to  /home/andrey/CLionProjects/<name of the repo>. When I open the IDE, it still overwrites defaultPaths and adds and additional value of  /data/<some otheuid>/CLionProjects/<nameoftherepo> to the paths entry.
I hope it helps and it will enable you to solve the problem or suggest me a way to workaround it.

**Comment by planteater** [comment]
@andrey-chu - This should be fixed in v7.2 of our extension, which was just released.
