### ISSUE TITLE
Have to press tab to complete a mention, but UI says press enter

### ISSUE THREAD

**Issue by dobesv** [TeamCodeStream/CodeStream#171]
**Describe the bug**

![image](https://user-images.githubusercontent.com/327833/79495369-5b9f0380-7fd9-11ea-9e21-a1879667ad14.png)

The tip at the bottom says to press enter to confirm the mention, but I actually have to press tab.

**System Info (please complete the following information):**

 - Version of the CodeStream extension: 7.0.1+44
 - OS + version: Linux
 - IDE + version: WebStorm 2020.1

**Comment by planteater** [comment]
@dobesv - Thanks for the report. Good news is we've already got this fixed and ready to go out in our next release. Should be on Monday, but I'll update you here.

**Comment by planteater** [comment]
This issue has been fixed in v7.1.1 of the CodeStream extension.
