### ISSUE TITLE
JetBrains Rider - CodeStream plugin does not comment in the correct line.

### ISSUE THREAD

**Issue by marlon-assef** [TeamCodeStream/codestream#172]
Steps to reproduce:

1. Open the plugin panel.
2. Click in any line of code.
3. In the CodeStream panel click the add comment icon.
4. The comment panel opens.
5. Do not click anywhere in the comment pane nor type any comment.
6. Click the button Cancel to cancel the comment.
7. Click the button Discard Comment to discard the comment.
8. Using the keyboard arrows move the cursor to another line (e.g. three lines down).
9. Press the shortcut to add comments **Ctrl+Shift+/** **c**.
10. The comment panel opens and shows a different line than the current one.

**Comment by planteater** [comment]
@marlon-assef - I'm trying to reproduce this on my end. After step #7, where you discard the codemark, how are you getting focus back into the editor? If I manually put focus into the editor with my mouse, and then use the keyboard arrows to move the cursor down a few lines, if I then initiate a codemark with the keyboard shortcut it does reflect the correct line. Thanks

**Comment by planteater** [comment]
@marlon-assef - Just wanted to follow up on my question above. Thanks!

**Comment by marlon-assef** [comment]
Hi, @planteater .

Please consider the code below:

`namespace CodeStream.Test
{
    public class Test
    {
        public bool MethodA()
        {
            return false;
        }

        public bool MethodB()
        {
            return true;
        }
    }
}`
Steps to reproduce:

1. Open the plugin panel.
2. Click at the end of line 7, after the semicolon.
3. In the CodeStream panel click the add comment icon.
4. The comment panel opens.
5. Do not click anywhere in the comment pane nor type any comment.
6. Click the button Cancel to cancel the comment.
7. Click the button Discard Comment to discard the comment.
8. Click at the end of line 7, after the semicolon.
9. Using the keyboard arrows move the cursor to the end of line 12, after the semicolon.
10. Press the shortcut to add comments Ctrl+Shift+/ c.
11. The comment panel opens and shows a different line than the current one.

**Comment by planteater** [comment]
Thanks @marlon-assef! Turns out it's on IDE-specific issue and I was using a different IDE than you when trying to reproduce.
