### ISSUE TITLE
[Feature][Jetbrains] Support for pushing comments in Codestream to the Merge Request in Gitlab.

### ISSUE THREAD

**Issue by suguspnk** [TeamCodeStream/codestream#174]
It would be good if we have the option to push comments to the merge requests directly from our IDE.
We tried using the Codestream and I think it's really good but due to this, we're not using it for now.

**Comment by planteater** [comment]
@suguspnk - Thanks for the feedback. The details haven't been finalized yet, but in the coming weeks we do plan to make a connection between CodeStream code reviews and GitLab merge requests. I think the general idea is that when a CodeStream code review is approved, you'd then have the option to either link to an existing MR or create a new MR. There would also be an option to have summary information about the code review pushed up into the MR. I'm not sure that we'd push the entire discussion thread into the MR, and more likely would just include a permalink to the code review on CodeStream. But, we'll see what customers want.

**Comment by eialanjones** [comment]
+1

**Comment by planteater** [comment]
While we don't push the actual comments up to the PR yet, we do now allow you to create a PR from codestream once a code review has been approved. When you do so, summary information about the review, including a permalink, are included in the PR. More details here:

https://www.codestream.com/blog/codestream-8-0-end-to-end-support-for-a-developers-workflow-from-feature-branch-to-pull-request

**Comment by planteater** [comment]
Since the GitLab MR integration was launched back in April 2021, I don't think we're giving much thought now to having comments from feedback requests appear in an MR. The focus is more on feedback requests being precursors to the MR.
