### ISSUE TITLE
After upgrading to IntelliJ CodeStream plugin version 14.29.0+512, it stopped listing merge requests

### ISSUE THREAD

**Issue by ysheinis** [TeamCodeStream/codestream#1741]
- CodeStream Extension version: 14.29.0+512
- IDE Version: IntelliJ IDEA 2023.2.1 (Community Edition) Build #IC-232.9559.62, built on August 23, 2023
- OS Version: Windows 10

Steps to Reproduce:

1. Upgrade to 14.29.0+512
2. Look at CodeStream window - it is blank now.
![image](https://github.com/TeamCodeStream/codestream/assets/34074379/b9d73be8-6575-474e-9738-fc383c443817)
4. Sign Out / Sign In does not help

**Comment by planteater** [comment]
@ysheinis - There was an email that went out last week on this. I'm afraid that the code review functionality (both pull requests and feedback requests) has been removed from the product. More details can be found here:

https://github.com/TeamCodeStream/codestream/issues/1742

**Comment by ysheinis** [comment]
Thank you, David, got it.

Will need to shop for a new tool.
