### ISSUE TITLE
Important Update: New product focus for CodeStream

### ISSUE THREAD

**Issue by planteater** [TeamCodeStream/codestream#1742]
When CodeStream was acquired by New Relic a little over two years ago, the idea was to be the first to bring observability into the IDE, alongside the many devtool integrations we already offered. Given the positive response to our observability features, it’s become clear to us that this is the area where we can add the most value to the daily lives of software developers, and we’ve decided to focus squarely on observability going forward.

With today's release (Sept. 12), the ability to create and review both pull requests and feedback requests has been removed from the product. For your in-IDE pull request needs, both GitHub and JetBrains have integrations you might want to check out.

We understand that some of you may use CodeStream exclusively for these features, but we would encourage you to try out our observability features with New Relic’s generous free plan that gives you 100GB of free ingest per month. The [code-level performance information](https://urldefense.proofpoint.com/v2/url?u=https-3A__codestream-2D8ff1d7fb074c.intercom-2Dclicks.com_via_e-3Fob-3Dfm-252BKlDcA-252FlrLifrozoZ5Z-252FqRTDEChfkw5ordUErJG-252BQtz8T-252F2Wpdj-252BmCVRI-252Brm0XmIzgLTJoA87gxwGSWORJy5YhonjKvZNkvg6jKrc0kiRyiSJX1MGI7k7650aNIu3u-26h-3Dbaeb101229f5023f38a12c48911a6ea9e21b9a04-2Dnjfgq0eq-5F117897701136714-26l-3D68de09e13959f344250f77b20717a3cc14032711-2D81429243&d=DwMFaQ&c=b1cAyl7Dw_ocqxUnP42wFtmjQSgaykGJS8OX77zrvq8&r=Hq4SI1jaMTtN2UlvSHvzISPfc0OA9bDJG3hWQdnszIdsBnIuu84XH7VShDJu16MU&m=lxJL-W2MXP8GrmgvLV5pITtZrFTukelWJZ0_csIQlBvRBUsaIAcbIz89rvK-Ou9z&s=nIIjxFEywZz5fcEbR9KjkpLMlJX0ogKV58DcirUAvMU&e=) that CodeStream shows in the editor, in context, is extremely powerful.

You’ll still be able to create code comments and issues, but the Issues and Codemarks sections of the CodeStream pane have been removed. Interaction with codemarks will largely be through the Activity Feed, email notifications, and sharing to Slack, Teams, Jira, GitHub, etc.

**Comment by aleksolutions** [comment]
I don't understand this decision. You had a great product that unified all the features that any developer would want so they wouldn't have to leave the IDE. 

Honestly, without being able to track my Jira issues and without being able to pull requests and see them, this plugin doesn't make sense to me anymore.

I would even understand if you had a separate product or if you made it a paid product, but not giving options to those of us who have been using it since its inception just seems sad to me.

**Comment by ujwal-setlur** [comment]
This decision has rendered this plugin totally useless to me. I relied on it to review MRs/PRs directly from VS Code. Thanks much!

**Comment by SFE-Brudnerd** [comment]
Agreed with @aleksolutions, this is a pretty frustrating experience. A paid product that provides a similar functionality would be acceptable. Outright revoking the bulk of the feature set of your product without notice seems like a terrible decision.

**Comment by ujwal-setlur** [comment]
At the very least you could have allowed someone to fork the project and maintain it.

**Comment by jimliu7434** [comment]
I relied on this ext. to review MRs and talk with my teammates from VS Code everyday. 
It's a very frustrated to me to see "Codemarks" & "Issues" been removed from main panel.

**Comment by halws** [comment]
During last 2 years I was using this extension every day, mostly PR reviews and jira issues. I've sent you a few mails with bugs, and genuinely have been pushing it within my team. But now it's gone - very sad.
For my use cases this extension was perfect. 

 Does anybody know extension for PRs reviews and jira issues?

**Comment by planteater** [comment]
@halws - JetBrains IDEs have a built in GitHub integration, and there's GitHub's own extension for VS Code. Also, Atlassian has a Jira extension for VS Code. I'm sure there are other options, but those are the ones I'm aware off the top of my head.

**Comment by ujwal-setlur** [comment]
None of the VS Code extensions allow full MR/PR review workflow including **approval** and **merge**, at least for GitLab. That's what I was so dependent on this extension for. Now, I have to leave the IDE to do approvals and merges. Sucks.

**Comment by TeoAvignon** [comment]
Could please add the feedback request back? It was a huge advantage of your product and I am pretty sure you can get more users thanks to it. The fact that you could do code review without pull request was no nice.

Hope you will get it back !
