### ISSUE TITLE
CodeStream panel fails to load in code-insiders

### ISSUE THREAD

**Issue by YuruiHong** [TeamCodeStream/codestream#1746]
- CodeStream Extension version:14.29.0-4414
- IDE Version:1.83.0-insider 03671d332bf6a34782d5adc64086bc8e083a1590 x64
- OS Version: Linux 6.4.0-4-amd64 x86_64 GNU/Linux

Steps to Reproduce:

1. Install the extension in code-insiders.
2. Click on the icon in the side bar, and the panel starts infinity loading
3. the same profile works for release version 1.82.1 6509174151d557a81c9d0b5f8a5a1e9274db5585 x64, (I made a soft link  for directories ~/.vscode and ~/.vscode-insiders)

**Comment by planteater** [comment]
We'll get on this asap! Thanks for the report.

**Comment by planteater** [comment]
@YuruiHong - This has been fixed in version 14.29.1
