### ISSUE TITLE
Can't write comments

### ISSUE THREAD

**Issue by martynorthstar** [TeamCodeStream/CodeStream#175]
I mark text, and use "comment"-popup-functions. It says: "There was an error creating the codemark." This renders me inefficient and I have been troubleshooting for hours without success. 

Sometimes, it doesn't say "there was an error"... it just says, press enter, after I press submit. I do so without success. 

I am using macOS, VSCode, Codestream, and Github desktop.

**Comment by bcanzanella** [comment]
Hi @martynorthstar I'm sorry you're running into a roadblock here. 

We need to see some additional logging on your end to debug this. The instructions for VSCode are here: https://github.com/TeamCodeStream/CodeStream/wiki/Instructions-for-finding-CodeStream-log-files
After you have the logs, can you send them to me at brian@codestream.com

thanks

**Comment by planteater** [comment]
@martynorthstar - Just wanted to follow up to see if we could get those log files. Would love to get this issue fixed for you asap. Thanks!
