### ISSUE TITLE
Missing inline git blame

### ISSUE THREAD

**Issue by Novocastrian** [TeamCodeStream/codestream#1754]
- CodeStream Extension version: 14.29.0+512
- IDE Version: PhpStorm 2023.2.1, Build #PS-232.9559.64

- OS Version: Windows 11 Pro

Steps to Reproduce:

1. Have plugin installed
2. Launch PHPStorm
3. Open any file that is tracked by the project's git repository
4. Select any line in the file

Anticipated outcome: plugin comments the git blame onto the line
Actual outcome: nothing happens

Looks like https://github.com/TeamCodeStream/codestream/pull/1726 removes this. Why? This leaves a gap in functionality for no reason.

**Comment by planteater** [comment]
There was an email communication about this last week. Unfortunately we've made the decision to focus exclusively on observability going forward.

https://github.com/TeamCodeStream/codestream/issues/1742
