### ISSUE TITLE
Better UX for PR commenting Refresh Rates

### ISSUE THREAD

**Issue by carlpulley** [TeamCodeStream/codestream#176]
I was looking through your documentation on the PR refresh rate. The documentation suggests that PR comments are pulled every 30 minutes and an IDE restart would be required if comments were required earlier.

Are there any plans to fix this? Surely a simple refresh button would be more convenient than forcing IDE restarts? Or maybe you have plans to make this poll timing configurable?

**Comment by ppezaris** [comment]
We're taking a look at options to improve this experience. Thank you for the feedback!

**Comment by planteater** [comment]
No longer applicable.
