### ISSUE TITLE
Memory leak in Phpstorm on Linux

### ISSUE THREAD

**Issue by miiimooo** [TeamCodeStream/codestream#1767]
- CodeStream Extension version:
- IDE Version: 2023.1
- OS Version: 6.1.0-1006-oem

Steps to Reproduce:

Happens occasionally, every few hours

**Comment by planteater** [comment]
Thanks for the report @miiimooo. Could I trouble you for a screenshot showing the memory usage, as well as a log file? In your IDE go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file.

You can send them to me at codestream@newrelic.com. Thanks.

**Comment by planteater** [comment]
@miiimooo - I'm going to close this for now, but definitely send over that log file when you get a chance and we'll pick things up from there.
