### ISSUE TITLE
Incorrect Jira URL on CodeStream created Jira Issue

### ISSUE THREAD

**Issue by carlpulley** [TeamCodeStream/CodeStream#178]
**Describe the bug**
Using IntelliJ/CodeStream I created a new Jira issue. I was able to view that issue in IntelliJ and in Jira (via a browser). However, the CodeStream Jira ticket URL was incorrect.

Our company name is (say) XXX YYYY and set in Jira. Our standard Jira URL (as viewed in a browser) is https://xxxyyyy.atlassian.net. Unfortunately, CodeStream was using the URL https://XXX%20YYYYatlassian.net which failed to resolve.

There is no obvious configuration option to resolve this type of issue.

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 7.0.2+45
 - OS + version: Win 10
 - IDE + version: IntelliJ 2019.3.4

**Comment by planteater** [comment]
@carlpulley - Quick question. Are you connecting to Jira's cloud service or an on-prem Jira Enterprise instance?

**Comment by carlpulley** [comment]
Jira's cloud service.

**Comment by planteater** [comment]
For some reason Jira is returning us a URL with a space in it. That would appear to be an issue on their side, but we're going to put in a change to strip out any spaces. I'll update you as soon as that fix is in. 

We also fixed the URL in the one issue that you'd already created.

**Comment by planteater** [comment]
@carlpulley - This should be fixed in v7.2 of our extension.
