### ISSUE TITLE
No code given when signing in via github from Teams

### ISSUE THREAD

**Issue by nibblesnbits** [TeamCodeStream/CodeStream#179]
I've added CodeStream to VSCode, which gave me a link to integrate with Teams.  Once the Teams extension was added, I attempted to sign in.  This is where the problem occurs.  I created my CodeStream account with my GitHub account, so when I click the Sign In button in Teams, I'm taken to the CodeStream sign in page, I click the GitHub sign in link, and I'm presented with screen saying "All Set!  Return to your IDE to start using CodeStream."  In Teams, the extension expects some sort "code" as stated in the message "After signing in, please copy the code shown on your screen and paste it here."  I see no code, therefore, I cannot sign in.

**System Info:**
 - Version of the CodeStream extension: 1.0.3 (Teams extension)
 - OS + version: Win 10
 - IDE + version: VSCode 1.44.2

**Log files**
(no log files that I can find)

**Comment by ppezaris** [comment]
Thank you for the report we will have a look.

**Comment by planteater** [comment]
@nibblesnbits - This should be fixed now. Can you give it another shot?

**Comment by nibblesnbits** [comment]
It works great now.  Thanks!
