### ISSUE TITLE
VS Code Unread Counts

### ISSUE THREAD

**Issue by JoseVf** [TeamCodeStream/CodeStream#18]
On VS Code Unread Counts seems like don't decrement.
I had a few messages and opened them, but the unread count still counting them as unread
<hr>
IDK if this can be useful but I will just leave it here  <br><br>

| software         | version
| ---------------- | -------
| VS Code | 1.29.1
| OS | macOS Mojave (10.14)
| CodeStream Plugin  | 0.24.2

**Comment by planteater** [comment]
@JoseVf - Apologies for the delay in following up here. Could I get a few more details? Are you referring to the count that shows in the VS Code status bar, or the counts that show to the right of a conversation's entry on the channel switcher? Or both? As you go into different conversations with unread DMs or mentions, the counts don't decrement?

Can you try signing out and back in again to see if that helps? Look for "CodeStream: Sign Out" in the command palette. Thanks!

**Comment by JoseVf** [comment]
· Just on the VS Code status bar.
· The count never decrement, even if I switch between conversations. I have to close and reopen VS Code to get the updated number.
· Sure, I can try signing out and back again.

**Comment by eamodio** [comment]
@JoseVf This should be fixed in CodeStream v0.30
