### ISSUE TITLE
Codestream keeps opening external merge windows

### ISSUE THREAD

**Issue by jpringle11** [TeamCodeStream/CodeStream#181]
When I have the CodeStream plugin enabled in either IntelliJ or VS Code, it keeps opening external merge tool windows.  I have no idea why, but it is incredibly frustrating.

I'm guessing it is for some reason invoking the git external merge tool I have configured for git, but I can't really correlate this to intended actions.

Platform is MacOS 10.15.4, this happens with both
IntelliJ Ultimate 2020.1, CodeStream 7.0.1+44
VS Code 1.44.2, CodeStream 7.2.0

**Comment by jpringle11** [comment]
Some further information ... it seems my colleague is on a local branch that is rooted at a prior version of /develop than I am at. When clicking on the codemark to see the context of the comment, it is launching the external merge tool and not doing anything in the IDE to show me the file or codemark.

And now, strangely, in VSCode it has stopped launching the remote merge tool (after I closed the windows) and appears to be working as expected.

As if there is some sort of initial "gotta run external git merge tool" hurdle to be cleared, and then it works ok...

**Comment by planteater** [comment]
@jpringle11 - We're admittedly a bit stumped by this one. Any chance I could trouble you for some log files? Feel free to send them to support@codestream.com if you'd prefer not to post them here. Thanks!

https://docs.codestream.com/userguide/faq/client-logs/

**Comment by planteater** [comment]
@jpringle11 - Never mind on the log files. We have a fix that will go out in our next release. I'll update you here as soon as it's available.

**Comment by jpringle11** [comment]
That's great!  Thank you!

**Comment by planteater** [comment]
@jpringle11 - This issue should be fixed in v7.2.1 of our extension. It's available now for VS Code, and should be available by tomorrow for IntelliJ (pending approval from JetBrains).
