### ISSUE TITLE
OpenTelemetry with extension

### ISSUE THREAD

**Issue by ShravanSunder** [TeamCodeStream/codestream#1869]
I'm unable to associate my cloudflare worker which is sending data to open telemetry and log push to new relic.  

I've setup monitoring with otel, but not sure how to make this extension work with otel. 

![2023-12-09 1245 Brave Browser New Issue · TeamCodeStreamcodestream](https://github.com/TeamCodeStream/codestream/assets/5294949/a51a6fed-54d4-4a73-8395-0818604302ee)

**Comment by planteater** [comment]
@ShravanSunder We've got some OTel support coming in January. I'll follow up here once it's available.

**Comment by ShravanSunder** [comment]
@planteater any updates on otel support :)

**Comment by planteater** [comment]
@ShravanSunder - We do have a little support in place now. For Otel services you'll see golden metrics, SLOs and related services. Next up will be to try to add support for errors.

**Comment by ShravanSunder** [comment]
@planteater question, how do i setup vscode to work with otel?  i only see the options in the picture.  Is there a doc or procedure to setup it up?

**Comment by planteater** [comment]
@ShravanSunder - That screenshot is of our instrumentation wizard, which is what you'd use if you wanted to instrument a service using a New Relic APM agent. In your case, presumably you've already got services instrumented with OTel. All you need to do is open a file from the repo that builds one of those OTel services, and then you'll be prompted to select that service from a dropdown list.

In the example below, where it says HELLO-NY you'll see the name of your repo, and then just start typing in the dropdown list to select the name of the OTel service that is built from that repo. Finally, click the blue button and you'll start to see performance data.

![Screenshot 2024-01-31 at 1 21 22 PM](https://github.com/TeamCodeStream/codestream/assets/3442587/d945932a-4545-406c-8ed6-4cd69949da7f)

**Comment by ShravanSunder** [comment]
@planteater Thanks!
So i'm sending info to new relic using otel http services.  i'm sending traces using 
- "@opentelemetry/exporter-trace-otlp-http"
- "@opentelemetry/exporter-log-otlp-http"

Its a monorepo of nodejs projects and a cloudflare worker

When i open any file in my monorepo I never see the option you show me
![2024-02-23 0258 Code honoApp ts — askluna — TS  JS  Node  Deno](https://github.com/TeamCodeStream/codestream/assets/5294949/df67896c-6801-4bf8-8657-3f2cf51a7c5d)


I have an entity in new relic that has my logs and traces so that part is working
![2024-02-23 0259 Brave Browser OpenTelemetry with extension · Issue #1869 · TeamCodeStreamcodestream](https://github.com/TeamCodeStream/codestream/assets/5294949/b8b2eae7-e961-4564-8c4e-8c9775a7c27d)

**Comment by planteater** [comment]
Thanks for the additional info @ShravanSunder! We'll dig into this and follow up with you shortly.

**Comment by planteater** [comment]
@ShravanSunder - Looks like this was a bug on our side. The check we were doing to see if you had any instrumented services was overlooking OTel. We've got a fix ready to go out in a release next week, but if you want to try it out now you can install the pre-release version below. Let me know how it goes! You should now get prompted to select the service to associate with your repo.

VS Code - https://drive.google.com/file/d/1f-oDX5rIuIl8Kn3XN7bXP3zgqZ8zGIxK/view?usp=sharing

JetBrains - https://drive.google.com/file/d/1kvWQtkgHOpbq_3vX6s5XncRjwTbXkCjn/view?usp=sharing

**Comment by ShravanSunder** [comment]
@planteater i'll wait till the official extension is out!  will let you know! thanks :)

**Comment by planteater** [comment]
@ShravanSunder - Fix is out now in v15.4.3!

**Comment by ShravanSunder** [comment]
@planteater it looks like i now see my services.  However, when i click `show performance`, it just spins, then stops and i don't see anything.

![2024-03-07 0316 Code CodeStream (Logs) — askluna — TS  JS  Node  Deno](https://github.com/TeamCodeStream/codestream/assets/5294949/70578daa-b1a7-4681-82f6-acafd91f561d)

after a few seconds
![2024-03-07 0317 Code NodeNativeApi ts — rivet — TS  JS  Node  Deno](https://github.com/TeamCodeStream/codestream/assets/5294949/1834b893-c4cc-4231-8d69-764a56d28ba3)

**Comment by ShravanSunder** [comment]
@planteater I can share you the outputlogs in vscode but not sure what the most secure way to do that is
