### ISSUE TITLE
git error on empty file

### ISSUE THREAD

**Issue by studio1729** [TeamCodeStream/CodeStream#187]
**Describe the bug**
Attempting to comment on, or raise an issue on, a file that is checked in but empty, fails.

Error message:
Sorry, we encountered a git error: Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false blame --root --incremental -w -L 40,40 -- test_run_pyhistory.py fatal: file pyhistory/test_run_pyhistory.py has only 0 lines 

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 7.2.1+49
 - OS + version: macOS 10.15.3
 - IDE + version: IntelliJ IDEA 2020.1.1 (Ultimate Edition)
Build #IU-201.7223.91, built on April 29, 2020
Runtime version: 11.0.6+8-b765.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
GC: ParNew, ConcurrentMarkSweep
Memory: 1933M
Cores: 8
Non-Bundled Plugins: com.codestream.jetbrains-codestream, com.microsoft.vso.idea, net.seesharpsoft.intellij.plugins.csv, Pythonid, aws.toolkit, ru.meanmail.plugin.requirements, org.intellij.scala, com.microsoft.tooling.msservices.intellij.azure, com.intellij.plugins.html.instantEditing

**Comment by planteater** [comment]
@studio1729 - Thanks for the report! I was able to reproduce the issue on my end, but I wanted to follow up to see if this was a real-world scenario or if it was just a test. Is there an actual need to add a comment in an empty file? I'm trying to decide if this is something worth fixing. ;-)

**Comment by studio1729** [comment]
Hi, thanks for following up! In our case, the empty file is supposed to contain unit tests; I want to flag this absence. That is a thing in our team sometimes ;_;  so I feel it’s an actual need.

Our team has really taken to CodeStream, keep up the good work!!
---
X

**Comment by planteater** [comment]
@studio1729 - This has been fixed in v7.2.2 of the CodeStream extension.
