### ISSUE TITLE
Add the ability to move issues/comments between teams

### ISSUE THREAD

**Issue by sicknote** [TeamCodeStream/codestream#188]
I have been using Codestream with a single team, and some issues from one client are in the wrong team. Whilst this is not a huge issue, as I can switch between teams to see the items, it would be really helpful to be able to move the items between teams.

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 7.1.1 +47
 - OS + version: Windows 10 Pro
 - IDE + version: Jetbrains IDE

**Comment by planteater** [comment]
@sicknote - I can have those issues moved to the other team for you, but I’ll need to know which issues as well as your email address. If you’d prefer not to post that information here, email me at support@codestream.com.

**Comment by sicknote** [comment]
@planteater no worries. I don't have _that_ many. I can wait. Just wanted the ticket logged, so hopefully it can be worked on.

Thanks
