### ISSUE TITLE
Toggle visibility of archived items

### ISSUE THREAD

**Issue by sicknote** [TeamCodeStream/codestream#189]
Add the ability to hide/show comments and issues based on whether they are archived / completed to keep the activity feed as clear as possible.

**System Info (please complete the following information):**

    Version of the CodeStream extension: 7.1.1 +47
    OS + version: Windows 10 Pro
    IDE + version: Jetbrains IDE

**Comment by planteater** [comment]
@sicknote - Can you give me a little more insight into why you'd want to filter the activity feed like this? I think in most cases, by the time you archive a codemark it's probably already back a ways in the activity feed. The activity feed is primarily geared towards notifying you about new/updates items, so it wasn't immediately clear to me why it would be important to suppress archived items that might be back farther in the feed. Would appreciate some additional insights. Thanks!
