### ISSUE TITLE
Option to place CodeStream in Side Bar / Panel

### ISSUE THREAD

**Issue by luveti** [TeamCodeStream/codestream#19]
It would be cool if the CodeStream "view / tab" could be moved to the panel that contains the Terminal and Output views. When adding a new split, the CodeStream tab usually resizes which becomes very annoying after a while!

Placing it in the sidebar would also be cool. But some people may end up needing to resize it when switching between tabs.

The search view actually allows the user to switch between it being in the sidebar and the panel section.

**Comment by eamodio** [comment]
We would *love* that too! Unfortunately that currently isn't possible given the constraints of the vscode extension api. Here is the open request that would allow us to enable that feature: https://github.com/Microsoft/vscode/issues/46585. Please up vote it 😄

**Comment by planteater** [comment]
After waiting for so long, this is now available in CodeStream 10.0!
