### ISSUE TITLE
Github Enterprise Issue creation fails

### ISSUE THREAD

**Issue by awreccan** [TeamCodeStream/CodeStream#190]
**Describe the bug**

I created an issue inside CodeStream in IntelliJ IDEA. I expect it to show up on my Github Enterprise repository. It didn't. Here are some related issues I'm seeing:
- My PAT hasn't been used yet (did CodeStream even try to post an issue to Github Enterprise?)
![image](https://user-images.githubusercontent.com/10543509/81787500-bde51880-9533-11ea-8257-80b9dcc7feae.png)
- The first dropdown is missing/blank - but there aren't any error messages
![image](https://user-images.githubusercontent.com/10543509/81787788-259b6380-9534-11ea-9a3a-0b424ab3a180.png)

**Background**
![image](https://user-images.githubusercontent.com/10543509/81787006-02bc7f80-9533-11ea-89b3-69a7dd9ec137.png)
I have an active Github Enterprise integration, using a personal access token. The entrypoint to set one up was rather hidden. For example, on the "Codemarks in current file" page,  clicking the PR toggle at the bottom offers options that don't include Github Enterprise:
![image](https://user-images.githubusercontent.com/10543509/81787343-79597d00-9533-11ea-8728-3dffe76e4826.png)

But I was able to create this integration via the "Create new issue" screen. I don't have a screenshot of that anymore because I've already set it up. This is what "Create new issue" looks like for me now:
![image](https://user-images.githubusercontent.com/10543509/81787420-99893c00-9533-11ea-8743-de5867ff6528.png)

**System Info (please complete the following information):**
 - Version of the CodeStream extension:
![image](https://user-images.githubusercontent.com/10543509/81788088-8f1b7200-9534-11ea-99a9-1cbad6cf8ccc.png)
 - OS + version:
![image](https://user-images.githubusercontent.com/10543509/81788117-9e022480-9534-11ea-9694-7cde7752fd3c.png)
 - IDE + version:
![image](https://user-images.githubusercontent.com/10543509/81788153-a9555000-9534-11ea-9e7d-f0174a8135fa.png)

**Comment by planteater** [comment]
@awreccan - As soon as the dev team comes online I'll have them dig into why that repo dropdown is empty for you.

I also wanted to note that the reason that GitHub Enterprise isn't listed when you click on that PR toggle is that we don't currently have support for GH Enterprise for that aspect of the integration. That is, the display of PR comments within CodeStream. That should be coming soon though.

**Comment by planteater** [comment]
@awreccan - It's possible that when you set up the GHE connection you may have had a typo in the Base URL. Its looks like our requests are trying to hit github.yourdomain.coms. Note the "s" at the very end.

Can you go to the Integrations page, disconnect from GHE, and then try connecting again. Once you reconnect, go to create an issue codemark and see if the repo dropdown is now populated. Thanks!

**Comment by awreccan** [comment]
That worked! Sorry for the typo and thanks a lot for the prompt support! 🙂 Maybe some error messaging with the ability to see the domain name might be useful going forward? Anyway, closing this!

**Comment by planteater** [comment]
@awreccan - Glad to hear that you're good to go now! We're definitely going to look into ways we could have caught this issue and messaged appropriately.
