### ISSUE TITLE
Codestream interferes with rebasing in Jetbrains Rider

### ISSUE THREAD

**Issue by caveman-dick** [TeamCodeStream/codestream#191]
When trying to rebase with the JetBrains Rider IDE I am getting lock issues saying that another process is locking the git repo. When I try to continue straight afterwards there is another error saying that the message file is gone. 

I disabled the codestream plugin and restarted. I tried the same action and it worked straight away. Restarting again with codestream enabled the issue was back. 

There is a flag you can check to stop your code using the GitRepository object when a rebase is in progress as the GitToolBox plugin uses this:

https://github.com/zielu/GitToolBox/blob/805741ddfe82b886075826a35a7c86049329d2ae/GitToolBox/src/main/java/zielu/gittoolbox/fetch/AutoFetchTask.java#L121

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 7.2.1+49
 - OS + version: Win 10
 - IDE + version: Rider 2020.1.2

**Comment by planteater** [comment]
@caveman-dick - Thanks for the report. Any chance I could trouble you to send us a log file? Just reproduce the issue, and then grab the log file by going to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. Thanks!

**Comment by planteater** [comment]
@caveman-dick - I should also note that you can send the log file directly to me at support@codestream.com instead of posting it here.

**Comment by planteater** [comment]
@caveman-dick - This has been fixed in v10.1.0.
