### ISSUE TITLE
Have PR/MR comments from GH/BB/GL flow through activity feed

### ISSUE THREAD

**Issue by suguspnk** [TeamCodeStream/codestream#193]
Currently, PR comments can only be viewed in "Codemarks in Current File". It would be good if it also exists in the activity feed so we can see all the PR comments for the branch.

P.S. It would be exciting if I won't have to leave my IDE when doing code reviews.

**Comment by thetoothpick** [comment]
This would be really useful for Bitbucket PR comments as well.
