### ISSUE TITLE
How to see subsequent code changes to a Code Review?

### ISSUE THREAD

**Issue by snowfrogdev** [TeamCodeStream/CodeStream#194]
So my teammate requested a CodeStream Code Review. I made some comments and marked them as required for approval. My teammate proceded to make the changes and make a new commit. But the new commit with the required changes to do not show up in the Code Review. How can the code review be updated to show the latest changes?

**Comment by planteater** [comment]
@snowfrogdev - At the moment, best bet is to have your teammate submit a new code review request. That said, sometime in the next week or so we'll have a new update out that will allow you to ammed a code review. That is, you'll be able to add additional commits and local changes to the review and then have the assigned reviewers take another look. I'll update you here as soon as this is available.

**Comment by planteater** [comment]
@snowfrogdev - This is now available in v7.3 of the CodeStream extension. Read more here:

https://www.codestream.com/blog/codestream-7-3-update-existing-code-reviews-with-additional-code-right-from-your-ide
