### ISSUE TITLE
.codestreamignore should accept directory/wildcard/regex exclusions

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [TeamCodeStream/CodeStream#195]
**Describe the bug**
We have some directories in our repos containing tracked files that never need review. I would like to be able to add these to the `.codestreamignore` file, but nothing other than a direct reference to each file seems to work. It would be great if this file worked more like a `.gitignore` file, but even just matching directories would be enough for my purposes.

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 7.2.5
 - OS + version: Win 10
 - IDE + version: 1.45.1

**Comment by ppezaris** [comment]
working on this one... should have a fix in our next release

**Comment by planteater** [comment]
@ehoogeveen-medweb - This is now available in v7.3.0 of the CodeStream extension, which was just released.

**Comment by ehoogeveen-medweb** [comment]
Great, thanks!
