### ISSUE TITLE
DPI scaling broken in IntelliJ on Linux

### ISSUE THREAD

**Issue by thetoothpick** [TeamCodeStream/codestream#203]
Hello,

When running on Ubuntu 20.04 with DPI scaling (either 150% or 200%), the CodeStream IntelliJ plugin only renders in the top left 1/4th of the pane (see screenshot below).

![image](https://user-images.githubusercontent.com/1460628/85341673-94f26480-b49d-11ea-9df2-05a594faec0f.png)

**Comment by planteater** [comment]
@thetoothpick - If you don't mind, try this. Go to Help > Edit Custom VM Options, and then add the following:

-Dsun.java2d.uiScale.enabled=false

Restart your IDE and let me know if that helps.

**Comment by thetoothpick** [comment]
Hi @planteater

This actually doesn't fix the problem - it just makes the text smaller.

Screenshot:

![image](https://user-images.githubusercontent.com/1460628/86429404-42d2ef80-bca4-11ea-9d5e-761b359f44d0.png)

**Comment by planteater** [comment]
@thetoothpick - Could you go to the About IntelliJ page and copy that info, then paste it here?

Ultimately, the issue here is our use of JXBrowser to render the CodeStream webview. The good news is that JetBrains has JCEF coming soon so we can leverage native functionality and hopefully eliminate these rendering issues.

**Comment by thetoothpick** [comment]
> IntelliJ IDEA 2020.1.2 (Ultimate Edition)
> Build #IU-201.7846.76, built on May 31, 2020
> Licensed to XXXXXXXXXXXX
> Subscription is active until December 6, 2020
> Runtime version: 11.0.7+10-b765.53 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> Linux 5.4.0-39-generic
> GC: ParNew, ConcurrentMarkSweep
> Memory: 3983M
> Cores: 16
> Registry: ide.suppress.double.click.handler=true
> Non-Bundled Plugins: String Manipulation, YAML/Ansible support, com.codestream.jetbrains-codestream, com.daylerees.rainglow, Lombook Plugin, app.teamhub, Jetbrains TeamCity Plugin, org.jetbrains.plugins.hocon, org.sonarlint.idea, com.intellij.ideolog, com.jetbrains.plugins.ini4idea, mobi.hsz.idea.gitignore, net.sjrx.intellij.plugins.systemdunitfiles, net.vektah.codeglance, org.intellij.plugins.hcl, com.atlassian.bitbucket.references, org.intellij.scala, Pythonid, org.jetbrains.kotlin
> Current Desktop: ubuntu:GNOME

**Comment by planteater** [comment]
@thetoothpick - We just released v8.3.1 of our extension that addresses this issue. Note, though, that you must be using v2020.2 of IntelliJ.
