### ISSUE TITLE
Unable to change email from VSCode

### ISSUE THREAD

**Issue by nfadili** [TeamCodeStream/codestream#204]
When requesting code reviews I am getting a warning that the email in my gitconfig does not match my CodeStream email. When I attempt to change it, I either get an error message saying 'that email is already taken' or it says it sends a confirmation email but I have not received any. I own both email addresses and have checked my spam folders.

I'd like to change my email to match what is in my gitconfig.

**Comment by planteater** [comment]
@nfadili - Best bet would be for you to email me at support@codestream.com, as I'll need both of the email addresses in question in order to determine what's going on here.  As soon as I know those addresses, I'll dig into this asap. Thanks!
