### ISSUE TITLE
Disconnects after a short time

### ISSUE THREAD

**Issue by unknownguy2002** [TeamCodeStream/CodeStream#21]
After about 25 seconds, the chat starts to disconnect.
<img width="590" alt="screen shot 2018-11-28 at 6 52 56 pm" src="https://user-images.githubusercontent.com/24543395/49147175-e7f64b00-f33e-11e8-9c17-8a71509d85c7.png">

**Comment by planteater** [comment]
@unknownguy2002 - Does this happen every time you load CodeStream? Any chance I could trouble you for some log files? If so, here are the details:

- In your VS Code user settings (see gear menu at bottom left of VSC), search for CodeStream and change the Trace Level setting to "Debug".
- Reload VS Code by going to the VS Code command palette (Cmd + Shift + P) and then searching for Reload Window.
- When the problem happens again, open the VS Code Output view with Cmd + Shift + U and select "CodeStream" from the dropdown at the top-right of that pane.
- Copy everything there and paste it into a text file to send to me (dave@codestream.com).
- Change the dropdown selection to "CodeStream (Agent)" and grab that output as well.

Thanks!

**Comment by eamodio** [comment]
@unknownguy2002 are you still experiencing the same issue? From the logs you provided it seems like the slack client isn't able to connect to the slack real-time server. Do you have a proxy or any other specific network configuration that might block that?

**Comment by unknownguy2002** [comment]
I have a VPN, but it wasn't turned on. yes, I'm still experiencing it

**Comment by eamodio** [comment]
Hrm. Can you try out CodeStream 0.30 to see if that has any effect on the behavior you are seeing?

**Comment by unknownguy2002** [comment]
Hmm.. trying now

**Comment by unknownguy2002** [comment]
Seems to be fixed
