### ISSUE TITLE
Allow a comment to be marked as a change-request when editing

### ISSUE THREAD

**Issue by natanavra** [TeamCodeStream/codestream#211]
1. Create a comment (forget ticking "Change Request")
2. Edit the comment and tick "Change Request"
3. Save
4. Nothing happens

Expected result:
Change request should be added.

**Comment by planteater** [comment]
@natanavra - In theory, you shouldn't be able to go back and turn a regular comment into a change request, but maybe we've got a loophole in there somewhere. Can you let me know the steps to reproduce this? I created a comment in a review, then went to edit it, and there was no change-request checkbox there. But maybe you're doing something slightly different than me. Also let me know what IDE you're using and which version of CodeStream. Thanks!

**Comment by majkinetor** [comment]
You should be able to do so.

I suggest also a hotkey like SHIFT + ENTER that automatically checks change request, and also global setting to make it default (I for instance rarely comment on code, everything is change request which makes me often forget to click it).
