### ISSUE TITLE
Error al generar comentario

### ISSUE THREAD

**Issue by rolmon** [TeamCodeStream/codestream#213]
Cuadno trato de realizar un comentario me sale el siguiente error "There was an error creating the codemark.". Soy el único con el problema en el equipo. Espero me puedan ayudar

**Comment by planteater** [comment]
@rolmon - Could I trouble you to send us a log file? Instructions for generating the log file are here:

https://docs.codestream.com/userguide/faq/client-logs/

If you want, you can email the log file to me at support@codestream.com. Thanks!

**Comment by marcelofarias** [comment]
@rolmon Podría usted enviarnos sus logs para support@codestream.com? Las instrucciones están aqui: https://docs.codestream.com/userguide/faq/client-logs/

Gracias!
