### ISSUE TITLE
private server

### ISSUE THREAD

**Issue by fleksin** [TeamCodeStream/CodeStream#22]
Hi all, I know this may be a long shot. But is it possible in the future to have CodeStream be deployed on a private server ? You know, for security reasons, Could CodeStream be bought as a private services and deployed as the buyer's wish? Sort of like JIRA.

**Comment by planteater** [comment]
@fleksin - I think there's a good chance that we offer an on-prem solution sometime in 2019.

**Comment by fleksin** [comment]
Thank you :) good to know

**Comment by christig** [comment]
I'd be interested in this as well. I'd like to introduce the product to my team but feel it'd be a non-starter without the option to store our data on our own private server.

**Comment by planteater** [comment]
@fleksin - We are currently beta testing our on-prem solution. If your team would like to be one of the first to kick the tires, reach out to us at support@codestream.com. Thanks!
