### ISSUE TITLE
Copy - Paste doesn't work inside CodeStream sidebar

### ISSUE THREAD

**Issue by hptavakoli** [TeamCodeStream/codestream#220]
Till now, when I create a comment, it was possible to copy and paste some parts of that, but now I can not do it. I just happened after updating VSCode to the last version.

VSCode info:
Version: 1.47.2 (user setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by planteater** [comment]
@hptavakoli - Can I get a few more details....

- When you copy the contents of the codemark/comment, is it after you click the codemark to go to its expanded view? Or are you copying from the collapsed view in either the Activity Feed or Current File tab?
- Are you copying text that you entered, or part of the code block?

Thanks!

**Comment by hptavakoli** [comment]
I do it as I did before, but it doesn't work now:

1. When I am writing some comment, It can not copy that
2. The right-click function is completely deactivated
3. Can not copy from the comment in editing mode and in view mode

I attached some image to make it more clear:

A: I selected part of the comment, **in collapse mode** but the copy doesn't work, right-click doesn't work.
![image](https://user-images.githubusercontent.com/37811925/87849263-738f6780-c8e7-11ea-8d3f-171a8b05546e.png)

B: I selected part of the comment, **in expand mode** but the copy doesn't work, right-click doesn't work.
![image](https://user-images.githubusercontent.com/37811925/87849298-bcdfb700-c8e7-11ea-9de1-b2d6bb29d8ce.png)

C: I selected part of the **code**, but the copy doesn't work, right-click doesn't work.
![image](https://user-images.githubusercontent.com/37811925/87849310-d680fe80-c8e7-11ea-8741-c7c4ccff56a2.png)

D: I selected part of the comment, in **Edit mode** but the copy doesn't work, right-click doesn't work.
![image](https://user-images.githubusercontent.com/37811925/87849321-f9131780-c8e7-11ea-970e-199187ad31ae.png)

**Comment by planteater** [comment]
Thanks for the additional info @hptavakoli! I just did some testing and I see as well that the right-click context menu does not appear. I'll see if we can get this fixed, but note that in the interim they keyboard shortcuts (i.e., Control C and Control V) do seem to work.

**Comment by hptavakoli** [comment]
Unfortunately, it doesn't work for, I have tried it and also check my clipboard with clipboard manager to see whats happened there, sometime it will copy just an empty string! but in most cases, it couldn't copy anything.

**Comment by planteater** [comment]
@hptavakoli - It looks like this is something that Microsoft broke with the latest version of VS Code. There are some open issues related to it on their GitHub. I'm following those issues and I'll update you here once they've released a fix.

**Comment by planteater** [comment]
@hptavakoli - Looks like this has been addressed in VS Code 1.47.3.

**Comment by hptavakoli** [comment]
Thanks for informing me
@planteater I have this version, it works sometimes but  still, sometimes it doesn't work, I didn't get why, but trying to figure out
