### ISSUE TITLE
Comment doesn't appear in some files

### ISSUE THREAD

**Issue by hptavakoli** [TeamCodeStream/codestream#221]
Previously When I add a comment on code, a blue chat icon was there to indicate there is a comment on this line or part of code.
But now it doesn't work in some files.

I have to file open (HTML & JS)
I can see comments in HTML, but not in JS.
I should mention even comments with Range feature (selecting different parts of code) are the same, I mean I can see the part which is in the HTML file, but not the part in my JS file.

I tried it on the other file in the same project, it works correctly, but not in this specific file.

**VSCode info:** (Was the same in the previous version, not solve after this update of VSCode as well)
Version: 1.47.2 (user setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by planteater** [comment]
@hptavakoli - Some additional questions here as well...

- In this JS file, are no codemarks appearing, or is it just new codemarks that don't show?
- By any chance was this file renamed?

Ultimately, I think we're going to need a log file to diagnose this.

- Open a file where you expect there to be codemarks, and then assuming you don't see then, immediately...
- Open the VS Code Output view (“View: Toggle Output” from the command palette) and select "CodeStream (Agent)" from the dropdown menu at the top-right. 
- Copy all of the output you see and save it in a text file.

If you'd prefer, email that file to me at support@codestream.com. Thanks!

**Comment by hptavakoli** [comment]
1. It doesn't show any code mark at this file.
2. No rename in this file, but change ar code happened *some part deleted, some code added or edited and so on)
- In sidebar, it can detect the comments and show them, also when I click on the part of code that I know there is a comment on that, it will show that specific comment, but code marks will not appear at all.

Please check this image:
![image](https://user-images.githubusercontent.com/37811925/87849420-cfa6bb80-c8e8-11ea-8b51-a5873a712eb8.png)

**About the second part, log file:**
I closed the VSCode, open it, and before doing any change, copy all log files in the text file (please check your email).

**Comment by marcelofarias** [comment]
Hi @hptavakoli ! Thanks for the information.

We believe there might be some interplay between CodeStream and some other VS Code extension that ends up affecting how we render the inline glyphs. Could you please provide the list of extensions you have installed so we can investigate it?

**Comment by hptavakoli** [comment]
Hi @marcelofarias , 
UWC. screenshots of my current extensions are here:
![image](https://user-images.githubusercontent.com/37811925/88032135-d9752c80-cb3d-11ea-872e-63b7ea524a62.png)
![image](https://user-images.githubusercontent.com/37811925/88032212-f14cb080-cb3d-11ea-97ce-618b6608bae3.png)

If you need more details, let me know.
* I will recommend you to check TabNine extension, it was the last extension that I installed, couldn't remember before updating VSCode or after that.

**Comment by planteater** [comment]
@hptavakoli - I wanted to let you know that we're still digging into this one, but we have yet been able to reproduce or diagnose the issue. Can you let me know if you're seeing this issue in any other JS files, or if it's specific to this one file? Thanks.

**Comment by hptavakoli** [comment]
Hi,
yes, it happened on another project as well. please check it here:
![image](https://user-images.githubusercontent.com/37811925/89570571-acf02e80-d826-11ea-91d4-1478e19f3940.png)

If you think it would be useful, I can give you access to this project, this is a test project.

**Comment by planteater** [comment]
@hptavakoli - If you don't mind, I'd love to get access to the project so that we can try to reproduce the issue in a scenario that more closely mimics your own. Thanks!

**Comment by hptavakoli** [comment]
@planteater it seems ok, just give me a way to provide your access to the project
It is on Bitbucket

**Comment by planteater** [comment]
Sounds good @hptavakoli. I'm codestreamdave on Bitbucket.

**Comment by planteater** [comment]
@hptavakoli - If that doesn't work, my email on BB is dave@codestream.com

**Comment by planteater** [comment]
@hptavakoli - Can you let me know if you are still seeing this issue?
