### ISSUE TITLE
Bug with Code range function

### ISSUE THREAD

**Issue by hptavakoli** [TeamCodeStream/codestream#234]
This issue usually happened and I think you should solve it because it will make this function (very nice function!) completely unusable.

Look at this screenshot, I just wrote this code (line 24) and I want to save the comment with some related range code to it:

![image](https://user-images.githubusercontent.com/37811925/89028737-3edecf80-d32d-11ea-9048-e86d7b71d791.png)

So, everything seems ok, am I right?
But immediately when I click on the submit, it will turn to this:

![image](https://user-images.githubusercontent.com/37811925/89028868-70f03180-d32d-11ea-9c8a-ce416430cba9.png)

So if you consider, you will find these issues:

1. My code started at line 24, but it mentioned that it is in line 22!
2. There is a comment sign in line 26 and it doesn't make sense at all, because not only I did not add any comment there, but also it was not in my selected range code
3. It will show that 2 parts of the code are changed (look at the codestream pannel, there is two error on the selected code range). First of all, I never change it at all, I just hit the submit button!!! also they totally mentioned a wrong line number.

I was really so excited about your extension and the idea, but it seems you have lots of bug in there, please try to solve it otherwise there is no way and we should leave you alone.
I reported a couple of bugs in the previous week and mostly they are blocking bug that I can not continue working with this extension or relly on it for our product documentation.

Update:
Even I use the **reposition code mark function** to fix it, I select the right position of the code, but still, it couldn't figure it out and again determined the wrong line number!!!

![image](https://user-images.githubusercontent.com/37811925/89029505-e6103680-d32e-11ea-87ac-485c05163772.png)

![image](https://user-images.githubusercontent.com/37811925/89029518-ee687180-d32e-11ea-9429-90cd00f83a37.png)

* It should be in line 24, not 22!

**Comment by planteater** [comment]
@hptavakoli - We think we might have a fix for this? Do you mind trying out a pre-release version of our extension? You can download it from here:

https://www.dropbox.com/s/qoqitn9ab9fyftc/develop-codestream-8.3.2%2B4333.vsix?dl=0

Once downloaded:

- Go to the Extensions entry in the VS Code activty bar
- Go to the ellises menu at the top-roght of the sidebar and select "Install from VSIX"
- Reload your IDE when prompted.

Now, go ahead and try to create a new codemark like the one you depicted above. Let me know how it goes. Thanks!

**Comment by planteater** [comment]
@hptavakoli - Version 8.3.2 is now available in the VS Code marketplace, so you can simply update the CodeStream extension as you would normally. Let me know if it fixes the issue. Thanks!

**Comment by hptavakoli** [comment]
It seems it is released, so I will download the stable version and inform you soon
