### ISSUE TITLE
GitLab Integration Request Flurry

### ISSUE THREAD

**Issue by tredmon** [TeamCodeStream/codestream#237]
From time to time the plugin makes a flurry of requests to get all the merge request notes for projects open in IntelliJ. This is fine for new microservice projects with only a few merge requests, but for old monolithic projects with tens of thousands of merge requests this causes a heavy load on the on-premise gitlab instance. Usually the gitlab instance handles ~20 api requests per second, but a single user in CodeStream can cause that number to jump to the 100s of requests per second mark (we've seen up to 12 thousand requests per minute from a single CodeStream user!), causing overall gitlab slowdowns or user api rate limiting if enabled (which would affect other user integrations).

I have 3 suggestions:
- Store all needed data from gitlab in local storage so a "request flurry" only needs to happen once per user
- Get only the merge requests/notes updated since the last gitlab comment sync
- Add a "request quota" option to the integration to allow users to configure the max requests per second

**Comment by planteater** [comment]
Thanks for the input @tredmon! Optimizing this integration is on our near term roadmap, along with a generally more powerful GitLab integration. I'll keep you posted here.

**Comment by aishvaryaps** [comment]
I was earlier able to validate my github integration in codestream.
however now i am getting errorr : 
**_Endpoint validation failed : Status Code 401_**

I am sure the password and user name is correct
![image](https://user-images.githubusercontent.com/48279639/101017431-193e2d00-3590-11eb-85ca-2163bc53faac.png)


Github Repo URL:
https://github.com/aishvaryaps/helloworld

**Comment by scottt732** [comment]
I'm not sure if this is the same issue, but I just took down our on-prem gitlab instance with 31.4k calls like this: `/api/v4/projects/mygroup/myproject/merge_requests/1234/changes` from `User-agent: node-fetch/1.0 (+https://github.com/bitinn/node-fetch)`. I was trying to work through a rebase/squash in a shell with the IDE idle in the background.

**Comment by planteater** [comment]
As of v12.11, we are no longer showing glyphs for PR comments in the editor gutter. Only in the gutter of the diffs for the PR.
