### ISSUE TITLE
Slack Integration: improve unread channel highlight

### ISSUE THREAD

**Issue by seangates** [TeamCodeStream/CodeStream#24]
Currently the unread channel highlight only shows bold. This is okay, but in my editor (with my current theme) the unread channels are actually hard to differentiate among the other channels. Maybe add another visual indication of unread status? Maybe a dot, icon, or increase the color contrast?

![image](https://user-images.githubusercontent.com/105656/49664257-8f920e00-fa0e-11e8-8f4c-348fec66eeb4.png)

**Comment by planteater** [comment]
Closing this, as support for stream-based comminucation within CodeStream is no longer a priority.
