### ISSUE TITLE
codestream docker image cannot download, the shell is not work!

### ISSUE THREAD

**Issue by ZxBee** [TeamCodeStream/codestream#244]
mkdir ~/.codestream
cd ~/.codestream
curl -s -O https://raw.githubusercontent.com/TeamCodeStream/onprem-install/master/install-scripts/codestream
chmod +x codestream
~/.codestream/codestream --quickstart

**Comment by jimmyjayp** [comment]
The images are in public repositories on docker hub and you haven't posted anything that might help me to troubleshoot your problem. Perhaps you could post a copy of your shell session where you attempted to run those commands?

**Comment by planteater** [comment]
@ZxBee - Hi! Just wanted follow up to see if you could provide some additional detail. Thanks!
