### ISSUE TITLE
Visual Studio 2019 Extension code selection/range fails when path contains two or more spaces.

### ISSUE THREAD

**Issue by unt1tled** [TeamCodeStream/codestream#257]
This one took me awhile to figure out. When the your project path contains two or more spaces (yes, not one), the [Visual Studio 2019 extension](https://marketplace.visualstudio.com/items?itemName=CodeStream.codestream-vs) fails to capture code selections or ranges.  

Here are the steps to reproduce:
1. Create a console app with a single space in the root of your C:\
```
mkdir 'New Project'
cd '.\New Project\'
dotnet new console
```
2. After opening the project, highlight a section of code and add a new Code Stream comment `CTRL+SHIFT+/, C`

3. Observe that the lines you've highlighted are captured in the Code Stream extension's codemark dialog:

![image](https://user-images.githubusercontent.com/5357052/90968112-97c9ff80-e4b6-11ea-9f15-47bb4235bf2d.png)

4. Repeat the steps 1-2 above, replacing "**New Project**" with "**New Project With Space**"

5. Observe that the lines you've highlighted are not captured in the codemark dialog:

![image](https://user-images.githubusercontent.com/5357052/90968116-a6b0b200-e4b6-11ea-95ba-732356d1ce90.png)

_Visual Studio 2019 Professional: v16.6.5
CodeStream Extension Version: 8.3.3.2443
Windows 10 Pro Insider Version 10.0.20197 Build 20197_

**Comment by planteater** [comment]
Thanks for the report @unt1tled. We'll dig into this right away!

**Comment by bcanzanella** [comment]
Hi @unt1tled 

This is fixed in the latest release (8.3.4)!

Thanks!
