### ISSUE TITLE
Codemarks: Display icons in glyph margin

### ISSUE THREAD

**Issue by ghost** [TeamCodeStream/codestream#26]
The inline icon decoration obscures my understanding of the code so it would be nicer if it was located in the glyph margin (similar to the Bookmarks extension).

**Comment by planteater** [comment]
We would love to do that, but unfortunately VS Code doesn't allow for icons in the glyph margin that have a clickable hover. That said, we're exploring an all-new way of associating codemarks with code blocks that will take the markers completely out of your source files. Stay tuned!

**Comment by planteater** [comment]
At this point it does not look like MSFT is going to add the support we need to move the icons into the gutter.
