### ISSUE TITLE
Request codestream/review/contents failed with message: spawn /usr/bin/git ENOENT

### ISSUE THREAD

**Issue by masi** [TeamCodeStream/codestream#262]
The error appear when I try to view certain files of a review. It does not affect all files, but the error persists for the affect files.

Me and my colleague are using PhpStorm. Neither restarting the IDE nor sending out a new review request helped.

**Comment by planteater** [comment]
@masi - Thanks for the report! C ould I trouble you for a log file? In PhpStorm, go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. Feel free to email it to me at support@codestream.com if you'd prefer not to post it here. Thanks!

**Comment by masi** [comment]
I've sent zip by mail.

**Comment by planteater** [comment]
@masi - Thanks for your patience on this. If you update to v9.0.4 of our extension this issue should be resolved now.
