### ISSUE TITLE
Button without any action and some undefined labels on VS Code

### ISSUE THREAD

**Issue by JoseVf** [TeamCodeStream/CodeStream#29]
I've seen a couple issues on VS Code's CodeStream  plugin. The first one is that the _delete_ button on the `Direct Messages` section does nothing at all.<br>
![screen shot 2018-12-12 at 9 11 51 am](https://user-images.githubusercontent.com/22102736/49875469-166c2f80-fdef-11e8-88db-74caf155baaa.png)<br>
![btnwithoutaction](https://user-images.githubusercontent.com/22102736/49877469-795fc580-fdf3-11e8-85db-619cff05a9b1.gif)

The other one is that the `Channel Settings` on a `Direct Message` chat shows some `undefined` labels.<br>
![screen shot 2018-12-12 at 9 11 32 am](https://user-images.githubusercontent.com/22102736/49877653-e2473d80-fdf3-11e8-9418-711bec4bb9b6.png)

**Comment by planteater** [comment]
Closing as the references areas of the service were removed many months ago.
