### ISSUE TITLE
Error 401: Unauthorized when opening a pull request

### ISSUE THREAD

**Issue by pabfloso** [TeamCodeStream/codestream#296]
I am trying to submit a pull request with CodeStream integration for IntelliJ logged with GitLab Self-Managed. 
When logging I specified my personal access token with full permissions but I still get this error when submitting a pull request.

![imagen](https://user-images.githubusercontent.com/39587382/95977289-fd809b00-0e18-11eb-979b-e0e0b6a0f5ca.png)

However, I am able to submit a "Request Review" without authorization problems. 

Do I have to do something else on my gitlab self-managed account apart from introducing the personal access token?

Thanks.

**Comment by planteater** [comment]
Thanks for reaching out on this. I think we'll need a log file to help diagnose this. Reproduce the issue and then in your IDE go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. If you'd prefer not to post the log file here, please send it to us at support@codestream.com. Thanks!

**Comment by planteater** [comment]
@pabfloso - Just wanted to follow up to see if we could get that log file. Thanks!

**Comment by planteater** [comment]
@pabfloso - One last request for that log file. Thanks!

**Comment by liuliangsir** [comment]
Same issue here. The followings are a bunch of screenshots.

![image](https://user-images.githubusercontent.com/8049878/97977661-85016e80-1e07-11eb-92f6-0243d08a5c2b.png)

**Comment by planteater** [comment]
@liuliangsir - Could I trouble you for a log file? Reproduce the issue and then in VS Code open the Output view (“View: Toggle Output” from the command palette) and select "CodeStream (Agent)" from the dropdown menu at the top-right. Copy all of the output you see and save it in a text file. f you'd prefer not to post the log file here, please send it to us at support@codestream.com. Thanks!

**Comment by liuliangsir** [comment]
@planteater awesome! I am so glad to help you address the issue above.

**Comment by planteater** [comment]
@liuliangsir - Could I trouble you to send the complete log file? Again, if you're not comfortable sharing that here, just email it to me at support@codestream.com. Thanks!

**Comment by liuliangsir** [comment]
@planteater I have already sent the complete log file. You should check out the email(support@codestream.com).

**Comment by planteater** [comment]
@liuliangsir - unfortunately I haven’t received anything. Maybe try sending it to me directly at dave@codestream.com?

**Comment by liuliangsir** [comment]
@planteater is here any update?

**Comment by planteater** [comment]
Not quite yet @liuliangsir, but hopefully we'll have an update very shortly.

**Comment by planteater** [comment]
@liuliangsir - Please check your Inbox for an email sent by one of my colleagues. He had some questions about your remotes.

**Comment by planteater** [comment]
@liuliangsir - Just wanted to confirm that you received Brian's email. Thanks!

**Comment by liuliangsir** [comment]
@planteater I have already answered the questions.

**Comment by liuliangsir** [comment]
@planteater is here any update?

**Comment by planteater** [comment]
@pabfloso @liuliangsir - This has been fixed in v10.1.0.
