### ISSUE TITLE
Logging to debug console when debugging different extension

### ISSUE THREAD

**Issue by RMacfarlane** [TeamCodeStream/CodeStream#3]
Apologies if this isn't the right place to log issues!

Issue Type: <b>Bug</b>

When I start debugging my own extension, CodeStream also starts in debug mode and logs a lot of data in the Debug Console:

![screen shot 2018-09-24 at 4 03 39 pm](https://user-images.githubusercontent.com/3672607/45983946-adf18b80-c013-11e8-827e-a7fd69038278.png)

It would be great if it didn't do that by default, or if there was a way to turn it off.

Extension version: 0.12.0
VS Code version: Code - Insiders 1.28.0-insider (29e67955fdb888fc6538ef60dc4664293f56d453, 2018-09-24T12:04:09.319Z)
OS version: Darwin x64 17.7.0

**Comment by eamodio** [comment]
Doh. Sorry about that. We'll get that fixed up in the next update (should be very soon)

**Comment by eamodio** [comment]
This is fixed in 0.13
