### ISSUE TITLE
Change email not working

### ISSUE THREAD

**Issue by yun-li** [TeamCodeStream/codestream#300]
I hope to change my email.
I do it like this 
Account -> Change email -> enter my new email -> wainting for the email link.

However, no new email sent to my email address. I checked Spam folder and use different email address and no help. Can you check with that?

My username on codestream in @iliyun

Thanks!

**Comment by planteater** [comment]
@yun-li - Thanks for reaching out on this. In order to help figure this out I'll need the current email address on your account as well as the new address you're trying to use. If you'd prefer not to post that information here, please email me at support@codestream.com. Thanks!

**Comment by yun-li** [comment]
@planteater Thanks. I just sent the info to support@codestream.com.

**Comment by planteater** [comment]
The issue with confirmation emails not going out when you change your email address has been fixed.
