### ISSUE TITLE
creating Feedback Request fails

### ISSUE THREAD

**Issue by ArchyInf** [TeamCodeStream/codestream#301]
When trying to create a new Feedback Request I get this git error:

`Error: Command failed: C:\Program Files\Git\cmd\git.exe -c core.quotepath=false -c color.ui=false log jm/Perf_vfx --format='%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e --not refs/heads/TEMP refs/heads/+ jm/2020.2 refs/heads/jm/AttachmentIssue refs/heads/jm/DX12Test refs/heads/jm/DrawCallCheck refs/heads/jm/EcsPrecreation refs/heads/jm/EntitiesUpdate refs/heads/jm/FinalFrontier refs/heads/jm/IKnowWhatImDoing_seriously refs/heads/jm/Mem refs/heads/jm/Mem.DropFbx refs/heads/jm/Mem.ImportFixes refs/heads/jm/MemDebug refs/heads/jm/Mem_EntityCaches refs/heads/jm/Mem_WIP_TEST refs/heads/+ jm/PS4 refs/heads/jm/Perf refs/heads/jm/Perf_2 refs/heads/jm/Perf_Vfx_2 refs/heads/+ jm/Perf_nav refs/heads/jm/RemotesFixes refs/heads/jm/Textures refs/heads/jm/Vulkan refs/heads/jm/XB1 refs/heads/jm/sony_switch refs/heads/jm/v0.18 refs/heads/master refs/heads/packages/InputSystem refs/heads/packages/PackageStart refs/heads/packages/Physics refs/heads/packages/ScriptableRenderPipeline refs/heads/packages/ScriptableRenderPipeline_2020.2 refs/heads/+ packages/com.unity.dots.editor refs/heads/packages/com.unity.entities refs/heads/release/v0.18 refs/heads/release/v0.19 -- fatal: bad revision 'refs/heads/+ jm/2020.2'`

**Comment by planteater** [comment]
@ArchyInf - Thanks for reporting this. Could I trouble you for a log file? That will help us get to the bottom of this. Instructions can be found at the link below, and if you'd prefer not to share the logs here you can email them to us at support@codestream.com. Thanks!

https://docs.codestream.com/userguide/faq/client-logs/

**Comment by planteater** [comment]
@ArchyInf - Could you also do a `git branch` and send us the output?

**Comment by ArchyInf** [comment]
Send everything to support@codestream.com

**Comment by planteater** [comment]
Thanks @ArchyInf! I haven't received anything yet, but I'll keep my eye out.

**Comment by planteater** [comment]
@ArchyInf - This has been resolved in v10.0.2 of the CodeStream extension. Let us know how it goes!
