### ISSUE TITLE
Add support for JIRA custom fields that don't have default values

### ISSUE THREAD

**Issue by tmyllymaki** [TeamCodeStream/codestream#309]
As I'm creating an issue to Jira the "add a " part of UI is empty and I can't open the issue type list:

![image](https://user-images.githubusercontent.com/10549023/97001549-34edf680-1541-11eb-8d54-27be5699c083.png)

Tested in VSCode and Rider.

**Comment by ppezaris** [comment]
Hi @tmyllymaki currently codestream is limited in the following way: we can only create issues that either don't have required custom fields, or if they do have required custom fields, there is a default value.

Is it possible that for your project, all of the ticket types contain a required custom field that does not have a default value?

**Comment by tmyllymaki** [comment]
I guess it's a plugin field which is required. It assigns a default value but I'm not quite sure if it has a proper default value. Couldn't figure anything else. Other required fields were regular Summary etc.

**Comment by planteater** [comment]
Duplicate of https://github.com/TeamCodeStream/codestream/issues/528
