### ISSUE TITLE
Is there any way to disable Codestream for particular project or use another account?

### ISSUE THREAD

**Issue by RIP21** [TeamCodeStream/codestream#311]
Let say I'm working on multiple projects in multiple teams or companies.
One may use Codestream, but others don't, and it creates a very frustrating experience when I open a project when there is no Codestream attached, but I still have this side panel for no reason. 
Or another, use case, when I have two different accounts. One for one organization and one for another organization. 
Or working profile and private profile for Opensource work let say.

Being able to log in separately in each project to different codestream accounts or not being logged at all for some, will be the best thing.

**Comment by planteater** [comment]
@RIP21 - I might suggest trying to use a single CodeStream account if possible, that way you can simply switch between CodeStream teams using the team switcher (under the headshot menu at the top-left of the CodeStream pane). When you create a new team (via that same menu), you can also specify if the team should be owned by the same organization/company as the current team, or you can create a separate organization to own the team. In other words, you can keep things totally separate when appropriate without needing multiple CodeStream accounts.
