### ISSUE TITLE
Gitea integration

### ISSUE THREAD

**Issue by Daniel451** [TeamCodeStream/codestream#312]
I'd like to raise a feature request for Gitea integration. Gitea is similar to GitHub, but fully open source https://gitea.io/en-us/

**Comment by planteater** [comment]
Thanks for the suggestion @Daniel451 !

**Comment by septatrix** [comment]
GitLens is also currently working on Gitea integration: https://github.com/eamodio/vscode-gitlens/issues/1379

**Comment by dionisvl** [comment]
Hello, please add Gitea compatibility to CodeStream PhpStorm plugin.
