### ISSUE TITLE
No pull request tab

### ISSUE THREAD

**Issue by turfaa** [TeamCodeStream/codestream#321]
I am using Goland with Gitlab self-managed.

I have enabled the "Pull Requests" in View, but the pull request tab is not there.

![image](https://user-images.githubusercontent.com/21698471/98924607-fc25b980-250f-11eb-8e7b-dc254851e1f9.png)

![image](https://user-images.githubusercontent.com/21698471/98924639-047df480-2510-11eb-944c-7743f9ccc12c.png)

**Comment by planteater** [comment]
Sorry for the confusion caused by that menu, but the Pull Requests section is currently only available if you’re connected to GitHub.
