### ISSUE TITLE
Error: Request codestream/provider/pullrequest failed with message: undefined is not a function

### ISSUE THREAD

**Issue by turfaa** [TeamCodeStream/codestream#322]
Steps to reproduce:
- Try to create an existing pull request.
- There will be an error "There is already an open pull request for this branch." and a button "View pull request"
- Click "View pull request"
- Got this error.
(This issue may be related with https://github.com/TeamCodeStream/codestream/issues/321)
![image](https://user-images.githubusercontent.com/21698471/98924915-5b83c980-2510-11eb-84c8-dfd8866cac6c.png)

**Comment by planteater** [comment]
Thanks for the report @turfaa ! I think the issue here is that we’re trying to open the PR in codestream, which doesn’t work for non GitHub PRs, instead of opening it on GitLab. We have a fix for this ready and it should be released tomorrow. I’ll update you then.

**Comment by planteater** [comment]
@turfaa - This should be fixed in v10.0.4 of the CodeStream extension.
