### ISSUE TITLE
Suggestion: Mattermost integration

### ISSUE THREAD

**Issue by turfaa** [TeamCodeStream/codestream#323]
I don't know if you are accepting this kind of suggestion or not, but it would be very helpful if you have an integration with [Mattermost](https://mattermost.org/).

**Comment by planteater** [comment]
We're absolutely accepting these type of suggestion @turfaa! Keep them coming! In this case, we already have an open issue for the addition of Mattermost, so I'll close this one as a duplicate.

https://github.com/TeamCodeStream/codestream/issues/58
