### ISSUE TITLE
Cannot create branch on submodule

### ISSUE THREAD

**Issue by cgb37** [TeamCodeStream/codestream#325]
<img width="690" alt="Screen Shot 2020-11-13 at 1 37 22 PM" src="https://user-images.githubusercontent.com/10423452/99108606-97bd3580-25b5-11eb-94c2-2cca7f730ec5.png">

I cannot create a branch from within my Codestream plugin in IntelliJ. It recognizes that a submodule exists, but I cannot select the submodule in the drop down even though the repo is shown in the dropdown.

**Comment by planteater** [comment]
Thanks for reporting this @cgb37. Could I trouble you for a log file? In IntelliJ, reproduce the issue and then go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. If you'd prefer not to share it here, you can email it to me at support@codestream.com. Thanks!
