### ISSUE TITLE
Now Handled By

### ISSUE THREAD

**Issue by cgb37** [TeamCodeStream/codestream#328]
I created an account for our team using the team service account. This account became the CodeStream Admin user. I added our team members via invite. In my IntelliJ Codestream plugin my user is somehow a sub account of the Admin account and I cannot push to github

<img width="502" alt="Screen Shot 2020-11-17 at 8 51 08 AM" src="https://user-images.githubusercontent.com/10423452/99398512-85dbdb00-28b2-11eb-9c68-5677850fd15f.png">

**Comment by planteater** [comment]
@cgb37 - If you're signed in as the team admin, the "Now Handled by" column will be dropdown lists, and the last entry in the list will allow you to "Delete Mapping". Here's some more information on how the Blame Maps work:

https://docs.codestream.com/userguide/features/myteam-section/#blame-map
