### ISSUE TITLE
Code Suggestion presentation issue in VS-Code Extension

### ISSUE THREAD

**Issue by FFWayne** [TeamCodeStream/codestream#331]
In conducting a code review, team-mate code suggestions are appearing in the VS-Code extension with what appears to be some missing components.
![Replace1](https://user-images.githubusercontent.com/68245168/104049355-b4cb4a80-5199-11eb-9eac-3ef050ffb640.png)

The same comment in the associated GitHub code review appears as below, for comparison.

![replace2](https://user-images.githubusercontent.com/68245168/104049361-b72da480-5199-11eb-910b-d51e480aa488.png)

**Comment by planteater** [comment]
Apologies for the delayed response @FFWayne. Support for GitHub's suggestion model is on the roadmap.

**Comment by FFWayne** [comment]
Thanks for the heads up @planteater - is there someplace I can go to check out the roadmap, or is that an internal document?

**Comment by planteater** [comment]
@FFWayne - We don't (yet) have a public facing roadmap, but I should have a clearer picture on when this will get addressed over the next week or two. I'll update you here once a delivery date becomes clearer.

**Comment by FFWayne** [comment]
@planteater any word on that update?

**Comment by planteater** [comment]
@FFWayne - Unfortunately, I don't have a specific timetable yet, although I will say that we're looking to close some of these feature gaps during Q1. Our goal is to completely replicate the suggestion functionality from GH, both in terms of making and applying a suggestion, but my hope is that we can at least get comments with suggestions to render nicely as a more immediate step.

**Comment by FFWayne** [comment]
Thanks for the update! My team will keep their eyes open.

**Comment by planteater** [comment]
@FFWayne - The rendering of suggestions should be addressed in 10.4.1. After you update, have a look and let me know how things are looking.

**Comment by FFWayne** [comment]
I am seeing some lovely code suggestions now. Thanks for getting to this @planteater!
