### ISSUE TITLE
Slack channel list not fully visible when creating CodeMark

### ISSUE THREAD

**Issue by GPavlovic** [TeamCodeStream/CodeStream#34]
Creating a code mark, some of the channel/direct message names are long, seems to force the popup menu out of view.

![image](https://user-images.githubusercontent.com/5474337/52488832-b98eba80-2b8e-11e9-8771-f6b62115866c.png)

**Comment by alex-mcleod** [comment]
I've got the same problem on VSCode...Slack channel / group names are basically invisible.

**Comment by planteater** [comment]
Thanks for the report @GPavlovic. We'll get on this asap!

**Comment by planteater** [comment]
Fixed in 0.34.0
