### ISSUE TITLE
Trello: Add token/support for card number in branch naming

### ISSUE THREAD

**Issue by snaptopixel** [TeamCodeStream/codestream#341]
We use card numbers to reference Trello cards, it'd be great if they were supported in branch naming

**Comment by planteater** [comment]
Thanks for the feedback @snaptopixel! It looks like we're using the wrong ID from Trello for branch naming. I think shortID is what corresponds to card number. I'll see if we can get that corrected.

**Comment by snaptopixel** [comment]
Ah thanks @planteater, we're a startup and only have one board currently, ha. It would work if we could do {boardName}-{shortID} I suppose. Thanks for looking into it!
