### ISSUE TITLE
Trello: Support Github Powerup

### ISSUE THREAD

**Issue by snaptopixel** [TeamCodeStream/codestream#342]
We use the Github Powerup to link cards to PRs. While the CodeStream functionality is similar (Adding a comment to the PR, etc) it's not as full featured.  https://trello.com/b/adY1EuWn/dev/power-up/55a5d916446f517774210004

**Comment by planteater** [comment]
@snaptopixel - Is there any specific aspect of GitHub's powerup that you'd like to see us replicate?

**Comment by snaptopixel** [comment]
Sure, the GitHub Powerup adds a preview of the PR with status checks etc.
