### ISSUE TITLE
Detecting wrong upstream repo/project (Jetbrain, Gitlab)

### ISSUE THREAD

**Issue by njam** [TeamCodeStream/codestream#345]
Codestream is detecting the wrong upstream project for my git repo with 4 remotes:
- name1: `git@gitlab.com:company/name1/project.git`
- name2: `git@gitlab.com:company/name2/project.git`
- origin: `git@gitlab.com:company/name3/project.git`
- upstream: `git@gitlab.com:company/project.git`

I would expect CodeStream to use `company/project` as the upstream project, but it's using `company/name1/project`.

- Codestream: 10.1.1+113
- IntelliJ: 2020.2.3

Possibly related: https://github.com/TeamCodeStream/codestream/issues/66

**Comment by njam** [comment]
Excerpt from the log:
```
2020-11-30 21:45:28,056 [ 315956]   INFO - agent.CodeStreamLanguageClient - [2020-11-30 20:45:28:056] [1dd] GitService.getRepoRemotes returned [ssh://git@gitlab.com:company/name1/project.git, ssh://git@gitlab.com:company/name2/project.git, ssh://git@gitlab.com:company/name3/project.git, ssh:// git@gitlab.com:company/project.git] • 0 ms
2020-11-30 21:45:28,524 [ 316424]   INFO - agent.CodeStreamLanguageClient - [2020-11-30 20:45:28:498] GitLab: Completed GET /projects/company%2Fname1%2Fproject/merge_requests?state=opened • 561 ms
```

**Comment by planteater** [comment]
@njam - We do prioritize the upstream remote for certain things. Could you give me some more details on where specifically in CodeStream you were seeing the wrong remote being used? Thanks!

**Comment by njam** [comment]
- Creating an issue defaults to the non-upstream project (but I can change it in the dropdown)
- Creating a pull request happens on the non-upstream project (with no way of changing it)
- I don't see any of the existing pull requests in CodeStream, I assume because it's loading them from the non-upstream project

**Comment by planteater** [comment]
Thanks for the additional info @njam!

#2 is unfortunately a limitation at the moment. We do have the ability to create a PR across forks for GitHub, but not yet for GitLab. I'll let you know as soon as we have GitLab support.

Similar situation for #3. The ability to view and review PRs in CodeStream is currently only available for GitHub.

**Comment by njam** [comment]
Ah got it, so this ticket is irrelevant then, closing.

Could be nice if this information was somewhere available (maybe it is, and I missed it).

**Comment by planteater** [comment]
@njam - We have it covered to some degree in the support matrix at the top of this article in our user guide, but I'll give some thought to how we might be able to better expose this information. Appreciate the feedback!

https://docs.codestream.com/userguide/workflow/pull-requests/
