### ISSUE TITLE
Gitlab: Only show issues for the open project

### ISSUE THREAD

**Issue by captnCC** [TeamCodeStream/codestream#346]
In the current state CodeStream shows all GitLab Issues for all projects I have access to. Is there a way to filter them down by project or something else?

**Comment by planteater** [comment]
@captnCC - We don't currently have additional filtering got GitLab, but that's definitely in the plans. I'll update you here as soon as it's available.

**Comment by AndyEveritt** [comment]
@planteater is there an update on this? And is it only an issue for gitlab or does it affect github too?

**Comment by planteater** [comment]
@AndyEveritt - It's only an issue for GitLab, since we have the ability to create custom filters for GitHub. We'll be adding that soon for GitLab as well.

**Comment by AndyEveritt** [comment]
OK, how do you automatically filter issues to only the currently open repository? I couldn't work it out from the documentation.

I'm using Vscode for reference.

**Comment by planteater** [comment]
@AndyEveritt - Sorry, just to clarify, there isn't a way to have the list only show issues from the current repo. But, you can create custom filters that would show you issues for a specific project, and you can easily switch back and forth between filters.

We will explore the possibility of creating a filter that is dynamic based on the current repo (which would obviously only apply if you had one of the code hosts as your selected issue tracker). I'll update you here as those plans come together.

**Comment by AndyEveritt** [comment]
Thank you, that would definitely be a feature that I'd be interested in

**Comment by AndyEveritt** [comment]
Looking for an update on this.

**Comment by planteater** [comment]
Hi @AndyEveritt - The UI work that would address this isn't scheduled until next quarter I'm afraid. Best bet in the short term would be to create a custom query in the Issues section for each project that you'd like to view distinctly (although i recognize that if you have a lot of projects this might not be practical.)
