### ISSUE TITLE
Cannot see own feedback requests that I approved

### ISSUE THREAD

**Issue by seniorquico** [TeamCodeStream/codestream#347]
My teammates and I are playing around with CodeStream, and we stumbled on a funny little issue.

I created a Feedback Request and sent it to a teammate. Then my teammate reviewed and approved it. Next, I re-opened it and added a second change. Interestingly, the Feedback Request UI allowed me to approve my own request... not quite what I was expecting, but I thought I'd mess around and select it. After having it approved, I wanted to turn it into a PR. However, the Feedback Request is no longer visible in the list.

Is the Feedback Request being hidden because I approved it and the UI is filtering completed items? Is there any way to view old/completed Feedback Requests so I can get this one back? The common sense thing is to not approve your own request... but even thinking longer term, if we want to get back to an older Feedback Request, is that possible?

Edit: I should've noted, both my teammate & I are using the VS Code extension.

_Another_ Edit: The notification email that was sent when my teammate approved the Feedback Request includes a link to open it in my IDE. If I click that link and open VS Code, I can get back to the Feedback Request. However, if I close the dialog, it still doesn't show up in my Feedback Requests list. It feels like there should be an option to change the Feedback Requests view to either (or both) show the ones that I opened or old ones that have already been approved or rejected.

**Comment by planteater** [comment]
@seniorquico - Thanks for the feedback! We've got some different ideas on the table to address this. One possibility is to divide the Feedeback Requests section into two subsections. One for Open FRs, and another for Recently Approved. The latter would show your N most recently approved FRs along with a button to create a PR. Do you think that would work?

Note that in the interim you can get to all of your FRs by going to the Search page and selecting the "Your Feedback Requests" filter.

**Comment by seniorquico** [comment]
Yes, that would definitely be a way to help address my request. Glad to hear you have some ideas! Looking forward to seeing how it unfolds.

**Comment by planteater** [comment]
@seniorquico - The idea I described above has just been released in v10.2.2 of the CodeStream extension.
