### ISSUE TITLE
Code Stream: GIT endpoint configuration issue

### ISSUE THREAD

**Issue by aishvaryaps** [TeamCodeStream/codestream#349]
I was earlier able to validate my github integration in codestream.
however now i am getting errorr : 
**_Endpoint validation failed : Status Code 401_**

The password and user name is correct
Also i am member of the project
![image](https://user-images.githubusercontent.com/48279639/101017431-193e2d00-3590-11eb-85ca-2163bc53faac.png)

Github Repo URL:
https://github.com/aishvaryaps/helloworld

Please let me know if any changes needed in the endpoint configuration

I am getting same error for Bitbucket endpoint integration as well

**Comment by planteater** [comment]
@aishvaryaps - I think you've got the wrong CodeStream. :-)

That looks like a page from VMware's Code Stream.
