### ISSUE TITLE
Account creation issues (Slack)

### ISSUE THREAD

**Issue by ChrisKatsaras** [TeamCodeStream/CodeStream#35]
My project manager set up Code Stream for our team and sent me an invite to join. Prior to this, I had set up an account using Slack. After receiving the invite, I was unable to view any of the Code Marks left by any of my team members (the only thing I was able to view Slack channels and messages). 
All of these Code Marks were created by users that were associated with my project managers Code Stream. 
It's important to note that any Code Marks made by users connected to our companies Slack, were visible.

**Comment by planteater** [comment]
@ChrisKatsaras - I've confirmed that you have two separate teams on CodeStream. The Slack-connected team you created and the one created by your project manager, which isn't connected to Slack. Best option is to have me delete one of those teams. If your company uses Slack, having a Slack-connected team on CodeStream is probably the way to go, so you can leverage your existing channels. My suggestion would be to delete the team that your project manager created. 

Let me know if you want to go this route. Assuming you do, everyone else can go ahead and sign out of that team (look for the Sign Out option under the ellipses menu) and then sign back in again using Slack. That will put them into the team you created.

**Comment by ChrisKatsaras** [comment]
Hi @planteater,
Thanks for the quick response! 
I agree, the best option here is to delete the team my project manager created and leave the Slack team open.
I'm also curious, why you can't view and be a member of multiple teams? 

Thanks,
Chris

**Comment by planteater** [comment]
All set @ChrisKatsaras. Remember to have everyone else from that other go ahead and sign out of CodeStream (look for the Sign Out option under the ellipses menu) and then sign back in again using Slack. That will put them into the team you created.

Technically you can be on multiple teams, but we don't yet have a mechanism in the UI to switch between the teams. You have to do it through the VS Code user settings. Definitely on our roadmap to get that into the UI though
