### ISSUE TITLE
How to assign a standalone M(P)R to someone?

### ISSUE THREAD

**Issue by liuliangsir** [TeamCodeStream/codestream#352]
As the above title says, I have no idea how to assign a standalone M(P)R mission to someone when opening a M(P)R directly. So we can feel free to use the code stream extension inside vscode without massive gitlab restrictions like launching browser for pure merge request.

**Comment by planteater** [comment]
@liuliangsir - The ability to view/review/manage PRs from CodeStream is currently limited to GitHub. This includes the ability to assign a PR to someone. We'll be adding support for GitLab soon though!
