### ISSUE TITLE
Show icons in PR gutter for outdated and resolved comments

### ISSUE THREAD

**Issue by FFdhorkin** [TeamCodeStream/codestream#353]
UPDATE 2/8/21 - Turns out the issue here was that the icons that weren't appearing were associated with "outdated" comments, which at the moment is expected behavior. However, it would be a useful enhancement to continue to show both outdated and even resolved comments, but with different colored icons to reflect their state.

---

I'm having some problems with codemarks in VS Code. Even when I'm in a file that I know has codemarks, they aren't showing up. Leaving new codemarks in files results in codemarks showing up for other people, but not for me. (I also have the "show comments from PRs" turned on, and when I look at a PR, I can see the comments in the Codestream sidebar, but no in-line glyph shows where the comment is located)

Three non-PR codemarks do show up in the codemark list; if I click on them, it will highlight relevant code, but there is no glyph, and if I view that same location after clicking the X by the codemark summary, there's no indication in the file there's a codemark there.

I thought this might be an extension conflict, so I tried disabling all my other extensions. Didn't help. I've tried fiddling with Codestream settings, signing in/out, uninstalling/reinstalling... always has the same problem.

I think this **may** be a compatibility issue with the WSL Remote extension. I cloned my repo in Windows directly (without the WSL layer) and opened Codestream... the 3 non-PR codemarks now show glyphs in the correct places, but when I open PRs, the glyphs still don't show up.

This bug pretty much defeats the entire point of Codestream. Any other troubleshooting steps I could try?

**Comment by planteater** [comment]
@FFdhorkin - Thanks for reporting this! A bit of a long shot, but is there any chance that you were in the CodeStream settings in VS Code and checked the "Auto Hide Markers" box? Assuming that isn't the case, could I trouble you for a couple of log files? In CodeStream go to a file where you're not seeing the glyphs. Then...

1. Open the Output view (“View: Toggle Output” from the command palette) and select "CodeStream" from the dropdown menu at the top-right. Copy all of the output you see and save it in a text file.
2. Change the dropdown select to “CodeStream (Agent)” and grab that output as well.

If you'd prefer not to share the log files here, send them to support@codestream.com. Thanks!

**Comment by planteater** [comment]
@FFdhorkin - Just wanted to follow up to see if we could get those logs. Thanks!

**Comment by FFdhorkin** [comment]
Sorry!  I did not see an email  notification for your replies. I've tried toggling "auto hide markers"  and that doesn't seem to be it.

I think this is a WSL Remote compatibility issue. Latest versions of VSCode/WSL Remote/CodeStream show glyphs in Windows file-system PRs, but not if I'm in a WSL repo.

Sending you an email now
