### ISSUE TITLE
Slack notifications not muted on VS Code

### ISSUE THREAD

**Issue by dfernandezramos** [TeamCodeStream/CodeStream#36]
Even when Slack is muted on CodeStream for Visual Studio Code I get notifications

**Comment by tortilaman** [comment]
Also experiencing this. Regardless of if I "mute all notifications", or set notifications to "none", I still get notifications.

**Comment by eamodio** [comment]
@tortilaman We are aware of the issue with "mute all notifications" (which will be fixed in the next release), but setting the notifications setting to "none" should stop the "toast" style notifications. Is that not the case?
