### ISSUE TITLE
some files opened in pycharm that have codesteam comment(after some changes) stop scrolling with the mouse wheel

### ISSUE THREAD

**Issue by PetrovskiIM** [TeamCodeStream/codestream#362]

**Comment by planteater** [comment]
@PetrovskiIM - Thanks for reaching out on this. Could I trouble you for a log file? Reproduce the issue and then go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file.

You can send the log file to me at support@codestream.com. Thanks!

**Comment by planteater** [comment]
@PetrovskiIM - Just wanted to follow up to see if we could get that log file. Thanks!

**Comment by planteater** [comment]
@PetrovskiIM - We haven't been able to reproduce this issue. I'm going to close it, but if you see the issue again please feel free to send a log file to me at support@codestream.com and we'll dig in.
