### ISSUE TITLE
GitHub: Could not resolve to a Repository with the name '/toonsquare'.

### ISSUE THREAD

**Issue by mwmw7** [TeamCodeStream/codestream#363]
I use the "Organization" feature in Github which name is "toonsqure"

But when I was trying to PR 

Below Error message was shown
![image](https://user-images.githubusercontent.com/1140031/103396511-1d517080-4b77-11eb-87a9-0ba9c06578c3.png)

**Comment by planteater** [comment]
Thanks for reaching out on this @mwmw7. Could I trouble you for a log file? Reproduce the issue and then go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file.

You can send the log file to support@codestream.com. Thanks!

**Comment by mwmw7** [comment]
╰─(๑˃̵ᴗ˂̵)و  git remote -v                      
toonsquare      git@github.com:/toonsquare/tooning-ionic-admin.git (fetch)
toonsquare      git@github.com:/toonsquare/tooning-ionic-admin.git (push)

**Comment by mwmw7** [comment]
[codestream15352082836941856135.tmp.zip](https://github.com/TeamCodeStream/codestream/files/5762597/codestream15352082836941856135.tmp.zip)

**Comment by planteater** [comment]
@mwmw7 - It looks like that log file you sent is some kind of binary file, so something didn't go right when you generated it. Could I trouble you to try one more time? Reproduce the issue and then go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. Thanks!

**Comment by mwmw7** [comment]
@planteater  thank you for your help

But It works now

The solution is 
1. I change my "origin" name to "toonsquare" 
2. git clone again my [repo](git@github.com:/toonsquare/tooning-ionic-admin.git )
3. reinstall codestream

**Comment by planteater** [comment]
Thanks for the update @mwmw7! We're pretty sure that the issue was the fact that your remote had an extra / in it between the domain and the GitHub org. That probably explains why re-cloning fixed things, because it fixed your remote. In any case, we're going to update our logic to cover that scenario.
