### ISSUE TITLE
VSCode: The 'Copy' button in PR copies the wrong branch name

### ISSUE THREAD

**Issue by miktap** [TeamCodeStream/codestream#364]
When viewing the PR in GitHub the `Copy` button copies the branch that is compared while in CodeStream the `Copy` button copies the base branch name.

**Comment by planteater** [comment]
Thanks for the heads up @miktap! We'll get that fixed asap, and I'll update you here.

**Comment by planteater** [comment]
@miktap - This issue has been fixed in v10.3.0. Thanks again for the report!
