### ISSUE TITLE
GitHub Actions Annotations Missing from CodeStream

### ISSUE THREAD

**Issue by rsappington** [TeamCodeStream/codestream#367]
We have GitHub Actions set up to run eslint. If an annotation is left on GitHub, it does not display in CodeStream. I am requesting to add this feature if it does not exist, otherwise I am reporting a bug.

I am using VS code and Reviewdog (eslint).

An example of an annotation.
![eslint](https://user-images.githubusercontent.com/48369528/104050110-ee508580-519a-11eb-8849-2766ba877319.png)

**Comment by vishalagrawal-jisr** [comment]
@rsappington Now they are coming for me, try updating the plugin.

**Comment by rsappington** [comment]
They still do not display. I am using version 10.4.1
