### ISSUE TITLE
IntelliJ plugin can get stuck on error pages

### ISSUE THREAD

**Issue by pepijnve** [TeamCodeStream/codestream#368]
On macOS in IntelliJ (2020.3.1), when I press the 'email' hyperlink, Mail.app pops up with the correct content prepopulated.

<img width="395" alt="Screenshot 2021-01-11 at 16 45 23" src="https://user-images.githubusercontent.com/225326/104203498-7ef1c480-542c-11eb-95a7-f8a2dcecc640.png">

The plugin then navigates to an error page and at this point there's no way to get back to the main screen without closing the current project and reopening it (i.e. reloading the plugin).

<img width="646" alt="Screenshot 2021-01-11 at 16 48 02" src="https://user-images.githubusercontent.com/225326/104203778-d2641280-542c-11eb-907e-6d26578b5c07.png">

**Comment by planteater** [comment]
Thanks for the report @pepijnve! We'll get this fixed. In the meantime, if you need to use this feature again before we get a fix in, you can fix things by selection "CodeStream: Reload webview" from the IDE's action list.

**Comment by pepijnve** [comment]
Just FYI, I'm getting this with all hyperlinks, not just the email one. I don't see the action you're referring to in the UI.

**Comment by planteater** [comment]
@pepijnve - Could you give me a specific example? While I am seeing the error with the email link, I haven't see it with the links I've tried so far. Thanks

**Comment by pepijnve** [comment]
<img width="286" alt="Screenshot 2021-01-22 at 14 33 11" src="https://user-images.githubusercontent.com/225326/105497215-d7438480-5cbe-11eb-8a2d-ba163a6a2b12.png">

<img width="1159" alt="Screenshot 2021-01-22 at 14 33 32" src="https://user-images.githubusercontent.com/225326/105497237-dca0cf00-5cbe-11eb-9815-41caf5cdfb11.png">

**Comment by planteater** [comment]
Thanks!

**Comment by planteater** [comment]
@pepijnve - After some investigation, it appears that this issue is specific to v2020.3.1 of IntelliJ. If you update to 2020.3.2 the issue should be resolved.
