### ISSUE TITLE
GitLab/GitLab SM support for viewing/reviewing MRs

### ISSUE THREAD

**Issue by apatryda** [TeamCodeStream/codestream#369]
Even though I have the self-managed GitLab integration turned on, I cannot neither list nor open (by providing an url) merge requests in my IDE (vscode). When I provide a direct URL to the MR I get the following error message: `t[e.method] is not a function`.

![image](https://user-images.githubusercontent.com/6566600/104383057-7d5cf500-552f-11eb-977c-15e48b7222fa.png)

**Comment by planteater** [comment]
@apatryda - Unfortunately, the ability to view/review PRs isn't available yet for GitLab (or Bitbucket). Only for GitHub/GitHub Enterprise. That said, we're working on support for GitLab and GitLab SM right now. I'll update you here once it's available.

**Comment by planteater** [comment]
My apologies Artur! I just now connected the dots between this report and our conversation via support. :-)

**Comment by apatryda** [comment]
No need :smiley:, thanks for connecting the dots and good luck on the feature :crossed_fingers:

**Comment by apatryda** [comment]
A note for GitLab SM: self managed instances of GitLab can be (and often are) hidden behind firewals, so if access is required from CodeStream servers - information on required firewall rules would be a nice thing (like at least a list of the IP's of CodeStream servers that might query the GitLab instance).

**Comment by liuliangsir** [comment]
It seems to be a duplicated issue, please check out [#352](https://github.com/TeamCodeStream/codestream/issues/352 ).

**Comment by apatryda** [comment]
@liuliangsir - I wouldn't say it's a duplicate.
I'd rather say those issues are related.

**Comment by apatryda** [comment]
You can help/monitor progress on `gitlab-prs` branch:
https://github.com/TeamCodeStream/codestream/compare/feature/gitlab-prs

**Comment by planteater** [comment]
GitLab support was added some time ago but I never closed this.
