### ISSUE TITLE
Support for Azure Devops PRs

### ISSUE THREAD

**Issue by AsafMah** [TeamCodeStream/codestream#371]
The integration with Azure Devops' Issues is really great, but I do wish there was an integration with its PRs.
That's the main reason I installed this pluggin.

**Comment by shane-lamb** [comment]
Would be awesome. I think this issue is asking the same: https://github.com/TeamCodeStream/codestream/issues/32

**Comment by NickRimmer** [comment]
It would be really cool feature!

**Comment by sheldonhull** [comment]
Is this blocked by other work or mostly just need more expressed interest in it?

**Comment by planteater** [comment]
@sheldonhull - The latter. We haven't really looked into what the scope of the effort would be, but at this point there hasn't been enough demand.

**Comment by gp-mlezotte** [comment]
Hello! I'm curious how you're gauging demand. This issue appears to be toward the top of the list based on thumbs-up reactions. What other factors are taken into account? Our organization uses Azure DevOps, and I suspect many others on the Microsoft stack do as well. This would be an amazing selling point for us to argue for CodeStream licenses, and would likely be the tipping point for us to attempt that argument.

**Comment by th-fulcrum** [comment]
Would definitely love for this integration to happen, especially consider you already support azure devops as an issue tracker...

**Comment by dannyhadders** [comment]
+1 on this feature

**Comment by NIV54** [comment]
Would also appreciate this feature

**Comment by daverod24** [comment]
+1  I also support this functionality would help a lot
