### ISSUE TITLE
Getting rate limited error when trying to load PR from URL or refresh PR in RubyMine

### ISSUE THREAD

**Issue by huguesbr** [TeamCodeStream/codestream#374]
I have this issue both in  RubyMine and VS, I've tried to logout and log back in of codestream (via github), same issue..

```
Request codestream/provider/generic failed with message: {"errors":[{"type":"RATE_LIMITED","message":"API rate limit exceeded"}],"status":200}
```

![image](https://user-images.githubusercontent.com/1517759/104569629-4aab1d80-5651-11eb-96a2-adfab25ee9c2.png)

**Comment by planteater** [comment]
@huguesbr - I think we'll need some logs to truly get to the bottom of this. In VS Code, open the Output view (“View: Toggle Output” from the command palette) and select "CodeStream (Agent)" from the dropdown menu at the top-right. Copy all of the output you see and save it in a text file. Or if you'd prefer, in RubyMine, go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. If you'd prefer not to post the log file here, you can send it to support@codestream.com.

That said, a couple of questions... Do you have a number of IDEs open at once? Do you have any other GitHub-related plugins or extensions running? GitHub's hourly rate limit isn't specific to CodeStream. It would apply to anything using your GitHib credentials.

Once we get that log file we'll dig into this, but note that after an hour your GitHub points should reset. Thanks!

**Comment by planteater** [comment]
Hi @huguesbr - Just wanted to follow up to see if we could get that log file. Thanks!

**Comment by huguesbr** [comment]
@planteater sorry for delay.. not sure what happened, but it's working now.. can't reproduce.. closing
