### ISSUE TITLE
when creating a review, you can can't exit the preview mode

### ISSUE THREAD

**Issue by taylahd** [TeamCodeStream/codestream#376]
Hello!

Using vs code, when I try to preview my review you can't exit it. see below.

![image](https://user-images.githubusercontent.com/77505362/104760169-fb3b1f00-572e-11eb-9da1-e4d24c0e633e.png)

thank you~

**Comment by planteater** [comment]
Thanks for the report @taylahd! We'll get this fixed asap.

**Comment by ppezaris** [comment]
should be fixed in the next release. we had a weird float issue.

**Comment by planteater** [comment]
This has been fixed in v10.4.1.
