### ISSUE TITLE
Receiving PR notifications for very old and closed PRs

### ISSUE THREAD

**Issue by anilanar** [TeamCodeStream/codestream#377]
[vscode extension, github]

Time to time, I'm receiving vscode notifications about 1 specific PR that is very very old and has been closed for years. The notification says  "[PR title] is waiting for your review".

The PR is in a private repo so I cannot share it.

Any way for me to debug it?

**Comment by planteater** [comment]
Thanks for reaching out @anilanar. In theory, you should only get a toast notification for a closed PR if you were newly added to it as a reviewer or assignee. Any chance that was the case with this PR?

**Comment by planteater** [comment]
Hi @anilanar - Just wanted to follow up on my previous question. Thanks!

**Comment by anilanar** [comment]
Definitely no. It's a PR that had no updates whatsoever and it's always one and the same PR I get notification for.

**Comment by planteater** [comment]
@anilanar - This issue has been fixed in v10.4.2.
