### ISSUE TITLE
Support Emacs 

### ISSUE THREAD

**Issue by andrew-oko-odion** [TeamCodeStream/codestream#38]
Hi All 

Nice tool I must admit. 

Can you please add support for Emacs.
its one single, most important editor that is missing from your roadmap.

**Comment by ppezaris** [comment]
Let me start by saying I am a HUGE emacs fan! Been using it since the lemacs/xemacs days.

Definitely on the list, but we are trying to prioritize based on customer demand.... I'm hopeful there will be enough demand for Emacs to support it!

**Comment by yurrriq** [comment]
Any update on this? CodeStream looks cool, but I'm diehard Emacs user.

**Comment by ppezaris** [comment]
We will tackle Emacs, and some other editors, towards the end of the year. If we open-sourced that client, would you be interested in helping to work on it?

**Comment by stevem995** [comment]
Please include Emacs support.

**Comment by andrew-oko-odion** [comment]
That sounds good
Would love to help

On Jan 14, 2020 2:36 PM, "Steve M" <notifications@github.com> wrote:

Please include Emacs support.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TeamCodeStream/CodeStream/issues/38?email_source=notifications&email_token=ABACDMF5CQ2GNGILTUH6VMDQ5W5V3A5CNFSM4GYWVWG2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEI4T6RY#issuecomment-574177095>,
or unsubscribe

**Comment by yurrriq** [comment]
I, too, but we willing to help as I'm able.

**Comment by stephsamson** [comment]
An emacs client would be amazing -- the CodeStream plugin is the only reason I'm still using JetBrains products.

**Comment by shivsoji** [comment]
Creating a plugin for [emacs-ng](https://github.com/emacs-ng/emacs-ng) which supports writing plugins in `Typescript/Javascript` would reduce the effort given that we can reuse most of the code. I am up for doing it. Let me know if anybody else wants to join in.

**Comment by nick781** [comment]
emacs or DIE
