### ISSUE TITLE
'Show archived/hidden' toggle in Codemarks section has no effect

### ISSUE THREAD

**Issue by pepijnve** [TeamCodeStream/codestream#382]
Toggling the 'Show hidden/archived codemarks' setting in the codemarks section of the main UI in the IntelliJ plugin does not seem to have any effect. The effective behaviour is that archived codemarks are always not displayed.

CodeStream version 10.4.0+121

**Comment by planteater** [comment]
Thanks for the heads up @pepijnve! I'll update you here once this has been fixed.

**Comment by planteater** [comment]
@pepijnve - With CodeStream 10.5 things have changed a bit. There's a new "Archived" section within the Codemarks section. It's persistent, but you can collapse it if so desired.

If you click the gear icon in the heading of the Codemarks section, you'll see the following option:

Show icons in editor gutter > Archived codemarks

You can toggle that setting to show/hide icons for archived codemarks in the editor gutter.
