### ISSUE TITLE
"Add comment" is not working

### ISSUE THREAD

**Issue by mwmw7** [TeamCodeStream/codestream#383]
Whenever I try to share a code block with a comment
Below error message is popped up

![image](https://user-images.githubusercontent.com/1140031/105804305-d07c8080-5fe2-11eb-9e41-38edfef49889.png)

And I already installed git and used it 
![image](https://user-images.githubusercontent.com/1140031/105804445-2ea96380-5fe3-11eb-9719-9ee77cc34501.png)

**Comment by planteater** [comment]
@mwmw7 - Thanks for reaching out. First thing to confirm is that if you had made a change to the git path, that you restarted your IDE after doing so. Assuming that's the case, could you grab a log file and send it to me at support@codestream.com? Reproduce the issue and then go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. Thanks!

**Comment by mwmw7** [comment]
@planteater thank you I just about send an email

**Comment by planteater** [comment]
@mwmw7 - I'm going to close this for now, but per my last email, we'll jump right back in again once we get that log file. Thanks!
