### ISSUE TITLE
Support for bring connected to multiple GitHub accounts

### ISSUE THREAD

**Issue by bazinga012** [TeamCodeStream/codestream#386]
I'm working on multiple projects and multiple jetbranins IDEs and I've logged-in via github (this account is different than my personal git account). Same codestream session is used across all IDEs and Projects. Is there any way to link a different git account to a given project or atleast atleast at the IDE level?

I know a different team can be created but If I'm using different github accounts for personal and professional work this is not an option.

**Comment by planteater** [comment]
@bazinga012 - Thanks for reaching out on this. There is a way to do this, but at the moment it would require you to stop using GH to sign into CodeStream. When you use GitHub to sign in, that GH connection applies across all of your teams. If you switch to authenticating with email/password, you can then have separate GitHub connections for your work and personal teams (which would both be under a single user account). If you want to do this, here are the steps:

1. Sign out of CodeStream, and then click on "Forgot password". This will send you an email you can use to set a CodeStream password.
2. Once you've set a password, sign into CodeStream using your email address and that password.
3. Go to the Integrations page (under that headshot menu) and disconnect from GitHub.
4. Now reconnect to GitHub.
5. You can now create a second CodeStream team for personal use by going to Switch Team > Create New Team (under headshot menu). Note that you'll use the Switch Team menu to go back and forth between your two teams, just like switching between Slack workspaces.
6. In the new team, go to the Integrations page and select GitHub, but this time be sure you're signed into you're personal GItHub account.

**Comment by planteater** [comment]
@bazinga012 - Just wanted to follow up to see if you were able to get your two teams set up with the separate GitHub connections.
