### ISSUE TITLE
Codemark issue with filenames containing "+" char

### ISSUE THREAD

**Issue by rsebbe** [TeamCodeStream/codestream#388]
In VSCode, when a filename contains the "+" char, which can be a common practice in Obj-C / Swift category - extension file naming, Codestream apparently fails to correctly create a codemark: 

- the codemark is created but does not appear in the list of the "Current Repository" (it's only listed under "All Codemarks").
- file navigation is broken: no navigation to the corresponding file when the codemark is clicked from the list.
- the blue message icon does not appear for these files on the corresponding line.

(interested to hear about a workaround to avoid renaming all these files if there is any, thx!)

**Comment by planteater** [comment]
Thanks for the report @rsebbe. We'll get on this asap!

**Comment by planteater** [comment]
This has been fixed in v10.6.0. Thanks for your patience @rsebbe!

**Comment by rsebbe** [comment]
Thank you. Indeed, just tested it (10.6.0) and it works as expected. 👍
