### ISSUE TITLE
Github Enterprise support

### ISSUE THREAD

**Issue by tortilaman** [TeamCodeStream/CodeStream#39]
Based on what I can see, I'm unable to login to a Github Enterprise account, only Github.com. This makes this tool kind of useless for my team unfortunately. It's a shame, as I'd love to try it out.

**Comment by eamodio** [comment]
While we will be definitely adding GitHub Enterprise support -- our current level of integration with GitHub explicitly is only for creating issues on GitHub when creating an issue within CodeStream. The rest of the CodeStream experience is agnostic to GitHub or GitHub Enterprise. Hope that helps.

**Comment by tortilaman** [comment]
@eamodio Thank you for the quick reply. I understand the rest of CodeStream will work without Github Enterprise support, it's just not ideal that either my team won't be able to add issues using CodeStream, or we'll have to now look in CodeStream as well as ZenHub / Github to find all issues.

If it's a matter of implementation, I'd be more than happy to add the Github enterprise auth flow.

**Comment by eamodio** [comment]
@tortilaman Ah, understood -- just wanted to make sure it was really the issue creation that was the blocker.

While we would love the help, we unfortunately aren't yet at the place where we can open that up -- we need to extract our integrations to use an exposed api first. Although I can say that adding GitHub enterprise is definitely on our short-term roadmap.

**Comment by cstryker** [comment]
@tortilaman I am Colin Stryker, one of the developers at CodeStream ... I am investigating enabling GitHub Enterprise support for CodeStream ... to start, would you be able to give me a quick summary of your installation? Is it an on-prem version? What is the auth process like? Is there any third-party auth involvement (eg. Active Directory) or do you auth straight to GitHub? We have no experience with GitHub Enterprise at this point so we'd be climbing the learning curve. Thanks for your help.

**Comment by tortilaman** [comment]
Hi @cstryker, thanks for the response. It's an on-premises install and uses third party auth (I'm pretty sure it's either SAML or IAM). I contributed the original Github Enterprise support to NetlifyCMS, and from my recollection things are mostly handled on Github's end. The big difference of course is you provide an endpoint for your particular install.

**Comment by cstryker** [comment]
@tortilaman So our experience with these integrations so far has been limited to OAuth 2.0. Since you offered to implement the auth flow, but unfortunately that isn't really possible at this time, would you be willing to give me a quick tutorial in how you would go about the implementation, and I can try to adapt our flow to what I learn from that?

**Comment by tortilaman** [comment]
I have a meeting in a few minutes, and can elaborate on this afterwards, but Github Enterprise connects with either "Github Apps", or Oauth Apps. Here's the basic info on Oauth authorization with Github Enterprise: https://developer.github.com/enterprise/2.16/apps/building-oauth-apps/authorizing-oauth-apps/

Again, I can expand on this in an hour or so.

**Comment by cstryker** [comment]
We have a pretty standard OAuth 2.0 implementation, so as long as GitHub Enterprise exposes an OAuth 2.0 API, I think it should be pretty easy ... it's just a matter of knowing where to redirect to begin the process.

**Comment by cstryker** [comment]
@tortilaman I'm reaching the end of my work on getting CodeStream to work with GitHub Enterprise, but I want to confirm that my assumptions will be correct for your setup. I'm assuming your administrator will set up a "CodeStream" app on your GitHub server ... that gives us three pieces of information we need to know to support the OAuth process: clientId, clientSecret, and url of your GitHub. For our first iteration (which I expect we'd release within the next few weeks), you'll have to give us that information and we will manually put it in place on our backend for your team. Later, you (or your administrator) will have the ability to administer it yourself. Does that sound like it will work or are there complications?

**Comment by tortilaman** [comment]
Sorry for my delayed response. I think that will work.

**Comment by cstryker** [comment]
Good news @tortilaman ... we now support GitHub Enterprise! You'll need to get the latest version of the extension. Then you'll need to follow the steps I outlined above: set up a "CodeStream" app on your GitHub server, and pass along to me (you can email direct to colin@codestream.com) the clientId, clientSecret, and url for your GHE installation. I'll set up the configuration on our backend to enable you to use GHE. If all goes well, you'd see your installation listed alongside the other integrations when you start to create an issue. At some point, we're probably going to redo that UI (it's getting unwieldy with all the integrations on the screen), but it should work in any case. 

We can leave this issue open until you've got it working in case any problems come up.

**Comment by tortilaman** [comment]
Thank you very much for your continued work and support Colin. I'm
travelling today, but I'll pm you the necessary details ASAP.

**Comment by cstryker** [comment]
Hi @tortilaman just wondering if you had a chance to get to this yet ... we're looking forward to seeing how our GHE integration will work for you. Thanks!

**Comment by planteater** [comment]
@tortilaman - Support for GitHub Enterprise is now available.
