### ISSUE TITLE
Jetbrains gutter in VCS resolve conflicts, icon shifting

### ISSUE THREAD

**Issue by meridsa** [TeamCodeStream/codestream#390]
In Jetbrains VCS resolve conflicts the gutter is used to click icons to shift changes from one commit into the merged result. The codestreams icon shifts these icons to cause presses on the left side, which is annoying, not a huge bug, but could be improved by having the codestream icon appear on the left side of the 'x' and '>>' buttons on the "left" version.

https://user-images.githubusercontent.com/35993351/106736003-35545e00-6615-11eb-8fb6-055f301e6401.mov

**Comment by planteater** [comment]
Thanks for reaching out @meridsa. You can turn off this behavior by going to Preferences/Settings > Tools > CodeStream and then unchecking the box that says "Show + icon on hover". This will change the behavior such that the CodeStream compose icon will only appear when you select a block of code, and not when you hover in the gutter.
