### ISSUE TITLE
Bitbucket PR: Bad Request: source: branch not found

### ISSUE THREAD

**Issue by genadis** [TeamCodeStream/codestream#391]
When creating a PR for Bitbucket, getting an error of "Bitbucket: Bad Request: source: branch not found: ...".

(Double checked the branch actually exists and sync from local to bitbucket cloud)

**Comment by planteater** [comment]
Thanks for the report @genadis! Could I trouble you for a log file? In VS Code, reproduce the issue and then open the Output view (“View: Toggle Output” from the command palette) and select "CodeStream (Agent)" from the dropdown menu at the top-right. Copy all of the output you see and save it in a text file. You can send it to me at support@codestream.com if you'd prefer not to post it here. Thanks!

**Comment by planteater** [comment]
@genadis - Just wanted to follow up to see if we could get that log file. Thanks!

**Comment by planteater** [comment]
@genadis - I'm going to go ahead and close this out since I haven't heard from you, but if you get a chance to grab that Agent log file, send it to me at support@codestream.com and we'll get on it asap. Thanks!
