### ISSUE TITLE
Codemark not showing code block

### ISSUE THREAD

**Issue by PiR1** [TeamCodeStream/codestream#392]
Hello,
Since a few days my code is no longer displayed in my codemarks.
I have the problem under IntelliJ but also under VS Code.

Plugin version: 10.4.2
![Screenshot 2021-02-05 111935](https://user-images.githubusercontent.com/12834310/107021556-8fcff480-67a4-11eb-88f4-655efd451207.png)

**Comment by planteater** [comment]
Thanks for reporting this! Could I trouble you for a log file? Instructions can be found here:

https://docs.codestream.com/userguide/faq/client-logs/

You can send the file to me at support@codestream.com if you’d prefer not to post it here. Thanks!

**Comment by PiR1** [comment]
Yes of course. I sent it to you by email

**Comment by planteater** [comment]
@PiR1 - We've identified a regression in our last release that is behind this issue. We'll be getting a fix out right away, but in the interim you can roll back to the previous release of our extension. I'll update you here as soon as the fix is available.

**Comment by PiR1** [comment]
Great, thank you for your speed.
I will downgrade the extension in the meantime.

**Comment by PiR1** [comment]
@planteater Version 10.4.3 fixes the issue.
Thank you for the speedy resolution of this bug !
