### ISSUE TITLE
Update Required

### ISSUE THREAD

**Issue by victorssr** [TeamCodeStream/codestream#394]
I'm with the latest version of the CodeStream VS Code extension, but when i try to "Sign up and Create a Team" i'm getting the "Update Required" message:

"We're all for vintage, but your version of CodeStream is simply too old! Please update to the latest version to continue.
Go to the Extensions view via the activity bar and then look for the Update button in the CodeStream entry."

I tried to reinstall the extension and it didn't work either.

**Comment by planteater** [comment]
@victorssr - Apologies for the confusion, but this is likely because the version of VS Code you're running is too old to support a more recent version of CodeStream. Make sure you're using v1.50 or later of VS Code.

**Comment by victorssr** [comment]
Omg! Thank you for the fast support. I'm really sorry for that, won't happen again

**Comment by planteater** [comment]
No worries at all @victorssr !
