### ISSUE TITLE
[Rider] Code Drag

### ISSUE THREAD

**Issue by deadmann** [TeamCodeStream/codestream#396]
I had later version 4.2 on Rider, and with update to 4.3 code comment got fixed, now I can select code, or when I hit comment, the UI shows the actual line in CodeStream UI.

Now, still one thing remained. The UI has a place where when you drag a code, it says drop it here. if you do that, the code get cut from your project file, and will vanish. please fix that too. Also dropping it has no effect at all.

**Comment by planteater** [comment]
@deadmann - Thanks for reaching out. I don't think CodeStream has anywhere in the UI where you can drag-and-drop code. You can drag a file into a codemark or feedback request, but not code. Is that a feature of Rider that you're describing? Maybe a share screenshot so we can get a better idea of what you're describing? Thanks!

**Comment by planteater** [comment]
@deadmann - Just wanted to follow up on this to see if you could provide any more information on that drag-and-drop issue.

**Comment by planteater** [comment]
@deadmann - I'm going to go ahead and close this out, but feel free to reach out to me directly at support@codestream.com if you want to dig into this further. Thanks!
