### ISSUE TITLE
Error while creating a PR on Github

### ISSUE THREAD

**Issue by alubchuk** [TeamCodeStream/codestream#397]
When I create a PR on github through codestream in vscode, it loads for some time and then shows the error. Even though it really created a PR (from the 2nd attempt), the PR itself doesn't show up in the `Pull Requests` list.

![image](https://user-images.githubusercontent.com/2202797/107499419-9fcd4700-6b9d-11eb-9553-ccca4c5e2ca9.png)

![image](https://user-images.githubusercontent.com/2202797/107499433-a2c83780-6b9d-11eb-8db1-75a95411941b.png)

**Comment by planteater** [comment]
@alubchuk - Thanks for reporting this! Could I trouble you for a log file? Reproduce the issue and then open the Output view (“View: Toggle Output” from the command palette) and select "CodeStream (Agent)" from the dropdown menu at the top-right. Copy all of the output you see and save it in a text file.

If you'd prefer not to post the log file here you can send it to me at support@codestream.com. Thanks!

**Comment by planteater** [comment]
@alubchuk - A couple of additional questions. Does the PR show up in the list if you click the Refresh icon? And does this happen every time you create a PR, or just that once? 

Don't forget to send that log file when you get a chance. Thanks!

**Comment by alubchuk** [comment]
@planteater It happens intermittently. Today, for example, I was able to create PRs. Refresh didn't help then. 
Ok, next time it happens, I’ll grab the logs and send them over to you.
Thanks for feedback!

**Comment by planteater** [comment]
Sounds good @alubchuk. For now, I'll close this, but if you see the issue again you can either re-open or just email the logs to me directly at support@codestream.com. Thanks!
