### ISSUE TITLE
An unexpected error has occurred. Please reload the window.

### ISSUE THREAD

**Issue by aaroncraig10e** [TeamCodeStream/CodeStream#4]
This is all I see now when toggling CodeStream

VS Code Insiders

**Comment by planteater** [comment]
Hi Aaron - Could I trouble you for a screenshot? Also, if you could view the VS Code Output and send us the contents for both "CodeStream" and "CodeStream (agent)". Lastly, with the CodeStream pane open, use the VSC command palette to "Open Webview Developer Tools" and then screenshot any red errors you see there. Thanks!

**Comment by aaroncraig10e** [comment]
I see `teamId` and session ids, etc, in the logs.  I'm assuming all of that stuff is safe to post in the public domain?  Or can I email you separately?

**Comment by planteater** [comment]
Feel free to email me directly at dave@codestream.com. Thanks!

**Comment by planteater** [comment]
This is fixed in 0.13.1.
