### ISSUE TITLE
Gutter comments and bookmarks

### ISSUE THREAD

**Issue by raphaelghub** [TeamCodeStream/CodeStream#40]
Noticed bookmarks and comments icon don't show in the vs code gutter. I use quokkas extension which uses the gutter too but it seems that's not the issue

<img width="1155" alt="Screen Shot 2019-03-17 at 5 24 15 PM" src="https://user-images.githubusercontent.com/9341646/54495200-a4b5ed00-48d9-11e9-9a88-d2032cca0673.png">

**Comment by planteater** [comment]
@raphaelghub - Thanks for the heads up on this issue. If you switch to a different source file and then back, do the codemarks appear in the gutter?

**Comment by raphaelghub** [comment]
@planteater no it doesn't :( also the comments are supposed to be context aware right ? I still see comments from another project when I switch to a different folder.
I currently only signed up for a codestream account though. Do i need other integrations for it to work ?

**Comment by eamodio** [comment]
@raphaelghub can you make sure that `codestream.showMarkers` is checked (`true`) in your vscode settings?

**Comment by raphaelghub** [comment]
> @raphaelghub can you make sure that `codestream.showMarkers` is checked (`true`) in your vscode settings?

Here @eamodio, Yes it is

**Comment by akonwi** [comment]
@raphaelghub Are the files you are commenting on in git repos pushed to a remote? Based on your screenshot, there's no commit hash for the bookmark you created because `Posted to: ` is blank. We can only track and show the contextual markers if we have enough information about the git repo.

**Comment by raphaelghub** [comment]
> @raphaelghub Are the files you are commenting on in git repos pushed to a remote? Based on your screenshot, there's no commit hash for the bookmark you created because `Posted to: ` is blank. We can only track and show the contextual markers if we have enough information about the git repo.

That was the problem! Thanks so much
