### ISSUE TITLE
codestream-agent is detected as a new process by Intego NetBarrier every time IntelliJ starts

### ISSUE THREAD

**Issue by nieldw** [TeamCodeStream/codestream#400]
Every time I start IntelliJ I have to whitelist the codestream-agent again. All other processes need to be whitelisted only once.

<img width="562" alt="image" src="https://user-images.githubusercontent.com/770125/107619431-d5386a00-6c5b-11eb-8124-c0bb5e89693b.png">

**Comment by planteater** [comment]
Thanks for the report @nieldw! I think we can make a change on our end so that you would only get prompted when we release a new version of the extension. I'll keep you posted here.

**Comment by planteater** [comment]
Fixed in v11.0.8 of our JetBrains extension.
