### ISSUE TITLE
Unable to amend a feedback request after a merge

### ISSUE THREAD

**Issue by pepijnve** [TeamCodeStream/codestream#401]
I started a feedback request from a feature branch. I made couple of extra commits, then merged in the integration branch and then made some additional commits. I'm now trying to amend the feedback request with additional commits, but the UI is stuck "Loading repo info". In Activity Monitor I can see the CodeStream sub process spawning short-lived git subprocesses, so it's still doing something, but it doesn't look like it's going to finish anytime soon. Is there any way to monitor what's going on via log files for instance?

**Comment by planteater** [comment]
@pepijnve - We're definitely aware of some issues around when you try to amend a review after merging another branch, and we are working on it. To help in that effort, could I trouble you for a log file? Instructions for grabbing them can be found at the following link. Note that we just need the Agent log in this case. Thanks!

https://docs.codestream.com/userguide/faq/client-logs/

**Comment by pepijnve** [comment]
Of course. I'll dig up those logs for you tomorrow.

**Comment by pepijnve** [comment]
@planteater here you go. The plugin seems to be stuck in a loop, querying the diff for the same commit over and over again.
[idea.log.zip](https://github.com/TeamCodeStream/codestream/files/5970602/idea.log.zip)

**Comment by hennidk** [comment]
@planteater , curious about whether the issues around amending after merge has been resolved? I seem to be having the same problem at the moment...
