### ISSUE TITLE
Unable to integrate with gitlab/jira without https

### ISSUE THREAD

**Issue by katzimoto** [TeamCodeStream/codestream#405]
I would like to use jira and gitlab with codestream and the server doesn't allow me to do it without https.

**Comment by planteater** [comment]
@katzimoto - Are you trying to connect to the cloud versions of Jira and GitLab, or Jira Server and GitLab Self-Managed? Assuming the cloud versions, I'm afraid this is accurate. We can't allow insecure connections from our backend.

**Comment by katzimoto** [comment]
I work with gitlab and jira am and trying to setup on perm codestream.

**Comment by planteater** [comment]
@katzimoto - To clarify though, are you connecting to the cloud versions of gitlab and jira, or on-prem?

**Comment by katzimoto** [comment]
On perm

**Comment by planteater** [comment]
Both of these integrations are set up within the CodeStream extension using personal access tokens (GitLab Self Managed) or api tokens (Jira Server). In other words, neither are set up by the on-prem admin. They're set up by individual users once they've signed up in the CodeStream extension. Can you confirm that this is how you set up the integrations?

**Comment by katzimoto** [comment]
I'm not entirely sure what you mean I haven't reached the point of setting up integrations.
While trying to enter the integration view from vs code as a user I got an error saying that I have to use https and I'm not quite sure what dose it mean and how to avoid this error (Im the admin on prem)

Thank you very much for your help🙂

**Comment by planteater** [comment]
@katzimoto - A screenshot of the page you're looking at, where you're getting that message about https being required, might be helpful here. Thanks!

**Comment by planteater** [comment]
And just to confirm, you have the CodeStream extension installed, you pointed it at your on-prem server, and you've signed up and created a team?

**Comment by katzimoto** [comment]
Unfortunately I am working in an air gapped network and can't get files out but the window that I tried to open it's sidebar->codestream->profile->integration and then I got the "we can't do integration without https"

**Comment by planteater** [comment]
Thanks for the info @katzimoto! We're digging into this now.

**Comment by planteater** [comment]
@katzimoto - I think we have this fixed. The URL below has a pre-release version of our extension.

https://www.dropbox.com/s/bov8lwzxxu0vuov/develop-codestream-10.5.2%2B5631.vsix?dl=0

﻿After downloading, click on the Extensions entry in the VS Code activity bar, and then select "Install from VSIX" from the ellipses menu at the top-right of the sidebar. You'll then be prompted to reload. Once you've installed the extension let me know if it fixes the issue.

We’ll be officially releasing that version either later today or tomorrow.

**Comment by katzimoto** [comment]
Great I will update you on Sunday

**Comment by planteater** [comment]
@katzimoto - We just released v10.6.0 of the CodeStream extension, so no need to use that VSIX anymore. You can just update as you would normally.
