### ISSUE TITLE
Issues view on side bar vscode doesn’t recognize issues from gitlab am with vscode on perm

### ISSUE THREAD

**Issue by katzimoto** [TeamCodeStream/codestream#409]
I work with codestream server in perm and with Gitlab-sm and when I create my issue it's appeared on my gitlab board but my issues view on the side bar doesn't show it.

**Comment by planteater** [comment]
@katzimoto - Just to confirm, the issue that you created is assigned to you? If so, does it appear in the Issues section if you click on the Refresh icon in that section's heading?
