### ISSUE TITLE
Have to reload vscode after inviting teammates

### ISSUE THREAD

**Issue by katzimoto** [TeamCodeStream/codestream#410]
I am using codestream on perm and when I tried to invite my teammate I had to reload my vs code to update the team list.

**Comment by planteater** [comment]
@katzimoto - That symptom is usually a sign of a broadcaster issue. That's the service that handles real-time messaging within the product. I'm sure it's a configuration issue, but to further diagnose we'll need some log files. First would be the broadcaster server logs. They can be seen by ssh-ing to your CodeStream server and running:

docker logs csbcast [-f]

We'll also want some client-side logs as well. In VS Code open the Output view (“View: Toggle Output” from the command palette) and select "CodeStream (Agent)" from the dropdown menu at the top-right. Copy all of the output you see and save it in a text file.

You can send both of these logs to me at support@codestream.com if you'd prefer not to post them here. Thanks!

**Comment by planteater** [comment]
Hi @katzimoto - Just wanted to follow up on those log files. Would love to figure this out for you!
