### ISSUE TITLE
Case sensitive branch names

### ISSUE THREAD

**Issue by ElRoberto538** [TeamCodeStream/codestream#411]
Branch names are case sensitive when creating them in Bitbucket from Jira, the current names generated when using {title} have a lowercase project name eg codestream-1349-taskname but Jira won't automatically link to the branch unless it matches exactly, e.g. CODESTREAM-1349-taskname. I can use {id}-{title} but then the task ID is repeated twice in each branch name. Any ideas?

**Comment by planteater** [comment]
Thanks for reaching out on this @ElRoberto538. I think we should be able to come up with a solution for you. I'll report back shortly.

**Comment by ppezaris** [comment]
@ElRoberto538 how would it look if we added an explicit setting to preserve case or not?
![image](https://user-images.githubusercontent.com/1483024/108781827-841c5600-7538-11eb-8055-d882551018eb.png)

**Comment by ElRoberto538** [comment]
@ppezaris That looks like it would work, I assume un-ticking that would leave it capitalized?

**Comment by ppezaris** [comment]
yes, exactly. look for this setting in our next release. default will be checked, but you can uncheck it.

**Comment by planteater** [comment]
@ElRoberto538 - This change is now available in version 10.6.1.

**Comment by ElRoberto538** [comment]
Thanks, works great!
