### ISSUE TITLE
Feedback request UI appears even if autoprompt is disabled in IntelliJ

### ISSUE THREAD

**Issue by pepijnve** [TeamCodeStream/codestream#412]
When committing changes, the CodeStream panel expands and shows the 'create feedback request' UI even though the 'Auto-prompt for feedback when committing' is set to disabled.

Tested with IntelliJ 2020.3.2 and CodeStream 10.6.0+130.

**Comment by planteater** [comment]
@pepijnve - We actually have two different mechanisms that auto trigger the Feedback Request form. One is committing via the command line (i.e., external to the IDE), and it is turned off via the toggle above the form. The other is committing from within the IDE itself. In that case, you simply uncheck the "Request feedback" box in the post-commit actions and we'll remember that setting for the next time. 

![JBCommitDlg](https://user-images.githubusercontent.com/3442587/108845574-997e9800-75ab-11eb-8a66-e462d19b453f.jpg)

Note that in some JetBrains IDEs the list of post-commit actions isn't exposed by default and you need to click to see the list.

**Comment by pepijnve** [comment]
Oh, there's another checkbox. I've switched to the non-modal commit window that's being advertised in your screenshot and there the option is hidden behind a cogwheel button. I was thinking the big switch at the top of this screen would control the same thing.

<img width="316" alt="image" src="https://user-images.githubusercontent.com/225326/108846041-6efa0280-75de-11eb-87d8-34642f82f66b.png">

or this one in the feedback request settings:

<img width="289" alt="image" src="https://user-images.githubusercontent.com/225326/108846158-8a650d80-75de-11eb-8394-e5736f145d13.png">

It's a bit confusing to have these related but subtly different settings.

**Comment by planteater** [comment]
Ah, I see. Sorry for the confusion. That checkbox doesn't actually exist anymore in the latest version of the extension, as we moved it out of the IDE settings and now store it in our own user preferences. That way it applies across all of your IDEs/computers. In that move, we may have accidentally turned the setting back on for you. Sorry about that!
