### ISSUE TITLE
Prompt for feedback when committing is displayed although it is disabled.

### ISSUE THREAD

**Issue by skorunka** [TeamCodeStream/codestream#414]
Version 10.6.0+130.
I think after last update, the dialog for feedback is displayed although "Auto-prompt for feedback when committing" is se to "No".

![image](https://user-images.githubusercontent.com/218913/109126950-26f9ed80-774e-11eb-951c-3a4494d88ed2.png)

**Comment by planteater** [comment]
@skorunka - Did you commit from the IDE or externally (e.g., the command line)? We actually have two separate mechanisms at work here. One that triggers the FR form after committing externally, and that is turned off via the toggle depicted in your screenshot. The other one is triggered when you commit from the IDE, and that is turned off by unchecking the "Request feedback" box in the after-commit actions.

**Comment by skorunka** [comment]
@bcanzanella Hi, from IDE(IntelliJIDEA). I see the "problem" was with this:
![image](https://user-images.githubusercontent.com/218913/109300017-466c4580-7836-11eb-90b0-af1095b70b00.png)
