### ISSUE TITLE
Publish to Open Vsx Registry

### ISSUE THREAD

**Issue by orellabac** [TeamCodeStream/codestream#415]
Could you please publish this extension too into the https://open-vsx.org/ ?

**Comment by planteater** [comment]
Thanks for the suggestion @orellabac! We'll look into this.

**Comment by lsascha** [comment]
Please deploy to Open-VSX. There is some i guess unofficial release on Open-VSX (see https://open-vsx.org/extension/CodeStream/codestream),
but it stopped working since it seems its not updated anymore and the Extension says `Update Required` since a couple days.

**Comment by planteater** [comment]
@lsascha - Sorry about that! The latest extension (12.12) should be up there now.
