### ISSUE TITLE
IntelliJ: "This file is not part of a git repository."

### ISSUE THREAD

**Issue by crummy** [TeamCodeStream/codestream#416]
* IDE: IntelliJ Ultimate 2020.3.2
* Plugin: Codestream 10.6.0+130
* Integration with Gitlab self-hosted

I'm clicking around files in my IDE, but under "Codemarks" I see a message "This file is not part of a git repository." whatever I click.

However, I am in a git repo. Just one project open, with a git repo at its root. Here are my IntelliJ logs:

[idea-logs-20210226-135239.zip](https://github.com/TeamCodeStream/codestream/files/6046736/idea-logs-20210226-135239.zip)

![image](https://user-images.githubusercontent.com/690626/109239079-88e35180-7839-11eb-8268-76b664c1b6cf.png)

**Comment by planteater** [comment]
Thanks for the report @crummy! We'll dig into this asap.

**Comment by crummy** [comment]
For what it's worth, I can no longer repro after updating to Codestream 10.6.1+131.

**Comment by planteater** [comment]
Thanks for the update @crummy! I'll close this for now, but definitely reach out if you notice the issue again.
