### ISSUE TITLE
Ampersands are altered in codeblock edits during a PR review

### ISSUE THREAD

**Issue by kwojcik** [TeamCodeStream/codestream#417]
vscode plugin v10.6.0

STRS
Start reviewing a github PR
Add a comment to review
![image](https://user-images.githubusercontent.com/8961787/109348083-e91dc780-7828-11eb-8c43-6fcc22ef326c.png)

Edit the comment,  to
![image](https://user-images.githubusercontent.com/8961787/109348128-f6d34d00-7828-11eb-8112-5328a8c0795f.png)

O
Comment gets saved as
![image](https://user-images.githubusercontent.com/8961787/109348140-fd61c480-7828-11eb-8268-bbcfe4beb902.png)

D
Comment gets saved as "test2 `&`"

It continues :)

STRS
complete the steps above
Edit the comment again, change it to the below
![image](https://user-images.githubusercontent.com/8961787/109347907-b1168480-7828-11eb-9041-acbf99f01e35.png)

O
![image](https://user-images.githubusercontent.com/8961787/109347940-ba9fec80-7828-11eb-86e9-635d18a9a1e7.png)

D
test2
```
&
```

**Comment by planteater** [comment]
Thanks for the report @kwojcik! We'll get this fixed.

**Comment by planteater** [comment]
Fixed in v11.0.6
