### ISSUE TITLE
VS Slack black text

### ISSUE THREAD

**Issue by TravorCharro** [TeamCodeStream/CodeStream#42]
This is how my codestream panel looks like (connected to Slack chat).
It's kinda hard to read.

I tried to reinstall codestream / reopen VS / change color theme to Light and back; but it didn't work.
When i chose 'Light' color theme in Visual Studio options, text's color doesn't change from black to white, and it looks as it should.

![02b53c400f683867312ce5970f4ded27](https://user-images.githubusercontent.com/33463233/54825240-23d26900-4cbe-11e9-8fa8-fecb239c9f80.png)

**Comment by eamodio** [comment]
@TravorCharro Sorry for the issue, but can you provide us some more details? Is the problem you are having only happen when you change themes? Or is it always happening even when you start VS fresh? If the latter, are you using a custom theme in VS? If you are, could you export your theme file and post it? Also could you post a screenshot of what another tool window in VS looks like (e.g. properties window -- since we know it uses the same color we key off of)

Thanks!

**Comment by TravorCharro** [comment]
> @TravorCharro Sorry for the issue, but can you provide us some more details? Is the problem you are having only happen when you change themes? Or is it always happening even when you start VS fresh? If the latter, are you using a custom theme in VS? If you are, could you export your theme file and post it? Also could you post a screenshot of what another tool window in VS looks like (e.g. properties window -- since we know it uses the same color we key off of)
> 
> Thanks!

The problem is always happening, even when i start VS fresh. "Dark" color theme is not custom, it's default in VS. 
![e840568c5e86b10d5cd74f016400f53e](https://user-images.githubusercontent.com/33463233/54903179-53ff4f00-4eec-11e9-90ac-c8dd422227c5.png)

**Comment by bcanzanella** [comment]
@TravorCharro If you're able, we'd love your help with this. There's minimal logging around the theming aspect of the extension for the version you have installed. Here's a [link](https://s3.amazonaws.com/codestream-prod/asset-distribution/vs/codestream-vs-0.50.0.400.vsix) to download a version of the extension that has some enhanced theme logging (codestream-vs-0.50.0.400.vsix) (it also includes a potential work-around for you). 

Once you've installed this version and you've gone to a Slack channel, navigate with file explorer to `%LocalAppData%\CodeStream\Logs`. Inside you should see a file called `vs-extension.log`. If you could attach that in an email to brian@codestream.com we can get to the bottom of this.

**Comment by TravorCharro** [comment]
@bcanzanella thank you for replying. I've sent mail with log to brian@codestream.com.

**Comment by bcanzanella** [comment]
thanks @TravorCharro got them. We know what's going on with this -- some RGBA CSS values are being calculated and written as inline styles without accounting for culture info. We should have a fix out soon.

**Comment by planteater** [comment]
Fixed in version 0.51.0
