### ISSUE TITLE
Delete branch after merge

### ISSUE THREAD

**Issue by ahopkins** [TeamCodeStream/codestream#421]
Is there the ability to delete a branch after merging the PR?

I see this message, but it would be nice to have a "delete branch" button here.

![image](https://user-images.githubusercontent.com/166269/109960211-33072180-7cf1-11eb-8a6e-d1a8b472e8c7.png)

**Comment by planteater** [comment]
@ahopkins - Thanks for the feedback! This is definitely on our roadmap, along with a number of other post-merge actions such as updating your ticket status, adding a link to the PR in the ticket, clearing your slack status, etc. This is actually quite high on our todo list right now.

**Comment by jorgv** [comment]
Hello, great tool! congratulations

Is there any update on the mentioned features?

**Comment by planteater** [comment]
@jorgv - No update I'm afraid. When it comes to the PR integration, the focus at the moment has been getting support for Bitbucket finished. After that I think we'll start to tackle requests like this one.

**Comment by ahopkins** [comment]
FWIW, it is irrelevant for me now.
