### ISSUE TITLE
Feature Request: single user / teamless mode

### ISSUE THREAD

**Issue by laundmo** [TeamCodeStream/codestream#423]
The functionality of integrating with git services that this extension offers seems awesome, but there is no need for me to have any team features (which, sidenote, aren't explained well) as I would just like to use this extension for the GitHub issues/PRs integration.
Would a mode where you don't need a team to get access to all features that only depend on the signed in account be possible?

**Comment by laundmo** [comment]
> One thing we're looking at is making it so that you can use this single-player mode functionality without even having to sign up.

Yep, thats basically exactly what im looking for. I may just create a account for now, but the way the sign-up is worded seems like codestream as a whole is only meant for organizations/teams and wont work for a single user.

sentences like
> Each organization that uses CodeStream has teams of their own. Teams are where all of their code discussions are kept, and they can only be joined by invitation.

are not really conductive to explaining to people that they dont need a group of people for codestream to work.

**Comment by LecrisUT** [comment]
In single-user mode, would the comments be synced if `.idea` or similar folders are also synced?
