### ISSUE TITLE
CodeStream work with only one repo (Pycharm)

### ISSUE THREAD

**Issue by theytaz3** [TeamCodeStream/codestream#427]
Hi ! 

for my main project, codestream works well overall. 
However, when I launch via pycharm another repo with the CodeStream extension enabled, Codestream doesn't even show me the page to log into my account and I have an infinite load. 

![image](https://user-images.githubusercontent.com/33628286/110137825-90729f80-7dd1-11eb-8628-73ad24d53cd5.png)

Unlike my main repo :

![image](https://user-images.githubusercontent.com/33628286/110137897-a7b18d00-7dd1-11eb-9df9-ad893e1b2924.png)

in the pycharm logs, I get this message when I open CodeStream : 

![image](https://user-images.githubusercontent.com/33628286/110138141-f2cba000-7dd1-11eb-8354-5e6ce6f3d39b.png)

**Comment by planteater** [comment]
@theytaz3 - Can you tell us how exactly you launched the second project? Thanks!

**Comment by theytaz3** [comment]
i launch my project with right clic and open folder as Pycharm : 


![image](https://user-images.githubusercontent.com/33628286/110140881-db41e680-7dd4-11eb-8a1a-0d00ee7601dc.png)

**Comment by theytaz3** [comment]
Ok so, i find a solution ! it's my repo path that was bad, the [Dev] was bugging Codestream. i changed the name of this folder to Dev and it works !
