### ISSUE TITLE
[Bug] Incorrect user/repo listed at bottom of a PR

### ISSUE THREAD

**Issue by lightmaster** [TeamCodeStream/codestream#429]
## Versions
CodeStream v10.6.1
VSCode 1.54.1

## Description
When viewing a PR in CodeStream, the message at the bottom of the PR that says `Add more commits by pushing to the <branch> branch on <user>/<repo>.` references the wrong user if the PR is located on upstream repo. IE: I fork a repo, make a features branch, create a PR with the upstream repo trying to incorporate the branch located in my repo into their repo.

## Screenshots

Codestream view of the PR:
![image](https://user-images.githubusercontent.com/5307827/110224064-72c33a00-7ea6-11eb-9b1d-061ec715f393.png)

Github's view of the same PR:
![image](https://user-images.githubusercontent.com/5307827/110224067-75be2a80-7ea6-11eb-9381-3c575bced1b9.png)

**Comment by bcanzanella** [comment]
thanks @lightmaster we're get that fixed.

**Comment by planteater** [comment]
@lightmaster - This has been fixed in v11.0.5.
