### ISSUE TITLE
vscode: make use of authentication api

### ISSUE THREAD

**Issue by akosyakov** [TeamCodeStream/codestream#431]
Since the last release VS Code provides native support of accounts, secrets and authentication providers, see 
- https://code.visualstudio.com/api/references/vscode-api#authentication
- https://code.visualstudio.com/api/references/vscode-api#SecretStorage

**Comment by planteater** [comment]
@akosyakov - We're actually already using that api. If you connect to GitHub from our VS Code extension it leverages this native support rather than sending you through an OAuth flow.
