### ISSUE TITLE
Issues: Add fuzzy search.

### ISSUE THREAD

**Issue by diazemiliano** [TeamCodeStream/codestream#438]
At current the experience of trying to find a specific issue its really awful.
It would be awesome to be able to have fuzzy search there.
![image](https://user-images.githubusercontent.com/64487650/110787196-d3a69580-824b-11eb-8ea4-f337b8a3ceaf.png)

**Comment by planteater** [comment]
Thanks for the suggestion @diazemiliano!

**Comment by diazemiliano** [comment]
Your welcome @planteater.
Thanks for `codestream`.
