### ISSUE TITLE
Gitlab On-Prem Support

### ISSUE THREAD

**Issue by netclectic** [TeamCodeStream/CodeStream#44]
It seems the Gitlab integration is only supported for gitlab.com - is there any way to configure it to use an on-prem gitlab instance or is there likely to be support for it in the future?

**Comment by cstryker** [comment]
@netclectic in theory we do support gitlab on-prem, though there is no way to configure for it on your end. But if you get your administrator to set up a "CodeStream" app on your on-prem installation, give us the url, client ID, and client secret for your app, we can configure a setting for your team that will allow you to auth and access your on-prem gitlab installation. 

Note that we haven't fully tested this functionality on our end (we have for github enterprise, but in theory they should work the same), so it might not work as expected. If you encounter difficulty, we'll be happy to work with you to get it to work as best we can.

**Comment by netclectic** [comment]
Interesting, I'm not sure if that will fly with our security guys but I'll pass it over to our gitlab admin guys and see what happens.

Thanks.

**Comment by planteater** [comment]
@netclectic - Any feedback from the admins?

**Comment by damageboy** [comment]
I'd also like to give on-prem gitlab a serious consideration.

Can you please explain WHAT sort of permissions from gitlab you guys would require?

**Comment by cstryker** [comment]
@damageboy as I told @netclectic above, I think it's just a matter of hooking up to an "app" that your admin guys would have to set up to access your gitlab through OAuth. As far as we know from looking through documentation, gitlab doesn't require finer-grained permissions (scopes), but as we haven't fully tried to go through it ourselves, I can't be fully confident in that answer either. In the coming weeks, we do plan to make on-prem integrations available through the CodeStream UI, but we're not there yet.

**Comment by cstryker** [comment]
@damageboy a little further investigation turned up that the scopes we require are defined when your admin actually sets up that "app" that allows the OAuth process ... the scopes required are "api", "read_user", and "read_repository", though to be honest I think more experimentation might be required to confirm/deny whether the "api" scope is required ... hope that answers your question better, at least for now.

**Comment by damageboy** [comment]
OK,
Is this something I could possibly setup?
How would we make a stab at this?

**Comment by Hoho5000** [comment]
Any updates here? Would love to get this integrated with an on premises GitLab server but am not sure how.

**Comment by cstryker** [comment]
@Hoho5000 thanks for asking ... we'll be looking into that next week, I'll keep this thread updated. To be clear, you're asking about GitLab issue integration? Because we also have a deeper integration in the works with GitLab pull requests.

**Comment by cstryker** [comment]
Good news ... we've got GitLab Enterprise support coming, should be available in a week or so, if not sooner. I'll update here when it's available.

**Comment by planteater** [comment]
Support for GitLab Enterprise is now available in v5.0 of our extensions.

**Comment by DanubeRS** [comment]
Is it possible to provide an example of the configuration for `~/.codestream/codestream-services-config.json`? Having a quick look through the source to see whether I can figure out how the on-prem url is set.

**Comment by cstryker** [comment]
@DanubeRS Is your goal to connect to a self-hosted GitLab from CodeStream?

**Comment by DanubeRS** [comment]
Both services are on prem, and non-public

**Comment by cstryker** [comment]
OK, we switched to a PAT-based model for those connections some time ago. All you would need to do to connect to your GitLab instance is go to the Integrations panel in CodeStream, click the "GitLab Self-Managed" button, and that will bring you to a panel where you can enter the URL to your GitLab instance and your own PAT. That should do it.

**Comment by DanubeRS** [comment]
Ah yep, excellent. I had this working prior, but was having issues creating/viewing MR. Looks as if MR review is not supported for GitLab, which was source for confusion. Thanks 👍

**Comment by cstryker** [comment]
Right. You'll see your MR comments alongside the code, but full support for MR integration (like we have for GitHub) isn't supported yet. It's coming soon, though, so stay tuned!

**Comment by DanubeRS** [comment]
Great, ill be keeping an eye on the issue #369
