### ISSUE TITLE
Issue Tracker: Taiga integration

### ISSUE THREAD

**Issue by LecrisUT** [TeamCodeStream/codestream#445]
Would be nice to also have intergrations with [taiga](https://taiga.io/). Although Taiga is not geared towards code-based projects as much, it is still evolving and the issue/kanban features are competitive with trello. [Here](https://taigaio.github.io/taiga-doc/dist/api.html) is the API documentation for it.

**Comment by planteater** [comment]
Thanks for the suggestion @LecrisUT!
