### ISSUE TITLE
Cannot connect to CodeStream

### ISSUE THREAD

**Issue by wanlinruo** [TeamCodeStream/codestream#446]
Hello, our company is conducting a code review, and I am very happy to use this product of yours, but encountered problems in the process of using it
background:
We built our own private server and configured it according to the documents you provided (documents are as follows: https://github.com/TeamCodeStream/codestream-server).
We set our own server url
![image](https://user-images.githubusercontent.com/21278600/111287582-52e9fe00-867e-11eb-919c-eb2c425e112c.png)
At the same time, I checked the status on the console
![image](https://user-images.githubusercontent.com/21278600/111287625-5f6e5680-867e-11eb-9de6-6d58559e46fb.png)
But I encountered a connection problem when I entered Android studio, as shown below:
![image](https://user-images.githubusercontent.com/21278600/111287702-70b76300-867e-11eb-8d0d-fd4d6db51bd6.png)
Can you help me see how to deal with it

**Comment by jimmyjayp** [comment]
When you started the codesstream-server services, it should have launched a broadcaster which listens on port 12004.  First, very that it's running by going to http://localhost:12004/no-auth/status . That should return OK.

Next we'd need to look at your codestream agent logs from inside your IDE. We have a page in our faq on how to get logs here https://docs.codestream.com/userguide/faq/client-logs/ .   In the log, search for 'broadcaster'. We need to see what the errors are.

**Comment by wanlinruo** [comment]
> When you started the codesstream-server services, it should have launched a broadcaster which listens on port 12004. First, verify that it's running by going to http://localhost:12004/no-auth/status . That should return OK.
> 
> Next we'd need to look at your codestream agent logs from inside your IDE. We have a page in our faq on how to get logs here https://docs.codestream.com/userguide/faq/client-logs/ . In the log, search for 'broadcaster'. We need to see what the errors are.

First,i run this url in my server,it show ok
![image](https://user-images.githubusercontent.com/21278600/111405535-a35b6d00-870b-11eb-89ee-7839b8f5576a.png)
Second,i follow your suggestion,get this log
[studio-logs-20210317-102145.zip](https://github.com/TeamCodeStream/codestream/files/6153344/studio-logs-20210317-102145.zip)

**Comment by wanlinruo** [comment]
I've dealt with this problem, but thank you anyway.

**Comment by planteater** [comment]
Glad to hear it @wanlinruo! Let us know if you need anything else.
