### ISSUE TITLE
 Codestream on Android Studio can not support Chinese input?

### ISSUE THREAD

**Issue by Callanna** [TeamCodeStream/codestream#447]
Hi！ CodeStream  is very nice Tool to Code Review. Our Team  decided to use it to manage code quality， but We find  that Codestream can not  support Chinese input.  Android Studio 4.1 ,Codestream version  is 10.6.0+130 .

**Comment by planteater** [comment]
@Callanna - Unfortunately you'll have to wait for the release of Android Studio 4.2. That version will be based on IntelliJ 2020.2, which includes native support for rendering a webview (JCEF). That native webview rendering does include support for Chinese input. I don't know the release date for Android Studio 4.2, but it can't be too far away at this point.

**Comment by Callanna** [comment]
![image](https://user-images.githubusercontent.com/14858726/111772430-ce9ab380-88e7-11eb-9425-b8c3f4efc140.png)
Android Studio 4.2 beta  also can not support Chinese input, Do we have to use the release version of Android Studio 4.2 ?

**Comment by planteater** [comment]
@Callanna - It doesn't look like the 4.2 beta includes JCEF. We'll do some more research to determine if/when that goes in.

**Comment by AliMaster** [comment]
![image](https://user-images.githubusercontent.com/4350415/112847917-213f5100-90da-11eb-9cbc-a0338c8b21f3.png)

`Android Studio Arctic Fox | 2020.3.1 Canary 12` is still not working well 

```
Android Studio Arctic Fox | 2020.3.1 Canary 12
Build #AI-203.7148.57.2031.7226969, built on March 23, 2021
Runtime version: 11.0.8+10-b944.6842174 x86_64
VM: OpenJDK 64-Bit Server VM by N/A
macOS 10.14.6
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 6
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.codestream.jetbrains-codestream
```
