### ISSUE TITLE
Support for marking a certain discussions(conversations) as resolved

### ISSUE THREAD

**Issue by liuliangsir** [TeamCodeStream/codestream#448]
As the above title says, I would like to have a similar feature. In addition, I also want to have another feature like collapsing resolved conversations.

**Comment by planteater** [comment]
@liuliangsir - Can you give me a little more detail here? You actually can resolve conversations on CodeStream, but how you do it depends on whether you're talking about codemarks or comments in a Feedback Request. Codemarks can be resolved simply by clicking the Resolve button at the bottom of the form. See more details here:

https://docs.codestream.com/userguide/workflow/discuss-code/#resolving-codemarks

In feedback requests, if you want to be able to resolve a comment, mark it as a "change request". To resolve a change request just check the box next to it in the Change Requests section of the feedback request.

**Comment by liuliangsir** [comment]
I am talking about comments in a Feedback Request. The followings are a bunch of screenshots. In addition, I would like to mark  comment as resolved one by one. That is because that a lot of unresolved comments take up huge space.

![image](https://user-images.githubusercontent.com/8049878/111856495-1b24d400-8966-11eb-930f-1495fd48a9e9.png)
