### ISSUE TITLE
Unable show defalut profile photo

### ISSUE THREAD

**Issue by wanlinruo** [TeamCodeStream/codestream#454]
As title,we found one problem,when we open android studio,cannot show defalut profile photo,we have to change  profile photo,we suggest that can we change the defalut profile photo,instead of https://gravatar.com/
![image](https://user-images.githubusercontent.com/21278600/112252053-4fb2cb80-8c97-11eb-821a-66418825c2bd.png)
thanks for your help

**Comment by planteater** [comment]
@wanlinruo - Are you still seeing issues with the headshots from Gravatar not rendering?

**Comment by wanlinruo** [comment]
> @wanlinruo - Are you still seeing issues with the headshots from Gravatar not rendering?

yes,gravatar not rendering, just like this
![企业微信截图_813a5959-5c25-490a-9622-3dd880acff59](https://user-images.githubusercontent.com/21278600/114803378-ed4e7600-9dd1-11eb-9c6f-bcaba9b9e554.png)

**Comment by planteater** [comment]
@wanlinruo - Try v11.0.4 of the CodeStream extension and let me know how things look. Our theory here is that there's some web proxy that the webview can't make these img requests to, so we put in a change to have the headshots fall back to the user of initials in these cases.
