### ISSUE TITLE
Feature Request: Allow viewing and editing of a custom filter

### ISSUE THREAD

**Issue by THammond9** [TeamCodeStream/codestream#457]
For Jira, after I add a custom filter I cannot edit that filter. There is also no way to see the whole filter as mine is too long. This is a problem when I am looking at my issues and am unable to find the one I want. I have no way of knowing _why_ my current filter is not showing the ticket that I am interested in. I then have to go Jira and create a new JQL and add it to my custom filters. This can lead to a situation where you are flip-flopping queries in some way and don't even know it.

Edit: forgot to note that I am using Visual Studio 2019

**Comment by planteater** [comment]
Thanks for the feedback @THammond9! I'll get this onto the roadmap.
