### ISSUE TITLE
When I view the MR I submit, I still see the 'Approve' button

### ISSUE THREAD

**Issue by ftcy0118** [TeamCodeStream/codestream#460]
This MR is submitted by me but I still see the 'Approve' button. When I clicked the button, nothing happened.

<img width="502" alt="截圖 2021-03-27 上午1 01 47" src="https://user-images.githubusercontent.com/1652347/112667543-52c8da00-8e98-11eb-84b3-993317e39729.png">

**Comment by planteater** [comment]
@ftcy0118 - Could I trouble you to download and install an updated version of the CodeStream extension from the following GDrive folder? Just look for the vscode extension with the highest version number.

https://drive.google.com/drive/folders/1mxPwlYAcxEGkZrwdv4JSjSACpP1277S6?usp=sharing

After downloading, click on the Extensions entry in the VS Code activity bar, and then select "Install from VSIX" from the ellipses menu at the top-right of the sidebar. You'll then be prompted to reload. Let me know if it fixed the issue. Thanks!

**Comment by ftcy0118** [comment]
fixed!
