### ISSUE TITLE
Turning off feedback suggest after commit is not working

### ISSUE THREAD

**Issue by xzaleksey** [TeamCodeStream/codestream#461]
After selecting "No" for suggesting a feedback prompt after a commit, it still appears.

**Comment by AliMaster** [comment]
see #414

**Comment by planteater** [comment]
@xzaleksey - Did you commit from the IDE or externally (e.g., the command line)? We actually have two separate mechanisms at work here. One that triggers the FR form after committing externally, and that is turned off via the toggle depicted in your screenshot. The other one is triggered when you commit from the IDE, and that is turned off by unchecking the "Request feedback" box in the after-commit actions.

![109300017-466c4580-7836-11eb-90b0-af1095b70b00](https://user-images.githubusercontent.com/3442587/112838530-2618ec00-906b-11eb-8e43-dcd84abcf32f.png)

**Comment by xzaleksey** [comment]
Internally, where can I find this "Request feedback" checkbox? Can't see it during commit

**Comment by xzaleksey** [comment]
Ok I found it :)

**Comment by planteater** [comment]
Good deal @xzaleksey! We're going to make an update so that turning off one mechanism will turn off the other as well.

**Comment by mhaggag** [comment]
For future reference, the settings is found by clicking the "Gear" icon here next to Amend. It took me way too long to find this, and it was driving me insane.
![image](https://user-images.githubusercontent.com/1469940/113925899-d1543e80-97eb-11eb-9b97-1027ccfbbec6.png)
