### ISSUE TITLE
[Jetbrains Gitlab Integration] Merge button still active and visible for merged pull requests

### ISSUE THREAD

**Issue by aderopoa** [TeamCodeStream/codestream#468]
On the gitlab Integration on Jetbrains, the merge button is still active for merged pull request. 

Will suggest it is greyed out or removed for merged pull requests.

**Comment by planteater** [comment]
@aderopoa - It looks like you may have grabbed an older version of the extension from that GDrive folder this morning. To make things easier, I went ahead and cleared out the older versions. Can you grab the jetbrains-codestream-10.7.4+3887 file and try again? Thanks!

https://drive.google.com/drive/folders/1mxPwlYAcxEGkZrwdv4JSjSACpP1277S6?usp=sharing

**Comment by aderopoa** [comment]
Thanks.
