### ISSUE TITLE
[VS] rebase button does not work

### ISSUE THREAD

**Issue by ftcy0118** [TeamCodeStream/codestream#469]
clicked and nothing happened

<img width="243" alt="截圖 2021-04-01 上午11 09 55" src="https://user-images.githubusercontent.com/1652347/113248123-e95d2700-92ee-11eb-927b-e9fd60b3a584.png">

**Comment by planteater** [comment]
@ftcy0118 - We don't have support for rebasing yet, so our next release will disable that button and add appropriate messaging. We should add support for rebasing very soon though.
