### ISSUE TITLE
[VS] submit button should be disabled if there is no comment

### ISSUE THREAD

**Issue by ftcy0118** [TeamCodeStream/codestream#470]
the button is always enabled and when I clicked 'submit' with no comment, this comment window is gone but no comment is posted at all (which is correct but I prefer just disable 'submit' button!)

<img width="259" alt="截圖 2021-04-01 上午11 31 40" src="https://user-images.githubusercontent.com/1652347/113248186-05f95f00-92ef-11eb-87d0-80a21c9851be.png">

**Comment by planteater** [comment]
In actuality, you should be able to submit without a comment. But, you shouldn't be able to submit if there are zero pending comments, which is the case in your screenshot. We'll get that fixed. Thanks!
