### ISSUE TITLE
[VS][feature request] show MR's approval status in MR list

### ISSUE THREAD

**Issue by ftcy0118** [TeamCodeStream/codestream#471]
It is helpful if I can know if these MR is approved or not (maybe even tell me who approve it?) when I check this list.

<img width="308" alt="截圖 2021-04-01 下午1 38 40" src="https://user-images.githubusercontent.com/1652347/113248446-9637a400-92ef-11eb-9e16-62e17b9a8613.png">

**Comment by planteater** [comment]
@ftcy0118 - Thanks for all of the feedback! In this case, would it make sense to simply not show MRs in the Waiting section once they've been approved?

**Comment by ftcy0118** [comment]
It might be a good idea! In my daily workflow, I am still interested in some approved MRs which is not accepted by me. For example, if a MR is reviewed and approved by someone else, but the title looks interested to me, I will still take a look on it. Another case, if a MR is approved by me but I noticed the comment count increased, I will go to check for the new comments.

Maybe you can add another list for these? (While GitLab `merge_requests` page just lists all MRs with approval status.)

**Comment by vmohir** [comment]
I think there should be MRs that are assigned to the user excluding the ones that are approved by them. In my case (a self-hosted Gitlab), I'm seeing all of the MRs even those that I'm not assigned to.

**Comment by paour** [comment]
In my workflow, we use both the Assigned and the Reviewer fields. I agree with @vmohir that I would like to see in the Waiting list MRs where I'm either assigned or reviewer, and I have not yet approved.

**Comment by christophedcpm** [comment]
I'm leaning towards what @ftcy0118 said. I like to have a clear list of MR that are expecting action from me. But I also like to have a view on all the new code that is going into the repo. 
Maybe we could have an extra list for those MR that we did not created or are not assigned to, with eventually configurable filter so we can choose exactly what to see in this list ?

**Comment by aderopoa** [comment]
Although the space is small, I will approach it differently. IMO the naming can be changed from `Waiting for my review` to `Open Reviews`. 
For reviews where I am a reviewer it can have an icon showing my attention is required and when I approve the MR, I have a small green check mark identifying that I have approved it. 
I will like to see reviews in the open column even after I have approved it to monitor comments and changes.

**Comment by planteater** [comment]
> Maybe we could have an extra list for those MR that we did not created or are not assigned to, with eventually configurable filter so we can choose exactly what to see in this list ?

@christophedcpm - You can actually do this today. If you click on the Filter icon in the heading of the Merge Requests section you'll be able to create a new subsection based on a custom query.

**Comment by planteater** [comment]
> Although the space is small, I will approach it differently. IMO the naming can be changed from `Waiting for my review` to `Open Reviews`.
> For reviews where I am a reviewer it can be pushed to the top and have an icon showing my attention is required and when I approve the MR, I have a small green check mark identifying that I have approved it.
> I will like to see reviews in the open column even after I have approved it to monitor comments and changes.

@aderopoa - The way this would work is that once the MR is either approved or closed, it would move from the Waiting section down to the Recent section. Do you think that accomplished what you're looking for, or would you prefer your idea of an Open section where the MRs remain until closed?

**Comment by aderopoa** [comment]
> > Although the space is small, I will approach it differently. IMO the naming can be changed from `Waiting for my review` to `Open Reviews`.
> > For reviews where I am a reviewer it can be pushed to the top and have an icon showing my attention is required and when I approve the MR, I have a small green check mark identifying that I have approved it.
> > I will like to see reviews in the open column even after I have approved it to monitor comments and changes.
> 
> @aderopoa - The way this would work is that once the MR is either approved or closed, it would move from the Waiting section down to the Recent section. Do you think that accomplished what you're looking for, or would you prefer your idea of an Open section where the MRs remain until closed?

I think having an open section where the MRs remain until closed is needed. Looking at it from a team perspective, it will be easier for the team to reach out to engrs yet to review. The open section informs me that action still needs to be taken to close a review. Might be my approval or another team members approval.

**Comment by planteater** [comment]
I think we're going to go ahead and combine the Waiting and Assigned sections, but unfortunately it doesn't look like GitLab exposes the approval state of an MR via their api. We're still exploring options though...

**Comment by planteater** [comment]
Unfortunately, due to limitations in the GL api there's actually not a lot we can do here. As noted above, we don't have access to the approval state. Additionally, older versions of GitLab Self Managed don't have support for reviewers, so for now, I don't think we can combine the Waiting and Assigned sections. 

For those of you that don't really use reviewers or assignees, my suggestion would be to create a custom query to show All Open MRs (state:opened). Just click the filter icon in the heading of the Merge Requests section.

The one change we did make, which will be applicable to @vmohir, is that if you're on an older version of GitLab Self Managed that doesn't support reviewers, we replace the Waiting on my Review section with an All Open section automatically.
