### ISSUE TITLE
[VS] I can see MR which is created by me in `Waiting on my Review` list

### ISSUE THREAD

**Issue by ftcy0118** [TeamCodeStream/codestream#472]
If I add myself into `Reviewers` , my MR will also shown in `Waiting on my Review` list. If you clicked into that MR, `Approve` button will be displayed and can be clicked.

If you use GitLab web to review, there is no `Approve` button at all. Also, I think the better way is just take this MR out from `Waiting on my Review` list.

**Comment by planteater** [comment]
We'll handle the Approve button as part of this report https://github.com/TeamCodeStream/codestream/issues/473

But, I think it is appropriate for the MR to show up in the Waiting section, even if you were the one to add yourself as a reviewer.
