### ISSUE TITLE
[VS] Approve button is displayed in `Created by Me` list

### ISSUE THREAD

**Issue by ftcy0118** [TeamCodeStream/codestream#473]
It should not displayed at all cause I cannot Approve my own MR

**Comment by planteater** [comment]
Thanks for the heads up on this @ftcy0118! It looks like the ability to prevent authors from approving is a premium feature that we weren't aware of. We'll take care of this and I'll follow up with you.

**Comment by planteater** [comment]
@ftcy0118 - If you grab the latest vscode build from here it should fix this issue.

https://drive.google.com/drive/folders/1mxPwlYAcxEGkZrwdv4JSjSACpP1277S6?usp=sharing
