### ISSUE TITLE
GitLab MR review doesn't always show new comment button in gutter

### ISSUE THREAD

**Issue by emmeram** [TeamCodeStream/codestream#474]
Frequently when I'm reviewing a file in a GitLab MR, I mouse over the gutter next to the line numbers and am only shown the new comment button for the line I have my cursor in. I would expect to be able to see the button in the gutter for any line I mouse over.

I haven't been able to nail down a pattern on this.

**Comment by planteater** [comment]
@emmeram - One thing to check, just to be sure... In your IDE go to Preferences > Tools > CodeStream and make sure the "Show + icon on hover" box is checked.

**Comment by emmeram** [comment]
Confirmed that it's turned on.

<img width="1094" alt="Screen Shot 2021-04-05 at 14 47 26" src="https://user-images.githubusercontent.com/68029381/113612449-de233780-961d-11eb-977e-d309b33f8e49.png">

**Comment by emmeram** [comment]
I've determined repeatable steps that cause the icon to not appear:

1. Load a GitLab MR using a URL
2. Open a file in the change list
3. Mouse over the gutter
4. Click the + button to add a comment to a line
5. Enter a value for the comment
6. Click 'Start Review'

When I next mouse over the gutter, the + button does not appear. I can click in the gutter and get no response. I can get the + button to come back by clicking on a random line in the file and mousing over the gutter again.

**Comment by planteater** [comment]
Thanks @emmeram! It looks like the issue is that submitting a comment takes the focus away from the diff. We'll look into a solution for this, but in the interim you can restore the proper behavior by clicking somewhere in the diff.
