### ISSUE TITLE
Keyboard shortcut for adding comment to GitLab MR review

### ISSUE THREAD

**Issue by emmeram** [TeamCodeStream/codestream#476]
(See attached image)

I'd like to be able to use a keyboard shortcut to add a comment to a GitLab MR review that's in-process. Command-Enter doesn't work.

![Add_To_Review_Button](https://user-images.githubusercontent.com/68029381/113611315-5688f900-961c-11eb-9e31-5fa77c96b22e.png)

**Comment by planteater** [comment]
Fixed in 11.0.4.
