### ISSUE TITLE
Large GitLab MRs not loading all files

### ISSUE THREAD

**Issue by emmeram** [TeamCodeStream/codestream#477]
In large merge requests, CodeStream does not load all files. The number of files shown in CodeStream seems to match the number of files that GitLab restricts to in their UI.

**Comment by marcelofarias** [comment]
@emmeram could you clarify what's the number and whether it's GitLab cloud or on-prem?

**Comment by emmeram** [comment]
It's GitLab cloud. The number seems to be 523. See the attached screenshot.

<img width="1592" alt="Screen Shot 2021-04-06 at 10 44 20" src="https://user-images.githubusercontent.com/68029381/113729506-13369500-96c5-11eb-8c45-40d7b9b242ca.png">

**Comment by planteater** [comment]
@emmeram - It does not appear that GitLab's api will return us all of the files in these scenarios. It seems we'll be limited just as the UI on gitlab.com is. I'm looking into whether or not we can identify this scenario and display some appropriate copy at the top of the Changes tab so that the user understands why they're not seeing all of the files.

**Comment by emmeram** [comment]
Could you use a diff between the source and target branches to build the file list instead of the results coming from the API?

Emmeram Morning
President
http://robotmorning.com
(513) 322-4831 x10
On Apr 14, 2021, 09:09 -0400, David Hersh ***@***.***>, wrote:

@emmeram<https://github.com/emmeram> - It does not appear that GitLab's api will return us all of the files in these scenarios. It seems we'll be limited just as the UI on gitlab.com is. I'm looking into whether or not we can identify this scenario and display some appropriate copy at the top of the Changes tab so that the user understands why they're not seeing all of the files.

**Comment by planteater** [comment]
Possibly, but it would be a pretty big departure from where we're at today. Hopefully GitLab improves their support, but this is something we could explore if that doesn't pan out.

**Comment by planteater** [comment]
@emmeram - Could I trouble to install the following version of our extension and let me know if the Changes tab now gives you an appropriate warning about why all files aren't listed?

https://www.dropbox.com/s/zroq7ijgops2e0b/codestream-jb-11.0.3%2B4014.zip?dl=0

If you don't mind, maybe even share a screenshot here. Thanks!

**Comment by emmeram** [comment]
I don’t appear to be receiving a warning. I have attached a screenshot.

Emmeram Morning
President
http://robotmorning.com
(513) 322-4831 x10
On Apr 15, 2021, 14:01 -0400, David Hersh ***@***.***>, wrote:

@emmeram<https://github.com/emmeram> - Could I trouble to install the following version of our extension and let me know if the Changes tab now gives you an appropriate warning about why all files aren't listed?

https://www.dropbox.com/s/zroq7ijgops2e0b/codestream-jb-11.0.3%2B4014.zip?dl=0

If you don't mind, maybe even share a screenshot here. Thanks!

**Comment by planteater** [comment]
The messaging should now be properly displayed in the latest version of the CodeStream extension (v11.0.3 for JetBrains).
