### ISSUE TITLE
Cannot see GitLab MRs for my review in CodeStream

### ISSUE THREAD

**Issue by emmeram** [TeamCodeStream/codestream#478]
(See attached)

CodeStream doesn’t show any merge requests for my review, but GitLab does. This may have to do with the fact that we do our merge request approvals based on groups, not on individual users. GitLab shows users the merge requests that require an approval from one or more groups that they’re a member of.

![Merge_Requests_My_Review](https://user-images.githubusercontent.com/68029381/113611535-a962b080-961c-11eb-823c-27c770c5addf.png)
![Merge_Requests_My_Review_In_GitLab](https://user-images.githubusercontent.com/68029381/113611541-ab2c7400-961c-11eb-8510-bdeeafde151e.png)

**Comment by planteater** [comment]
@emmeram - I notice that in the GitLab header the Merge Requests icon (towards the right) doesn't have a badge on it, which leads me to think that GitLab also doesn't think that MR has you as a reviewer. If you click on that Merge Requests icon, and then select "Review requests for you", is this MR listed?

Either way, could you click on it and see what the list of reviewers looks like? Thanks!

**Comment by emmeram** [comment]
I see that you're correct; GitLab doesn't show me as reviewer on any merge requests. We don't attach reviewers to MRs, instead setting approval rules and using those to control what approvals an MR must have. Any developer qualified under the rules can then approve. I've attached a screenshot showing what that looks like.

Given the way we handle approvals, it would be nice to see the same merge requests that show when going to a GitLab group's merge requests page within CodeStream.

<img width="1904" alt="Screen Shot 2021-04-06 at 06 00 14" src="https://user-images.githubusercontent.com/68029381/113694933-53cee800-969e-11eb-8725-4a46cc8e0b1c.png">

**Comment by planteater** [comment]
@emmeram - Since you don't use the Reviewer field, I'm guessing you just want to see all open MRs. You can do this by creating a custom query. Just click on the Filter icon in the heading of the Merge Requests section and then use GitLab search syntax to create an "All Open" section (state:opened) that would show you all open MRs.
