### ISSUE TITLE
Feature Request: create patch from feedback request

### ISSUE THREAD

**Issue by 123qweasdzxc32** [TeamCodeStream/codestream#480]
Does CodeStream have the ability to create a git patch (or something similar) from a feedback request? If not that, something where I could easily grab the changes from a feedback request and apply them locally would be acceptable. Thanks!

**Comment by planteater** [comment]
Thanks for the input @123qweasdzxc32! We've been kicking around an idea like this. Nothing officially on the roadmap just yet, but I'll keep you posted.
