### ISSUE TITLE
Feature Request: Starting work on an issue also creates a new changelist in Android Studio

### ISSUE THREAD

**Issue by spyderrsh** [TeamCodeStream/codestream#481]
It would be nice if Codestream managed the changelists so that they don't automatically merge with local (non-committed changes). In this case I have a changelist to modify my environment to work with AS Canary 13, but it's not to be committed into the team repository. When I create a new branch from an issue, it would be nice if it kept that branch in a changelist (as below) so changes don't automatically get mixed with local changes. These could also be reflected in the WIP view as changes pertaining to the current issue being worked on.

![image](https://user-images.githubusercontent.com/3034414/113898746-63772b00-9789-11eb-8fbe-19fb5d6a88db.png)
![image](https://user-images.githubusercontent.com/3034414/113898779-6b36cf80-9789-11eb-9aa4-ec453560c639.png)

**Comment by planteater** [comment]
Great suggestion @spyderrsh! Thanks!
