### ISSUE TITLE
Error loading git info

### ISSUE THREAD

**Issue by wanlinruo** [TeamCodeStream/codestream#483]
![image](https://user-images.githubusercontent.com/21278600/113958153-2aa38880-9853-11eb-83da-3838a74f5bc9.png)
idea-logs：
[idea-logs-20210407-103628.zip](https://github.com/TeamCodeStream/codestream/files/6275568/idea-logs-20210407-103628.zip)

**Comment by planteater** [comment]
@wanlinruo - Can you download the pre-release version of the CodeStream extension from the following URL and let me know if it fixes the issue?

https://www.dropbox.com/s/ssfhba3z1goetti/codestream-jb-11.0.1%2B3963.zip?dl=0

Once you've downloaded the file, you can install it by going to Preferences/Settings > Plugins and then select "Install Plugin from Disk" from the gear menu at the top-right. You'll then need to restart your IDE.

**Comment by planteater** [comment]
@wanlinruo - This issue should be fixed in v11.0.2 of our JetBrains extension (v11.0.3 for VS Code).

**Comment by edsonv** [comment]
Is this issue closed? I'm getting the same error, plus, I cannot create branches from Jira integration but don't Know if these two errors are related
