### ISSUE TITLE
Github PR fails to load if it contains commits that weren't fetched yet

### ISSUE THREAD

**Issue by guyguy2001** [TeamCodeStream/codestream#485]
I tried to enter a PR from this panel, and got an infinite loading screen with the following error:
![image](https://user-images.githubusercontent.com/6932278/114097735-23b75d00-98c9-11eb-8a47-53cd9e608d88.png)
```
Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false cat-file -t 40876aae68846f40343933f17ec198fc06c6903b
fatal: git cat-file: could not get object info

Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false cat-file -t 40876aae68846f40343933f17ec198fc06c6903b
fatal: git cat-file: could not get object info

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at Pipe.<anonymous> (net.js:674:12)
```

It got solved when I ran git fetch; I can confirm it fetched new commits, and that the commit it didn't find (40876aae) wasn't there before the fetch.

I tried to reproduce it in a new repository, but failed to.
The repository I had the bug in is private, in case it is relevant.

**Comment by planteater** [comment]
Could I trouble you to send some agent logs? Reproduce the issue and then open the Output view (“View: Toggle Output” from the command palette) and select "CodeStream (Agent)" from the dropdown menu at the top-right. Copy all of the output you see and save it in a text file.

If you'd prefer not to share the log file here, feel free to send them to me at support@codestream.com. Thanks!

**Comment by guyguy2001** [comment]
I sent it via email, since I didn't have time to eye it all to make sure my API key or any other sensitive information isn't shown there.
However, here is another warning I received that I want to share here so it will show in the search results:
```[2021-04-10 19:26:50:853] GIT: Running(/home/guy/projects/website-for-reference): git rev-parse --abbrev-ref favorite-scripts-update@{u}
[Warn  - 10:26:50 PM] [2021-04-10 19:26:50:854] Error(/home/guy/projects/website-for-reference): /usr/bin/git -c core.quotepath=false -c color.ui=false remote show upstream)
    (128) Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false remote show upstream
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

[2021-04-10 19:26:50:855] GIT: Completed(/home/guy/projects/website-for-reference): git remote show upstream in 7 ms```

**Comment by planteater** [comment]
@guyguy2001 - I'm going to go ahead and close this out for now, but per my last email, if you can get us a new log file (after first reproducing the issue) we'll get this figured out. We were also wondering if there was any chance that the remote in question is configured to require typing a password to fetch?

**Comment by guyguy2001** [comment]
Alright; I'll try to send everything this weekend, sorry for not doing so yet.
The remote is private, so I'm pretty sure it requires a password (at least for the first fetch)
