### ISSUE TITLE
11.0.0 upgrade with Self Host results in "Unexpected error has occured"

### ISSUE THREAD

**Issue by DanubeRS** [TeamCodeStream/codestream#486]
Keenly awaiting 11 and its Gitlab Self-hosted support. Super excited to try it out!

Unfortunately, after upgrade, the following error is displayed in the Rider (2021.1) panel

![image](https://user-images.githubusercontent.com/2668630/114113507-2003f480-9922-11eb-9221-e6135dc3dd8e.png)

Self-host instance details
![image](https://user-images.githubusercontent.com/2668630/114113568-52aded00-9922-11eb-92da-fb53527c9dd5.png)

I have emailed rider logs.

**Comment by marcelofarias** [comment]
Hi @DanubeRS

In addition to the logs you've sent, do you see any errors in the CodeStream webview console? In the list of actions (`ctrl + shift + a` or `cmd + shift + a`, depending on your OS), select "CodeStream: open webview dev tools".
![image](https://user-images.githubusercontent.com/1028286/114116506-d7612280-98b2-11eb-995f-1b838bd93d66.png)

Thanks

**Comment by DanubeRS** [comment]
Sure thing. Log output:

`webview.html:1 Connecting router
webview.html:11 Flushing 1 queued message(s)
webview.html:17 Router connected
webview.js:46 Error: An error occured while selecting the store state: Cannot read property 'name' of undefined.
    at At (webview.js:78)
    at webview.js:78
    at za (webview.js:46)
    at yi (webview.js:46)
    at vi (webview.js:46)
    at gi (webview.js:46)
    at webview.js:46
    at Do (webview.js:46)
    at Mo (webview.js:46)
    at Es (webview.js:46)
Xi @ webview.js:46
i.componentDidCatch.n.callback @ webview.js:46
Yi @ webview.js:46
Ki @ webview.js:46
Ro @ webview.js:46
No @ webview.js:46
(anonymous) @ webview.js:46
t.unstable_runWithPriority @ webview.js:55
ks @ webview.js:46
Es @ webview.js:46
ys @ webview.js:46
Cs @ webview.js:46
notify @ webview.js:78
t.notifyNestedSubs @ webview.js:78
n.notifySubscribers @ webview.js:78
t.handleChangeWrapper @ webview.js:78
o @ webview.js:28
(anonymous) @ webview.js:80
(anonymous) @ webview.js:78
requestAnimationFrame (async)
(anonymous) @ webview.js:78
s @ webview.js:28
a @ webview.js:28
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
(anonymous) @ webview.js:78
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
dispatch @ webview.js:22
(anonymous) @ webview.js:78
(anonymous) @ webview.js:80
dispatch @ webview.js:22
(anonymous) @ webview.js:78
o @ webview.js:78
s @ webview.js:78
Promise.then (async)
o @ webview.js:78
s @ webview.js:78
Promise.then (async)
o @ webview.js:78
s @ webview.js:78
(anonymous) @ webview.js:78
(anonymous) @ webview.js:78
(anonymous) @ webview.js:78
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
o @ webview.js:78
s @ webview.js:78
(anonymous) @ webview.js:78
(anonymous) @ webview.js:78
$K @ webview.js:80
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
o @ webview.js:1
(anonymous) @ webview.js:28
o @ webview.js:1
n @ webview.js:1
(anonymous) @ webview.js:1
(anonymous) @ webview.js:1
webview.js:78 Exception caught in React component tree: An error occured while selecting the store state: Cannot read property 'name' of undefined. {stacktrace: "Error: An error occured while selecting the store …ream13796503305056130455.tmp/webview.js:46:97753)", info: {…}}
Cl @ webview.js:78
componentDidCatch @ webview.js:80
i.componentDidCatch.n.callback @ webview.js:46
Yi @ webview.js:46
Ki @ webview.js:46
Ro @ webview.js:46
No @ webview.js:46
(anonymous) @ webview.js:46
t.unstable_runWithPriority @ webview.js:55
ks @ webview.js:46
Es @ webview.js:46
ys @ webview.js:46
Cs @ webview.js:46
notify @ webview.js:78
t.notifyNestedSubs @ webview.js:78
n.notifySubscribers @ webview.js:78
t.handleChangeWrapper @ webview.js:78
o @ webview.js:28
(anonymous) @ webview.js:80
(anonymous) @ webview.js:78
requestAnimationFrame (async)
(anonymous) @ webview.js:78
s @ webview.js:28
a @ webview.js:28
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
(anonymous) @ webview.js:78
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
dispatch @ webview.js:22
(anonymous) @ webview.js:78
(anonymous) @ webview.js:80
dispatch @ webview.js:22
(anonymous) @ webview.js:78
o @ webview.js:78
s @ webview.js:78
Promise.then (async)
o @ webview.js:78
s @ webview.js:78
Promise.then (async)
o @ webview.js:78
s @ webview.js:78
(anonymous) @ webview.js:78
(anonymous) @ webview.js:78
(anonymous) @ webview.js:78
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
o @ webview.js:78
s @ webview.js:78
(anonymous) @ webview.js:78
(anonymous) @ webview.js:78
$K @ webview.js:80
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
o @ webview.js:1
(anonymous) @ webview.js:28
o @ webview.js:1
n @ webview.js:1
(anonymous) @ webview.js:1
(anonymous) @ webview.js:1
webview.js:46 TypeError: Cannot read property 'name' of undefined
    at ou (webview.js:78)
    at iu (webview.js:78)
    at webview.js:78
    at webview.js:78
    at webview.js:78
    at webview.js:78
    at webview.js:78
    at Function.jt.fetchDocumentMarkers [as mapToProps] (webview.js:80)
    at r (webview.js:78)
    at Function.r.mapToProps (webview.js:78)
Xi @ webview.js:46
i.componentDidCatch.n.callback @ webview.js:46
Yi @ webview.js:46
Ki @ webview.js:46
Ro @ webview.js:46
No @ webview.js:46
(anonymous) @ webview.js:46
t.unstable_runWithPriority @ webview.js:55
ks @ webview.js:46
Es @ webview.js:46
ys @ webview.js:46
Cs @ webview.js:46
notify @ webview.js:78
t.notifyNestedSubs @ webview.js:78
n.notifySubscribers @ webview.js:78
t.handleChangeWrapper @ webview.js:78
o @ webview.js:28
(anonymous) @ webview.js:80
(anonymous) @ webview.js:78
requestAnimationFrame (async)
(anonymous) @ webview.js:78
s @ webview.js:28
a @ webview.js:28
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
(anonymous) @ webview.js:78
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
dispatch @ webview.js:22
(anonymous) @ webview.js:78
(anonymous) @ webview.js:80
dispatch @ webview.js:22
(anonymous) @ webview.js:78
o @ webview.js:78
s @ webview.js:78
Promise.then (async)
o @ webview.js:78
s @ webview.js:78
Promise.then (async)
o @ webview.js:78
s @ webview.js:78
(anonymous) @ webview.js:78
(anonymous) @ webview.js:78
(anonymous) @ webview.js:78
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
o @ webview.js:78
s @ webview.js:78
(anonymous) @ webview.js:78
(anonymous) @ webview.js:78
$K @ webview.js:80
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
o @ webview.js:1
(anonymous) @ webview.js:28
o @ webview.js:1
n @ webview.js:1
(anonymous) @ webview.js:1
(anonymous) @ webview.js:1
webview.js:78 Exception caught in React component tree: Cannot read property 'name' of undefined {stacktrace: "TypeError: Cannot read property 'name' of undefine…eam13796503305056130455.tmp/webview.js:78:143162)", info: {…}}
Cl @ webview.js:78
componentDidCatch @ webview.js:80
i.componentDidCatch.n.callback @ webview.js:46
Yi @ webview.js:46
Ki @ webview.js:46
Ro @ webview.js:46
No @ webview.js:46
(anonymous) @ webview.js:46
t.unstable_runWithPriority @ webview.js:55
ks @ webview.js:46
Es @ webview.js:46
ys @ webview.js:46
Cs @ webview.js:46
notify @ webview.js:78
t.notifyNestedSubs @ webview.js:78
n.notifySubscribers @ webview.js:78
t.handleChangeWrapper @ webview.js:78
o @ webview.js:28
(anonymous) @ webview.js:80
(anonymous) @ webview.js:78
requestAnimationFrame (async)
(anonymous) @ webview.js:78
s @ webview.js:28
a @ webview.js:28
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
(anonymous) @ webview.js:78
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
dispatch @ webview.js:22
(anonymous) @ webview.js:78
(anonymous) @ webview.js:80
dispatch @ webview.js:22
(anonymous) @ webview.js:78
o @ webview.js:78
s @ webview.js:78
Promise.then (async)
o @ webview.js:78
s @ webview.js:78
Promise.then (async)
o @ webview.js:78
s @ webview.js:78
(anonymous) @ webview.js:78
(anonymous) @ webview.js:78
(anonymous) @ webview.js:78
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
o @ webview.js:78
s @ webview.js:78
(anonymous) @ webview.js:78
(anonymous) @ webview.js:78
$K @ webview.js:80
(anonymous) @ webview.js:80
(anonymous) @ webview.js:80
o @ webview.js:1
(anonymous) @ webview.js:28
o @ webview.js:1
n @ webview.js:1
(anonymous) @ webview.js:1
(anonymous) @ webview.js:1
`

Isolated a react bubbled exception
![image](https://user-images.githubusercontent.com/2668630/114126428-bf81b100-993b-11eb-9761-ea78fb3195d9.png)

**Comment by marcelofarias** [comment]
Thanks @DanubeRS! If possible, could you copy the contents of the `stacktrace` property please?

**Comment by DanubeRS** [comment]
Sure, hopefully this is what you are after @marcelofarias
```
{
   "stacktrace":"Error: An error occured while selecting the store state: Cannot read property 'name' of undefined.\n    at At (file:///var/folders/kp/w252s7f12bjc_jhl4qbdgnmm0000gn/T/codestream13796503305056130455.tmp/webview.js:78:150221)\n    at file:///var/folders/kp/w252s7f12bjc_jhl4qbdgnmm0000gn/T/codestream13796503305056130455.tmp/webview.js:78:1202283\n    at za (file:///var/folders/kp/w252s7f12bjc_jhl4qbdgnmm0000gn/T/codestream13796503305056130455.tmp/webview.js:46:51776)\n    at yi (file:///var/folders/kp/w252s7f12bjc_jhl4qbdgnmm0000gn/T/codestream13796503305056130455.tmp/webview.js:46:58573)\n    at vi (file:///var/folders/kp/w252s7f12bjc_jhl4qbdgnmm0000gn/T/codestream13796503305056130455.tmp/webview.js:46:58392)\n    at gi (file:///var/folders/kp/w252s7f12bjc_jhl4qbdgnmm0000gn/T/codestream13796503305056130455.tmp/webview.js:46:58111)\n    at file:///var/folders/kp/w252s7f12bjc_jhl4qbdgnmm0000gn/T/codestream13796503305056130455.tmp/webview.js:46:90044\n    at Do (file:///var/folders/kp/w252s7f12bjc_jhl4qbdgnmm0000gn/T/codestream13796503305056130455.tmp/webview.js:46:90345)\n    at Mo (file:///var/folders/kp/w252s7f12bjc_jhl4qbdgnmm0000gn/T/codestream13796503305056130455.tmp/webview.js:46:90727)\n    at Es (file:///var/folders/kp/w252s7f12bjc_jhl4qbdgnmm0000gn/T/codestream13796503305056130455.tmp/webview.js:46:97753)",
   "info":{
      "componentStack":"\n    in Unknown\n    in div\n    in t\n    in styled.div\n    in nq\n    in div\n    in t\n    in styled.div\n    in div\n    in t\n    in styled.div\n    in Unknown\n    in div\n    in b$\n    in injectIntl(b$)\n    in m\n    in Unknown\n    in m\n    in zE\n    in t\n    in t\n    in IntlProvider\n    in eK"
   }
}
```

**Comment by marcelofarias** [comment]
I believe we are close, @DanubeRS. Based on the screenshot you posted, I believe there is at least one more exception in the console. If so, could you get the same information for the other exception(s) please? Thanks!

**Comment by DanubeRS** [comment]
Ah yes

```
{
   "stacktrace":"Error: An error occured while selecting the store state: Cannot read property 'name' of undefined.\n    at At (file:///var/folders/kp/w252s7f12bjc_jhl4qbdgnmm0000gn/T/codestream2271101809758027563.tmp/webview.js:78:150221)\n    at file:///var/folders/kp/w252s7f12bjc_jhl4qbdgnmm0000gn/T/codestream2271101809758027563.tmp/webview.js:78:1202283\n    at za (file:///var/folders/kp/w252s7f12bjc_jhl4qbdgnmm0000gn/T/codestream2271101809758027563.tmp/webview.js:46:51776)\n    at yi (file:///var/folders/kp/w252s7f12bjc_jhl4qbdgnmm0000gn/T/codestream2271101809758027563.tmp/webview.js:46:58573)\n    at vi (file:///var/folders/kp/w252s7f12bjc_jhl4qbdgnmm0000gn/T/codestream2271101809758027563.tmp/webview.js:46:58392)\n    at gi (file:///var/folders/kp/w252s7f12bjc_jhl4qbdgnmm0000gn/T/codestream2271101809758027563.tmp/webview.js:46:58111)\n    at file:///var/folders/kp/w252s7f12bjc_jhl4qbdgnmm0000gn/T/codestream2271101809758027563.tmp/webview.js:46:90044\n    at Do (file:///var/folders/kp/w252s7f12bjc_jhl4qbdgnmm0000gn/T/codestream2271101809758027563.tmp/webview.js:46:90345)\n    at Mo (file:///var/folders/kp/w252s7f12bjc_jhl4qbdgnmm0000gn/T/codestream2271101809758027563.tmp/webview.js:46:90727)\n    at Es (file:///var/folders/kp/w252s7f12bjc_jhl4qbdgnmm0000gn/T/codestream2271101809758027563.tmp/webview.js:46:97753)",
   "info":{
      "componentStack":"\n    in Unknown\n    in div\n    in t\n    in styled.div\n    in nq\n    in div\n    in t\n    in styled.div\n    in div\n    in t\n    in styled.div\n    in Unknown\n    in div\n    in b$\n    in injectIntl(b$)\n    in m\n    in Unknown\n    in m\n    in zE\n    in t\n    in t\n    in IntlProvider\n    in eK"
   }
}
```

**Comment by planteater** [comment]
@DanubeRS - We think we might have a fix for this. Can I trouble you to download the extension from the following URL and give it a shot?

https://www.dropbox.com/s/meqq2dm8qwno18v/codestream-jb-11.0.1%2B3967.zip?dl=0

Once you've downloaded the file, you can install it by going to Preferences/Settings > Plugins and then select "Install Plugin from Disk" from the gear menu at the top-right. You'll then be prompted to restart your IDE.

Let me know how it goes! Thanks.

**Comment by planteater** [comment]
Actually @DanubeRS use this one instead:

https://www.dropbox.com/s/zyhz73d6oc5cww7/codestream-jb-11.0.1%2B3972.zip?dl=0

- Sign out of CodeStream by using the "CodeStream: Sign out" action in your IDE's actions list (cmd + shif + a)
- Uninstall CodeStream, and then install again using the version at the link above.
- See if the problem persists.

Note that this is a special build that should definitely give us some insight into what's going on. But, it will probably be very slow, so you won't want to keep using on an ongoing basis.

**Comment by planteater** [comment]
OK, I'm cautiously optimistic that we've got an actual fix this time. Here's another update to the extension. Let me know how it goes!

https://www.dropbox.com/s/um0w8l7ml8u07df/codestream-jb-11.0.1%2B3976.zip?dl=0

**Comment by DanubeRS** [comment]
Yep, that looks to have worked (as in the sidebar content starts to load) but now there seems to be another error occuring.

[-1618177573500.log](https://github.com/TeamCodeStream/codestream/files/6292832/-1618177573500.log)

An example of a timestamp that has failed formatting

`2021-02-01T13:10:33.532+10:00` 
i.e:
```
new Intl.DateTimeFormat("en", {
				day: "numeric",
				month: "short",
				year: "2-digit"
			})
				.format("2021-02-01T13:10:33.532+10:00")
				.replace(/(\d\d)$/, `'$1`);
```

**Comment by planteater** [comment]
@DanubeRS - This has (finally!) been fixed in v11.0.2 of our extension for JetBrains. It has to go through the JetBrains approval process, which usually takes 24 hours. But if you don't want to wait you can download it here:

https://www.dropbox.com/s/plb8e4pohe3p3oq/codestream-jb-jcef-11.0.2%2B140.zip?dl=0

Thanks for your patience!

**Comment by DanubeRS** [comment]
Awesome, tested and now cooking with gas! Thanks for the help.

**Comment by planteater** [comment]
v11.0.2 of the JetBrains extension is now available in the marketplace.
