### ISSUE TITLE
MR Query for `scope:all` does not work in 11.0 for gitlab.com

### ISSUE THREAD

**Issue by patmuk** [TeamCodeStream/codestream#487]
in codestream 11.0  
In Merge Requests, connected to a hosted gitlab.com (free) project,  
creating a `New Merge Request Query` with `scope:all` does not work.

(On Mac OS 11.2.3 if that matters.)

**Comment by planteater** [comment]
@patmuk - I just did a quick test and a scope=all query seemed to return results for me. Obviously we have that other issue you reported about not being able to save queries, but I used the Test Query button and did get results. I assume that Test Query didn't return anything for you in this case?

**Comment by patmuk** [comment]
ah, that is an interesting issue :)  
`scope=all` works for me as well, but `scope:all` does not!  
(Notice `=` vs `:`).

`:` seems to be the syntax for the other attributes, `scope:created_by_me` is the example line. Typo here?

**Comment by patmuk** [comment]
Forgot to answer on your direct question: Yes, with `scope:all` the test query button showed the spinner for a while and just returned to show the label, without any results - not even showing `NO MRs match this query`.

**Comment by patmuk** [comment]
Oh, I just saw that my complete query works only as `scope=all wip:no state=opened`, but not `scope:all wip=no state:opened`.  
Is it string vs boolean?  
Or an unintended inconsistency?

**Comment by patmuk** [comment]
Now in Version 11.0.4 (and maybe before as well) it does not work as intended.
`scope:all` does not return any results, as described above, but
`scope=all` does not return all results. It returns the same results as `scope:created_by_me`.
I assume the `=` instead `:` is the root error.

**Comment by planteater** [comment]
We've got a fix coming for this in our next release. Should be in the next couple of days.

**Comment by patmuk** [comment]
Great! Thanks.

**Comment by planteater** [comment]
@patmuk - Unfortunately, it looks like we're blocked here by a known GitLab issue.  

https://gitlab.com/gitlab-org/gitlab/-/issues/22699

**Comment by dpalita** [comment]
I got it working with "Only show PRs from open repos" checked + custom query `state:opened`.

NB : I also get 500 errors with the direct use of the api (eg in postman) if I do not specify the project id, which I guess is what happens when you activate the "Only show..." checkbox.

**Comment by patmuk** [comment]
Works for me as well, thanks!
