### ISSUE TITLE
Save custom MRs in 11.0 does not work

### ISSUE THREAD

**Issue by patmuk** [TeamCodeStream/codestream#488]
in codestream 11.0
In Merge Requests, connected to a hosted gitlab.com (free) project,
Saving a  `New Merge Request Query` does not work.
`test query` works fine,  
`save query` does not complain,  
but the query is not listed in the list of default queries.

(On Mac OS 11.2.3 if that matters.)

**Comment by planteater** [comment]
Thanks for the report @patmuk! We'll get on this asap.

**Comment by planteater** [comment]
Fixed in CodeStream 11.0.2.
