### ISSUE TITLE
IntelliJ: Starting work on issue and creating branch does not update UI

### ISSUE THREAD

**Issue by pepijnve** [TeamCodeStream/codestream#490]
Scenario:

1. Choose an issue from the Issues section
2. Choose 'start work' and make sure the 'create new branch' option is selected

Expected result:

IntelliJ shows the newly created branch as the current branch and the branch is visible in the version control (Git in my case) log view

Actual result:

The branch is created and has been checked out, but this is not reflected in the UI. Pressing the 'refresh' button in the Git log view gets things back in sync. It would be nice if the codestream plugin code trigger this automatically.

**Comment by planteater** [comment]
@pepijnve - We're looking into whether or not there's a way for us to force the IDE to recognize the branch change, but in the interim it appears that a change in focus will trigger.

**Comment by planteater** [comment]
Fixed in v11.0.12
