### ISSUE TITLE
Documentation Request: How to leave a team

### ISSUE THREAD

**Issue by thedelk** [TeamCodeStream/codestream#492]
There is currently no obvious or documented way for a developer to leave a team. I am still part of my former employer's team and am still receiving weekly update emails, and I can still see team activity in the CodeStream extension in VS Code.

I can't see actual code diffs (though I can see diff _counts_), but I imagine being able to view the names/aliases of new developers and code commit messages is a security issue.

Please advise.

**Comment by planteater** [comment]
@thedelk - I'm going to go ahead and close this, but go ahead and add a reply here or email me at support@codestream.com if you'd like me to remove you from the former employer's team, or delete your account entirely.

**Comment by thedelk** [comment]
In my case, I was discharged from my position, so it's not exactly feasible for me to be in contact with the team owner.

If you could remove me from my former employer's team that would be great; I just imagine my case isn't the only scenario in which it might not be reasonable to contact CodeStream or the original team owner to be removed.

Thank you for your help.

**Comment by planteater** [comment]
All set @thedelk
