### ISSUE TITLE
Visual Studio 2019 transparent background

### ISSUE THREAD

**Issue by aguycalledpete** [TeamCodeStream/codestream#494]
After installing the extension for Visual Studio 2019 and logging in through GitLab I could successfully see codemarks, feedback requests etc. However, while testing how I could use the extension I have found that when I click to open a codemark or feedback request, the background of the new window which opens in the extension is transparent making the details difficult to read.
![2021-04-13 09_19_03-Clipboard](https://user-images.githubusercontent.com/66066155/114520461-5d75c400-9c39-11eb-8bfd-d829374f6e0e.png)

**Comment by planteater** [comment]
@aguycalledpete - Are you running v11.0.3 of the CodeStream extension? This issue should be fixed in the latest release.

**Comment by aguycalledpete** [comment]
I have updated to the newer version of the extension now and this issue has been fixed, thanks 👍
