### ISSUE TITLE
Request codestream/provider/generic failed with message: Cannot read property 'full' of undefined

### ISSUE THREAD

**Issue by Callanna** [TeamCodeStream/codestream#496]
<img width="756" alt="image" src="https://user-images.githubusercontent.com/14858726/114646047-207b0180-9d0d-11eb-886d-f1475c3062c2.png">
loading url :
<img width="753" alt="image" src="https://user-images.githubusercontent.com/14858726/114645927-e7429180-9d0c-11eb-9a95-1f8c43733a2a.png">

**Comment by Callanna** [comment]
codestream version is 11.0.2

**Comment by ppezaris** [comment]
Do you know which version of GitLab you are using?

**Comment by Callanna** [comment]
<img width="604" alt="image" src="https://user-images.githubusercontent.com/14858726/114662652-a73ed700-9d2b-11eb-97ca-787c3f2b240d.png">

**Comment by Callanna** [comment]
[Uploading studio-logs-20210414-141505.zip…]()

**Comment by Callanna** [comment]
[studio-logs-20210414-141505.zip](https://github.com/TeamCodeStream/codestream/files/6308565/studio-logs-20210414-141505.zip)

**Comment by planteater** [comment]
Are you able to update your installation to a more recent version? I’m not sure we’re going to be able to support anything older than 12.X.

**Comment by Callanna** [comment]
Gitlab should not be upgraded anytime soon

**Comment by planteater** [comment]
Thanks @Callanna - I'll see what we can do.

**Comment by dyxushuai** [comment]
Same issue and Gitlab version 11.4.0

**Comment by caandspb** [comment]
Same issue, Gitlab version 12.2.0-ee

**Comment by krishnaraj** [comment]
Not sure if this is related but getting the following error when used with Gitlab community edition 13.0.6

`Request codestream/provider/generic failed with message: Cannot read property 'indexOf' of null`

**Comment by planteater** [comment]
@krishnaraj - I think that's probably a separate issue. Could I trouble you for an agent log file? You can send it to me at support@codestream.com. Thanks!

https://docs.codestream.com/userguide/faq/client-logs/

**Comment by planteater** [comment]
Hi folks - After some considerable effort, we've determined that it's not realistic for us to support versions of GitLab Self Managed older than 12.10. There are just too many properties missing from earlier versions for us to be able to work around. 12.10 is also the earliest version in the 12 series that GitLab still supports.

We do still have some work to do to get things completely working in 12.10, but that should be ready in this week's release.

**Comment by realgs** [comment]
same thing, GitLab Community Edition [v16.0.1] :/

**Comment by planteater** [comment]
@realgs - Next time this happens can you grab a log file and send it to me at codestream@newrelic.com? Thanks!

https://docs.newrelic.com/docs/codestream/troubleshooting/client-logs/
