### ISSUE TITLE
The user headimg  loading error,Text in the wrong line

### ISSUE THREAD

**Issue by Callanna** [TeamCodeStream/codestream#497]
<img width="478" alt="image" src="https://user-images.githubusercontent.com/14858726/114647311-781a6c80-9d0f-11eb-9950-59d24fab666b.png">

**Comment by planteater** [comment]
@Callanna - Is that the only place where the headshot image from gravatar isn't rendering, or is it broken everywhere? For example, check your profile. Or replies in a codemark/feedback request thread.

**Comment by Callanna** [comment]
broken everywhere ! the gravatar isn't rendering,

**Comment by planteater** [comment]
Gotcha. Looks like this is a duplicate of https://github.com/TeamCodeStream/codestream/issues/454

Can you follow that issue? I'll update things over there.
