### ISSUE TITLE
GitLab MR doesn't show commits created after MR is added

### ISSUE THREAD

**Issue by EriBloo** [TeamCodeStream/codestream#498]
When I add new MR all commits are showing properly, but when I later commit to the same branch new commits are not displayed.

That is the last commit in Codestream:
![image](https://user-images.githubusercontent.com/19932449/114711165-ed496a00-9d2e-11eb-9573-6335d75ea60b.png)
While in reality it should be:
![image](https://user-images.githubusercontent.com/19932449/114711255-08b47500-9d2f-11eb-9169-0161e2b5c16f.png)

Please note that number of new commits is correct. Changes in files also display properly.

**Comment by planteater** [comment]
@EriBloo - Just to confirm, if you click the Refresh button in the MR sidebar, the commits still don't appear?

**Comment by EriBloo** [comment]
> @EriBloo - Just to confirm, if you click the Refresh button in the MR sidebar, the commits still don't appear?

Yes, this state is after refreshing.

**Comment by planteater** [comment]
Fixed in 11.0.5 for VS Code / 11.0.4 for JetBrains.
