### ISSUE TITLE
Display issues on JetBrains/Linux/4k

### ISSUE THREAD

**Issue by spyderrsh** [TeamCodeStream/codestream#499]
On some of my screens the font size for CodeStream gets tiny. Just wondering if you can add the option to increase the font size.

**Comment by planteater** [comment]
@spyderrsh - Any chance your running linux and on a 4k monitor? We've got some known issues with the JetBrains/linux/4k combination. In fact, we've opened up an issue with JetBrains on this if you want to upvote it...

https://youtrack.jetbrains.com/issue/IDEA-266671
