### ISSUE TITLE
Feature Request: Add checkbox option on Gitlab MR View for VSCode

### ISSUE THREAD

**Issue by belfortmaycon** [TeamCodeStream/codestream#500]
Today, when using checkbox option on web Gitlab MR description, on VSCode it shows just the markdown.

Example of MR Description markdown:

```md
- [ ] Some text
- [x] Some text
```
To check it in VSCode I must edit the MR and insert `x` for the "checkbox"

**Comment by planteater** [comment]
Thanks for the feedback @belfortmaycon. I'm not sure if GitLab's api supports checkbox states yet, but we'll see if we can figure something out.

**Comment by belfortmaycon** [comment]
Hi @planteater, would not be like a frontend perspective and send to api like a description update? Today on Gitlab, if click on checkbox on description a new "comment" is added to the MR activity, same happens when click to edit the description and change the `[ ]` to `[x]`. 

This already happen when doing the same edit step on CodeStream
