### ISSUE TITLE
Bug: Comments been add as Review on Gitlab MR Review changes on VSCode

### ISSUE THREAD

**Issue by belfortmaycon** [TeamCodeStream/codestream#501]
When open a Gitlab MR on VScode and go to `Changes` tab, any comment added create a separated review thread.

In my perspective, should be 2 different steps: Add just a comment and add a review thread. 

Also couldn't understand the how the button `Review Changes` works since each comment already start a new review thread.

![image](https://user-images.githubusercontent.com/74875894/114761703-3c939880-9d37-11eb-9920-cc1897b5b56c.png)

The expected behavior is that I could add only comment without start a unresolved thread and bulk the submit review changes like in Gitlab Web.

Thanks

**Comment by planteater** [comment]
Good catch @belfortmaycon! Looks like we have a little bleed over from out GitHub functionality. GitHub has the notion of submitting a review without any actual code comments. This doesn't exist on GitLab, and that button is only to submit a review once there are pending comments. We should probably just not show it until there's at least one pending comment.

**Comment by belfortmaycon** [comment]
Hi @planteater, also Gitlab has comments without requesting a code review. Maybe on comment dialog add the option to add comment that needs a review or just a comment

**Comment by planteater** [comment]
@belfortmaycon - We already support that. When you comment on code you can add comment or start/add to review. Just like on GitLab. What GitLab doesn’t have is the notion of a review without code comments.

**Comment by belfortmaycon** [comment]
> @belfortmaycon - We already support that. When you comment on code you can add comment or start/add to review. Just like on GitLab. What GitLab doesn’t have is the notion of a review without code comments.

Yes @planteater but when add the comment with a code block is creating as a review thread on Gitlab with a pending `Resolve Thread`.

On VSCODE:
![image](https://user-images.githubusercontent.com/74875894/114876994-4075f800-9dd5-11eb-9c39-110a9a5332fc.png)

On MR:
![image](https://user-images.githubusercontent.com/74875894/114877442-a95d7000-9dd5-11eb-97f7-95610ec104fc.png)

Because that I have opened as a Bug

**Comment by planteater** [comment]
I'll admin to not being a GitLab expert, but i think this is consistent with how GitLab does things. On GitLab, if I add a comment using the "Add comment now" option, that does still create a thread that can be resolved, even though it's not part of a review.

**Comment by belfortmaycon** [comment]
> I'll admin to not being a GitLab expert, but i think this is consistent with how GitLab does things. On GitLab, if I add a comment using the "Add comment now" option, that does still create a thread that can be resolved, even though it's not part of a review.

You right @planteater! If selecting any code block it add as a review thread and if any code block is selected it is a normal commnet.

Thanks!
