### ISSUE TITLE
Using color on datasources problem

### ISSUE THREAD

**Issue by marconst** [TeamCodeStream/codestream#505]
if i activate a color on a datasource (right mouse click -> color settings) it looks like this:

![image](https://user-images.githubusercontent.com/5818157/114849821-6f459b80-9de0-11eb-8858-259c9b196201.png)

ps: nice theme :)

**Comment by planteater** [comment]
@marconst - Is this issue related to the CodeStream extension (codestream.com) in any way?

**Comment by marconst** [comment]
haha I'm sorry wrong repo.
