### ISSUE TITLE
Feature Request: Don't reset scroll position when switching tabs

### ISSUE THREAD

**Issue by FFdhorkin** [TeamCodeStream/codestream#506]
If I scroll down on the comments tab, then switch to the commits or diff tabs, then switch back, it resets my scroll position.

In a review with a large number of comments, this can be quite disruptive and frustrating.

I'd like to see scroll position preserved, so that I don't have to hunt for the comment I was last looking at.

**Comment by planteater** [comment]
@FFdhorkin - This has been release in v11.0.7 of the CodeStream extension.
