### ISSUE TITLE
Jetbrains, PHPStorm - not able to set comment bookmark or permalink in v0.52.3+1

### ISSUE THREAD

**Issue by thorsten-weber** [TeamCodeStream/CodeStream#52]
Everything is loading and showing as expected.
Just by selecting code an either using shortcut or icon for "Comment", "Bookmark" "Issue" or "Permalink" nothing happens further.

There is just the pane showing like you may see in the screenshot
![dev - PhpStorm](https://user-images.githubusercontent.com/20163921/57070109-bb23d680-6cd6-11e9-8cc6-c96164cbc328.png)

I have seen this working here in a previous version. I update freshly this morning, and I am sure it worked until then.

**Comment by marcelofarias** [comment]
Could you send us you idea.log file? Either post it here or send to support@codestream.com.

Log files can be obtained via Help -> Compress Logs and Show in ...
https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

**Comment by marcelofarias** [comment]
Also, does it work after an IDE restart?

**Comment by thorsten-weber** [comment]
> Could you send us you idea.log file? Either post it here or send to [support@codestream.com](mailto:support@codestream.com).
> 
> Log files can be obtained via Help -> Compress Logs and Show in ...
> https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

I sent an email to support with the logs

**Comment by thorsten-weber** [comment]
> Also, does it work after an IDE restart?

No, after restarting nothing was changed. I tried two or three times.

**Comment by thorsten-weber** [comment]
I maybe found an clue.
I was working on a systemd service template file.
They are named like "name-of-service@.service" for multi-instance services.

Maybe it was the filename who is invoking these problems?

I tried now another template file, where codestream seems to work fine!

**Comment by marcelofarias** [comment]
I had literally just sent you an e-mail asking if it works on files without the @ character in the name/path!

Working on a fix now. Thanks for the information :)

**Comment by akonwi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GH #52](https://trello.com/c/Ijf1SJxe/1699-gh-52)

**Comment by marcelofarias** [comment]
Fixed on v0.53.0+1
