### ISSUE TITLE
Commenting on GitLab MR yields wrong diff for comment

### ISSUE THREAD

**Issue by iammathew** [TeamCodeStream/codestream#522]
Hey CodeStream-Team,

I have the following issue when reviewing MRs in VSCode using CodeStream (on GitLab):

Every time I select only one line to comment on, Codestream adds multiple lines on top to the comment :)

It seems to always choose the 8 lines above (incl. the first line you chose, regardless of the number of lines chosen in the UI). Especially on multiline comments, this is confusing behavior! In the UI during commenting, everything is displayed correctly.

Otherwise great extension and service :)

**Comment by planteater** [comment]
Thanks for the report @iammathew! I did a little test and it seems like we're replicating the behavior you would see if you commented via gitlab directly. See my example in the screenshot below. But, let me know if I'm not following the correct steps to reproduce. Maybe send a similar comparison screenshot to highlight the issue? Thanks!

![Screen Shot 2021-04-22 at 9 11 18 AM](https://user-images.githubusercontent.com/3442587/115720975-90ac0780-a34b-11eb-8a6c-ba0d29a69ebc.png)

**Comment by planteater** [comment]
@iammathew - Just wanted to follow up on my last reply. Thanks!

**Comment by iammathew** [comment]
@planteater Thanks for such a quick response, didn't get around to answer In time.
Indeed the behavior is the same to GitLab on a single line comment :)

I re-checked and what threw me off is the diverging behavior on multi-line comments.
When commenting multi-line in GitLab it will ensure all of them are visible on the comment, when doing the same through CodeStream it will act the same like you just commented on the first line of the multi-line comment, therefore not showing all the selected lines, in comparison to doing it directly on GitLab.

Will add pictures here in the evening :)

**Comment by planteater** [comment]
@iammathew - Thanks for the clarification! I see the issue now.

**Comment by planteater** [comment]
Fixed in v11.0.9
