### ISSUE TITLE
Availability of Discord Server as Messaging Providers

### ISSUE THREAD

**Issue by SyedUmerHasan** [TeamCodeStream/codestream#526]
I am looking for a solution within codestream to send notifications on the discord server
Like you can see, we can send notifications to slack, I am looking for an option to send messages likewise. 
Thanks 

![image](https://user-images.githubusercontent.com/24965764/115972606-d09c0600-a568-11eb-8cb4-1b1bafbad1b9.png)

**Comment by planteater** [comment]
@SyedUmerHasan - Thanks for the input! I think this is largely covered by the following issue though so I'm going to close this one as a duplicate.

https://github.com/TeamCodeStream/codestream/issues/58
