### ISSUE TITLE
support exclude files by pattern

### ISSUE THREAD

**Issue by AlexElin** [TeamCodeStream/codestream#527]
Currently the plugin supports exclusion only whole directions.
It'd be good for the plugin to support exclusion specifcs files by pattern.

For example, there's an Angular project. I want to exclude test files which have names like lalala._spec.ts_
There's no a dir only, so I can't use existing functionality "Exclude directories"

**Comment by planteater** [comment]
@AlexElin - Just to confirm, you're referring to the .codestreamignore file we leverage in feedback requests? Assuming so, it should support the use of wildcards. Did that not work for you?

**Comment by planteater** [comment]
@AlexElin - Just wanted to follow up on my previous reply. Thanks!

**Comment by planteater** [comment]
@AlexElin - I'm going to go ahead and close this out, but feel free to re-open if you get a chance to respond to my questions above. You can also email me directly at support@codestream.com.
