### ISSUE TITLE
IntelliJ - "Do not have the repo open"

### ISSUE THREAD

**Issue by rblalock** [TeamCodeStream/CodeStream#53]
<img width="479" alt="Screen Shot 2019-05-04 at 9 47 09 PM" src="https://user-images.githubusercontent.com/211819/57186997-840c1b80-6eb6-11e9-97df-b00ca821797b.png">

In Intellij, the comments do not show up but I can go to the channel and see them.  When I click on one I get the message "You dn't currently have the repo open".  I'm not sure what that means.  

Also, it works fine in VSCode.

**Comment by marcelofarias** [comment]
Could you send your idea log files to support@codestream.com?

Log files can be obtained via Help -> Compress Logs and Show in ...
https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

**Comment by marcelofarias** [comment]
Also, if you open the respective file, do you see the Codemark in the spatial view?

**Comment by planteater** [comment]
To clarify that last comment from Marcelo, he's referring to the "Current File" tab. The leftmost one in the CodeStream global nav.

**Comment by rblalock** [comment]
Following up on this.  I do not experience this behavior anymore.  I was able to work around this by closing the file and reopening and it worked fine.
