### ISSUE TITLE
Request codestream/provider/generic failed with message: GitLab Self-Managed 11.3.0 is not yet suppoted

### ISSUE THREAD

**Issue by CaJR8023** [TeamCodeStream/codestream#530]
Request codestream/provider/generic failed with message: GitLab Self-Managed 11.3.0 is not yet suppoted

**Comment by planteater** [comment]
@CaJR8023 - Unfortunately, we've determined that we aren't able to support instances of GitLab Self Managed older than v12.10. There are simply too many properties that aren't available in the old versions.
