### ISSUE TITLE
Gitlab MR view: show the number of added/removed lines

### ISSUE THREAD

**Issue by evll** [TeamCodeStream/codestream#532]
It would be extremely useful to see the number of removed/added lines (or maybe even some additional markings for newly added/removed files) in the Gitlab MR view.

Compare the view from Gitlab's web interface

![image](https://user-images.githubusercontent.com/9748640/116510526-b8f8b080-a8cd-11eb-83ee-8de6629a1176.png)

with

![image](https://user-images.githubusercontent.com/9748640/116510598-d594e880-a8cd-11eb-840e-057bac72f7ea.png)

**Comment by planteater** [comment]
Great suggestion @evll! I'll see if we can get this onto the roadmap.
