### ISSUE TITLE
Issue with reviewing changes (GitLab Self Managed)

### ISSUE THREAD

**Issue by trompj** [TeamCodeStream/codestream#534]
Not entirely sure what's happening here... I can see/do essentially everything except actually viewing changes/reviewing them on MRs. I can click the link to go to GitLab and see the ticket, but not actually view through CodeStream. Wondering if you have any insight into this or if it is a known issue? Doesn't seem to be though. I thought it may be an authentication issue at first, but I can see everything else...

Error Loading Pull Request:
Internal server error: {"response":{"errors":[{"message":"Internal server error"}],"status":500},"request":{"query":"query GetPullRequest($fullPath: ID!, $iid: String!) { project(fullPath: $fullPath) { mergeRequest(iid: $iid) { headPipeline { id sha status stages { nodes { name detailedStatus { label tooltip } } } detailedStatus { favicon icon label text tooltip } } assignees(last: 100) { nodes { id name login: username avatarUrl } } participants(last: 100) { nodes { id name login: username avatarUrl } } labels(last: 15) { nodes { id color title } } currentUserTodos(state: pending, last: 1) { nodes { body id targetType state } } } }}",

**Comment by planteater** [comment]
@trompj - Can you let me know which version of GitLab Self Managed you're running? If you add /api/v4/version to the end of the URL for your GitLab Self-Managed instance the resulting page will show you your version information. Thanks!

**Comment by trompj** [comment]
{"version":"13.9.2-ee","revision":"2817b49bf5d"}

**Comment by planteater** [comment]
Thanks @trompj! When you have a sec, could I also trouble you for a log file? Reproduce the issue and then in your IDE go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file.

If you'd prefer not to share that file here, feel free to send it to me at support@codestream.com.

**Comment by planteater** [comment]
@trompj - Just wanted to follow up to see if we could get that log file. Thanks!

**Comment by trompj** [comment]
@planteater I just sent a clean log file after performing the error action.

**Comment by trompj** [comment]
@planteater I am going to close this issue. It was actually an issue with a missing IntelliJ update. Just updated that and CodeStream today and the requests are returning properly. Thanks for your assistance!
