### ISSUE TITLE
Are bitbucket PRs supported?

### ISSUE THREAD

**Issue by JP01** [TeamCodeStream/codestream#538]
We are using bitbucket server and wanting to try out an onprem installation of codestream.

According to the docs, bitbucket PRs are not supported:
"""
Reviewing a pull request
The ability to review pull requests is currently not available for Bitbucket.
"""
https://docs.codestream.com/userguide/workflow/pull-requests/

But this page seems to suggest it's possible
https://www.codestream.com/integrations/bitbucket

Could this be clarified please :)

**Comment by planteater** [comment]
@JP01 - Our integration with Bitbucket currently allows you to create PRs from CodeStream, and will show comments from BB PRs alongside the code blocks they refer to. The integration doesn't yet allow you to view/review PRs. We just rolled out that support for GitLab, and Bitbucket is next on the list. I would suggest following this issue to get updated when we're ready to start beta.

https://github.com/TeamCodeStream/codestream/issues/372
