### ISSUE TITLE
Slack Integration: Keep unrelated messages out of JetBrains Event Log

### ISSUE THREAD

**Issue by pwgraham91** [TeamCodeStream/CodeStream#54]
I use Android Studio and Slack. Since integrating with Codestream, every DM sent to me in Slack gets sent to my Event Log in Android Studio. This seems like unintended behavior.

![android____Documents_flosports_android__-_____app_src_main_res_layout_activity_reset_password_xml__app_](https://user-images.githubusercontent.com/7291189/57315584-84283900-70b9-11e9-8a70-7fca3bdd6014.png)

**Comment by marcelofarias** [comment]
Thanks for the report. CodeStream notifications will not be displayed the in the event log by default in the next release. In the meanwhile, you can turn it off in the notification settings.

![image](https://user-images.githubusercontent.com/1028286/57330243-725b8b80-70e3-11e9-8d0b-276bd9260b80.png)

**Comment by marcelofarias** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GH #54](https://trello.com/c/zeHGNCNS/1719-gh-54)

**Comment by planteater** [comment]
Fixed in 1.0.1.
