### ISSUE TITLE
Gitlab add support for MR environment link

### ISSUE THREAD

**Issue by DanubeRS** [TeamCodeStream/codestream#540]
We deploy review environments locally, and sometimes need to quickly verify something inside a deployment.
![image](https://user-images.githubusercontent.com/2668630/116944976-e2dd1900-acb9-11eb-9f2d-adfad47384b4.png)
Is it possible to add the review environment link like the Gitlab UI shows?

**Comment by bcanzanella** [comment]
@DanubeRS Just to get some additional context, on this MR, https://gitlab.com/gitlab-org/gitlab/-/merge_requests/60019

We have the following under the pipelines box. Is that what you're referring to?

![image](https://user-images.githubusercontent.com/834948/117162257-9e707c80-ad90-11eb-943e-093c44fff624.png)

thanks

**Comment by DanubeRS** [comment]
Yes, both that and the "View App" button if applicable would be super handy
