### ISSUE TITLE
Markdown comments visible in view

### ISSUE THREAD

**Issue by M-ZubairAhmed** [TeamCodeStream/codestream#541]
# Problem
The markdown comments seems to be appearing in the view panel of the extension
<img width="535" alt="image" src="https://user-images.githubusercontent.com/17708702/116978591-8d1c6700-ace1-11eb-855e-ba671b7ea9e0.png">

# Fix
One possible fix would be to use regex and replace the text before rendering. I did something similar in another similar github extension. https://github.com/mattermost/mattermost-plugin-github/pull/172
Let me know if i can help you with that

**Comment by bcanzanella** [comment]
@M-ZubairAhmed could you provide a little additional context here? I'm not entirely sure what part of CodeStream that screenshot is from.

**Comment by planteater** [comment]
Never mind @M-ZubairAhmed. We figured out that you're looking at the markdown from a PR template. We'll get that fixed.

**Comment by M-ZubairAhmed** [comment]
do you want me to look into it ? @planteater @bcanzanella

**Comment by bcanzanella** [comment]
@M-ZubairAhmed sorry about the pump-fake but we do need some additional details from you as to where you're seeing this. Thanks!

**Comment by M-ZubairAhmed** [comment]
@bcanzanella 
steps to reproduce
- in the extension, open issues tab
- click on any issue
- 

https://user-images.githubusercontent.com/17708702/117329606-6e20ff00-aeb2-11eb-9047-8f0939a8b3d8.mov

**Comment by M-ZubairAhmed** [comment]
have your folks found the issue ?

**Comment by planteater** [comment]
Fixed in v11.0.8. Thanks for your help!
