### ISSUE TITLE
IntelliJ Diff view does not include file name

### ISSUE THREAD

**Issue by nieldw** [TeamCodeStream/codestream#544]
When reviewing a Diff the filename is not included in the tab name or breadcrumb, making it hard to know which file you're viewing, especially when reviewing a large feedback request.
<img width="168" alt="image" src="https://user-images.githubusercontent.com/770125/117287695-ebc11c80-ae6a-11eb-81e0-87e519e08b12.png">

**Comment by planteater** [comment]
Thanks for the feedback @nieldw! I'll see if we can get this done in an upcoming release.

**Comment by planteater** [comment]
We weren't able to get the file name into the tab name, but we did add it to the header of the diff itself. This is in v11.0.6.

<img width="914" alt="Screen Shot 2021-05-14 at 6 24 51 AM" src="https://user-images.githubusercontent.com/3442587/118257924-3818e780-b47d-11eb-97f4-7201b97573ba.png">
