### ISSUE TITLE
"Jump to source" IntelliJ shortcut does not work in Diff view

### ISSUE THREAD

**Issue by nieldw** [TeamCodeStream/codestream#545]
The "Jump to source" IntelliJ shortcut does not work in Diff view. I expect this view to behave more like the native diff screen.

**Comment by planteater** [comment]
@nieldw - At the moment JetBrains doesn't have support for this in a git diff. We've opened the following issue for them. Feel free to upvote it! :-)

https://youtrack.jetbrains.com/issue/WEB-50312
