### ISSUE TITLE
Reviewing Gitlab MR with a partial commit range shows invalid changesets

### ISSUE THREAD

**Issue by evll** [TeamCodeStream/codestream#547]
Reviewing Gitlab MR with a partial commit range shows invalid changesets. Certain changes from selected commits are missing from the diff.

**Comment by bcanzanella** [comment]
@evll can you post some additional details as to what you're seeing? Also, perhaps adding some screenshots and explanation of what you're expecting to see? thanks!

**Comment by evll** [comment]
Simplest example: a newly added file was later modified in an additional commit:

![image](https://user-images.githubusercontent.com/9748640/117611710-a9e6ed80-b16c-11eb-95f8-bbf8878c3e0a.png)

The diff view does not show the changes (Gitlab's web interface does that correctly when viewing this single commit), but shows the file as added in this single commit:

![image](https://user-images.githubusercontent.com/9748640/117611833-dac72280-b16c-11eb-835b-766cfc3e6858.png)

But there are many more other mismatches, this one is just the simplest to explain.

**Comment by planteater** [comment]
Fixed in v11.0.7 of our extension for JetBrains.
