### ISSUE TITLE
Feedback request only shows last commit

### ISSUE THREAD

**Issue by PiR1** [TeamCodeStream/codestream#548]
Hello,
When I want to make a feedback request I can only select the last commit but I made 3 commits on this branch (see screenshot).
![Screenshot 2021-05-07 113432](https://user-images.githubusercontent.com/12834310/117430242-38b6f880-af28-11eb-9d9e-8918a4f5994c.png)

I'm on IntelliJ (v2021.1.1) , Codestream version 11.0.4+143

**Comment by planteater** [comment]
@PiR1 - We have a fix going out for this later today, although it usually takes JetBrains 24 - 48 hours to approve a release so it probably won't be available until Monday. I'll update you as soon as it's been approved.

**Comment by PiR1** [comment]
> 
> 
> @PiR1 - We have a fix going out for this later today, although it usually takes JetBrains 24 - 48 hours to approve a release so it probably won't be available until Monday. I'll update you as soon as it's been approved.

Alright, thank you !

**Comment by planteater** [comment]
This should be fixed in v11.0.5
