### ISSUE TITLE
Atom :: Error compiling Less stylesheet & An unexpected error has occurred.

### ISSUE THREAD

**Issue by devo-wm** [TeamCodeStream/codestream#551]
Attempting to test drive codestream in Atom for other members of the team and I ran into the following:

Error compiling Less stylesheet:  ~/.atom/packages/codestream/dist/webview/styles/webview.less

Line number: 89
'./providers.less' wasn't found. Tried - ~/.atom/packages/codestream/dist/webview/styles/providers.less,/Applications/Atom.app/Contents/Resources/app.asar/node_modules/one-light-syntax/styles/providers.less,/Applications/Atom.app/Contents/Resources/app.asar/node_modules/one-light-ui/styles/providers.less,/Applications/Atom.app/Contents/Resources/app.asar/static/variables/providers.less,/Applications/Atom.app/Contents/Resources/app.asar/static/providers.less,providers.less

Tried logging into my account any ways and initially received 
> An unexpected error has occurred.
> Click here to reload.
> If the problem persists please contact support@codestream.com

After clicking to reload the webview looks a little wonky:
<img width="456" alt="Screen Shot 2021-05-07 at 1 02 55 PM" src="https://user-images.githubusercontent.com/50152349/117446989-d1537580-af34-11eb-96e9-ec19f4ad66c5.png">

Not as familiar with atom as I am with vs code so not sure where to find the relevant debug output you guys need.

**Comment by aka434112** [comment]
![image](https://user-images.githubusercontent.com/19742583/117928302-fc650d00-b318-11eb-8708-51b0d2c65672.png)

@planteater

**Comment by AdamMarsden** [comment]
Can confirm that this is still an issue.

<img width="424" alt="Screenshot 2021-05-29 at 10 58 28" src="https://user-images.githubusercontent.com/2641173/120066121-e1aacc00-c06c-11eb-9442-0c9dfa8df8b4.png">

**Comment by planteater** [comment]
Unfortunately I have bad news. We've decided to pull the plug on our Atom extension. Compared to the tens of thousands of people using our other extensions, we were literally down to single digits with the Atom extension and just couldn't justify putting more effort into it.

If any of you end up switching from Atom to VS Code at some point, we'd obviously love for you to continue using CodeStream.
