### ISSUE TITLE
IntelliJ: Using "Compare next file" and "Next Difference" buttons in Diff view does not mark files in the CS list as _viewed_

### ISSUE THREAD

**Issue by nieldw** [TeamCodeStream/codestream#559]
Using "Compare next file" and "Next Difference" buttons in Diff view does not mark files in the CS list as _viewed_.

<img width="144" alt="image" src="https://user-images.githubusercontent.com/770125/117642744-f4299800-b187-11eb-96af-a186e2da49b6.png">

When I use these buttons to navigate the list of changes I expect the files I view like this to be marked as viewed.

**Comment by planteater** [comment]
@nieldw - This should be fixed in the latest version of the CodeStream extension.
