### ISSUE TITLE
JetBrain IntelliJ IDEA plugin: can not input Chinese when add a comment or create issue etc.

### ISSUE THREAD

**Issue by impself** [TeamCodeStream/codestream#56]
**Describe the bug**
When I select a piece of code and add an issue, I can't type in Chinese. The input box can only display English, but there is no problem with VS Code. I am not sure if it is a plugin problem or an ide problem.

In VS Code ：**Good!** I can choose Chinese characters.
<img width="492" alt="Xnip2019-05-10_18-36-51" src="https://user-images.githubusercontent.com/18463575/57521399-c4561880-7352-11e9-9d18-1f5ac90b2851.png">

In IntelliJ IDEA:**Oh NO!** I can only enter English characters.
<img width="617" alt="Xnip2019-05-10_18-38-37" src="https://user-images.githubusercontent.com/18463575/57521433-dc2d9c80-7352-11e9-9828-3ba5aaeffede.png">

**System Info (please complete the following information):**
 - Version of the CodeStream extension: V 0.53.0+1
 - OS + version: Mac OS 10.14.4
 - IDE + version: IntelliJ IDEA 2019.1.2

**Comment by yhan219** [comment]
V`1.0.2+2` also has this problem.

**Comment by cshuo** [comment]
+1

**Comment by planteater** [comment]
@impself @yhan219 @cshuo - Could you give us some more details on what kind of keyboard you're using? Specifically, is it a keyboard that types Chinese characters natively, or is it an English/QWERTY keyboard that uses some form of transliteration to convert roman characters to Chinese? Any details you can provide would be very helpful. Thanks!

**Comment by cshuo** [comment]
@planteater hi, i'm using keyboard in macbook pro, and type Chinese simply using Chinese input method.

**Comment by RedCheezeCake** [comment]
Hi~ ✋ 
I have similar issue when I use Korean character. (#68)
When writing Korean characters, those characters are separated.
For example, when I try to write `안녕`, It is wrote as `ㅇㅏㄴㄴㅕㅇ`.
(in normal case, `ㅇㅏㄴ`->`안`, `ㄴㅕㅇ`->`녕`)

**Comment by sjzdl** [comment]
+1, hope solved soon.

**Comment by biscuitsCheng** [comment]
+1, hope solved soon.

**Comment by jasonHao** [comment]
i'm using keyboard in macbook pro, and type Chinese simply using Chinese input method.i'm using keyboard in macbook pro, and type Chinese simply using Chinese input method.  
hope solved soon.

**Comment by jasonHao** [comment]
@planteater

**Comment by artikell** [comment]
+1, hope solved soon.

**Comment by tomsean** [comment]
+1, hope solved soon.

**Comment by noakcn** [comment]
+1， hope solved soon.

**Comment by on-future** [comment]
+1

**Comment by whomakemecrazy** [comment]
+1

**Comment by MozyOk** [comment]
+1 same Japanese too.

**Comment by naihuayang** [comment]
+1

**Comment by naihuayang** [comment]
This plugin is very useful, but
**It is very important to input multi language**

**Comment by naihuayang** [comment]
<img width="1678" alt="WX20200404-182600@2x" src="https://user-images.githubusercontent.com/7445145/78456029-cc712200-76a1-11ea-83eb-afe28ba128f2.png">

**Comment by z199172177** [comment]
+1

**Comment by byunda** [comment]
+1

**Comment by seolys** [comment]
I still can't enter Korean. When will it be fixed?

**Comment by planteater** [comment]
Stay tuned! We should have a solution coming very soon. JetBrains will be releasing their JCEF (Java Chromium Embedded Framework) in 2020.2, and once they do we'll be able to use that to render the CodeStream webview. This will also, finally, allow us to support Chinese, Korean, Japanese, etc. I'll post again here once this is available.

**Comment by planteater** [comment]
Hi everyone! Version 8.3.1 of the CodeStream extension was just approved. If you're running v2020.2 of a JetBrains IDE, this will finally address the issue with being able to enter Chinese, Korean, Japanese, etc. characters. I'll close this issue, but do let us know if you still see any problems. Thanks!

**Comment by 512DIDIDI** [comment]
Still ran into the problem
System Info：
Version of the CodeStream extension: v 10.7.3_143
OS + version: Mac OS 11.2.2
IDE + version: Android Studio 4.1.3

**Comment by planteater** [comment]
@512DIDIDI - You'll need to wait for Android Studio 4.2, although we still haven't determined whether it will actually ship with JCEF.

**Comment by LKHcoding** [comment]
>Hi~ ✋
>I have similar issue when I use Korean character. (https://github.com/TeamCodeStream/codestream/issues/68)
>When writing Korean characters, those characters are separated.
>For example, when I try to write 안녕, It is wrote as ㅇㅏㄴㄴㅕㅇ.
>(in normal case, ㅇㅏㄴ->안, ㄴㅕㅇ->녕)

same issue recurred

using webstorm (ver. 2023.1.2 => new UI Enabled)

**Comment by noakcn** [comment]
你发的邮件我已经收到了。
                                    以上为自动回复邮件

**Comment by planteater** [comment]
@LKHcoding - What operating system are you using?

**Comment by LKHcoding** [comment]
> @LKHcoding - What operating system are you using?

@planteater 
i'm using macOS Ventura (13.2)

**Comment by LKHcoding** [comment]
@planteater 
Is this issue in progress?
I still can't enter Korean. When will it be fixed?

i'm using macOS Ventura 13.2, m1 processor
webstorm (2023.2.1 -> the most recent version)
codeStream plugin (14.28.0+511 -> the most recent version)

**Comment by noakcn** [comment]
你发的邮件我已经收到了。
                                    以上为自动回复邮件
