### ISSUE TITLE
Android Studio 4.2 can not support Chinese input

### ISSUE THREAD

**Issue by Callanna** [TeamCodeStream/codestream#560]
Android Studio 4.2 can not support Chinese input
<img width="529" alt="image" src="https://user-images.githubusercontent.com/14858726/117649768-8189de00-b1c2-11eb-80b9-c3cac650127c.png">
<img width="369" alt="image" src="https://user-images.githubusercontent.com/14858726/117649834-923a5400-b1c2-11eb-8f97-cc5998b48ef5.png">

**Comment by planteater** [comment]
It doesn't look like they've added JCEF support into 4.2 yet.

**Comment by Jadyli** [comment]
+1

**Comment by Jadyli** [comment]
+1

**Comment by planteater** [comment]
Although they're still not shipping Android Studio with JCEF you can add it yourself. Here are the instructions.

For Android Studio 2021.1+:

- Open menu item Help  Find action…​ and search for “Choose Boot Java runtime for the IDE…​”
- Choose a runtime “11.0.x…​” labeled “JetBrains Runtime with JCEF” and install it. The IDE will restart.
- Go to the settings of the AsciiDoc plugin and check if the preview is set to “JCEF Browser”. Change it to “JCEF Browser” if this is not the case.

For Android Studio 4.2 and 2020.3+:

- Install the plugin “Choose Runtime”.
- Open menu item Help  Find action…​ and search for “Choose Runtime…​”
- Choose a runtime "jbrsdk-11_0_…​tar.gz" or later and install it. The IDE will restart.
- Go to the settings of the AsciiDoc plugin and check if the preview is set to “JCEF Browser”. Change it to “JCEF Browser” if this is not the case.

Once you've done this, go to Preferences > Tools > CodeStream and make sure the "Use JCEF WebView" box is checked.
