### ISSUE TITLE
IntelliJ balloon notifications (and log) replace "this" with feedback request name

### ISSUE THREAD

**Issue by nieldw** [TeamCodeStream/codestream#565]
Little bug. If the text of a comment on a feedback request contains the text "this" it is replaced with the name of the feedback request in the notification and log.

<img width="366" alt="image" src="https://user-images.githubusercontent.com/770125/117816858-42fa2f00-b267-11eb-97e5-039188a098b6.png">

It actually reads "But this is a copy paste".

**Comment by planteater** [comment]
@nieldw - We've got a fix ready to go out in our next release. I'll update you as soon as it's out there.

**Comment by planteater** [comment]
This fix is now available in v11.0.6 of the CodeStream extension for JetBrains.
