### ISSUE TITLE
PHPStorm 2021.1.2 - Automatic prompt for feedback when commiting while option turned off

### ISSUE THREAD

**Issue by tstrijdhorst** [TeamCodeStream/codestream#567]
I specifically unchecked the option to `Auto-prompt for feedback when committing` yet every time I make a commit it automatically opens the codestream window to ask for feedback.

As I commit quite often and don't actually use this feedback feature it is annoying me to the point of wanting to uninstall the whole plugin.

Is this a bug or something I am not understanding?

**Comment by planteater** [comment]
@tstrijdhorst - We'll be simplifying this shortly, but for now there are actually two different mechanisms that trigger the auto-prompt, one for when you commit from the command line and one for when you commit from within the IDE.

When you commit from the command line, you can turn this off via the toggle that appears at the top of the FR form.

When you commit from within the IDE, just uncheck the "Request feedback" box and it will remember this selection going forward. Note that in some JetBrains IDEs the After Commit actions are not exposed by default and you may need to expose them to see that checkbox.

 ![JBCommitDlg](https://user-images.githubusercontent.com/3442587/117969761-d8440480-b2f5-11eb-971d-af638d5055c1.jpg)
