### ISSUE TITLE
Cygwin git support

### ISSUE THREAD

**Issue by dailytabs** [TeamCodeStream/CodeStream#57]
**Describe the bug**
In IntelliJ, when attempting to "Add Comment" I get the "No Remote URL" error message.

`git remote -v` shows remote is setup correctly for both repositories in the project.

This project has 2 git repositories. Both have remotes setup properly. They are also properly defined in IntelliJ's settings (Settings > Version Control).
![image](https://user-images.githubusercontent.com/1219653/57788691-8451b580-7705-11e9-80ef-bf45f7a46dfa.png)

**System Info:**
 - Plugin 1.0.1+1
 - Win 10 Home 1809
 - IntelliJ 2019.1.1

**Log Files**
I would get the logs, but the link you provide (https://github.com/TeamCodeStream/CodeStream/wiki/Instructions-for-getting-CodeStream-log-files) just redirects to /wiki and there is nothing about log files on that page.

**Comment by planteater** [comment]
@dailytabs - Apologies for the incorrect link. Here's the correct one for grabbing the log files.

https://github.com/TeamCodeStream/CodeStream/wiki/Instructions-for-finding-CodeStream-log-files

Feel free to post them here, or send them to us at support@codestream.com. Thanks!

**Comment by dailytabs** [comment]
[idea-logs-20190516-152755.zip](https://github.com/TeamCodeStream/CodeStream/files/3188711/idea-logs-20190516-152755.zip)

**Comment by dailytabs** [comment]
IntelliJ picked up git via Cygwin:
![image](https://user-images.githubusercontent.com/1219653/57881762-1fbf5500-77f0-11e9-8ec3-10a5ad40b8ce.png)

**Comment by marcelofarias** [comment]
@dailytabs is `C:\tools\cygwin\bin` included in your `%PATH%` variable (can you call `git --version` from PowerShell)?
If not, does it help if you add it and restart Windows?

**Comment by dailytabs** [comment]
PS C:\Users\dwhite> git --version
    git version 2.17.0
    PS C:\Users\dwhite> Get-Command git | Select-Object -ExpandProperty Definition
    C:\tools\cygwin\bin\git.exe

**Comment by marcelofarias** [comment]
@dailytabs The issue is related to the use of CodeStream with git on Cygwin. We are working on a solution for this problem.

**Comment by dailytabs** [comment]
👍

**Comment by marcelofarias** [comment]
Fixed on version 1.1.0+1

**Comment by philzartis** [comment]
Just hit this issue on cygwin git version 2.27.0 and CodeStream version "10.6.1+131".

**Comment by planteater** [comment]
@philzartis - Could I trouble you for a log file? In your IDE go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. If you'd prefer not to post it here, you can send it to me directly at support@codestream.com. Thanks!
