### ISSUE TITLE
MVS Community Git Issues custom filter dont work.

### ISSUE THREAD

**Issue by alxrMironov** [TeamCodeStream/codestream#570]
Not with repo, not with assignee and etc.

![image](https://user-images.githubusercontent.com/30952168/118081630-6a1a4300-b3c4-11eb-8ebf-8eed113295bf.png)

**Comment by bcanzanella** [comment]
Could you explain a little more what you're expecting to see? It looks like there are results when you test `assignee:@me` are those results incorrect?

**Comment by alxrMironov** [comment]
Yes. No one is correct. After play some with filter, i suspect that it doesn't works at all. Only with default show assigned to me, which is active if no custom filter is set.

Maybe i handle it in wrong way? Im expecting, what it works like generic github search filter across all the github.
![image](https://user-images.githubusercontent.com/30952168/118154325-94e5b500-b41f-11eb-95eb-e68bd1ce1511.png)
![image](https://user-images.githubusercontent.com/30952168/118154359-9dd68680-b41f-11eb-987b-8f9b8adaf7c1.png)

**Comment by planteater** [comment]
@alxrMironov - I think the issue is that you've got the label and query fields reversed. "assignee:@me" should be in the top field, and "Default" should be in the bottom one.

**Comment by alxrMironov** [comment]
Ehh =) My bad. Thank you. This is really mine stupid mistake.

**Comment by planteater** [comment]
No worries @alxrMironov! We're actually going to update that form to try to make things a little clearer.
