### ISSUE TITLE
CodeStream can't find repos in multi-root workspace

### ISSUE THREAD

**Issue by iuriatan** [TeamCodeStream/codestream#574]
In my VsCode workspace there are multiple folders root of different repositories. When I try to review or detail a commit in one of these repos, codestream says `Repo <name> not found in your editor`.

Am I missing any configuration or some change must be done for it to work well in multi-root workspaces?

**Comment by planteater** [comment]
@iuriatan - Could you give me a little more insight into what your folder structure looks like? Particularly the number of levels between the repos and the top-level folder. You could also just post a screenshot (or email it to support@codestream.com). Thanks

**Comment by planteater** [comment]
@iuriatan - Just wanted to follow up on my previous reply. Thanks.

**Comment by iuriatan** [comment]
Sorry for the delay (I lost track of the notifications) 🙇🏼‍♂️ 

I use a pretty standard [multi-root workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces). All my repositories are open through "Add folder to workspace". As I work with client's micro services architecture, I deal with a lot of application repositories at once. Here is my workspace file structure:
```json
{
  "folders": [
    {
      "path": "clinent.repo1"
    },
    {
      "path": "client.api.repo2"
    },
    {
      "path": "client.repo3"
    },
    {
      "path": "client.svc.repo4"
    },
    {
      "path": "backend"
    },
    {
      "path": "client.auth"
    },
    {
      "path": "client.frontend"
    }
  ],
  "settings": { }
}
```

**Comment by planteater** [comment]
Thanks @iuriatan! That all looks pretty straightforward, so unfortunately we'll probably need a log file to really figure out what's going on here. Instructions can be found here:

https://docs.codestream.com/userguide/faq/client-logs/

If you'd prefer not to post the log files here, feel free to send them to me at support@codestream.com. Thanks!

**Comment by planteater** [comment]
@iuriatan - I'm going to go ahead and close this out, but when you're able to grab that log file feel free to reopen this or just email me at support@codestream.com. Thanks

**Comment by Miksser** [comment]
@planteater Hello. I have same problem in phpStorm.
The plugin does not see my folders and does not allow me to watch a full-fledged diff
![image](https://user-images.githubusercontent.com/27306203/124296925-2d1c3280-db63-11eb-8083-3b1bd6c498f4.png)

**Comment by planteater** [comment]
@Miksser - Could I trouble you for a log file? That would allow us to see what folders CodeStream detected. In your IDE go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. If you'd prefer not to post it here, feel free to email it to me at support@codestream.com. Thanks!

**Comment by Miksser** [comment]
This is a small problem = (Because a full log can store sensitive company information. Can you sent me the "grep" command I need to run?

**Comment by planteater** [comment]
You could try to search for "repository search" and "precondition", but admittedly this might be a challenge.
