### ISSUE TITLE
Support for other messaging/collaboration services

### ISSUE THREAD

**Issue by cassioscabral** [TeamCodeStream/codestream#58]
Is there any plans to support others tools besides Slack, such as Mattermost?

**Comment by planteater** [comment]
@cassioscabral - Definitely! Mattermost and Discord are two in particular that are on our radar. I don't have specific timing right now, but Q3 is a good possibility.

**Comment by tedyoung** [comment]
Would love to have Discord support for my Twitch live-coding stream (Twitch chat would be great, too -- I wrote an IntelliJ plugin for the Twitch chat API).

**Comment by dpesch** [comment]
I would love a Mattermost integration

**Comment by turfaa** [comment]
Really looking forward to the Mattermost integration.

**Comment by savy-91** [comment]
👍 for mattermost

**Comment by absolutejam** [comment]
What about a general webhook integration too? So, if an integration like MatterMost does not exist, we can handle it ourselves?

**Comment by kirinnee-atomi** [comment]
There are other less popular collaboration tools and I think a web hook solution would be good!

**Comment by JosNun** [comment]
+1 for Discord support or webhooks that can be used in a platform-agnostic fashion.

**Comment by VincenzoSalernoCitel** [comment]
+1 for Discord and webhooks

**Comment by nmsohn** [comment]
+1 for Discord and webhooks

**Comment by cognitus** [comment]
any new?

**Comment by duplexsystem** [comment]
+1

**Comment by evelant** [comment]
I'm guessing this is no longer a priority since codestream was acquired. I doubt the big companies they have as customers use Discord, Element, webhooks, etc like many small time and open source devs do. I love the idea of codestream but it seems to have evolved toward targeting big organizations and unfortunately now seems less useful to smaller orgs and indie devs.

**Comment by planteater** [comment]
@evelant Unfortunately there just hasn't been enough demand, even prior to the acquisition. Even then, the drop-off after Slack and Teams is incredibly steep. I won't say never, but its admittedly not looking good.

**Comment by mattaereal** [comment]
+1 for Discord / Webhooks :)
