### ISSUE TITLE
Error creating the codemark in renamed files

### ISSUE THREAD

**Issue by FFWayne** [TeamCodeStream/codestream#596]
When attempting to leave a comment on a file whose name has changed during a code review, I've noticed that attempting to leave comments past an arbitrary seeming line number in the file, I'm met with the following error:
![image](https://user-images.githubusercontent.com/68245168/120037882-32f88400-bfb7-11eb-8d90-c59fa7db40ba.png)

I'll follow up with the output from error logs in a private e-mail.

**Comment by planteater** [comment]
Fixed in v11.0.13.
