### ISSUE TITLE
 "Go to Definition" does not work in the diff view in vs code

### ISSUE THREAD

**Issue by MaikKlein** [TeamCodeStream/codestream#598]
"Go to Definition" does not seem to work in the diff mode in vs code. I am not sure if this is an lsp issue or an codestream issue.
I did check out the branch locally, if I just open the file I do get all my IDE features like goto definition.

I am using the [rust analyzer lsp](https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer)

![2021-05-30-142732_2510x1315_scrot](https://user-images.githubusercontent.com/1994306/120104153-653ee880-c153-11eb-9bad-b92f2ddf8379.png)

**Comment by planteater** [comment]
@MaikKlein unfortunately VS Code doesn’t yet have support for code intelligence inside git diffs. We’ve raised the issue with them in the past and there didn’t seem to be much interest in the idea on their part.

**Comment by MaikKlein** [comment]
> @MaikKlein unfortunately VS Code doesn’t yet have support for code intelligence inside git diffs. We’ve raised the issue with them in the past and there didn’t seem to be much interest in the idea on their part.

You probably already know this, but I do get code intelligence with https://github.com/microsoft/vscode-pull-request-github in the diff view.

![2021-06-06-103855_2510x1315_scrot](https://user-images.githubusercontent.com/1994306/120918203-750a7f80-c6b3-11eb-9543-6af6de46beeb.png)

**Comment by hgezim** [comment]
Seems to be that the context menu item shouldn’t be available if it’s going to produce incorrect results.
