### ISSUE TITLE
Can't connect to GitHub Pull Request

### ISSUE THREAD

**Issue by homezonebenny** [TeamCodeStream/codestream#599]
### GitHub Pull Request not working

I'm **_already connected to GitHub_**  with the VSCode Codestream Plugin.
Everything seems working **_except_** the Pull Request.

If you try to create a Pull Request it ask you (again) for a GitHub connection but then fail to connect.

**See screenshot:**
https://i.imgur.com/EBsNAWV.png

**Is it a bug or is there a simple solution for it?**

**Comment by planteater** [comment]
@homezonebenny - By any chance do you have any repos open in your IDE that aren't hosted on GitHub cloud? Looking at some of your remotes it seems like maybe they might be on your own self-hosted GitHub, in which case you would need to connected to our GitHub Enterprise integration.

**Comment by homezonebenny** [comment]
@planteater 
Not that I could think of.
In VSCode I have a "**NAME.code-workspace**" file for each project.

In the windows credential manager I removed everything so that I had to re-auth my GitHub completely.
Then I'm connected and I can see and use everything **except** the Pull Requests.
When I open a new Pull Request it ask me to connect to GitHub, what's strange.

**Comment by planteater** [comment]
If you get a sec, do a `git remove -v` for the repo in question and let me know the output. If you'd prefer not to post it here, you can send it to me at support@codestream.com. Thanks.

**Comment by homezonebenny** [comment]
@planteater 
E-Mail sent with all the informations I could possibly deliver.
Hope this is enough to explain my configuration.

**Comment by homezonebenny** [comment]
@planteater 
**Maybe I found something.**

In the VS Code settings.json file I changed this to absolute path:
`"git.defaultCloneDirectory": "D:\\VSCode_Workspace",`

Before it was like this:
`"git.defaultCloneDirectory": "\\VSCode_Workspace",`

Can you change it to an relative path at yourself to see if this creates this issue for you?

\
I'm at work right now so I can't verify that it's working since I get the orange message that

> We’re having problems connecting to CodeStream. Hold tight, we’ll keep trying...

**Comment by cstryker** [comment]
@homezonebenny regarding the orange banner, if you are running behind a proxy please see these instructions: https://docs.codestream.com/userguide/faq/proxy-support/.  If this doesn't help, please retrieve your logs following these instructions: https://docs.codestream.com/userguide/faq/client-logs/. You can send them to me at colin AT codestream.com.
