### ISSUE TITLE
Can't be login from github

### ISSUE THREAD

**Issue by chenjiefeng2001** [TeamCodeStream/codestream#601]
I try to authentication my GitHub account to visual studio code, but the extension can't response the request when I authentication the account from webpage.
![image](https://user-images.githubusercontent.com/34204823/120453571-c0781180-c3c5-11eb-8493-d4dc052fab29.png)
Just like this, if it works correct, the extension should receive a api_link to allow CodeStream to authentication my GitHub account.

**Comment by planteater** [comment]
@chenjiefeng2001 - I'm not totally sure I understand the issue. I checked your account and it looks like you are signed up. If you go back to your IDE, what do you see there? You should now be signed into CodeStream. If not, can you share a screenshot of what you're seeing?

You might also want to make sure that CodeStream is listed as a trusted extension. In VS Code, go to the menu item depicted in the screenshot below, and then make sure the box next to CodeStream is checked.

<img width="441" alt="Screen Shot 2021-06-02 at 8 04 42 AM" src="https://user-images.githubusercontent.com/3442587/120477045-4c178100-c379-11eb-835d-2bcaf7083923.png">

**Comment by chenjiefeng2001** [comment]
OK ,The Problem has been sloved, I check it and found the error that I close the proxy ,Now it work correct. Thank you for your help o((>ω< ))o
