### ISSUE TITLE
IntelliJ: Can't disable 'Request Feedback' after committing changes

### ISSUE THREAD

**Issue by JKuhn** [TeamCodeStream/codestream#609]
Whenever I commit something in IntelliJ 2021.1, the 'Request Feedback' 
![image](https://user-images.githubusercontent.com/32623089/120716361-0d6cfc80-c51a-11eb-80af-a86b8851a2d8.png)
dialog comes up, even when I have the 'Auto-prompt' disabled, and also when the option is disabled in the Feedback Request settings
![image](https://user-images.githubusercontent.com/32623089/120716489-39887d80-c51a-11eb-8b34-1a9e27a5b96e.png)

That's super annoying and prevents the team from starting to use CodeStream

**Comment by planteater** [comment]
@JKuhn - We'll be simplifying this shortly, but for now there are actually two different mechanisms that trigger the auto-prompt, one for when you commit from the command line and one for when you commit from within the IDE.

When you commit from the command line, you can turn this off via the toggle that appears at the top of the FR form.

When you commit from within the IDE, just uncheck the "Request feedback" box and it will remember this selection going forward. Note that in some JetBrains IDEs the After Commit actions are not exposed by default and you may need to expose them to see that checkbox.

![JBCommitDlg](https://user-images.githubusercontent.com/3442587/120717044-ed472a00-c494-11eb-92ae-417cbe6ec21d.jpg)
