### ISSUE TITLE
How to add account information to the database in batches

### ISSUE THREAD

**Issue by wanlinruo** [TeamCodeStream/codestream#613]
As in the question, our company is using codestream, but there are about a hundred people in the team. The efficiency of registering an account by each person is too low. How can we add accounts to the database in batches at once? Thank you for answering.

**Comment by planteater** [comment]
@wanlinruo - We don't currently have the ability to invite in batch, but we do have an alternative to inviting that might be useful in your situation. Check the following article in our user guide that describes a way to give people access to a CodeStream team based on what repos they have open in their IDE at the time they install CodeStream. For example, you can say that anyway that has the frontend repo open in their IDE is allowed to simply join the FrontEnd team you created on CodeStream. No invitations necessary.

https://docs.codestream.com/userguide/features/team-administration/#onboarding-settings
