### ISSUE TITLE
Does not work in android studio

### ISSUE THREAD

**Issue by sanni-aubergine** [TeamCodeStream/codestream#615]
My android studio 
Android Studio 4.2.1
Build #AI-202.7660.26.42.7351085, built on May 10, 2021
Runtime version: 11.0.8+10-b944.6916264 x86_64
VM: OpenJDK 64-Bit Server VM by N/A
macOS 10.16
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 6
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.bloc.intellij_generator_plugin, com.intellij.javafx, com.codestream.jetbrains-codestream, Dart, org.jetbrains.kotlin, io.flutter, de.mariushoefler.flutter_enhancement_suite

After installing CodeStream from plugin section and then opening it from right side shows this

![Screenshot 2021-06-09 at 2 08 12 PM](https://user-images.githubusercontent.com/61491299/121322254-72ff2580-c92c-11eb-8d48-99a9e80565cd.png)

**Comment by sanni-aubergine** [comment]
JCEF not available

**Comment by planteater** [comment]
@sanni-aubergine - Unfortunately, we are no longer able to distribute JXBrowser with our extension, which means that we can't officially support Android Studio until JCEF support is added. Hopefully this will come soon, but in the meantime, please download the previous version of the CodeStream extension, v11.0.8, from the marketplace:
 
https://plugins.jetbrains.com/plugin/12206-codestream-github-gitlab-bitbucket-prs-and-code-review/versions

Be sure to sure either 11.0.8+148 or 11.0.8+171 based on the version of Android Studio you're running. Looks like for you, you would want build 148.

Once you've downloaded the file, you can install it by going to Preferences/Settings > Plugins and then select "Install Plugin from Disk" from the gear menu at the top-right. You'll then be prompted to restart your IDE.

**Comment by sanni-aubergine** [comment]
Thanks, I was able to manually install this plugin as per your suggestion.
-----
Recently, CodeStream was acquired!!! Eagerly waiting for an update with pro features that will be coming for free to everyone.

**Comment by planteater** [comment]
Just a quick note to let you know that official Android Studio support should be coming back in the next day or two. Note that it will require Android Studio 4.2 or later. I'll update this issue again once it's available.

**Comment by sanni-aubergine** [comment]
Great, thanks.
Eagerly waiting for the update

**Comment by planteater** [comment]
Android Studio support is back now in v11.0.11 of the CodeStream extension. It requires Android Studio 4.2 or later.
