### ISSUE TITLE
Intellij Unable to add comment to PR on an Opensource project

### ISSUE THREAD

**Issue by vedhavyas** [TeamCodeStream/codestream#618]
Whenver I tried to submit a comment on a PR i get the following error
```
There was an error creating the codemark.
```

<img width="603" alt="Screenshot 2021-06-14 at 2 02 18 PM" src="https://user-images.githubusercontent.com/7549475/121889135-23986b00-cd19-11eb-93a0-49e325baf29d.png">

**Comment by planteater** [comment]
@vedhavyas could I trouble you for a log file? Reproduce the issue and then in your IDE go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file.

if you’d prefer not to post it here you can send it to me at support@codestream.com. Thanks.

**Comment by vedhavyas** [comment]
@planteater sent the logs over the email.

**Comment by DanubeRS** [comment]
I have also recieved this error for Gitlab Self-Managed, with report of an "Internal Server Error"

Logs have been sent to support emaIl

**Comment by planteater** [comment]
@vedhavyas - It looks like you've authenticated with GitHub, but did not grant permission for CodeStream to access the centrifuge repo. Check the following article on how to address that and let me know if that fixes things.

https://docs.codestream.com/userguide/faq/github-org-repos/

**Comment by vedhavyas** [comment]
Okay. will check. Thanks!

**Comment by planteater** [comment]
Hi @vedhavyas - Just wanted to check in to see if that solved the issue for you.

**Comment by vedhavyas** [comment]
yes this is resolved thanks!
