### ISSUE TITLE
Privacy concern: Don't send emails to users who have not accepted an invitation

### ISSUE THREAD

**Issue by willydee** [TeamCodeStream/codestream#619]
## Steps to reproduce
* Create a Team account
* `Invite a teammate via Email`, or from `Suggested Teammates`
* **Don't** accept the invitation
* Cause some activity in a project
* Wait a week or two

## Expected result
Invited member should receive one single invitation email, but no further emails.

## What happens instead
Invited person retrieves a weekly team activity email with details about merge requests et al.

**Comment by willydee** [comment]
@planteater there was an invitation pending for a third participant in the same team, which I revoked after the user was concerned about the allegedly unsolicited email, containing readable details about merge requests. PM forthcoming.

**Comment by kiriti999** [comment]
@planteater Please check the app properly. My fellow team members got an invite - not by accident and they asked me what this app was about. If it was by accident then this git issue won't be created by someone else.

**Comment by planteater** [comment]
@kiriti999 - Can you clarify what the issue is? I see there are two people on your team. Yourself and one other user that was invited.

**Comment by Zephirin** [comment]
I'm seeing that if you open a PR with specific reviewers, they get an email about codestream, even if they're not part of the codestream team.

**Comment by Zephirin** [comment]
Could have been a Feedback Request, I can look into that.
