### ISSUE TITLE
Slack DMs showing all the time

### ISSUE THREAD

**Issue by asthomasdk** [TeamCodeStream/CodeStream#62]
**Describe the bug**
We are using VC Code and CodeStream. 

We have only selected to see messages from the one channel in Slack (codestream) that I have chosen for codestream messages, we are getting all of our direct messages from Slack popping up. This is annoying, as we are not expecting to use codestream as a replacement client for Slack. 

Is there some way this can be turned off? 

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 1.0.1
 - OS + version: Win 10
 - IDE + version: VS Code 1.33.1

**Comment by planteater** [comment]
@asthomasdk - You can turn off desktop notifications in CodeStream by going to VS Code settings, searching for CodeStream, and then scrolling down to the Notifications setting. Select the None option. This will actually become the default for users on teams connect to Slack starting in our next release.
