### ISSUE TITLE
Can't seem to access the Visual Studio marketplace link

### ISSUE THREAD

**Issue by fatpowaranga** [TeamCodeStream/codestream#622]
I've struggled for quite a while now trying to get CodeStream installed into Visual Studio (not VS Code). It seems to be linked to everywhere, but the page is inaccessible? Is this temporary or is something going on? Would like to give it a test there as a majority of my team prefer VS over VS Code for what we work on.

**Comment by planteater** [comment]
Unfortunately, we had to take down the VS extension temporarily as we work through some licensing issues. I'll follow up here as soon as it's available again.

**Comment by planteater** [comment]
The VS extension is now available in the marketplace again.

https://marketplace.visualstudio.com/items?itemName=CodeStream.codestream-vs
