### ISSUE TITLE
Cannot disable auto-feedback request on creating commit through Rider

### ISSUE THREAD

**Issue by benbelow** [TeamCodeStream/codestream#632]
I'd like to try CodeStream for interacting with Github PRs, but I'm not interested in trying feedback requests as well. 

I've disabled the checkbox for "auto feedback request on commit" - but I'm still finding the codestream window pop up whenever I make a commit through the Rider UI. 

This is enough of an inconvenience to make me not want to try Codestream for my PRs after all

**Comment by planteater** [comment]
@benbelow - "auto feedback request on commit" refers to the toast notifications you get when a teammate commits. The prompt to create a Feedback Request when *you* commit is something else altogether.

There are two different ways to turn that off, depending on whether you commit from within the IDE or via the command list. If you commit from the command line (i.e., external to the IDE), when the Feedback Request form pops up you should see a toggle at the top of the page to turn it off going forward.

If you commit from within the IDE, just uncheck the "Request feedback" box the next time you commit and it will remember this selection going forward. Note that in some JetBrains IDEs the After Commit actions are not exposed by default and you may need to expose them to see that checkbox.

![JBCommitDlg](https://user-images.githubusercontent.com/3442587/122969972-451dd600-d35b-11eb-9fe2-971d792f7cbf.jpg)

**Comment by benbelow** [comment]
Got it, thanks for the quick feedback!
