### ISSUE TITLE
codestream-agent didn't close after idea close

### ISSUE THREAD

**Issue by bluelovers** [TeamCodeStream/CodeStream#64]
**Describe the bug**

codestream-agent didn't close after idea close

![image](https://user-images.githubusercontent.com/167966/58489233-6cfed780-819d-11e9-8038-fed315e2ea71.png)

![image](https://user-images.githubusercontent.com/167966/58489379-c404ac80-819d-11e9-91a3-3ad58711e70d.png)

**System Info (please complete the following information):**
 - Version of the CodeStream extension: [e.g., 0.53.1]
 - OS + version: [e.g. Win 10]
 - IDE + version: [e.g. VS Code 1.33.1]

**Log Files**
Sending log files along with your report will help us investigate the issue. Instructions can be found here: https://github.com/TeamCodeStream/CodeStream/wiki/Instructions-for-finding-CodeStream-log-files

**Comment by planteater** [comment]
@bluelovers - This should be fixed in v1.3
