### ISSUE TITLE
Improve `Blame Map`

### ISSUE THREAD

**Issue by ljubadr** [TeamCodeStream/codestream#641]
Currently I need to manually get the list of emails and then to add them one by one. For bigger project it's slow and painful task

I'm running `git shortlog --summary --numbered --email` and I'm getting over 100 results that I need to add manually

**Suggestions**

1. Add import option where we can add the CSV. For example, each row should be `<code autorhed by email>, <now handled by email>`

2. Make the email autocomplete from the list of previous contributors. By typing few letters we would get email suggested from the list of all contributors (minus the ones that were already mapped)

**Comment by planteater** [comment]
Thanks for the suggestion @ljubadr!
