### ISSUE TITLE
CodeStream pane is empty in JetBrains IDEs on Linux

### ISSUE THREAD

**Issue by materemias** [TeamCodeStream/codestream#642]
The plugin window is just an empty page, it worked before. I tried uninstalling/restart/reinstall cycle, also logged out with no effect
![image](https://user-images.githubusercontent.com/529994/124179691-77de7180-dab3-11eb-8331-73e07ef48236.png)

it worked before... 
Intellij Idea ultimate 2021.1.3

**Comment by planteater** [comment]
@materemias - Can you try using the "CodeStream: sign out" action from the IDE's action list? After doing that, sign back in and see if that does the trick.

If it doesn't, I think we'll need a log file. In IntelliJ go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. If you'd prefer not to post it here, feel free to send it to me at support@codestream.com. Thanks!

**Comment by materemias** [comment]
@planteater after logging out I don't have the chance to log back in since no UI elements are loaded :) I've sent a mail to you with the logs

**Comment by marcelofarias** [comment]
Hi @materemias. Based on the logs and version information provided, this might be a glitch in IntelliJ's 2021.1.3 Linux JCEF component. Could you check if CodeStream eventually renders if you resize its Tool Window? Alternatively, you can temporarily switch to JxBrowser webview under Settings > Tools > CodeStream > uncheck "Use JCEF webview" (requires restart).

Let me know if any of these improve the situation for the time being.

**Comment by materemias** [comment]
thanks for the hint @marcelofarias , resizing the tool window did not help, I faced the same disappearing content problem on 2021.1.2 as well eventually., disabling JCEF webview brought it back (for now, will keep watching), but nw the ide starts with this alert... after ok-ing it everything seems to be ok
![image](https://user-images.githubusercontent.com/529994/124310961-3e6a3c80-db6d-11eb-8662-9d1c6ef5e407.png)

**Comment by sabat24** [comment]
I installed it for the first time on Ubuntu and had same issue. Turnig off the webview option and restarting IDE helped without any errors.

**Comment by sabat24** [comment]
In work we use Debian and turning off JCEF WebView doesn't help. After  small random amount of time (10 seconds or 2 minutes) everything disapears from right pane and I have to restart my IDE to get it work again.

**Comment by GrzegorzWalewski** [comment]
Had same issue, disabling JCEF webview helped.

**Comment by marcelofarias** [comment]
https://youtrack.jetbrains.com/issue/IDEA-273222

**Comment by kiliw** [comment]
Same issue. The solution from @marcelofarias helped. Thanks a lot.

**Comment by ParogDev** [comment]
> Hi @materemias. Based on the logs and version information provided, this might be a glitch in IntelliJ's 2021.1.3 Linux JCEF component. Could you check if CodeStream eventually renders if you resize its Tool Window? Alternatively, you can temporarily switch to JxBrowser webview under Settings > Tools > CodeStream > uncheck "Use JCEF webview" (requires restart).
> 
> Let me know if any of these improve the situation for the time being.

Thank you!!! I just spent a few hours reproducing this over and over and for the first time I have a consistent solution for Linux, turning off JCEF webview. If it helps you guys at all, when a project is first created, it shows up fine. If you close the project and re-open it without closing the IDE, it works fine. As soon as you close the project however, there is no way to bring it back without turning off JCEF.

**Comment by iLeW** [comment]
I had the [same issue](https://github.com/TeamCodeStream/codestream/issues/535#issuecomment-921022481). [The solution proposed by @marcelofarias](https://github.com/TeamCodeStream/codestream/issues/642#issuecomment-873116358) solved the problem. Thank you.

**Comment by txomon** [comment]
In my case I was able to observe that while opening the projects from scratch (first IDE instance) doesn't work, without disabling the JCEF webview, if I open another project and then open the one project I'm interested in, the webview will start suddenly rendering

**Comment by ConnahGriffin** [comment]
Using DataSpell and the fix mentioned by @marcelofarias worked as well

**Comment by planteater** [comment]
As a workaround for now, all users of our JetBrains extension on Linux will automatically use JxBrowser for webview rendering instead of JCEF.

**Comment by marcelofarias** [comment]
JCEF should be working on Linux now and that's the preferred engine to render CodeStream. Please make sure "Use JCEF WebView" is checked under Settings > Tools > CodeStream.
