### ISSUE TITLE
DataGrip: Auto-prompt for feedback when committing opens despite setting "No"

### ISSUE THREAD

**Issue by pesse** [TeamCodeStream/codestream#644]
In DataGrip (2021.1.3) I have the setting "Auto-prompt for feedback when committing" set to off, but whenever I commit through the IDE, a feedback window opens.

**Comment by planteater** [comment]
@pesse - If you update to version 11.0.11 of the CodeStream extension it should resolve this. Prior to this version there was a separate mechanism to control the auto-prompt whenever you committed from within the IDE (i.e., a checkbox in the after-commit actions). With version 11.0.11, the toggle at the top of the feedback request form now controls things regardless of where the commit happened.
