### ISSUE TITLE
Codemark comment reply missing `Add Code Block`

### ISSUE THREAD

**Issue by ljubadr** [TeamCodeStream/codestream#645]
When you create a codemark you have a button `Add Code Block`. We can add multiple code blocks to the same comment

But when you are replying to the codemark comment there is no option to `Add Code Block` and you need to copy the code and paste it as markdown which is less than optimal

Could you add option to reply to the codemark comment with the button `Add Code Block`?

EDIT:
vscode: 1.57.1
codestream: 11.0.12
ubuntu 20.04

What info do you need when we submit new issues? Do you have some terminal commands that we can run to collect all the info that you need? Or maybe vscode command that we can run to generate the needed info?

**Comment by planteater** [comment]
@ljubadr - Thanks for the suggestion! We do have on our roadmap the ability to reply to a codemark with either a code block or a suggested change. I don't have a timetable for this just yet, but I'll update you here once things firm up.
