### ISSUE TITLE
"Repo not found in your editor" when remote is not origin

### ISSUE THREAD

**Issue by Ten0** [TeamCodeStream/codestream#646]
If I open repository `Ten0/bar` that is a fork of `foo/bar`, to review a PR from `Somebody/bar/feature1` that asks to be merged in `foo/bar/master`, despite all 3 remotes being registered in my git repository as respectively `origin`, `upstream` and `Somebody`, CodeStream complains that "Repo `bar` not found in your editor. Open it, or clone the repo."

It looks like CodeStream should be able to access the commits and give the diffs in that scenario, and that error message is incorrect.

**Comment by Ten0** [comment]
It looks like this:
https://github.com/TeamCodeStream/codestream/blob/dcbafd09ab05948f3efad8a6c7ad8f7e5cec5edc/shared/ui/store/providerPullRequests/reducer.ts#L835
is the function responsible for that and it looks like it should work, no?

**Comment by bcanzanella** [comment]
@Ten0 in the vscode console, what does the `console.error(`Could not find repo for repoName=${repoName} repoUrl=${repoUrl}`);` error print?

**Comment by Ten0** [comment]
Hmmmmm... I feel bad now: just opened the repository again to answer that question, and it actually worked.
I couldn't find what changed to make it not-work again.
Closing this... until it happens again and I can answer the question. :)
