### ISSUE TITLE
Standalone (w/o codestream server)

### ISSUE THREAD

**Issue by vhdirk** [TeamCodeStream/codestream#649]
We are wondering if there are any plans to deliver a subset of the features in a standalone version that can work without connecting to the codestream cloud service.

We aren't actively using the cloud features (like codemarks); we're using the (vscode) extension primarily for fast access to our issue tracker and code review platform, which are independent from each other.

**Comment by planteater** [comment]
@vhdirk - Thanks for the suggestion! We don't have a standalone service on the roadmap at the moment, but you never know...
