### ISSUE TITLE
UI unusable on ChromeOs

### ISSUE THREAD

**Issue by alerman** [TeamCodeStream/codestream#65]
**Describe the bug**
Picture attached. When trying to use codestream, the UI is not centered. This causes the buttons to send comments to be unviewable

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 1.0.2+2
 - OS + version: Chrome OS 75.0.3770.61
 - IDE + version: Intellij Ultimate 2019.1.3

![Screenshot 2019-06-01 at 9 40 44 AM](https://user-images.githubusercontent.com/119506/58749249-af503f00-8451-11e9-81e3-5dbd593269b2.png)

**Comment by alerman** [comment]
Here is an example after login. 
![Screenshot 2019-06-01 at 9 45 37 AM](https://user-images.githubusercontent.com/119506/58749277-0ce48b80-8452-11e9-9841-b495f52e91cc.png)

**Comment by marcelofarias** [comment]
Try right clicking on the CodeStream tool window handler and selecting "Move To"> "Left Top".

![image](https://user-images.githubusercontent.com/1028286/58749332-d3f8e680-8452-11e9-9701-9ca1b5358215.png)

**Comment by alerman** [comment]
@marcelofarias I tried that...tried each of the possible options in the move to menu with no success

**Comment by marcelofarias** [comment]
@alerman could try to move the CodeStream tool window again and send us your IntelliJ IDEA logs?

https://github.com/TeamCodeStream/CodeStream/wiki/Instructions-for-finding-CodeStream-log-files

**Comment by alerman** [comment]
I will at my next free moment, probably over the weekend

**Comment by alerman** [comment]
[idea-logs-20190609-191404.zip](https://github.com/TeamCodeStream/CodeStream/files/3270095/idea-logs-20190609-191404.zip)

**Comment by planteater** [comment]
@alerman - I know that it's been quite some time, but I was wondering if you were still seeing this issue. Since this issue was reported we've moved to JetBrains' native JCEF for rendering out webview (as long as your running 2020.2 or later of your IDE) and that might have help here.
