### ISSUE TITLE
Markdown code block in description not formatted nicely

### ISSUE THREAD

**Issue by Ali-MRDN47** [TeamCodeStream/codestream#650]
## Bug description
Markdown code block (```) in description is not formatted nicely
## Actions

select a code block on the editor and click on create issue
- enter the title and the assigners and write your description
- on a new line write a markdown code block
- ![CodeStream_Bugs_create_issue](https://user-images.githubusercontent.com/60549126/125050906-b4f1c780-e0a2-11eb-8fb3-5e720da9d2fa.png)

- When opening markdown preview, everything is formatted nicely
- ![CodeStream_Bugs_markdown_preview](https://user-images.githubusercontent.com/60549126/125051031-d8b50d80-e0a2-11eb-9080-a88107e4c84e.png)
- submit the issue and open it to show the result: Formatting is broken
- ![CodeStream_Bugs_open_created_issue](https://user-images.githubusercontent.com/60549126/125051110-ebc7dd80-e0a2-11eb-9071-73c230f2a9a0.png)
## Expectation

A markdown code block in a description is formatted nicely, similar to the markdown preview

**Comment by planteater** [comment]
Fixed in the latest version of the CodeStream extension.
