### ISSUE TITLE
Open CodeStream on a new VSCode tab

### ISSUE THREAD

**Issue by Alireza29675** [TeamCodeStream/codestream#652]
<img width="1440" alt="Screen Shot 2021-07-12 at 4 19 26 PM" src="https://user-images.githubusercontent.com/2771377/125282707-ee3d6800-e32c-11eb-8d37-0147878f8010.png">

As it can be seen, when the CodeStream panel is open there's a little space to review the code. What if we could open CodeStream on a separate tab as we have this option for Terminal?

<img width="508" alt="Screen Shot 2021-07-12 at 4 23 09 PM" src="https://user-images.githubusercontent.com/2771377/125283226-73c11800-e32d-11eb-8a13-8f1f8ad8ea6e.png">

**Comment by planteater** [comment]
Thanks for the feedback @Alireza29675! We've got some UI changes in the plans that should allow you to keep the CodeStream sidebar at a narrower width so that you'll have more room for the diff. I'll update you here when that's ready.
