### ISSUE TITLE
[VS Code] Open CodeStream in editor window instead of explorer

### ISSUE THREAD

**Issue by svipas** [TeamCodeStream/codestream#658]
As title says. Personally I feel it will be way more convenient. Because right now it's hard to manage PR in such small window like explorer.

**Comment by planteater** [comment]
Thanks for the feedback @svipas. Would you consider this to be the same as the following issue?

https://github.com/TeamCodeStream/codestream/issues/652

**Comment by svipas** [comment]
Yes, closing since it's duplicate.
