### ISSUE TITLE
References point to fork of repository

### ISSUE THREAD

**Issue by anderoonies** [TeamCodeStream/codestream#66]
## Description

In the comment messages in Slack, all links to our repository point to a fork (mine), rather than the main repository.

For example, in something like:

---
*andy* commented on code:
> Can we remove this dependency?

[path/to/requirements.txt (Line 123)](bogus_url)
```
dumb_requirement==1.2.3
```
---
the url always points to my fork, regardless of whose Slack client the link is seen in.

**Comment by planteater** [comment]
Hi @anderoonies - We've got some enhancements to the links we provide in the Slack posts that are on our short term roadmap. These should allow you to control which repo the GitHub links go to, as well as allow you to link directly into the IDE/CodeStream.

**Comment by planteater** [comment]
@anderoonies - We working on some change to better support the forking model. Quick question for you. Can you let me know what you typically name the remote that points to the central repository? Is it usually/always named something like "upstream"? Thanks!

**Comment by planteater** [comment]
Fixed in version 8.3.5 of the CodeStream extension (v8.3.6 if you're using a JetBrains IDE).
