### ISSUE TITLE
JetBrains IDE: CodeStream install gives 404.

### ISSUE THREAD

**Issue by ShawnMcCool** [TeamCodeStream/codestream#660]
I'm getting a 404 when trying to click install in the marketplace.

![image](https://user-images.githubusercontent.com/560749/126606604-6cb1c66a-f4b3-4d83-8b86-2c3ac4212a04.png)

![image](https://user-images.githubusercontent.com/560749/126606564-b86aa9d3-6571-4b92-9e10-cd2e500bea3d.png)

AND when I click the link off of the website.

![image](https://user-images.githubusercontent.com/560749/126606736-af176a38-6aab-47dc-b95e-906195ae9c3f.png)

![image](https://user-images.githubusercontent.com/560749/126606791-c1481c7d-21ae-4d6a-a7ee-ed920bb2f613.png)

![image](https://user-images.githubusercontent.com/560749/126606828-ede60f6b-a0b1-41bc-8ba9-ddf9e134b76e.png)

PHPStorm version 2020.2

**Comment by TakaakiAndo1** [comment]
The same thing happens with Webstorm.

**Comment by planteater** [comment]
Thanks for the report! We've brought this up with the JetBrains team and I'll report back once we figure out what's going on.

**Comment by bcanzanella** [comment]
Got confirmation from the folks at JetBrains that this should be fixed now (it works for me now too)
