### ISSUE TITLE
GitLab MR: Group milestones

### ISSUE THREAD

**Issue by julienverrecchia** [TeamCodeStream/codestream#662]
### Context
In GitLab, a milestone may be defined at the project level or at the group level.
Usage example: a milestone may be a sprint iteration for multiple apps.

### Observed
When editing an MR in CodeStream, only milestones defined at the project level are retrieved.
If the "group milestone" is set in GitLab, it is properly displayed.

### Expected
When editing the MR's milestone, retrieve both "group" and "project" milestones.

Thanks

**Comment by planteater** [comment]
Thanks for the feedback @julienverrecchia !
