### ISSUE TITLE
"You don't currently have x repo open" even though that specific repo is opened

### ISSUE THREAD

**Issue by pesse** [TeamCodeStream/codestream#667]
Hi, 

when opening a code comment a coworker created, I get the message "You don't currnetly have the x repo open". It doesn't change even when I locate and select exactly that repo in the same branch the comment was created.

![2021-07-26 08_41_46-SPM_BBBW_V5 2 – README md](https://user-images.githubusercontent.com/8362976/126944843-e3b9f875-80ef-40a5-8620-60dcc598664f.png)

Am I doing something wrong? Are there specific additional requirements?`

Samuel

**Comment by planteater** [comment]
@pesse - Could I trouble you to do a `git remote -v` for that repo and paste the output here? Thanks

**Comment by pesse** [comment]
```
git remote -v
origin  http://w12tfs01/Productive/_git/SPM_BBBW_V5.2 (fetch)
origin  http://w12tfs01/Productive/_git/SPM_BBBW_V5.2 (push)
```

**Comment by pesse** [comment]
I did a couple of tests: The coworker uses the IP-based URL to the repo, I am using the domain-based URL to the repo.
If it is a precondition that the URL to the remote has to be the exact same thing for all CodeStream users of a team, I think it would be great to have that requirement documented.

**Comment by bcanzanella** [comment]
> ```
> git remote -v
> origin  http://w12tfs01/Productive/_git/SPM_BBBW_V5.2 (fetch)
> origin  http://w12tfs01/Productive/_git/SPM_BBBW_V5.2 (push)
> ```

@pesse how are you getting http://w12tfs01 to resolve? is that being served locally? is there a `host` file mapping? I've never seen an http git remote look like that (i've seen plenty of ssh-aliased remotes though)

**Comment by pesse** [comment]
w12tfs01 is just the name of the TFS server, reachable from local network. No host file mapping or anything special, it's really just the dns-name of the server.

**Comment by bcanzanella** [comment]
@pesse can you repeat the issue again, and then send your log files to support@codestream.com? here are the instructions detailing how to find them: https://docs.codestream.com/userguide/faq/client-logs/ thanks.

**Comment by pesse** [comment]
What exactly do you mean by "repeat" the issue? I still have a code comment that will always tell me that I don't have the correct repo open if my remote is using the servername instead of the IP address.
What would you like me to do so you can get meaningful logs?

**Comment by bcanzanella** [comment]
by "repeat" the issue, I just want to make sure that you send logs after completing an action that generates the error you're seeing in the UI. I'm not sure what IDE you're using, but errors don't persist in VSCode across reloads, and JetBrains co-mingles all the errors from all the extensions (so they're harder to follow)

**Comment by planteater** [comment]
@pesse - Put another way, simply open that same codemark, and then generate the log file by going to Help > Collect Logs and Diagnostic Data in your IDE. This will open the finder where you should see a newly created zip file.

**Comment by planteater** [comment]
@pesse - Just wanted to follow up to see if we could get that log file. Thanks!

**Comment by pesse** [comment]
Hey @planteater sorry I could not provide them yet - busy days and now off for a bit. Will try to provide the logs sometime next week.

**Comment by planteater** [comment]
@pesse - I'm going to close this out, but if you get a chance to open that codemark and then generate a log file, send it to support@codestream.com and we'll get right on it. Thanks!
