### ISSUE TITLE
Assign repos to slack channels

### ISSUE THREAD

**Issue by jnjaeschke** [TeamCodeStream/CodeStream#67]
When having Codestream connected to Slack, it seems that for each new Codemark the last frequented channel will be used by default. It would be pretty nice to "connect" a repository to a slack channel: "repoX" --> "#repoX-developers" so that by default all codemarks of a repo are routed to a dedicated channel (and not to, say, "#whats-for-lunch" :) ).

If this is actually possible, I could not find the option in the settings...

**Comment by gsinghab2** [comment]
+1

**Comment by planteater** [comment]
This is part of the most recent version of the CodeStream extension. In the dropdown where you select the channel to share to, look for the gear menu at the top to specify a default channel per repo.
