### ISSUE TITLE
Branch naming was incorrectly created when try to work on a JIRA ticket

### ISSUE THREAD

**Issue by mochadwi** [TeamCodeStream/codestream#670]
<img width="561" alt="Screen Shot 2021-07-27 at 11 56 33 AM" src="https://user-images.githubusercontent.com/7057959/127097740-94897e00-910c-49ef-aab9-ef3e225685df.png">

Based on the above image:

Actual: `sapp-6622--android]-fe]-new-token-mechanism-part4`
Expected: `sapp-6622-[android][fe]-new-token-mechanism-part4`

**Comment by mochadwi** [comment]
Looks like this is an issue from intellij idea

https://youtrack.jetbrains.com/issue/IDEA-274455

Therefore codestream, replace the `[` to `-` instead? cmiiw

**Comment by planteater** [comment]
@mochadwi - I don't think left brackets are allowed in branch names. I tried to manually create a branch name with one on GitHub and it was replaced with a dash.
