### ISSUE TITLE
Open a Merge Request:Cannot read property 'full' of undefined

### ISSUE THREAD

**Issue by yunmengjiuzhang** [TeamCodeStream/codestream#671]
![image](https://user-images.githubusercontent.com/32187913/127157097-e4ceb889-22eb-4773-a520-e2124dea16ac.png)
 

![image](https://user-images.githubusercontent.com/32187913/127157377-b297ce63-f0e5-4608-9f69-78ff10ad12ef.png)

Android Studio version:
![image](https://user-images.githubusercontent.com/32187913/127157503-c39222ba-5b4c-42fb-8f2a-26b530acaf94.png)

codestream version:
![image](https://user-images.githubusercontent.com/32187913/127157460-105f6136-78ba-4a86-8c55-ffffae7a7edc.png)
 
[studio-logs-20210727-205120.zip](https://github.com/TeamCodeStream/codestream/files/6885588/studio-logs-20210727-205120.zip)

**Comment by yunmengjiuzhang** [comment]
![image](https://user-images.githubusercontent.com/32187913/127157991-fc29d2a6-0172-4696-8464-dc85cedc9f35.png)
  
My colleagues are good and can successfully create Mr

**Comment by planteater** [comment]
@yunmengjiuzhang - Unfortunately, CodeStream requires version 12.10 or later.

**Comment by yunmengjiuzhang** [comment]
I didn't find this version on the official website

![企业微信截图_de431a3d-ab4b-482a-87b2-618728b8a08d](https://user-images.githubusercontent.com/32187913/127250712-bd662f14-c357-49ab-bd7d-5a5d4df9408a.png)

**Comment by Callanna** [comment]
@planteater  Can you support it, no? Strongly require compatibility with low version gitlab, after all before lower versions of gitlab can be available. Our company gitlab is very difficult to upgrade. Can you develop and do some compatibility? Otherwise we won't use it, our android team is currently trying out the Codstream phase. Otherwise we might use other tools.

**Comment by planteater** [comment]
Unfortunately, I don't think so. That release is a little over two years old, and the number of elements that we need for MR functionality aren't supported in that release.

**Comment by Callanna** [comment]
we update gitlab to 12.10 .
