### ISSUE TITLE
Error Msg:  having problems connecting to CodeStream.

### ISSUE THREAD

**Issue by Callanna** [TeamCodeStream/codestream#672]
Error Msg: We’re having problems connecting to CodeStream. Hold tight, we’ll keep trying...
If your CodeStream server is behind a firewall, make sure you're connected to your VPN.

I have connected to  VPN, Two Window ,one has error,but another no.
![image](https://user-images.githubusercontent.com/14858726/127437073-42f23993-cf09-4394-8d25-c3fdcd91364c.png)

 CodeStream do not be automatically updated, always prompt errors, causing the whole page is not operable, can only be restarted IEAD. 
 
[idea-logs-20210729-133037.zip](https://github.com/TeamCodeStream/codestream/files/6898097/idea-logs-20210729-133037.zip)

![image](https://user-images.githubusercontent.com/14858726/127436450-ace014e1-d5b9-43c4-aef4-01c6fec7b229.png)

**Comment by phy-lei** [comment]
I also like that, is it codeStream server not work? how can i resolve this problem?

**Comment by jimmyjayp** [comment]
Can you please confirm that you are trying to connect to the CodeStream cloud service?  That error message implies you're using CodeStream On-Prem which we've discontinued. The CodeStream cloud server is at https://api.codestream.com/ .

**Comment by Callanna** [comment]
![image](https://user-images.githubusercontent.com/14858726/127589073-6f712679-c5d8-4e9a-a26c-5e1f63af91f1.png)

We use our own server.  Our own servers can only be accessed on the intranet (the company's network). Every time the computer takes breath screen, there is this prompt. Then it can only be restarted.

**Comment by planteater** [comment]
Unfortunately, CodeStream's on-prem service has been discontinued and is no longer supported.

**Comment by Callanna** [comment]
@planteater  You mean that is  the question of  codestream server? And is it no longer supported later?

**Comment by planteater** [comment]
That is correct.
