### ISSUE TITLE
Request codestream/reviews/create failed with message: Cannot create review. Payload exceeds 10MB

### ISSUE THREAD

**Issue by VityaTape** [TeamCodeStream/codestream#673]
![image](https://user-images.githubusercontent.com/35968938/127465407-05acdc79-96a3-4390-ac74-4d526afb6c87.png)

i cant send request with just 2 files
what i need to do to fix it?
i can fix it by my  self?

**Comment by planteater** [comment]
@VityaTape - Unfortunately it looks like you've come across a bit of a shortcoming with feedback requests, although one that should very rarely be encountered. Long story short, when you create an FR we calculate the diffs relative to the last commit from someone other than yourself. This allows us to construct the diffs on the fly for the person doing the review. In some cases, going back to a commit from someone else may require us to go back so far that the payload for the FR becomes too big. Does this sound like it might be the case here?  We do have a solution for this problem in the works, but my hope is that this isn't something you run into commonly.

**Comment by VityaTape** [comment]
A commit from my reviewer fixed this issue.
Thank you, have a nice day
