### ISSUE TITLE
Err:CodeStream is always loading，Restboot Android Studio  is not available 

### ISSUE THREAD

**Issue by Callanna** [TeamCodeStream/codestream#674]
<img width="493" alt="wecom-temp-77bd1a49f26a8b20aa511d1faa8faf20" src="https://user-images.githubusercontent.com/14858726/127589998-e0a7d70f-4356-472f-9542-5bcf0ca3a920.png">

<img width="335" alt="wecom-temp-889e92055d7be18d374fa5af50de52e8" src="https://user-images.githubusercontent.com/14858726/127590011-c3b37d22-9d3c-4ea9-ba6f-786c18bd9db3.png">

<img width="615" alt="wecom-temp-6125fd5b4fc23e0a5735aea3c52f7eb3" src="https://user-images.githubusercontent.com/14858726/127590020-95676654-7dcd-4644-8271-e830850bbad5.png">

<img width="1277" alt="wecom-temp-2c10fbaaefe98bd27b9897653666b7b5" src="https://user-images.githubusercontent.com/14858726/127590167-3afa2d6a-a632-4a15-8841-899421eab8f5.png">
[studio-logs-20210729-161235.zip](https://github.com/TeamCodeStream/codestream/files/6904736/studio-logs-20210729-161235.zip)

**Comment by planteater** [comment]
@Callanna - The other issue you submitted indicated that you were using CodeStream on-prem, which is no longer supported. Is that this the case here?

**Comment by Callanna** [comment]
Yes, but these are two issues

**Comment by planteater** [comment]
@Callanna - Let's try this. In your IDE go to Preferences/Settings > Tools > CodeStream, and then uncheck the box that says "Use JCEF webview". Restart your IDE and let me know if things are better.

**Comment by Callanna** [comment]
we try it，but No effect, the problem is still there

**Comment by planteater** [comment]
This should be fixed in v11.0.13 of CodeStream's extension for JetBrains.
