### ISSUE TITLE
CodeStream Can't Loading

### ISSUE THREAD

**Issue by ahmetbarut** [TeamCodeStream/codestream#675]
This problem occurred after I updated phpstorm, I uninstalled CodeStream and tried to restore it but the solution didn't work. Indicated in the photo

![image](https://user-images.githubusercontent.com/36641723/127611587-f1743139-9045-4135-8b47-ce0826e2312a.png)

**Comment by kiliw** [comment]
Same for me in Intellij Idea on Linux

**Comment by Falabu** [comment]
Same here, on PhpStorm 2021.2 - #PS-212-4746.100
The corresponding log from Storm
[log.txt](https://github.com/TeamCodeStream/codestream/files/6906097/log.txt)

**Comment by planteater** [comment]
@Falabu @ahmetbarut - Are both of you running Linux as well? If so, this may be related to #642 which has the following JetBrains issue underlying it. https://youtrack.jetbrains.com/issue/IDEA-273222

**Comment by kiliw** [comment]
Thanks @planteater for the hint. https://github.com/TeamCodeStream/codestream/issues/642#issuecomment-873116358 helped

**Comment by ahmetbarut** [comment]
https://github.com/TeamCodeStream/codestream/issues/642#issuecomment-873116358 I solved with this comment
