### ISSUE TITLE
submiting issues taking forever to execute 

### ISSUE THREAD

**Issue by Uncletetsuo** [TeamCodeStream/codestream#676]
Issue Type: <b>Bug</b>

-open a folder within WSL: Ubuntu-20.04 
-open a file 
-selecting a line of code
-generate a issue card with code references
-trying to submit the card is taking forever 

Extension version: 11.0.13
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.68GB free)|
|Process Argv|--crash-reporter-id 22bcef48-6307-4ef3-83b2-2e814634d541|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|Memory (System)|6.07GB (5.55GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30346473

```

</details>

**Comment by Uncletetsuo** [comment]
![image](https://user-images.githubusercontent.com/59348678/128074110-5782f519-f6a0-453e-94d4-cb6eb478f2b4.png)

**Comment by planteater** [comment]
@Uncletetsuo - Just curious, but if you create a CodeStream-only issue (i.e., don't create one on Jira), do you see the same performance issue?

**Comment by Uncletetsuo** [comment]
![Screenshot 2021-08-03 180919](https://user-images.githubusercontent.com/59348678/128097633-74e76bc4-d269-4d9c-9468-4b06d0f5e39b.jpg)
![Screenshot 2021-08-03 180826](https://user-images.githubusercontent.com/59348678/128097634-13adc1ad-4f67-4c44-94f8-731d4c2f41ef.jpg)

here i did the same steps, but i didn't open VS code with my WSL2,

**Comment by Uncletetsuo** [comment]
![Screenshot 2021-08-03 181309](https://user-images.githubusercontent.com/59348678/128097869-262c4590-4ad6-49b5-9abf-51137e84b82b.jpg)
this is the codestream only, it also has the same issue

**Comment by planteater** [comment]
@Uncletetsuo - Could I trouble you for a log file? Reproduce the issue and then open the Output view in VS Code (“View: Toggle Output” from the command palette) and select "CodeStream (Agent)" from the dropdown menu at the top-right. Copy all of the output you see and save it in a text file. If you'd prefer not to share it here, you can send it to me directly at support@codestream.com. Thanks!

**Comment by planteater** [comment]
@Uncletetsuo - Just wanted to follow up to make sure you saw the reply/suggestion above.

**Comment by planteater** [comment]
@Uncletetsuo - I'm going to close this out for now, but if you can a chance to try the solution referenced in JJ's reply above and it doesn't work, please let us know. Thanks.
