### ISSUE TITLE
Unable to find a few Gitlab labels in CodeStream

### ISSUE THREAD

**Issue by mochadwi** [TeamCodeStream/codestream#679]
Context:

We have a label called: `needs-rebase` & `beta-release`

In CodeStream, we were unable to find/search the `needs-rebase` label, but in the other hands `beta-release` is searchable, as shown in the below images:

<img width="1335" alt="Screen Shot 2021-08-05 at 11 04 12 AM" src="https://user-images.githubusercontent.com/7057959/128289322-500e48c4-2b5e-40b8-a7a1-18f249f6f301.png">
<img width="1332" alt="Screen Shot 2021-08-05 at 11 04 23 AM" src="https://user-images.githubusercontent.com/7057959/128289352-81c8484b-ce61-4d3e-8636-e925241b22b4.png">
<img width="394" alt="Screen Shot 2021-08-05 at 11 04 50 AM" src="https://user-images.githubusercontent.com/7057959/128289360-9ba83181-611c-4648-b8b3-b8acbdf94a18.png">
<img width="403" alt="Screen Shot 2021-08-05 at 11 05 05 AM" src="https://user-images.githubusercontent.com/7057959/128289365-5d11dd16-7a9f-4d13-b4f6-d3e2f3a438b2.png">
<img width="260" alt="Screen Shot 2021-08-05 at 11 05 16 AM" src="https://user-images.githubusercontent.com/7057959/128289369-29518673-627c-4d61-a6f1-f03771d798a7.png">
<img width="256" alt="Screen Shot 2021-08-05 at 11 05 30 AM" src="https://user-images.githubusercontent.com/7057959/128289372-ac646da4-a218-4cd3-9e35-d0ee6e731d0e.png">

**Comment by patrick-morgan** [comment]
@mochadwi Just to verify, are these labels and the respective MR you are trying to add them to all on the same project?

**Comment by mochadwi** [comment]
> @mochadwi Just to verify, are these labels and the respective MR you are trying to add them to all on the same project?

yes, the label is exist in the same project, we search the label inside a project (not a group as shown in here)

<img width="839" alt="Screen Shot 2021-08-13 at 10 07 39 AM" src="https://user-images.githubusercontent.com/7057959/129299397-0910d655-b18f-4c2f-a47e-e9c2f6e39a8b.png">
