### ISSUE TITLE
Is it possible to edit custom filter in Issues?

### ISSUE THREAD

**Issue by mochadwi** [TeamCodeStream/codestream#680]
<img width="388" alt="Screen Shot 2021-08-05 at 10 36 02 PM" src="https://user-images.githubusercontent.com/7057959/128378631-68fe5412-3da8-43fd-849e-55751dafef22.png">

There's only 3 Options:

1. Choose one of custom filter (to show the issues)
2. Create Custom Filter
3. Delete Custom Filter

Is it possible to edit custom filter at the moment? or am I missing something (e.g: this is a paid plans?)

**Comment by planteater** [comment]
Thanks for the feedback @mochadwi! I'm going to close this as a duplicate of #457
