### ISSUE TITLE
can't display emoji

### ISSUE THREAD

**Issue by bluelovers** [TeamCodeStream/codestream#681]
![image](https://user-images.githubusercontent.com/167966/128641453-5eb99a1c-83a5-4438-93e3-6ebe69c07b0e.png)

https://github.com/Stepsize/github-integration-demo/pull/1#issuecomment-661968832

**Comment by planteater** [comment]
@bluelovers - Can you confirm for me that you're using a JetBrains IDE? If so, we're working on a fix for this issue. The emoji render in our VS Code extension, but not the JetBrains extension.

**Comment by bluelovers** [comment]
![image](https://user-images.githubusercontent.com/167966/128642948-c3ea8a70-adab-4d31-bbaa-16816e8fec73.png)

![image](https://user-images.githubusercontent.com/167966/128642960-d5b6e736-b95d-413a-b084-1f0cffa7324b.png)

**Comment by planteater** [comment]
Fix in v11.0.14 of CodeStream's extension for JetBrains.
