### ISSUE TITLE
IntelliJ IDEA - Using tasks/changelists for preset commit messages with time spent

### ISSUE THREAD

**Issue by ParogDev** [TeamCodeStream/codestream#683]
IntelliJ IDEA has this feature where you can set tasks ( That I normally retrieve in Jira in the same way that I do with CodeStream )

I can't seem to find an answer on this; When setting up Task server ( Jira in my case ) it lets you auto populate the commit with the current task and other things you choose to be part of your commit message.

![image](https://user-images.githubusercontent.com/14525894/129057557-dac2f71c-75d4-437a-85cf-53cbb2201e73.png)

This makes it so I can start a task that I pull from Jira, complete it and then press `CTRL+K` and it automatically fills the time spent on it, and Jira takes that value from the commit message.

The issue; When I open a CodeStream task, my old task stays there, and the timer keeps going up as well. So every time I change Jira issue, I have to do it both in CodeStream AND in tasks. Any idea if that's intended behavior? I feel it could easily be automated using the "change task" action, as the rest (changelist / empty tasks) popups are handled by the IDE.

**Comment by APshenkin** [comment]
Any Update on this? This is really cool feature from Intellij. Really want to see it here
