### ISSUE TITLE
No obvious way to go back from Forgot Password screen

### ISSUE THREAD

**Issue by bpmct** [TeamCodeStream/CodeStream#69]
**Describe the bug**
Once you enter the forgot password screen, I see no way to exit it. I stay on the screen even when I press the "Sign in" button in the VS Code bottom bar. Or when closing and opening the CodeStream panel.

![434f66b8fcf5a5b46e91a84cc3390ba6](https://user-images.githubusercontent.com/22407953/61074549-f84aca00-a3e5-11e9-9de8-6adf00dc7b4d.png)

**System Info (please complete the following information):**
 - CodeStream 1.3.1
 - Windows 10
 - VS Code 1.33.1

**Comment by planteater** [comment]
Fixed in 1.3.2
