### ISSUE TITLE
PHPStorm - Changing PR remote branch makes the branch unable to be found. Can only PR on default ( production ) branch

### ISSUE THREAD

**Issue by ParogDev** [TeamCodeStream/codestream#693]
When doing a PR, it shows "Production" as the base branch.
![image](https://user-images.githubusercontent.com/14525894/129927765-c1dec088-a581-4312-8fcd-e472bb63b5da.png)

In the dropdown, I see my remote, which is appended by "bitbucket/" 
![image](https://user-images.githubusercontent.com/14525894/129928069-f07038a3-ea01-4e7a-bcc1-9b28abf7b907.png)

No matter what I select from the dropdown, including `bitbucket/production` ( which isn't the same as `production` I guess ) it does a bad request to bitbucket.

![image](https://user-images.githubusercontent.com/14525894/129928224-8ce22138-14d5-43b0-8c5b-b0a595b95e78.png)

I've sent the part of the log where this is happening by email. 

Running on Ubuntu 20.04; PHPStorm 2021.2

**Comment by bcanzanella** [comment]
@ParogDev thanks for the report. we have a pending fix for this.

**Comment by planteater** [comment]
This should be fixed in v11.0.13 of CodeStream's extension for JetBrains.
