### ISSUE TITLE
I would like to create gitlab merge request comments in directly from main code pane

### ISSUE THREAD

**Issue by poul1x** [TeamCodeStream/codestream#694]
I prefer reviewing code looking at main code pane. Switching from main code pane to small "Diff Chunks" is uncomfortable for me. I would like to create GitLab comments directly from main code pane.

![Screenshot (1)](https://user-images.githubusercontent.com/31695750/130149929-48eea7df-3f67-44d2-a52f-1e93d147eb6b.png)

**Comment by planteater** [comment]
@poul1x - I'm not sure if this gets you exactly what you're looking for, but if you switch to either List view or Tree view when viewing the PR (see red circled section labeled "A") you'll get side-by-side diff views in the editor pane. From their you can select a block of code to comment on and then comment either via the context menu ("B") or via the icon that appears to the left of the selection in the CodeStream pane ("C").

<img width="1283" alt="Screen Shot 2021-08-19 at 6 51 27 PM" src="https://user-images.githubusercontent.com/3442587/130154574-bea0a4ca-bb6c-4fcb-b7cf-220653ed7947.png">

**Comment by poul1x** [comment]
Awesome! That I was looking for. Thank you.
