### ISSUE TITLE
Issue filters for Linear

### ISSUE THREAD

**Issue by DraperDanMan** [TeamCodeStream/codestream#696]
Currently, filters are only supported for Github. It's pretty frustrating to see hundreds of issues you have been assigned to that aren't in the current Cycle/Sprint. The ability to filter by @me and cycle:active as well as other filtering like label:bug etc would be a godsend. 

Similar for Jira when the integration gets upgraded.

**Comment by planteater** [comment]
Thanks for the feedback @DraperDanMan! I'll see if we can get this onto the roadmap.
