### ISSUE TITLE
Once joined more than one channel, I can't choose into which channel a comment should go to anymore

### ISSUE THREAD

**Issue by pesse** [TeamCodeStream/CodeStream#70]
**Describe the bug**
When I'm only member of the #general channel, I can choose the label color and the channel where a comment should go to.
Once I joined a second channel, this option is gone and I can only influence it by "being" in the channel I want to post to.

Related: It's also not possible to edit a comment and change channels

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 1.3.1
 - OS + version: Win 10
 - IDE + version: DataGrip 2019.1.4

**Comment by planteater** [comment]
@pesse - Thanks for the report! Looks like we've had a little regression there. We'll get that fixed asap. I wasn't able to reproduce the part about not being able to edit though. Any additional detail you can add on that part?

**Comment by pesse** [comment]
I expressed it badly: I can edit a comment, but I can't change channels/labels there either once belonging to more than one channel

**Comment by planteater** [comment]
@pesse - As a short term workaround, if you create a 3rd channel (which you don't need to actually use), it should bring back the dropdown for channel selection.

**Comment by pesse** [comment]
Ha, thank you for that workaround, didn't try that out :D

**Comment by pesse** [comment]
@planteater I added a 3rd channel, the dropdown is shown again when editing a comment, but if I select a different channel and submit, nothing happens.
Is it not allowed to switch channels for a comment or is this a bug?

**Comment by planteater** [comment]
@pesse - Guess that workaround wasn't such a good workaround after all. Fortunately, we've fixed the issue for real in v1.3.2 of our extension. It's available for Atom, VS Code and VS already, but I'll update you here once that version is out for JetBrains.

**Comment by planteater** [comment]
@pesse - 1.3.2 is now available for JetBrains.

**Comment by pesse** [comment]
Can not confirm the fix.
I now have the dropdowns, yes, but it doesn't work to change them (Version 1.3.3). Nothing happens when I do.

**Comment by planteater** [comment]
@pesse - I just tested myself and it seems to be working. When I create a codemark, I have the dropdown with all of the channels listed, and the codemark correctly appears in whichever channel I select. So, for example, I'm on the Current File tab in CodeStream. I create a codemark, selecting a channel from the dropdown. Then, after I create the codemark I go to the Channels tab, select the given channel, and I do see the codemark appear there. I've tried this with all three of the different channels I have in this test team.

Are you doing anything differently than I am?

**Comment by pesse** [comment]
This is probably a different issue. I made a video to show what I'm doing:

[codestream_not_possible_to_move_comments.zip](https://github.com/TeamCodeStream/CodeStream/files/3431260/codestream_not_possible_to_move_comments.zip)

**Comment by planteater** [comment]
@pesse - OK, I think I see what's going on. In some of the JetBrains IDEs that dropdown is functional when it should be disabled. You should not be able to change a codemark's channel once it's been published, so when you edit it the dropdown should be disabled. That's working correctly in PyCharm, but not in DataGrip or Android Studio. We'll dig it into it. Again, though, the bug here is that the dropdown should not be functional. You can't change the channel selection when editing.

**Comment by pesse** [comment]
Okay, that's a bit unfortunate (because it doesn't allow cleanup/organizing besides labels) but would be okay if the option was disabled then

**Comment by planteater** [comment]
Unrelated, we've got some big changes coming, both in terms of how codemarks are shared, as well as much more powerful labeling and grouping capabilities. I think these changes should address your needs.

**Comment by planteater** [comment]
With our next release (late next week), the channel selector won't be displayed at all when editing.
