### ISSUE TITLE
I am not able to see the codestream conversation on teams and I cannot respond from teams

### ISSUE THREAD

**Issue by SDAdham** [TeamCodeStream/codestream#700]
Hi, I am not able to respond from teams to codestream or see codestream conversation on teams
Sending a test message
![image](https://user-images.githubusercontent.com/11182824/130996027-89e02d8a-08be-417b-9302-463a0df9ab38.png)

On teams (I cannot see the thread neither that I can respond if I tried - it won't show up there at codestream in vscode):
![image](https://user-images.githubusercontent.com/11182824/130996123-a6bda69b-e3c2-425e-b3fc-c7651ac83553.png)

**Comment by planteater** [comment]
@SDAdham - Thanks for reaching out on this. Unfortunately the MS Teams integration doesn't yet support replies, but we do hope to finally add support for that in the coming months. This is already covered in a separate issue, so I'm going to close this one as a duplicate. Please follow this issue:

https://github.com/TeamCodeStream/codestream/issues/159

Thanks!
