### ISSUE TITLE
IJ: Text is duplicated when I do "Paste"

### ISSUE THREAD

**Issue by osipxd** [TeamCodeStream/codestream#702]
### Steps:

1. Copy email to login in CS - <kbd>Ctrl</kbd> + <kbd>C</kbd>
2. Paste the email into a field in the authorization form (just for example, this issue occurs with any text fields) - <kbd>Ctrl</kbd> + <kbd>V</kbd>
3. Look at the field

### Actual result:

Email duplicated

### Expected result:

Email is not duplicated

### Environment

**OS:** macOS 11.2.3\
**IDE:** IDEA Ultimate 2021.2.1\
**Keymap in IDE:** GNOME\
**CodeStream:** jb-11.0.13

**Comment by planteater** [comment]
Fix in v11.0.14 of CodeStream's extension for JetBrains.

**Comment by osipxd** [comment]
Unfortunately, still reproducible for me on `jb-11.0.16`.\
When I trying to paste anything to comment during Code Review.

**Comment by planteater** [comment]
@osipxd - I haven't been able to reproduce this so far. Could you go to the About IntelliJ page, copy that info, and share it with me? Also, just to confirm, are you pasting into a comment in a Feedback Request or in a Merge Request? Thanks

**Comment by osipxd** [comment]
> Also, just to confirm, are you pasting into a comment in a Feedback Request or in a Merge Request?

Both, in MR and in FR. But it is also reproducible for any text field in Code Stream.
If I change the keymap from GNOME to macOS (where `Paste` shortcut is <kbd>Cmd</kbd>+<kbd>V</kbd> instead of <kbd>Ctrl</kbd>+<kbd>V</kbd>), everything works OK.

![image](https://user-images.githubusercontent.com/3684355/135709781-625cf670-e1c4-403a-9945-4576c29b1723.png)
