### ISSUE TITLE
Does codestream keeps a copy of code?

### ISSUE THREAD

**Issue by SDAdham** [TeamCodeStream/codestream#703]
Hi, I'd like to know if codestream keeps a copy of code? Or how do you handle code storage? (from a privacy point of view)

**Comment by planteater** [comment]
Thanks for reaching out @SDAdham. More details, can be found on our security page, but the gist of it is that CodeStream does store snippets of code when you create a Codemark or Feedback Request. For example, when you highlight a block of code and comment on it, that block of code is stored along with the message. CodeStream follows industry standard best practices when it comes to handling these snippets of code (encryption in flight, at rest, etc.).

https://www.codestream.com/security

**Comment by SDAdham** [comment]
@planteater thank you for the response, the link clarified, last question: does codestream share code with 3rd parties?

**Comment by planteater** [comment]
@SDAdham - No, we definitely do not share code with any 3rd parties.

**Comment by SDAdham** [comment]
Thanks @planteater !
