### ISSUE TITLE
IJ: Unified viewer for diffs

### ISSUE THREAD

**Issue by osipxd** [TeamCodeStream/codestream#708]
IDEA provides "Unified viewer" mode for diffs, but diffs opened from CodeStream always use "Side-by-side viewer".
It would be great to be able to use "Unified viewer" for CodeStream reviews so it is more compact.

![image](https://user-images.githubusercontent.com/3684355/132477603-d27a191e-97ef-465d-a110-0f635f3663f0.png)

**Comment by planteater** [comment]
Thanks for the feedback @osipxd!

**Comment by andidev** [comment]
please add support for this! A real pain on laptops screens to have 3 columns shown (before | after | files changed (codestream tool window)).

**Comment by andidev** [comment]
Another point here to support this is because this is how github shows PR diffs and that is what people are used to when switching to code stream and merging PRs.

**Comment by Melodeiro** [comment]
Any hope to get it implemented? Or an option to use the built-in intellij viewer?
