### ISSUE TITLE
When edit comment, change the channel and submit has no effect

### ISSUE THREAD

**Issue by xsoul** [TeamCodeStream/CodeStream#71]
Edit one of the existing comment on #general channel, then change the "post to" with another channel, hit Submit button, the comment does not appear at the selected new channel.

**Comment by planteater** [comment]
@xsoul - Thanks for the report. The actual bug here is that you shouldn't be allowed to change the channel selection when editing a codemark. It looks like we make it appear that you can do this depending on how you get to the edit form. We'll get this fixed up asap.

**Comment by planteater** [comment]
@xsoul -  Fixed in v1.3.3
