### ISSUE TITLE
Leaving a CodeStream team

### ISSUE THREAD

**Issue by jfcieslak** [TeamCodeStream/codestream#714]
It seems that it is not possible for me as a team member to leave a team on my own. can only admin users remove members? It seems to be a huge overlook, unless I am missing something in the GUI and CodeStream docs.

**Comment by planteater** [comment]
Thanks for the feedback @jfcieslak. This is is definitely on our roadmap.

I'm going to close this issue as a dupe of the following one, so you might want to follow it instead.
https://github.com/TeamCodeStream/codestream/issues/163
