### ISSUE TITLE
VS 2019 extension can't redirect to code file from Channel's comment

### ISSUE THREAD

**Issue by xsoul** [TeamCodeStream/CodeStream#72]
Step to reproduce:

1. Install CodeStream visual studio extension for VS 2019.
2. Create a comment to a code block in any channel.
3. Close my code file and go to the channel
4. Click on the comment's quote code, no effect and can't redirect to the previous code file.

Note: VS Code has no issue.

**Comment by planteater** [comment]
@xsoul -  Fixed in v1.3.3
