### ISSUE TITLE
Feedback requests of deleted users

### ISSUE THREAD

**Issue by Arzaroth** [TeamCodeStream/codestream#721]
Hi,

We are currently testing CodeStream with some of my colleagues and one of them decided to delete his account then recreate it, using the same email.

His feedback requests and codemarks now don't belong to anyone.
Even I as an admin cannot reassign or delete them, and no one can amend the feedback requests.

Since deleting users can and will happen at some point (e.g. someone leaving the company), this is a real concern.

In order to do some upkeep, I would like to be able to at least to be to delete those as an admin.

It there another way to achieve this?

**Comment by planteater** [comment]
@Arzaroth - Thanks for the feedback. Allowing admins to delete content is definitely on our roadmap.

In the meantime, I'd be happy to take care of this for you. Either here, or via email to support@codestream.com, let me know which user's FRs/codemarks you'd like to have deleted.

**Comment by Arzaroth** [comment]
Thank you for your answer.

Knowing it's on your roadmap is enough for me. We'll live with it in the meantime, it's no big deal.
