### ISSUE TITLE
Change access token gitlab

### ISSUE THREAD

**Issue by viduc** [TeamCodeStream/codestream#722]
Hello,

I must change my access token in code stream. I dont find where i can do it. I try to remove plugin and new install it but my configuration was reloaded and i cant change it.

Can you help me to find where i can do it?
Thanks

**Comment by planteater** [comment]
Hi @viduc - To disconnect from GitLab, in CodeStream click on your username at the top of the page and select "Integrations". Click on the green tile for GitLab and select "Disconnect". You can then click on the blue GitLab tile to reconnect.
