### ISSUE TITLE
Codestream View in PhpStorm does not match with Gitlab

### ISSUE THREAD

**Issue by svenmarnitz** [TeamCodeStream/codestream#723]
Moin,

the view in phpstorm codestream does not match with the same view in gitlab

![image](https://user-images.githubusercontent.com/85940069/134473907-9b8e4ff5-d325-425f-ba7f-ef6a68268694.png)

![image](https://user-images.githubusercontent.com/85940069/134474080-e4d2340e-c316-4e1e-a5f3-3a89c3dc7210.png)

thx

**Comment by planteater** [comment]
Thanks for the report @svenmarnitz. We're actually pushing out a release right now that will fix this. Should be approved by JetBrains on Monday, but I'll update you here when it's available.

Note that, at least for now, we can't really do much about the Merge button, as GitLab's api doesn't provide us enough info to control its state properly. But, if you try to merge and the MR really can't be, you'll get an error message.

The checkboxes should be addressed by this release though.

**Comment by planteater** [comment]
Fixed in v11.0.16
