### ISSUE TITLE
Network not stable in China

### ISSUE THREAD

**Issue by yun-li** [TeamCodeStream/codestream#725]
Hi, I am very interested in CodeStream and am a heavy user of CodeStream. Our team use CodeSteram extensively and I also recommend a lot of people to use CodeStream.

However, it is a little bit painful to use CodeStream in China. I have to close VScode and reopen it to get it back to the network. I know it is because of the Greate Fire Wall, but is there any plan to set up some server nodes in China? Thanks a lot.

**Comment by planteater** [comment]
Thanks for reaching out @yun-li. Unfortunately, we don't have any near term plans to set up in China. The problem at the moment appears to be that we use PubNub for real-time messaging, and their service is very frequently blocked in China.
