### ISSUE TITLE
Only Show Toast Notifications for MRs/PRs that match the filters configured in the MR/PR Tree View

### ISSUE THREAD

**Issue by c4tachan** [TeamCodeStream/codestream#727]
My organization has automation around the creation of MRs in GitLab. When an MR is created, it is assigned to EVERY developer with access to the repository, regardless of whether it is relevant to them. Because of this, I deleted most of the existing MR filters (such as the "Assigned to Me" and "Awaiting my Review" filters), and created a filter that is specific to the target branches I am working on.
However, I am still getting toast notifications for every MR that is created on our repository.

What I'd like to see enhanced, is to filter the PRs/MRs that generate toast notifications to only those that are available in the filters configured.

**Comment by planteater** [comment]
Thanks for the feedback @c4tachan! And for the PR, which we admittedly haven't had a chance to look at. One thing I did want to confirm though...

>  I am still getting toast notifications for every MR that is created on our repository.

You should only get a toast for a PR where you are added as a reviewer or assignee. Is that the case for you? Or are you literally getting a toast for all PRs, even if you're not a reviwer/assignees?

**Comment by c4tachan** [comment]
When I created PRs on my forked repo in GitHub, I was seeing toast notifications for all of the PRs that I created. I'm not sure exactly why, and I'm not entirely sure that they weren't appearing correctly according to the pre-PR https://github.com/TeamCodeStream/codestream/pull/728 business rules.

As an example, this was my 5th test PR on my fork, and it did create a toast notification; https://github.com/c4tachan/codestream/pull/5

**Comment by c4tachan** [comment]
For testing whether my changes in the PR were working, I deleted all of the base filters (except for "Recent") from the PR Tree View, and added a single filter that only returned open PRs on a specific Base branch (In this case, it was the `Test_Base_Branch`).

PRs I created that were going to merge into the `develop` branch should not have generated any toast notifications once I had completed my changes.

I do find it odd though, because the default queries in `PR_QUERIES` are correct, and work properly when I manually put them into GitHub, so the PRs I made into my own `develop` branch should not have notified even before my changes, because they were neither assigned to me, nor were they requesting a review by me.

It is possible that I am remembering incorrectly however. So please don't put too much effort into re-evaluating those queries or the API that uses them just yet. I'm pretty sure my my PR #728 will provide a fix anyway.

**Comment by planteater** [comment]
@c4tachan - Just wanted to follow up on the questions above. Thanks!

**Comment by planteater** [comment]
I'm working on getting that PR merged in, but obviously would still love to resolve this issue for you as well. I'm going to close this for now, but reach out directly at support@codestream.com
