### ISSUE TITLE
Merge Requests - Certificate has expired

### ISSUE THREAD

**Issue by reyvateil** [TeamCodeStream/codestream#729]
Hello,

I've recently just started using the CodeStream. On day one the CodeStream integration with GitLab worked as intended. Next day I started receiving the error below. The PAT has api scope. 

Due to the date, my suspicion is that the error is somehow related to the recent DST Root CA X3 expiration (30 September 2021) and transition to ISRG Root X1 certificate?

OS: Windows 10
IDE: Visual Studio Code
CS: v11.0.16

```
Request codestream/provider/generic failed with message: request to
https://custom.gitlab.com/api/v4/user failed, reason: certificate has expired
```

**Comment by jimmyjayp** [comment]
Hi @reyvateil  - I need more information to understand the nature of what's going on.  If there's a request in the CodeStream agent that's failing, can you please provide the section of the agent log that reports the request and failure? We don't cache anything about the integration endpoints (certificates, etc...) so it isn't clear to me what exactly is failing. The output you posted above makes me think there's something wrong with gitlab's certificate - which I'm doubtful there is.

This page shows how to see agent logs.
https://docs.codestream.com/userguide/faq/client-logs/

**Comment by reyvateil** [comment]
Including the output of CodeStream agent:
```
[Error - 21:39:14] [2021-10-04 19:39:14:567] ClientRequest.<anonymous>
FetchError: request to https://custom.gitlab.com/api/v4/user failed, reason: certificate has expired
FetchError: request to https://custom.gitlab.com/api/v4/user failed, reason: certificate has expired
    at ClientRequest.<anonymous> (c:\Users\reyvateil\.vscode\extensions\codestream.codestream-11.0.16\dist\agent.js:46:92755)
    at ClientRequest.emit (events.js:223:5)
    at ClientRequest.EventEmitter.emit (domain.js:475:20)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:223:5)
    at TLSSocket.EventEmitter.emit (domain.js:475:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

```

**Comment by planteater** [comment]
@reyvateil - Just wanted to follow up on the question above. Thanks!

**Comment by planteater** [comment]
@reyvateil - I'm going to close this out for now, but please feel free to re-open if you get a chance to follow up. Thanks
