### ISSUE TITLE
Merge Request view is not showing if there is merge conflict

### ISSUE THREAD

**Issue by sohan-dutta** [TeamCodeStream/codestream#734]
**Issue:**

I used codestream to create a merge request in Gitlab. Once the MR got created, in the MR details view it is not showing if there are any merge conflicts, but showing in Gitlab.

![image](https://user-images.githubusercontent.com/80874945/136508332-e1f605d2-9e16-4c78-aaf1-5bcec739d9a9.png)

![image](https://user-images.githubusercontent.com/80874945/136508373-691a84b1-b374-4266-b575-c789e8539c08.png)

**Comment by planteater** [comment]
@sohan-dutta - This should be fixed in v12.6 of the CodeStream extension.
