### ISSUE TITLE
Github Pull Request can be merged when branch protection prevent this

### ISSUE THREAD

**Issue by mccool** [TeamCodeStream/codestream#738]
When branch protection rules are in place at github they are not being enforce in the pull request view in codestream. 

Github site PR
![Screen Shot 2021-10-12 at 4 56 48 PM](https://user-images.githubusercontent.com/648237/137040157-d17f48a5-65a3-485b-977a-7f1cbef71928.png)

Codestream view of the pull request
<img width="900" alt="Screen Shot 2021-10-12 at 4 56 35 PM" src="https://user-images.githubusercontent.com/648237/137039947-10c2ccee-fd8d-46d6-9173-23533280f04a.png">

**Comment by patrick-morgan** [comment]
Hey @mccool, can you send along what specific branch protection rules you have in place? I can see a few of them from the image above, but a screenshot of your specific settings for the repo would be really helpful in getting this fixed. Thanks!

**Comment by planteater** [comment]
@mccool - Just wanted to follow up on Patrick's question above. Thanks.

**Comment by planteater** [comment]
@mccool - I'm going to close this out for now, but if you get a chance to send over the branch protection rules, just shoot them to me at support@codestream.com and we'll dig right in. Thanks

**Comment by mccool** [comment]
Sorry. I didn't get any notifications from the mentions. I'll just send them in an email. 

Thanks!
