### ISSUE TITLE
Extension messes with default settings

### ISSUE THREAD

**Issue by zalanlevai** [TeamCodeStream/CodeStream#74]
**Bug description**
The extension, when freshly installed from the Visual Studio Marketplace, overrides a number of default settings unrelated to the extensions functionality, including (but not limited to) text editor syntax highlighting rules, scrollbar width and others.

The following screenshots illustrate the encountered problems well:
*The **left** side depicts the text editor **before** installing the extension, the **right** side depicts the text editor **after** installing the extension.*

![codestream_comparison_namespaces](https://user-images.githubusercontent.com/12102131/61403367-825acd00-a8d5-11e9-90a4-28885cfcd58c.png)
![codestream_comparison_namespaces2](https://user-images.githubusercontent.com/12102131/61403377-8686ea80-a8d5-11e9-925f-52e7b4126654.png)
![codestream_comparison_code](https://user-images.githubusercontent.com/12102131/61403388-8981db00-a8d5-11e9-8cb4-78c8f0c1e06b.png)

**System Info:**
 - **Version of the CodeStream extension**: 1.3.3.409
 - **OS**: Windows 10 Version 1809 (OS Build 17763.615)
 - **IDE**: Visual Studio 2019 Community 16.1.6

**Log Files**
Not applicable.

**PS**
The bug has already been reported through the following [Twitter post](https://twitter.com/c_tolkien/status/1095061899492786176) in February, 5 months ago.

**Comment by bcanzanella** [comment]
Hi zalanlevai, thanks for the report.

Unfortunately, we're still working on a fix for the editor syntax highlighting issue. We've been in contact with the folks at Microsoft and it's apparently a bug that only an update to Visual Studio can fix.

**Comment by zalanlevai** [comment]
Thank you for the quick reply.

That's certainly strange; here's hoping that the issue can be fixed as soon as possible.

**Comment by planteater** [comment]
Fixed in version 2.1.0
