### ISSUE TITLE
Rider CodeStream window does not render properly after switching resolutions

### ISSUE THREAD

**Issue by PatrickSvenssonSL** [TeamCodeStream/codestream#740]
After switching from an external monitor with lower resolution, to one with larger resolution, the plugin window does not re-scale its content properly.
![image](https://user-images.githubusercontent.com/91597534/137289138-ee09af35-8fd2-4bb5-9b36-ada33e59aabb.png)

**Comment by planteater** [comment]
@PatrickSvenssonSL - Can you let me know what OS you're running?

**Comment by PatrickSvenssonSL** [comment]
Windows 10
