### ISSUE TITLE
Visual Studio 2022 support

### ISSUE THREAD

**Issue by xperiandri** [TeamCodeStream/codestream#742]

**Comment by vladanstrigo** [comment]
Are there any plans to make the extension available for 2022?

**Comment by planteater** [comment]
@vladanstrigo - Definitely. We should begin work on this in the next few weeks. I'll update you here as soon as we have something available.

**Comment by islamal5tib** [comment]
please ASAP  :(
I couldn't update to VS 2022 because of this

**Comment by mrhodel** [comment]
+1

**Comment by uhcl-lund** [comment]
Wish I had more time in my day to help out, but I really need VS2022 support -- just saying...

Do we know if it even "runs" in VS2022?  What issues exist?

**Comment by dev-thinks** [comment]
The only reason still am opening Visual studio 2019. Waiting for CodeStream for VS2022.

**Comment by des2k7** [comment]
also waiting :(

**Comment by trousyt** [comment]
Any update on 2022 support?

**Comment by planteater** [comment]
@trousyt - Work is underway, but I don't think we're quite far enough yet for me to give you a good delivery date. Hopefully soon though.

**Comment by Vectar** [comment]
Would have been great to of had this ready for FutureStack.  Feels like it was pre-maturely announced as announced as being compatible with VS.  I was considering bringing this to the teams to get feedback, but given this, it is simply not viable for our use case. Are we talking weeks, months, or "awaiting prioritization"?

**Comment by planteater** [comment]
@Vectar - Work on this will be starting late June, with an expected delivery late summer.

**Comment by Vectar** [comment]
Ok thanks for the clarification.

**Comment by xperiandri** [comment]
Are you going to embed some UI element into a StatusBar?

**Comment by CalvinAllen** [comment]
> Are you going to embed some UI element into a StatusBar?

Hey, @xperiandri, not sure what you mean here, can you clarify?

**Comment by xperiandri** [comment]
https://github.com/swdotcom/visualstudio-codetime/issues/3

**Comment by xperiandri** [comment]
![image](https://user-images.githubusercontent.com/2365592/141858342-ee1b4de9-2522-4417-9017-52ad35832eca.png)

**Comment by CalvinAllen** [comment]
> [madskristensen/DialToolsForVS#19](https://github.com/madskristensen/DialToolsForVS/issues/19)

I see, thanks for the updates. As far as I'm aware, there are no plans for any functionality like that (though @planteater could confirm for certain). 

Overall, the goal for VS2022 is to support it just like VS2019 (same features, etc.).

**Comment by THammond9** [comment]
Hi, I was wondering if this is still on track for "late summer"?

**Comment by CalvinAllen** [comment]
Started passing around some internal builds for feedback / QA, so we're getting close!

**Comment by CalvinAllen** [comment]
Visual Studio 2022 support has arrived!

https://marketplace.visualstudio.com/items?itemName=CodeStream.codestream-vs-22

Give it a go and let us know if you run into any issues!
