### ISSUE TITLE
Intellij issue with GitLab code reviews

### ISSUE THREAD

**Issue by zaretskyy** [TeamCodeStream/codestream#747]
Hi all, I am getting the following error while trying to do code review on internal GitLab with CodeStream.
![image](https://user-images.githubusercontent.com/3071410/138669944-dd2339f6-1fc7-41a3-92e9-1a5c44b4a02e.png)

I have this repo opened in editor though...

**Comment by planteater** [comment]
@zaretskyy - Can you let me know if you're still seeing this issue with that latest version of the CodeStream extension?

**Comment by planteater** [comment]
@zaretskyy - I'm going to close this out for now, as I'm pretty sure it was addressed by another recent fix, but feel free to reopen if you're still seeing issues. Or reach out to me at support@codestream.com. Thanks
