### ISSUE TITLE
Can't login with Slack

### ISSUE THREAD

**Issue by xsoul** [TeamCodeStream/CodeStream#75]
Hi CodeStream,

I invite my friend with a code, he did accepted the invitation and sign up using Slack. But after that he couldn't login anymore with Slack, the attached is the error screenshot.

Please help.
![hhhhhh](https://user-images.githubusercontent.com/5644701/61616608-7c7d3700-ac9b-11e9-829d-3946ba7afd39.png)

**Comment by planteater** [comment]
@xsoul - Looks like your friend is using a very old version of the codestream extension. Have them update to the latest and that should do it. 

Note, though, that they shouldn’t sign up with slack though if they want to join your team. If you invited them via email, and they got an invitation with a code, that means your team isn’t one connected to Slack and they should not use Slack to sign up. 

When they update their extension they’ll see the option to enter their invitation code.
