### ISSUE TITLE
"The git repository for this review is not currently open in the IDE" even when the repo and the modified files are open in VS Code

### ISSUE THREAD

**Issue by guhan-lily** [TeamCodeStream/codestream#751]
Seeing this error when reviewing a github PR within CodeStream extension in VSCode - "The git repository for this review is not currently open in the IDE" - even when not just the repo but even the files modified in that particular review are open in VS Code.

The problem persists even when I click `locate` and open the already opened repo once again.

Restarting VS Code doesn't fix the issue either.

**Comment by planteater** [comment]
@guhan-lily - We'll likely need a log file to really dig into this. Reproduce the issue and then open the Output view in VS Code (“View: Toggle Output” from the command palette) and select "CodeStream (Agent)" from the dropdown menu at the top-right. Copy all of the output you see and save it in a text file.

If you'd prefer not to share the file here, feel free to send it to me directly at support@codestream.com.

**Comment by planteater** [comment]
@guhan-lily - Just wanted to follow up to see if we could get that log file. Thanks!

**Comment by planteater** [comment]
@guhan-lily - I'm going to close this for now, but if you do get a chance to send over that log file we'll dive right in. Thanks.

**Comment by guhan-lily** [comment]
@planteater I just emailed the log file to support@codestream.com

I noticed a few other things: This happens when I try to open a PR or Feedback request in the codestream tab, when that request is for a repo that is different from the repo that is currently open in the vscode IDE. I am ok if such a cross-repo review is not possible, but the `Locate...` button was misleading since it does nothing when I try to locate and click on the repo of that request.
