### ISSUE TITLE
IJ: `TestUrlHandler` action is incompatible with 2021.3+

### ISSUE THREAD

**Issue by trespasserw** [TeamCodeStream/codestream#752]
These lines:
https://github.com/TeamCodeStream/codestream/blob/b63284f216519394a301ae20e40043e127c8eb14/jb/src/main/kotlin/actions/TestUrlHandler.kt#L17-L18
The API was changed before the plugin was published - that's why backward compatibility wasn't preserved.

If the action is still important, one may use `JBProtocolCommand.execute("idea/codestream/...")` or `CommandLineProcessor.processProtocolCommand("jetbrains://idea/codestream/...")`.

**Comment by planteater** [comment]
Thanks @trespasserw! We'll get this fixed in our next release. I'll update you here as soon as it's available.
