### ISSUE TITLE
Missing NewRelic One Login

### ISSUE THREAD

**Issue by aakarshsingh** [TeamCodeStream/codestream#754]
I was guided to install CodeStream from my NewRelic One account but I don't see the option to log in using my NR One API Key. 

![image](https://user-images.githubusercontent.com/6056091/140708731-4e52bb72-f1c8-46ef-8aa3-93f6161dfdf6.png)

Here is what NR told me to do: 
![image](https://user-images.githubusercontent.com/6056091/140709507-a1685bbc-fad1-45a2-ab01-45c8bf803750.png)

Where is the NewRelic One Connection?

Versions:
Code Stream Plugin: 12.0.4+205
IntelliJ IDEA 2021.2.3 (Ultimate Edition)
Build #IU-212.5457.46, built on October 12, 2021

**Comment by planteater** [comment]
@aakarshsingh - First you’ll need to creat an account with CodeStream, and then you’ll be prompted to connect to New Relic using your api key.

**Comment by aakarshsingh** [comment]
Thank you, that wasn't clear in the instructions over the NR One and that is what stumped me.

**Comment by planteater** [comment]
Thanks for the feedback @aakarshsingh. I'm going to tweak the instructions here to make them clearer.
