### ISSUE TITLE
No option to "Connect to New Relic One"

### ISSUE THREAD

**Issue by hippyjim** [TeamCodeStream/codestream#756]
I've just installed CodeStream on PHPStorm as instructed here: 

![image](https://user-images.githubusercontent.com/1640736/140917672-f45dd438-e39c-4d92-8159-d13314556d0f.png)

And it gives me an API key, but there's nowhere to put it. It says I should choose the "Connect to New Relic One" option, but it wants me to sign in with other accounts (that I don't have). Seems very broken.

![image](https://user-images.githubusercontent.com/1640736/140917709-c7ca570a-4013-44e5-b2d2-bcca9ae28928.png)

**Comment by hippyjim** [comment]
Giving up as it's hammering me with certificate errors and slows my IDE to an unusable crawl

**Comment by planteater** [comment]
@hippyjim - Sorry for the confusion, but you have to sign up for CodeStream first abs then you’ll be prompted to enter your New Relic api key.
