### ISSUE TITLE
Adding a Jira issue with Codemarks has empty Jira Issue Type dropdown to entry fails

### ISSUE THREAD

**Issue by gpinkham** [TeamCodeStream/codestream#757]
I have several Jira projects in Jira Cloud..   I can see them all in the project list Dropdown but whenever I select my project associated with the code project the type drop down is empty (interestingly all the other projects work fine. .but they are not associated with this code project so they are of no use)

Just installed Codestream plugin today so should be the latest.  I am also running VSCode in dev-container (slim linux)

Version: 1.61.1
Commit: c13f1abb110fc756f9b3a6f16670df9cd9d4cf63
Date: 2021-10-14T01:23:30.274Z (3 wks ago)
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

**Comment by planteater** [comment]
@gpinkham - There is one possible explanation for this. Any issue type that has a required field (other titles, description and assignee) that doesn't also have a default value isn't currently supported by CodeStream. I suspect that's probably the case here, in which case we can close this as a dupe of https://github.com/TeamCodeStream/codestream/issues/528

**Comment by gpinkham** [comment]
ok that makes sense.   component is required..   No clue how to add a default to it.   Will do some digging.  I may change the behavior to not required as most people just don't get how to set the component..
