### ISSUE TITLE
Unable to Assign PR in VS Code with Bitbucket

### ISSUE THREAD

**Issue by gpinkham** [TeamCodeStream/codestream#758]
This is likely to be a missing (soon to be) feature instead of some set up/configuration issue but wanted to confirm that.    Either way maybe a feature matrix for PR's would be a good thing to add to the docs.   I don't see anything in the doc that says assigning is limited to github.   
thanks!

**Comment by planteater** [comment]
@gpinkham - That's really covered by the other issue that you commented on...

https://github.com/TeamCodeStream/codestream/issues/372#issuecomment-955791298

We could certainly add the ability to assign a PR as part of creating it, but our current model has that being handled by our broader capabilities of being able to manage and review the PR from the IDE. And we don't yet have that for bitbucket. Just curious, are you BB cloud or on-prem? Unlike with GH and GL, those are two completely distinct products for BB and will require two separate integration efforts on our part.

**Comment by gpinkham** [comment]
I'm using bb cloud.    So just so I follow.  You would create the PR and then edit the PR to add reviewers?
Thanks

**Comment by planteater** [comment]
Yep. We our current GH and GL implementations, when you click to create the PR you're then immediately taken to an in-IDE representation of the PR where you can edit assignees, labels, milestones, etc.
