### ISSUE TITLE
Requested clarification on eventual cost of CodeStream

### ISSUE THREAD

**Issue by brandondrew** [TeamCodeStream/codestream#761]
Almost nowhere (that I've seen) is there any mention of CodeStream coming with a price tag, except indirectly on https://onenr.io/01qwLZvxmj5, where it says 

> A free preview is available for everyone until January 12, 2022!

So is what we're seeing now just a free sample meant to hook us? If so, what will the eventual price be?

**Comment by planteater** [comment]
Hi @brandondrew - Thanks for reaching out, and apologies for the confusion. CodeStream itself is a free service. The part that is in preview is CodeStream's integration with New Relic One. Come January, you'll need to have a paid seat on New Relic One in order to use the integration.
