### ISSUE TITLE
Problem with first installing and attempting to login in CodeStream

### ISSUE THREAD

**Issue by matttychen** [TeamCodeStream/codestream#763]
<img width="1792" alt="Screen Shot 2021-11-12 at 12 37 41 PM" src="https://user-images.githubusercontent.com/52254796/141404906-df8a05dd-70c7-4bab-974f-05366460d79c.png">

This is the issue that I get when I first install CodeStream. I'm not prompted to do anything, it's just stuck on this loading screen.

**Comment by planteater** [comment]
Please refer to the following issue. Unfortunately this is due to a change in the most recent update of VS Code. 

https://github.com/TeamCodeStream/codestream/issues/760
