### ISSUE TITLE
Gitlab open merge request error field 'workInProgress' 

### ISSUE THREAD

**Issue by FouquerYohann** [TeamCodeStream/codestream#764]
Hi 
Error while loading pull request in intelliJ plugin.

`Error Loading Pull Request:
Field 'workInProgress' doesn't exist on type 'MergeRequest': {"response":{"errors":[{"message":"Field 'workInProgress' doesn't exist on type 'MergeRequest'","locations":[{"line":25,"column":7}],"path":["query GetPullRequest","project","mergeRequest","workInProgress"],"extensions":{"code":"undefinedField","typeName":"MergeRequest","fieldName":"workInProgress"}}],"status":200,"headers":{}},"request":{"query":"query GetPullRequest($fullPath: ID!, $iid: String!, $after: String) { project(fullPath: $fullPath) { name mergeRequestsEnabled mergeRequestsFfOnlyEnabled removeSourceBranchAfterMerge mergeRequest(iid: $iid) { approvedBy(first: 50) { nodes { avatarUrl name login: username } } id iid createdAt sourceBranch targetBranch title description webUrl state mergedAt workInProgress reference projectId mergeWhenPipelineSucceeds mergeableDiscussionsState author { name login: username avatarUrl } diffRefs { baseSha headSha startSha } commitCount project { name path webUrl fullPath } sourceProject { name path webUrl fullPath } upvotes downvotes milestone { title id webPath dueDate } subscribed userDiscussionsCount discussionLocked forceRemoveSourceBranch reviewers { nodes { id name login: username avatarUrl } } timeEstimate totalTimeSpent updatedAt userPermissions { adminMergeRequest canMerge } discussions(first: 50, after: $after) { pageInfo { endCursor hasNextPage } nodes { ...discussionFragment } } } }}fragment discussionFragment on Discussion { createdAt id notes { nodes { author { name login: username avatarUrl } body bodyHtml createdAt discussion { id replyId createdAt } id position { x y newLine newPath oldLine oldPath filePath diffRefs { baseSha headSha startSha } } project { name } resolvable resolved resolvedAt resolvedBy { login: username avatarUrl } system systemNoteIconName updatedAt userPermissions { adminNote readNote resolveNote awardEmoji createNote } } } replyId resolvable resolved resolvedAt resolvedBy { login: username avatarUrl }}"}}`

CodeStream version : 12.0.4+205
Gitlab version : {"version":"14.5.0-pre","revision":"4f38c758e73"}

Looks the same as https://github.com/TeamCodeStream/CodeStream/issues/482

**Comment by FouquerYohann** [comment]
https://github.com/TeamCodeStream/codestream/issues/748#issuecomment-966876624

**Comment by planteater** [comment]
Fixed in v12.1
