### ISSUE TITLE
I connected Bitbucket and JIRA and then created a bug and accidentally chose Bitbucket, unable to change to JIRA

### ISSUE THREAD

**Issue by kalani96746** [TeamCodeStream/CodeStream#77]
Steps to reproduce:
BUG #1: Cant change from Bitbucket to JIRA after selecting bitbucket
1) Connect both Bitbucket and JIRA
2) Select a line and create a bug.  Choose Bitbucket from the list.
3) Attempt to change to JIRA (unable to)
BUG 2: First item gets set as the default
4) Disconnect Bitbucket.  JIRA can now be chosen.  Choose JIRA.
5) Reconnect Bitbucket.  Note how on the item and future bugs that Bitbucket remains selected.
<img width="513" alt="Screen Shot 2019-07-24 at 12 41 28 PM" src="https://user-images.githubusercontent.com/2937547/61833577-6ba20200-ae10-11e9-8461-30f17616b085.png">

**Comment by planteater** [comment]
@kalani96746 - At the moment, as you've probably surmised, you can really only be connected to a single issue-tracking service. For now, just disconnect from all but one. The good new, though, is that we've got a release coming as soon as next week that will allow you to be connected to as many as you want and choose between them on an issue by issue basis.
