### ISSUE TITLE
"Repo <repo> not found in your editor. "

### ISSUE THREAD

**Issue by domcc** [TeamCodeStream/codestream#771]
Hello,

When opening a c# solution file in Jetbrains Rider and opening a Gitlab Merge request the Codestream plugin says "repo <repo> not found in your editor. Open it, or clone the repo".

Our solution file is in the root of our repo. If i open the root directory rather than the root solution file then Codestream works as expected however this is not how you open a solution in Rider so none of the code navigation, build etc works.

Is there a way around this?

Thanks,
Dominic

**Comment by marcelofarias** [comment]
Hi @domcc! We'll be glad to find a way to make it work. Could you please send us your Rider logs? In your IDE go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. You can send it to us at support@codestream.com.

**Comment by planteater** [comment]
@domcc - Just wanted to follow up to see if we could get that log file. Thanks.

**Comment by planteater** [comment]
@domcc - I'm going to close this for now, but if you do get a chance to grab that log file please send it to support@codestream.com and we'll get right on this. Thanks
