### ISSUE TITLE
Request codestream/provider/generic failed with message: Must accept GitLab Terms of Service

### ISSUE THREAD

**Issue by alan-wischmeyer-climate** [TeamCodeStream/codestream#772]
I have installed CodeStream in both Intellij IDEA and VSCode and I am receiving the following message, but I was never prompted to agree to any terms of service. How do I resolve this issue? 

"Request codestream/provider/generic failed with message: Must accept GitLab Terms of Service" 

<img width="348" alt="Screen Shot 2021-11-19 at 12 10 38 PM" src="https://user-images.githubusercontent.com/24576409/142671096-83a15206-c233-4dc7-a187-8ccefffc21f3.png">

**Comment by bcanzanella** [comment]
@alan-wischmeyer-climate if you login to your gitlab instance in a web browser, are you prompted to accept the GitLab Terms of Service?

**Comment by alan-wischmeyer-climate** [comment]
I went to the web browser and signed out of GitLab. Then, I signed into to GitLab and no terms of service were presented. Now, we do sign in via Okta.

**Comment by bcanzanella** [comment]
Are you using a self-managed version of GitLab?

If so, this looks like it might be something setup by your GitLab admin: https://docs.gitlab.com/ee/user/admin_area/settings/terms.html

**Comment by alan-wischmeyer-climate** [comment]
I found out we are using a self-managed version of GitLab. I sent the link you provided to our administrator and he confirmed that the terms of service are enabled and required.

**Comment by alan-wischmeyer-climate** [comment]
Our administrator is wondering if my account was enabled before that setting was enforced. He is looking to see if there is a way to enable that on my account.

**Comment by alan-wischmeyer-climate** [comment]
Here is a page that my administrator had me visit.

<img width="1358" alt="Screen Shot 2021-11-19 at 3 44 06 PM" src="https://user-images.githubusercontent.com/24576409/142696332-34bdb581-b83e-4d36-9a06-9cd94625ee06.png">

**Comment by bcanzanella** [comment]
if you continue on that screen and then reload your IDE, does CodeStream still show that error?

**Comment by alan-wischmeyer-climate** [comment]
Yes, I continued on that screen and it took me directly into GitLab. Since then, I have restarted Intellij IDEA and VSCode a number of times, but that error still persists.

**Comment by bcanzanella** [comment]
Ok, let's try something that takes CodeStream out of the equation. 

Can you create a gitlab token from your gitlab instance with an `api` scope, then run this curl command, replacing yourGitLabServer.com host with your gitlab host and replacing XXX with your gitlab token.

```curl --header "PRIVATE-TOKEN: XXXX" "https://yourGitLabServer.com/api/v4/user"```

what kind of response do you see?

**Comment by alan-wischmeyer-climate** [comment]
I changed a lot of information to blah.blah, but here is the structure of the response.
`{
  "id": 114,
  "name": "Blah Blah",
  "username": "blah.blah",
  "state": "active",
  "avatar_url": "https://secure.blah.com/avatar/blah?s=80\u0026d=blah",
  "web_url": "https://gitlab.blah.com/blah.blah",
  "created_at": "2019-09-04T16:08:58.138Z",
  "bio": "",
  "location": null,
  "public_email": "",
  "skype": "",
  "linkedin": "",
  "twitter": "",
  "website_url": "",
  "organization": null,
  "job_title": "",
  "pronouns": null,
  "bot": false,
  "work_information": null,
  "followers": 0,
  "following": 0,
  "local_time": "7:04 PM",
  "last_sign_in_at": "2021-11-19T20:32:07.363Z",
  "confirmed_at": "2019-09-04T16:08:58.107Z",
  "last_activity_on": "2021-11-22",
  "email": "blah.blah@blah.com",
  "theme_id": 1,
  "color_scheme_id": 1,
  "projects_limit": 100000,
  "current_sign_in_at": "2021-11-22T15:33:22.630Z",
  "identities": [
    {
      "provider": "saml",
      "extern_uid": "blah.blah@blah.com",
      "saml_provider_id": null
    }
  ],
  "can_create_group": false,
  "can_create_project": true,
  "two_factor_enabled": false,
  "external": false,
  "private_profile": false,
  "commit_email": "blah.blah@blah.com",
  "shared_runners_minutes_limit": null,
  "extra_shared_runners_minutes_limit": null
}`

**Comment by bcanzanella** [comment]
if you disconnect your GitLab integration on CodeStream, then re-add the your GitLab Self-Managed integration with yourGitLabServer.com host and the token you created with the above test, does CodeStream still fail to list merge requests?

**Comment by alan-wischmeyer-climate** [comment]
Adding the GitLab Self-Managed integration with a token resolved the issue. Thank you for all your time and trouble working through this issue.
