### ISSUE TITLE
`Pending` comments (when preparing a review) are deleted

### ISSUE THREAD

**Issue by pjanowski** [TeamCodeStream/codestream#774]
When I start a PR review and add a comment, after hitting the `Add to Review` button, the comment is not saved. I completed a major review in this way without noticing it and at then end when I submitted my review, all of the comments except one were gone. This has not happened before and I'm not sure what the cause is but it's a huge miss: user has to redo the entire review and loses trust in `Codestream`.

**Comment by planteater** [comment]
@pjanowski - This has been fixed in v12.2. Looks like it was due to a schema change by GitHub.

**Comment by pjanowski** [comment]
Thanks for the quick fix!
