### ISSUE TITLE
Markdown in CodeStream seems improperly display in Slack thread

### ISSUE THREAD

**Issue by mochadwi** [TeamCodeStream/codestream#775]
CodeStream display the proper markdown

<img width="409" alt="Screen Shot 2021-11-22 at 12 13 01 PM" src="https://user-images.githubusercontent.com/7057959/142804608-546a9dd6-34f9-4db1-87d4-218a8b0e2155.png"/>

Slack seems showing extra `div` instead
<img width="1082" alt="Screen Shot 2021-11-22 at 12 13 18 PM" src="https://user-images.githubusercontent.com/7057959/142804601-8ae60f12-3fdc-4b34-bd01-4096d2813dd2.png"
/>

**Comment by planteater** [comment]
Thanks for the report @mochadwi. I haven't been able to reproduce the issue though. Any chance you could share a screenshot of the underlying markdown?

**Comment by planteater** [comment]
@mochadwi I'm going to close this for now, but if you're able to get me some more details on what the actual markdown post looked like you can either re-open or send it to me at support@codestream.com. Thanks.
