### ISSUE TITLE
VSCODE PR fails if forked-repo branch has same name as the (base) repo branch

### ISSUE THREAD

**Issue by diatech** [TeamCodeStream/codestream#778]
When forked branch's name is the same as the upstream branch. The pull request pane will keep failing and asking "Choose different branches above to open a pull request"

The original git pull-request extension does not have the issue.

**Comment by planteater** [comment]
@diatech - This has been fixed in v12.4 of the CodeStream extension. If you're using a JetBrains IDE it may take a day or so to get approved.
