### ISSUE TITLE
DataGrip: When adding a Comment/Issue via key-shortcut you don't get "real" focus/can not type

### ISSUE THREAD

**Issue by pesse** [TeamCodeStream/CodeStream#78]
**Describe the bug**
I'm in the editor, mark a code area, hit the key-shortcuts for "add comment" but can't continue typing. The cursor "shows" in the comment-box, but I don't have real focus so I have to click into the comment-box first to be able to type

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 1.3.3
 - OS + version: Win 10
 - IDE + version: DataGrip 2019.1.4

**Comment by planteater** [comment]
@pesse - Fixed in v1.3.4
