### ISSUE TITLE
Not work icon  in gitlab 

### ISSUE THREAD

**Issue by meded90** [TeamCodeStream/codestream#782]
![gg-frontend – mixins scss 2021-11-30 16-17-00](https://user-images.githubusercontent.com/1769500/144054372-fed80828-2a26-46bf-8bf9-b35bddbc80f9.jpg)

**Comment by planteater** [comment]
@meded90 - Is this GitLab cloud or GitLab Self-Managed?

**Comment by planteater** [comment]
@meded90 - I'm going to close this for now, but please reach out to me at support@codestream.com with more info when you get a chance.
