### ISSUE TITLE
I was disappointed not to see Gogs

### ISSUE THREAD

**Issue by 514759979** [TeamCodeStream/codestream#789]
Hope you can support Gogs, thank you

**Comment by planteater** [comment]
@514759979 Thanks for reaching out on this. While I would love to leave this open as a feature request, the reality is that supporting new code hosts is a huge effort and there's almost no chance that we'd end up supporting Gogs. 

While you may not be able to use CodeStream to manage your pull requests, there's lots of other great features that you can still take advantage of... like discussing code with Codemarks and reviewing work-in-progress with Feedback requests.
