### ISSUE TITLE
Support for branches

### ISSUE THREAD

**Issue by pesse** [TeamCodeStream/CodeStream#79]
**Describe the bug**
Maybe I am just doing it wrong, but what deeply confuses me is that I have no indication of the branch a comment or issue was created on.
The chance is very high that someone comments on an issue in a branch which is gone in a different branch and I can not really see why I'm getting different information.

IMO, when I'm in a branch different to the one a comment/issue was created, I should get a warning about that.

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 1.3.3
 - OS + version: Win 10
 - IDE + version: DataGrip 2019.1.4

**Comment by planteater** [comment]
@pesse - Thanks for the feedback here. Triggered some internal discussion and I think we'll be able to get branch info included with codemarks sometime in the next couple of weeks. I'll update this issue once it's out there.

**Comment by planteater** [comment]
Version 2.1.2 now includes branch info when there's a diff between the code referenced in the codemark and what you have locally.
