### ISSUE TITLE
Add possibility to add multiple reviewers to Gitlab MR

### ISSUE THREAD

**Issue by Mexator** [TeamCodeStream/codestream#790]
I am using CodeStream plugin for Android Studio with Gitlab self-hosted. When I open a Merge Request with the plugin, I want to add more than one reviewer for the MR. But I cannot - after I add reviewer, it replaces already added reviewer. So I must enter Gitlab web UI to add reviewers

**Comment by planteater** [comment]
@Mexator - Unfortunately GitLab's api doesn't allow us to determine whether you have support for multiple reviewers so you have to explicitly turn on that support. Look for the option under the gear menu in the Merge Requests section of the CodeStream pane.

![Screen Shot 2021-12-16 at 11 33 38 AM](https://user-images.githubusercontent.com/3442587/146411354-539bd79c-d981-4578-9abe-56a1428d2a14.png)
