### ISSUE TITLE
Please fix the very obviously problematic button and text colors 

### ISSUE THREAD

**Issue by StingyJack** [TeamCodeStream/codestream#796]
![image](https://user-images.githubusercontent.com/15381181/147373413-87b46b39-76a1-47f6-a742-920eb71c371b.png)
Black text on black background is incredibly hard to read.   Please just use normal colors for buttons and text.

**Comment by StingyJack** [comment]
At least one button shows in a way I can read it. 
![image](https://user-images.githubusercontent.com/15381181/147373479-95c08d68-111b-453f-a240-09e68ca34e41.png)

**Comment by planteater** [comment]
@StingyJack - The CodeStream colors should honor whatever theme you have selected in your IDE. Can you let me know which IDE you're using and what color theme you have selected? Thanks.

**Comment by StingyJack** [comment]
VS 2019
Theme is "Blue (Extra Contrast)", Windows is not using high contrast settings.   I have been known to customize colors in the past but I dont think I've had to do that with VS2019 or later.  If there are specific color elements I should look for WRT those buttons, lmk and I can try to tweak them
![image](https://user-images.githubusercontent.com/15381181/147390777-e0a98288-d5de-4204-8a4c-7b603587616d.png)

**Comment by StingyJack** [comment]
@planteater - I tried a few themes to see what may be different, screenshots are at the end.
Switching it to Dark Mode makes the buttons readable, but then the overall IDE is harder to see for me.
Switching to Light makes the buttons less readable but still a "dark on still too dark" color contrast (passes wcag AA but not AAA), and the IDE is blinding otherwise.
Choosing Blue results in the same hard to see representation I get with my usual theme choice (Blue Extra Contrast). This is the default theme for VS out of the box, and since Dark works so well and nothing else does, it looks like everyone working on this is using dark mode.  

Dark
![image](https://user-images.githubusercontent.com/15381181/147398414-db4117eb-d8f9-49dd-8c64-8bedabdf0c68.png)

Light
![image](https://user-images.githubusercontent.com/15381181/147398439-686ab26b-4318-4b9d-accd-d52ea4d02b1b.png)

Blue or Blue (Extra Contrast)
![image](https://user-images.githubusercontent.com/15381181/147398464-f89e39b5-f330-4a95-98cd-8e466b7998be.png)

**Comment by StingyJack** [comment]
@planteater on a side note, I did try to figure this out but could only get as far as seeing the web view control' stylesheets. Nothing in there looks like its reading a theme from VS

**Comment by planteater** [comment]
Thanks for all the leg work @StingyJack! We'll get this figured out. We've got a lot of people out for the holidays this week, so might not be any movement here until next week.

**Comment by planteater** [comment]
@StingyJack - We've got a fix ready for this issue. I don't have a specific release date yet, but should be no later than Monday. I'll update you here once it's available.

**Comment by planteater** [comment]
@StingyJack - This should be fixed in v12.6 of the CodeStream extension.

**Comment by StingyJack** [comment]
Yes, much nicer now. thank you. 
![image](https://user-images.githubusercontent.com/15381181/148419675-41ef4491-05bf-4b74-811e-8a82dbb3e9e6.png)
