### ISSUE TITLE
Can't login with slack

### ISSUE THREAD

**Issue by MrToxy** [TeamCodeStream/CodeStream#80]
**Describe the bug**
I try to login with slack, and after code stream redirects me to install the app on slack, after clicking on install I always get this error:

Authentication failed
We were not able to authenticate you with Slack (error: PRVD-1002). Contact support if you need assistance, or return to your IDE to try again.

No matter what I do.

**System Info (please complete the following information):**
 - Version of the CodeStream extension: latttest
 - OS + version: mac os, latest
 - IDE + version: vscode latest

**Comment by planteater** [comment]
@MrToxy - We'll dig into this asap. In order to do so I need to know the name of the Slack workspace you're authenticating with, as well as your email address in that workspace. If you'd prefer, you can send that info to me at support@codestream.com. Thanks!

**Comment by MrToxy** [comment]
@planteater  I'm trying to connect to `companyfactory.slack.com` and the email I'm using is `joao@juicee.io`

**Comment by planteater** [comment]
@MrToxy - Got it. I think I see the issue now. Looks like joao@juicee.io is already on a Slack-connected CodeStream team called "juicee". I assume that's a different workspace than companyfactory. Unfortunately, at the moment, a single CodeStream user account can only be on one Slack-connected team. This restrictions should go away in the next month or so, but for now If you need to have CodeStream teams for both of those Slack workspaces you would need to change your email address in the companyfactory workspace.

**Comment by MrToxy** [comment]
@planteater thank you for the swift reply! I will change the email for that workspace as you suggested and  report back.

Thank  you

**Comment by MrToxy** [comment]
@planteater quick update, that worked perfectly. thanks again.

A quick suggestion would be to add a meaningful error message instead of an error code
