### ISSUE TITLE
Android Studio issue with self managed GitLab

### ISSUE THREAD

**Issue by ibitton** [TeamCodeStream/codestream#817]
I'm able to sign in apparently as comments are working but I'm getting the following error message under "Load MR from URL" in the AS plugin:
`Request codestream/provider/generic failed with message: invalid json response body at <self-managed-gitlab-repo>/users/sign_in reason: Unexpected token < in JSON at position 0`

**Comment by ibitton** [comment]
Sent. Thanks

**Comment by planteater** [comment]
@ibitton - Sent you an email, but it seems like there might be an issue with the base URL you entered. I'll close this for now and we can keep going via email if that turns out not to be the issue.
