### ISSUE TITLE
How to add Entities to the list in Observability?

### ISSUE THREAD

**Issue by StingyJack** [TeamCodeStream/codestream#827]
I can see DEV, QC, and one PROD app in the entities list.  I'm missing our UAT entries and some PROD entries. 
![image](https://user-images.githubusercontent.com/15381181/150582549-3c2c8228-5b83-496b-b5c6-46521be31447.png)

I dont see any buttons for attaching entities as is depicted in the docs. https://docs.newrelic.com/docs/codestream/codestream-ui-overview/observability-section/

**Comment by planteater** [comment]
@StingyJack - If there are additional entities that need to be associated with that repo, you'll need to make the association via the service summary page on New Relic One. Look for the Repositories section at the bottom-right side of that page.
