### ISSUE TITLE
Jetbrains :: Bookmarks Position Incorrect After Their Initial Creation

### ISSUE THREAD

**Issue by lots0logs** [TeamCodeStream/CodeStream#83]
**Describe the bug**
When I click a bookmark that I created in a previous session it goes to the incorrect location of the code.

**System Info (please complete the following information):**
 - CodeStream 2.0.0+1
 - Arch Linux
 - PHPStorm 2019.2 (192.5728.108)

**Log Files**
* [phpstorm-logs-20190806-163417.zip](https://github.com/TeamCodeStream/CodeStream/files/3474255/phpstorm-logs-20190806-163417.zip)

**Comment by planteater** [comment]
@lots0logs - Looks like you generated that log file prior to updating to the latest version of CodeStream. Would you mind generating a new log file? Also, if you don't mind, look for the instructions here to create a more verbose log file. Thanks!

**Comment by lots0logs** [comment]
Its working properly now :man_facepalming:
