### ISSUE TITLE
Support for Apple Silicon (universal binary)

### ISSUE THREAD

**Issue by mochadwi** [TeamCodeStream/codestream#837]
Google recently release support for Apple Silicon for their Platform Tools: https://issuetracker.google.com/issues/160004878#comment22

When I check the _**Activity Monitor**_ seems **_CodeStream_** using an Intel version, based on below images:

<img width="657" alt="Screen Shot 2022-01-27 at 11 37 55 AM" src="https://user-images.githubusercontent.com/7057959/151292894-a047e492-31a5-4f67-8d18-1285a79b1b69.png">

Would be nice if CodeStream team also support this ❤️

**Comment by planteater** [comment]
@mochadwi - This should be addressed in v13.0 of the CodeStream extension.
