### ISSUE TITLE
Atom Proxy SSL Verification cant be deactivated

### ISSUE THREAD

**Issue by schwatvogel** [TeamCodeStream/CodeStream#84]
**Button 'Proxy Strict S S L' has no function**
likely related to #11. Proxy as such seems to work, but 
deactivating this Button whilst using a Proxy, that intercept SSL traffic (and therefore provides a erroneous SSL Cert to the client), does not have any effect. You still get a Login Timeout(no errro is displayed in atom).
Javascript console has the relevant error message:
`Request codestream/registration failed with message: Registration failed:
request to https://api.codestream.com/no-auth/register failed, reason: unable to get local issuer certificate`

**System Info :**
 - Version of the CodeStream extension: [2.0.0] - 2019-8-1
 - OS + version: [Archlinux]
 - IDE + version: [Atom 1.39.1]

**Log Exerps**

`Uncaught (in promise) ResponseError: Request codestream/registration failed with message: Registration failed:
request to https://api.codestream.com/no-auth/register failed, reason: unable to get local issuer certificate
    at /home/user/.atom/packages/codestream/dist/codestream.js:1:9701
    at /home/user/.atom/packages/codestream/dist/codestream.js:1:9995
    at Immediate.E.size.setImmediate (/home/user/.atom/packages/codestream/dist/codestream.js:1:10356)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)`

**Comment by akonwi** [comment]
@schwatvogel After changing that setting you should reload the window. Have you tried again after restarting the window?

**Comment by schwatvogel** [comment]
@akonwi yes, i restarted the plugin, and after that did not make a difference, i restarted the whole atom app. STill no difference

**Comment by akonwi** [comment]
@schwatvogel So the Strict SSL option only applies if Proxy Support is set as "override" and you have a Proxy URL. Do you have both of those set as well?

**Comment by schwatvogel** [comment]
arg, sorry for beeing so unspecific. I had proxy settings to `on`not `override` Since it worked with the prexy settings i entered in the field, i assumed .. well anyhow. That fixed it (mostly, when using slack as a backend the avatars are missing, but i dont think thats the issue here

regards and thanks again
