### ISSUE TITLE
Codemarks position themselves at the end of file

### ISSUE THREAD

**Issue by Arzaroth** [TeamCodeStream/codestream#844]
When adding codemarks to certain files (big ones, I've yet to find a threshold but it occurs often for one in particular with >2000 lines), their positions are somewhat broken.

What tends to happen is the first few work without a itch, then after a while adding a new codemark forces the position of the previous one (in the same file) to the end of said file.
I've tried to reposition manually, but it gets forced at the end of the file all the same if I were to add a new codemark.

The code range themselves are fine and show the correct line number.

**Comment by marcelofarias** [comment]
Hi @Arzaroth! Could you add more color about the state of the file when the codemarks were created (did you have uncommitted changes, for instance?). Also, does the problem occur immediately after the codemark creation or after editing and/or committing the file?

Also, could you please send us your IDE logs as described here: https://docs.newrelic.com/docs/codestream/troubleshooting/client-logs

Thanks!

**Comment by Arzaroth** [comment]
The file (and the whole repository for that matter) was clean : No uncommitted changes, no commits waiting to be pulled or pushed.

I've sent you the log file to your support address (support@codestream.com) as it may or may not contain sensitive information.

Cheers.

**Comment by Arzaroth** [comment]
I'll add that after closing then reopening VSCode, some of the previously bugged codemarks were working again, but not all of them.

**Comment by planteater** [comment]
@Arzaroth - This issue should be fixed in v12.12 of the CodeStream extension.
