### ISSUE TITLE
After latest update phpstorm + codestream + slack notification no longer works

### ISSUE THREAD

**Issue by GimpMaster** [TeamCodeStream/codestream#847]
It seems like my slack integration no longer works. It says I'm connected to my Team and my slack workspace. However it can't pull in any channels so it refuses to post to slack. 

I tried re-authenticating but it still doesn't seem to work. Any thoughts on what to try next?

**Comment by planteater** [comment]
@GimpMaster - Can you try the following.... disconnect from Slack via the Integrations page, restart your IDE, and then reconnect. If that doesn't do the trick, a log file would be appreciated. Instructions for generating one can be found here.

https://docs.newrelic.com/docs/codestream/troubleshooting/client-logs/

Thanks!

**Comment by planteater** [comment]
@GimpMaster - Just wanted to follow up to see if that worked for you. Thanks

**Comment by GimpMaster** [comment]
@planteater - I just tried your steps. Disconnected. Restarted. Reconnected. Unfortanetely all i get is the screenshot below

![image](https://user-images.githubusercontent.com/7818200/153066815-d9d8e529-c1c1-41ab-8b3c-0f26ec5fa10e.png)


Basically it says I'm connected, but it asks what channel I want to post in and I can't downselect. I will try to generate some client-logs now.

**Comment by GimpMaster** [comment]
Ok, I emailed the phpstorm client logs to support@codestream.com and referrenced this issue url. Thanks!

**Comment by planteater** [comment]
@GimpMaster - Could I trouble you to update to v12.12 of the CodeStream extension and let me know if the problem persists? If so, another log file would be great. Thanks!

**Comment by GimpMaster** [comment]
Hey David. I'm on v12.11.0+219 and it appears to be working fine now.

I'll update here and try..........

That version seems to work as well.

Thank you for following up.

Josh
