### ISSUE TITLE
Unable to Change Username

### ISSUE THREAD

**Issue by makertech81** [TeamCodeStream/CodeStream#85]
Hey, I was wondering how I can change my username, because I entered in the wrong thing thinking it was a different field.  Is there anyway how to do this? 

Thanks,
TJ

**Comment by planteater** [comment]
@makertech81 - We'll soon have tools in place for you to do this on your own, but in the meantime, just let me know the username you'd like and I'll take care of it. You can also email it to us at support@codestream.com if you'd prefer.
