### ISSUE TITLE
App.codestream.com down

### ISSUE THREAD

**Issue by matthijsthoolen** [TeamCodeStream/CodeStream#86]
**Describe the bug**
I try to login with Slack from PHPStorm, when I click the link to authenticate (https://app.codestream.com/service-auth/slack?state=**STATEREMOVED**), i get a browser error (domain not found). 

**System Info (please complete the following information):**
 - Version of the CodeStream extension: 2.0.1+1 (according to PHPstorm marketplace, 1.0.2+2 according to codestream...)
 - OS + version: Windows 10
 - IDE + version: PHPStorm 2019.2

**Comment by planteater** [comment]
Looks like you’re actually running the old version of the extension, which points to a web app that no longer exists. If you update to 2.0.1 you should be good to go.

**Comment by matthijsthoolen** [comment]
@planteater no, still not working. Time-out is extremely fast, but even if the browser manages to complete the sign-in before the time-out, I do not get signed in and still get a time-out.

**Comment by planteater** [comment]
@matthijsthoolen - Just to confirm, when you get redirected to the web you're no longer hitting an app.codestream.com URL and you're actually seeing the Slack auth page?

**Comment by planteater** [comment]
Assuming that's the case, could I trouble you to send us a log file? Instructions for finding the log file can be found here: https://github.com/TeamCodeStream/CodeStream/wiki/Instructions-for-finding-CodeStream-log-files

Feel free to email it to support@codestream.com if you'd prefer.

**Comment by planteater** [comment]
@matthijsthoolen - Just wanted to follow up to see if you send over that log file. We'll dig into asap and figure this out for you!

**Comment by matthijsthoolen** [comment]
> @matthijsthoolen - Just to confirm, when you get redirected to the web you're no longer hitting an app.codestream.com URL and you're actually seeing the Slack auth page?

I get the slack 'confirm new app' window, and even get a mail from slack that a new app has been added. Everytime I do a 'retry' a new instance of the app is added to slack. I also get a 'All set' message in the browser from codestream.

**Comment by matthijsthoolen** [comment]
@planteater i emailed the logs to the mail as requested. Seems that storm can't reach the requested URL. I tried to disable my proxy settings, but that didn't solve it.

**Comment by jimmyjayp** [comment]
Can you verify that this works in a browser ?
https://api.codestream.com/no-auth/status

**Comment by matthijsthoolen** [comment]
@jimmyjayp verified and works. Also works from phpstorm (System settings -> HTTP Proxy has a check connection option).

DNS is already on 8.8.8.8., 

When I select another workspace, I get authentication failed. On my main workspace authentication in Slack works. Only the connection back to Codestream in PHPStorm isn't working. 

I was using codestream already, so it did work previously.

On another desktop (and also another slack workspace), the connection is working.

**Comment by akonwi** [comment]
@matthijsthoolen So on this same computer where you see this error, you had logged in successfully before?

**Comment by akonwi** [comment]
You mentioned you tried to disable your proxy settings. Did you also specifically disable proxy support in the CodeStream plugin settings? If not, can you do that and try again? If it continues to fail, we'll need to see the new logs too.

**Comment by matthijsthoolen** [comment]
@akonwi 

Everytime I open phpstorm with codestream, the login is already failed (only a 'try again' button). I also get the following message:

![image](https://user-images.githubusercontent.com/1309536/63323522-4aa4d200-c326-11e9-9f01-f6ab323c3243.png)


I disabled proxy support in codestream settings, still no luck. Will try to reinstall now.

**Comment by matthijsthoolen** [comment]
Tried a reinstall for codestream. Instantly gives a 'try again', but 'try again' seemed to work this time :) 

Finally logged back in 👍 

I have no clue why this happened, the 'timeline':
- Started using codestream almost from day one of jetbrains plugin release. Did work, only sometimes quite slow (no connection to slack?)
- Multiple updates for plugin, needed to re-login sometimes. But still working.
- I think it stopped working after the 2.0 version. 
- Update of plugin, remove all codestream app installs in Slack etc. all did not work
- Reinstall did the trick :)

**Comment by planteater** [comment]
@matthijsthoolen - I'm glad that you're finally back in! Note that the PRV-1002 error could have been a separate issue. It typically means that you're trying to sign in with a Slack workspace different than the one you signed up with. In any case, hopefully smooth sailing from here!
