### ISSUE TITLE
what problem 

### ISSUE THREAD

**Issue by xuweiweiwoaini** [TeamCodeStream/CodeStream#87]
![image](https://user-images.githubusercontent.com/25677587/63070411-a7327680-bf4d-11e9-85e7-b0e9b1158863.png)

**Comment by xuweiweiwoaini** [comment]
i can not submit,what problem ??

**Comment by akonwi** [comment]
Are you able to click on the submit button? If you are, is it just unresponsive or does it show a loading spinner indefinitely? 

Your log file could be helpful. Instructions for finding the log file can be found here: https://github.com/TeamCodeStream/CodeStream/wiki/Instructions-for-finding-CodeStream-log-files. Feel free to email it to support@codestream.com if you'd prefer with this issue number as the subject.

**Comment by xuweiweiwoaini** [comment]
I think it may be a network problem, after all, I live in the Eastern Hemisphere.

**Comment by xuweiweiwoaini** [comment]
I think it may be a network problem. After all, I live in the Eastern Hemisphere, and its country is China! !
