### ISSUE TITLE
Cannot connect to on-premise GitLab in VS2019 extension

### ISSUE THREAD

**Issue by lukasf** [TeamCodeStream/codestream#871]
I have added the GitLab Integration in VS2019 extension and entered the GitLab on-premise server URI and API Key. However, the "MERGE REQUESTS" area shows the following error:

`Request codestream/provider/generic failed with message: request to <GitLabServer>/api/v4/user failed, reason: unable to verify the first certificate`

When I enter the URI into a browser window, it shows me my current user info as json. So the URI is correct and the browser does not have any issue with the certificatss.

**Comment by planteater** [comment]
Hi @lukasf - Can you let me know what version of GLSM you're running? Instructions can be found here:

https://docs.newrelic.com/docs/codestream/troubleshooting/glsm-version

More than likely we'll also need a log file, and those instructions are here:

https://docs.newrelic.com/docs/codestream/troubleshooting/client-logs

Thanks!

**Comment by planteater** [comment]
@lukasf - Actually, you might want to check this article first in case this is a proxy / self-signed certificate issue.

https://docs.newrelic.com/docs/codestream/troubleshooting/proxy-support

**Comment by lukasf** [comment]
@planteater Thank you! Indeed after disabling strict SSL verification, things are working well now.
