### ISSUE TITLE
isolate {id} from {title} when you set up a branch from Jira issues

### ISSUE THREAD

**Issue by jyzhao** [TeamCodeStream/codestream#872]
At this moment, when you set up a branch from Jira issues, and you specify the branch name format, `{title}` actually contains `{id}`
for example, if I specify the branch name format to be `feat: {id} {title}`, it will be `feat:__jira-123__jira-123__enable-dark-mode-on-the-ui`
Is there any way to remove "id" from "title"

**Comment by planteater** [comment]
@jyzhao - Unfortunately there isn't. For whatever reason, Jira includes the id in the title. These are the values we get back from them directly.

**Comment by jyzhao** [comment]
@planteater thanks for the quick reply. that's a bummer from Jira. great product from CodeStream team nevertheless.
