### ISSUE TITLE
[TypeScript] Find all references during code review did not find all references

### ISSUE THREAD

**Issue by hgezim** [TeamCodeStream/codestream#879]
Steps:

1. Check out branch that's under review
1. Click on a that's under review
2. Right click on a class name and click Find all References

Video of steps: https://cln.sh/1MRAk4

Actual:
It only found the reference in the file I clicked.

Expected:
To find all references like the rest of VS code does.

**Comment by planteater** [comment]
@hgezim - I would suggest following this issue:

https://github.com/TeamCodeStream/codestream/issues/598

Unfortunately VS Code doesn’t yet have support for code intelligence inside git diffs. We’ve raised the issue with them in the past and there didn’t seem to be much interest in the idea on their part.

**Comment by hgezim** [comment]
Seems like that context menu item should be removed then since someone could rely on that and cause issues.
