### ISSUE TITLE
Login to Slack not usable on VSCode Remote Environment

### ISSUE THREAD

**Issue by estsauver** [TeamCodeStream/CodeStream#88]
When you use the VSCode remote development extension, the links don't open anywhere. (Understandably, xdg-open doesn't magically open across an ssh connection. :)) 

Proposed Behavior: VSCode should show the link to open in a browser manually. 
Workaround: I edited the xdg-open bundled with the extension to write the url it was trying to open to a file. That worked, but was cumbersome.

**Comment by planteater** [comment]
@estsauver - Support for VS Code remote development is definitely on our roadmap. Will update you here as soon as it's ready.

**Comment by aNickzz** [comment]
@planteater how far down the road is it? Is it worth waiting or should i just sign in some other way?

**Comment by aNickzz** [comment]
On that thought, is it likely that codestream will work at all in a remote workspace?

**Comment by planteater** [comment]
@aNickzz - I'm hoping to get this out in a release sometime next week.

**Comment by aNickzz** [comment]
Thanks for the reply :) Looking forward to giving codestream a try

**Comment by planteater** [comment]
@estsauver @aNickzz - Sorry it took so long, but support for VSC remote dev is now available in v7.2.1 of our extension.
