### ISSUE TITLE
As a user I'd like to use PAT (Personal access tokens) to use CodeStream instead of requesting access to organization

### ISSUE THREAD

**Issue by ryan-efendy** [TeamCodeStream/codestream#881]
instead of requesting access to org
![image](https://user-images.githubusercontent.com/12979345/155219442-76038eef-19d6-4e88-a192-f4bcb336e2d7.png)

can we auth via PAT (Personal access tokens) instead?
![image](https://user-images.githubusercontent.com/12979345/155219529-34255ec9-720e-49d4-8543-2cc0b8ca5fef.png)

**Comment by planteater** [comment]
Thanks for the feedback @ryan-efendy. This is actually something we're actively discussing. I'll keep you posted.

**Comment by oscles** [comment]
I don't connect with https://gitlabe2.ext.net.company.com, added the PAT, and trow this error:

![image](https://user-images.githubusercontent.com/32989503/161283828-cc001b42-816f-40e6-9c55-7ca3b07459d7.png)

**Comment by planteater** [comment]
@oscles - I think we'll need a log file to dig into that. Instructions for grabbing a log can be found below. Email it to me directly at support@codestream.com.

https://docs.newrelic.com/docs/codestream/troubleshooting/client-logs/

Might also want to check out this article as well:

https://docs.newrelic.com/docs/codestream/troubleshooting/proxy-support

**Comment by planteater** [comment]
@ryan-efendy - We should have a PAT option available for GH in the next few weeks. I'll update you as soon as it's out there.

**Comment by planteater** [comment]
@ryan-efendy - The latest version of the CodeStream extension (v12.16) now has the option to connect to GitHub (or GitLab) using a personal access token. Just click on your username at the top of the CodeStream pane, select Integrations, and then look for the GitHub button.
