### ISSUE TITLE
Comment thread status (Resolved/Unresolved) are incorrect initially or if changed externally (i.e. in gitlab interface).

### ISSUE THREAD

**Issue by bflamand** [TeamCodeStream/codestream#889]
This occurs with Intellij 2021.3.2 and codestream plugin 12.11.0+219 connected to a Gitlab Self-Managed server v13.7.4

Refreshing the MR also does not update thread resolve status correctly.
For example, a thread marked as resolved in gitlab, will appear as unresolved in codestream when first opening the MR. If we press "resolve thread" in codestream, the resolved status will be displayed correctly but this only last until the MR window is open. If we close the MR window and reopen it again, we again loose de correct resolve status.

Thread status should be maintained correctly, And at the very least, it should be updated when refreshing the MR with the intellij plugin manually.

**Comment by planteater** [comment]
@bflamand - This should be fixed in v12.13 of the CodeStream extension.
