### ISSUE TITLE
Add a way to mark a comment/thread as resolved with the treeview

### ISSUE THREAD

**Issue by bflamand** [TeamCodeStream/codestream#890]
There appears to be no way to mark a thread as resolved when using the treeview to inspect the code. Clicking on the "view comment" icon only show a "read-only view" of the comment thead.
We should be able to mark this comment as resolved.
In addition, resolved comments should not contribute to the comments count number shown in the treeview for a particular file.

We are currently evaluating codestream with this setup:
- Intellij 2021.3.2
- codestream plugin 12.11.0+219
- connected to a Gitlab Self-Managed server v13.7.4

**Comment by planteater** [comment]
Thanks for the feedback @bflamand! We're going to be doing a big UX overhaul of the PR experience soon and I'll factor this into that work.

**Comment by bflamand** [comment]
Any ETA on that overhaul? I think codestream could be a great tool for our company but the issues mentioned here are pretty much show-stoppers for us. Also you should consider fixing the current bug where the thread resolved statuses are not updated correctly which makes it impossible to manage them correctly inside codestream intellij. Please take a look at this issue here: https://github.com/TeamCodeStream/codestream/issues/889

**Comment by planteater** [comment]
@bflamand - We're still spec'ing out the details so a little hard to say. My guess is the 4 to 6 week timeframe. I'll try to get someone to gif #889 before then though.
