### ISSUE TITLE
GitLab MR missing code in comments

### ISSUE THREAD

**Issue by robwilde** [TeamCodeStream/codestream#891]
Going through MR and there is no code or even line numbers

Here is the Mr in CodeStream
![Screenshot from 2022-03-01 10-02-46](https://user-images.githubusercontent.com/1083106/156080118-d98d2a80-769a-475b-9f82-78d68d35f97f.png)

Here is what it looks like in GitLab
![Screenshot from 2022-03-01 10-03-45](https://user-images.githubusercontent.com/1083106/156080150-21697121-22d9-4221-928f-4723a2f2e880.png)

**Comment by robwilde** [comment]
Just as a reference here is another MR I have in CodeStream but is showing the code

![Screenshot from 2022-03-01 10-13-37](https://user-images.githubusercontent.com/1083106/156080346-3973117c-f506-40be-a0ad-b684d19cd3e6.png)

**Comment by planteater** [comment]
@robwilde - Could I trouble you for the version of GitLab you’re running, as well as a log file? Instructions for both are below. Thanks 

https://docs.newrelic.com/docs/codestream/troubleshooting/client-logs/

https://docs.newrelic.com/docs/codestream/troubleshooting/glsm-version

**Comment by planteater** [comment]
@robwilde - I should note that if you'd prefer not to share the log file here, you can send it to me directly at support@codestream.com
