### ISSUE TITLE
"404 Project Not found" when creating new merge request

### ISSUE THREAD

**Issue by Tom-bGenius** [TeamCodeStream/codestream#898]
When using CodeStream in IntelliJ, I get an error saying "404 Project Not Found" when I try to create a new merge request for GitLab (self-managed). Everything else seems to be working fine: I can view existing merge requests, comment on them, approve them, merge them, etc. 

This is what I'm seeing in the log file:
[idea.log](https://github.com/TeamCodeStream/codestream/files/8204672/idea.log)

A GET request is being made to https://gitlab/api/v4/projects/%2Fmyproject. Which is incorrect because the path with namespace for the project is: gitlab/myproject. So the url should be https://gitlab/api/v4/projects/gitlab%2Fmyproject.

Is this a bug or am I doing something wrong?

**Comment by bcanzanella** [comment]
hi @Tom-bGenius could you confirm that you are using GitLab self-managed and the url to the instance is `https://gitlab` ?

Also, could you send your full set of IntelliJ logs to support@codestream.com? Additional directions can be found here: https://docs.newrelic.com/docs/codestream/troubleshooting/client-logs/ 

thanks!

**Comment by Tom-bGenius** [comment]
Hi @bcanzanella , yes my instance of Gitlab self-managed is running on https://gitlab

I send an email with the logs.

Thanks

**Comment by planteater** [comment]
@Tom-bGenius - We've got a fix for this ready to go in our next release, but in the interim you can download this pre-release version of the extension. After downloading, go to Preferences/Settings > Plugins in IntelliJ and then select “Install plugin from disk” from the gear menu at the top-right. Then restart your IDE.

https://drive.google.com/file/d/10JNo2IN8r9HHG-J1F6CF4cec3wKdel3X/view?usp=sharing

**Comment by Tom-bGenius** [comment]
@planteater Great, I installed the pre-release and it's working now.

Thanks for fixing it so quickly!

**Comment by planteater** [comment]
@Tom-bGenius - This fix is now available in our production release of v12.13.
