### ISSUE TITLE
Cannot add other user into private channel

### ISSUE THREAD

**Issue by fksad** [TeamCodeStream/CodeStream#9]
OS: win10 1803
IDE: VSCode 1.28.1

I sign in with the codestream account and created a private channel. When I use '/add @nickname' command to add my teammate, everything seems normal, however, he could not find the entrance the channel and there was no link in the content of the invitation e-mail. The response of `/who` is only myself. I lookup for the  document for help and find no content about that.

Please check it.

P.S. My teammate crate his own team during registration，which may be one possible cause. The `\invite @nickname` command didn't work either.

**Comment by planteater** [comment]
Yep, looks like there's a bug with adding people to a channel. Will get that fixed asap!

If you'd like us to delete one of the two teams you guys created just email us at support@codestream.com. In the meantime, you can specify which team you'd like to use via VS Code user settings. Go to user settings and search for CodeStream. Then scroll down to the CodeStream:Team field and enter the name of the appropriate team.

**Comment by planteater** [comment]
Fixed in v0.18
