### ISSUE TITLE
Using multiple chat providers 

### ISSUE THREAD

**Issue by asthomasdk** [TeamCodeStream/CodeStream#91]
Is it possible to use CodeStream with multiple chat providers - and different teams - at the same time? 

We have different projects and teams, some using Slack and some using Teams (and also different Git providers) that I would like to use CodeStream with. 

it would be useful to then be able to set the team etc. for a specific repo, so that CodeStream knows what the default place to send things to is.

**Comment by bcanzanella** [comment]
Hi @asthomasdk, thanks for the message. We're working on supporting this scenario very soon.

**Comment by planteater** [comment]
@asthomasdk - Apologies for not following up on this, but CodeStream added support for this with our 6.0 release back in January.
