### ISSUE TITLE
Connect via Slack in Visual Studio not possible

### ISSUE THREAD

**Issue by mapfel** [TeamCodeStream/CodeStream#92]
I tried to connect via my Slack account in Visual Studion with CodeStream extension "Sign in with Slack".
Then the browser open with permissions request. 

After confirming that I got a positive feedback:

	All Set!
	Return to your IDE to start using CodeStream. 

But in Visual Studio now it complains with:

	Login timed out. Please try again

**Comment by planteater** [comment]
@mapfel - Thanks for the report! We'll get on this asap. Can I trouble you for a log file? Instructions for locating the log file can be found here: https://github.com/TeamCodeStream/CodeStream/wiki/Instructions-for-finding-CodeStream-log-files

**Comment by mapfel** [comment]
In the attachment, you can find the screenshots and the log-files.
[CodeStream.Issue92.pdf](https://github.com/TeamCodeStream/CodeStream/files/3573298/CodeStream.Issue92.pdf)

**Comment by bcanzanella** [comment]
Hi @mapfel by any chance are you using a proxy to connect to the internet? If so, CodeStream has some additional proxy settings in Tools > Options > CodeStream that you can set.

**Comment by planteater** [comment]
Hi @mapfel - Just wanted to follow up on Brian's earlier question regarding proxy settings. Thanks!
