### ISSUE TITLE
Is there a way to host an own CodeStream Server?

### ISSUE THREAD

**Issue by xetra11** [TeamCodeStream/CodeStream#93]
Since in the settings there is the option to edit the Server URL I wonder if there is any way to host an own CodeStream Server maybe as a docker container?

**Comment by planteater** [comment]
@xetra11 - Definitely! We have an on-prem version of CodeStream that was launched recently, and it is docker-based. If you're interested in trying it out, reach out to us at support@codestream.com. Thanks!
