### ISSUE TITLE
Error when adding a comment

### ISSUE THREAD

**Issue by P3ter** [TeamCodeStream/codestream#935]
Hi,

When I want add a comment with code inside I have the error message below : 

_Sorry, we encountered a git error: Error: Your current branch does not have any commits yet. For further work you should add one._

![image](https://user-images.githubusercontent.com/1431205/160634999-faa35940-287c-4841-a192-3e392db91b23.png)

The error appears only if I select code to add it on the comment : 

![image](https://user-images.githubusercontent.com/1431205/160635146-a8ce0835-58ee-4549-9caf-7211a2d10964.png)

I don't know if it's related, but I have the error below on every codemarks thats contains a code block : 

`You don’t currently have this file in your repo.`

**Comment by planteater** [comment]
@P3ter - Unfortunately, CodeStream does need there to be at least one commit in the repo in order for commenting to work. I assume this is a brand new repo?

**Comment by P3ter** [comment]
Unfortunately the repos is not new, there are commits everyday :-(

**Comment by planteater** [comment]
Gotcha, in that case could I trouble you for a log file? In your IDE go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. You can email it to me directly at support@codestream.com. Thanks.

**Comment by P3ter** [comment]
Thanks for your help. Logs sent.

**Comment by marcelofarias** [comment]
@P3ter based in our email exchange, it looks like the issue was caused by an extraneous .git folder in a subdirectory of your repo.
