### ISSUE TITLE
How does CodeStream perform with major code changes?

### ISSUE THREAD

**Issue by xetra11** [TeamCodeStream/CodeStream#94]
I wonder if CS could keep up with for instance renaming of class files or major refactorings?
It be unlucky to loose all comments, issues and code documentations if something is simply moved and renamed.

**Comment by planteater** [comment]
@xetra11 - In the short term, we've got a feature being worked on right now that will allow you to manually update the code location of a codemark in cases like this. But, we are also working on a more automated way to handle file renames as well.
