### ISSUE TITLE
can't add comment to review

### ISSUE THREAD

**Issue by dvdlsbn** [TeamCodeStream/codestream#950]
Sometimes the button doesn't show up, can't get why.
**[edit 1]**  happens when I select changed code :
![Screenshot_2022-04-11_13-57-41](https://user-images.githubusercontent.com/103422160/162737641-77c65936-2b0c-4f05-a5e5-6fd943f5e781.png)
![Screenshot_2022-04-11_11-30-57](https://user-images.githubusercontent.com/103422160/162721799-ba43d5cf-1325-420b-811d-12cd7d652c37.png)

I should get that third button :
![Screenshot_2022-04-11_11-30-39](https://user-images.githubusercontent.com/103422160/162721809-5c0327dd-349d-42e7-ae13-b902c2422b70.png)

**Comment by dvdlsbn** [comment]
I select changed / added code. This one for instance 
![Screenshot_2022-04-11_13-57-41](https://user-images.githubusercontent.com/103422160/162734718-f8f54225-bf76-4c1b-93d1-0419e9b0ac55.png)
:

**Comment by bcanzanella** [comment]
thanks for the report @dvdlsbn. could I trouble you to send your error logs to support@codestream.com? instructions for finding them is here: https://docs.newrelic.com/docs/codestream/troubleshooting/client-logs/. thanks.

**Comment by dvdlsbn** [comment]
Ok I'll do that.

**Comment by dvdlsbn** [comment]
documentation for android studio is outdated (2017) + for windows only.

**Comment by planteater** [comment]
@dvdlsbn - I think you might be looking at the wrong section of that article. Android Studio is a JetBrains IDE so to grab a log file:

In your IDE go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file.

**Comment by planteater** [comment]
@dvdlsbn - I'm going to close this out for now, but when you get a chance please do send that log file over and we'll dig into the issue.
