### ISSUE TITLE
VSCode: need option to refresh PR on error

### ISSUE THREAD

**Issue by bluddy** [TeamCodeStream/codestream#952]
I often get errors while trying to load a PR in CodeStream. The problem is that it seems like the PR is cached by CodeStream: when I click on the PR again, there's no attempt to reload it. Instead, I immediately get brought to the same error message. This is obviously a big issue: we need an icon next to each individual PR, or in a context menu, to retry loading it in case of failure.

**Comment by planteater** [comment]
@bluddy - I'm going to close this out since we're working the issue via email now.
