### ISSUE TITLE
Stash Support

### ISSUE THREAD

**Issue by mustafaozhan** [TeamCodeStream/codestream#96]
Thank you for the amazing tool! 🎉  Is it possible to integrate it with Stash also ? I couldn't find a workaround for it. If not is there any plan for integration ?

Regards

**Comment by planteater** [comment]
@mustafaozhan - Just to confirm, you're referring to what is now known as Bitbucket Server? And if so, you're interested in integrating with the issue-tracking component of that service? If so, we do have plans to support that. Hopefully sometime in Q4.

**Comment by mustafaozhan** [comment]
Hello  @planteater,
Yes exactly the **Bitbucket Server** but rather than `issue-tracking` i also wonder that, is it possible to integrate **Bitbucket Server** and **GitHub**  with some component which will be commenting into PRs itself, rather than just posting to some Slack messages to specific channel(it is still a plus), it will be really great since most of the companies will be wishing to have something documented in their git server instead of  having messages in Slack.

**Comment by planteater** [comment]
Stay tuned! A PR integration is coming in the next few weeks!
