### ISSUE TITLE
Failure when checking out new branch

### ISSUE THREAD

**Issue by Dorukyum** [TeamCodeStream/codestream#962]
The issue addressed in #854 persists. This happens most of the time when creating a new branch using the Checkout Branch button on a pr on the side view. Here's the message:
```
Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false checkout {BRANCH_NAME}
error: pathspec '{BRANCH_NAME}' did not match any file(s) known to git
```

**Comment by planteater** [comment]
@Dorukyum - Could I trouble you for a log file? In your IDE go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. If you'd prefer, you can send the file to me at [support@codestream.com](mailto:support@codestream.com). Thanks!

**Comment by Dorukyum** [comment]
I'm unable to find the button I can use to collect logs on VSCode.

**Comment by planteater** [comment]
Sorry about that @Dorukyum! Not sure why I had it in my head that you were using a JetBrains IDE. In VS Code, open the Output view (View: Toggle Output from the command palette) and select "CodeStream (Agent)" from the dropdown menu at the top-right. Copy all of the output you see and save it in a text file. Thanks!
