### ISSUE TITLE
newrelic_agent.log file created

### ISSUE THREAD

**Issue by madhugod** [TeamCodeStream/codestream#967]
Hello there,

After updating to VSCode 1.67.1, everytime I open a project there is a new file `newrelic_agent.log` that is created in the project's root directory.

I think the New Relic CodeStream extension is creating this file, as disabling the extension (v12.17.0) stopped the file from being created.

**Comment by bcanzanella** [comment]
thanks for the report @madhugod and sorry about that. we're working on a hotfix release for this.

**Comment by odex21** [comment]
> hi @odex21 can you try again with the latest version, v13.1.1? thanks.

It's work. I disconnected the wifi so that codestream could not be initialized, and this logfile no longer appears
