### ISSUE TITLE
Repo not found if the folder with 2 Git Repositories opened in Intellij Idea 

### ISSUE THREAD

**Issue by alekseybykovesprow** [TeamCodeStream/codestream#968]
Hi, I have a problem with Intellij Idea CodeStream plugin.
I have a project with Frontend (React app) and Backend (Java + Spring Boot). Projects are located in GitLab repositories (diffrent ones). But I clone them in the common parent directory. So the structure is the following:
```
myProject
--- frontend
--- backend
```
The reason for this is not to open 2 different instances in Intellij Idea.
The problem come if I want to to the code review with CodeStream plugin in Intellij Idea. I can load the merge requests, but when I go to the "Changes" tab I have an error "Repo backend not found in your editor. Open it, or clone the repo."

**Comment by planteater** [comment]
@alekseybykovesprow - Could I trouble you for a log file? In your IDE go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. You can email it to me at support@codestream.com. Thanks!

**Comment by alekseybykovesprow** [comment]
Unfortunately I can not send the log files from my working machine. I can give you steps to reproduce. Will it be enough. It will nor require a lot of time

**Comment by alekseybykovesprow** [comment]
Sent you obfuscated log file

**Comment by planteater** [comment]
@alekseybykovesprow - This should have been fixed in one of our recent releases. Can you update to the latest extension and try again? Thanks

**Comment by alekseybykovesprow** [comment]
Hi, Thanks. I have version 13.1.1+237 and still has this problem.
"Repo XXX not found in your editor. Open it or clone the repo"
But the repo is opened in Intellij Idea, I can commit and push files

**Comment by alekseybykovesprow** [comment]
I think I will remove CodeStream plugin as it's does not work for our GitLab On Premise repository. It's very pity

**Comment by planteater** [comment]
@alekseybykovesprow - Today is a holiday in the US, so I don't have anyone online. Let me follow up with you tomorrow once I can discuss with them. GitLab on-prem should work just fine. 

If there's any way you could send a log file, even if it's partially redacted, that would probably help considerably. But we'll do our best without one.

**Comment by alekseybykovesprow** [comment]
Sure. Let's discuss tomorrow if it help. Please contact me, when you are available

**Comment by dsellarsnr** [comment]
Hey @alekseybykovesprow I am getting setup to troubleshoot this - will be in touch tomorrow.

**Comment by dsellarsnr** [comment]
@alekseybykovesprow can i get the output of `git --version` and the idea.log entries that contain startCore or repositorySearch? (if you have git bash `cat idea.log | grep 'repositorySearch\|startCore'`. 

Also curios from your example project structure if myProject has a `.git` folder?

**Comment by alekseybykovesprow** [comment]
Hi. Can we be in touch tomorrow? Maybe some messenger? Actually I can say that I have such a problem with only 2 projects. It's a backend and frontend application of same product. They are located at the separate repositories, but have similar url in git repository (the only one difference is in the backend I have backend phrase in the middle of the repository url, for frontend - frontend one). For all other projects it works
Repositories where plugin does not work:
https://x.y.com/companyname/a_b_product1/a-b-product1-backend
https://x.y.com/companyname/a_b_product1/a-b-product1-frontend
Repository server is Gitlab On Premise

**Comment by alekseybykovesprow** [comment]
Yes. Sure. Please let me know when you are online

**Comment by planteater** [comment]
Fixed in v13.3.
