### ISSUE TITLE
Authentication failed - Change workspace

### ISSUE THREAD

**Issue by bender513** [TeamCodeStream/CodeStream#97]
**Describe the bug**
Installed plugin. When I initially connected, I selected the wrong workspace. When I went to change it, I got the error message:

```
**Authentication failed**
We were not able to authenticate you with Slack (error: PRVD-1002). Contact support if you need assistance, or return to your IDE to try again.
```

Issue sounds like: https://github.com/TeamCodeStream/CodeStream/issues/80

**System Info (please complete the following information):**
 - Version of the CodeStream extension: [2.1.0+1]
 - OS + version: [macOS Mojave v10.14.4
 - IDE + version: [IntelliJ IDEA 2019.2.2 (Ultimate Edition)]

**Comment by planteater** [comment]
Hi @bender513 - Let me know the name of the team you created. I'll have it deleted so that you can sign up again with the correct workspace. Thanks!

**Comment by planteater** [comment]
Or, just send me your email address. You can either post it here, or send it to me directly at support@codestream.com

**Comment by bender513** [comment]
ben.smith@cdk.com

**Comment by planteater** [comment]
@bender513 - All set. You should be able to sign up again using the other workspace. Let me know if you run into any issues.

**Comment by bender513** [comment]
Thank you for the quick response!

--Ben
