### ISSUE TITLE
Work In Progress Feature

### ISSUE THREAD

**Issue by pvs9** [TeamCodeStream/codestream#972]
Hey, why there is now Work In Progress feature nowadays, I remember I had it when we used Code stream around a year ago. Thanks

**Comment by planteater** [comment]
@pvs9 - The WIP section was removed a while back because it was minimally used and we wanted to declutter the CodeStream sidebar a bit. There's a chance that functionality may return at some point, but no definitive plans right now.

**Comment by pvs9** [comment]
Ok, it's just strange vecause you can hide not needed functions in settings as i see
