### ISSUE TITLE
Feature request : Tagging system on codemarks

### ISSUE THREAD

**Issue by jeantil** [TeamCodeStream/codestream#977]
We are experimenting with codestream in general to see if it would match our team's need. 
One of the request that pops up regularly is the possibility to tag codemarks as in categorize them (best practices examples, peer2peer feedbacks,pear2team feedback, code to refactor, etc.) 
a tagging system would allow for that in a flexible way. 
it would need to include : 
- ability to tag a codemark with 1-n tags
- ability to filter codemarks by tags
- ability to review all existing tags and merge a tag in another tag to acccount for typos

we use the IJ extension

**Comment by planteater** [comment]
@jeantil - Good news is that, with the exception of the merging, all of this functionality already exists. When you create a codemark just look for the tag icon at the bottom right of the text area. You’ll find tagging functionality very similar to that on Trello. 

On the Search page look for the blue Filter drop down to filter by a tag.

**Comment by jeantil** [comment]
Awesome, I somehow missed it completely
the tag merge would be nice but can be worked around

sorry for the noise
