### ISSUE TITLE
Gitlab repo not found in webstorm

### ISSUE THREAD

**Issue by g-bastianelli** [TeamCodeStream/codestream#982]
When i open an MR it always told me that repo si not found. It was working well but since 2 or 3 weeks, it's not.
![Capture d’écran 2022-05-23 à 11 09 01](https://user-images.githubusercontent.com/15146913/169785401-734d324c-6ff5-450a-afcf-8a5d50126d74.png)
The repo is open.

**Comment by planteater** [comment]
@g-bastianelli - We'll probably need a log file to dig into this. In your IDE go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. You can send the file to me at support@codestream.com.

One thing to check though, do you have this repo opened directly in your IDE, or do you have a folder that contains the repo opened?

**Comment by planteater** [comment]
@g-bastianelli - Just wanted to follow up on that log file. Thanks!

**Comment by planteater** [comment]
@g-bastianelli - I'm going to close this, but feel free to send us that log file at any time and we'll dig right in.
